### PR TITLE
[Wallet] Fix verification bugs and implementing profiling

### LINKED ISSUE #37: User SNBAT paste the same verification code twice
### Expected Behavior

An error message that prevents the user from pasting the same verification code twice.

### Current Behavior

The user can paste the same code twice, which leads to failing verification.

### LINKED ISSUE #199: Fix retried verifications
### Expected Behavior

Users can continue and succeed a partially complete verification

### Current Behavior

The UI is messed up for continuing a partially complete verification (ie after app restart or retry button)

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

- Fix bug allowing duplicate entry of the same attestation code
- Fix bugs preventing the UI from handling restarting of partly completed verifications
- Fix bug causing unnecessary resubmission of `setAccount` txs
- Implement basic profiling tool in our analytics class
- Cleanup verification related analytics and add perf data to it
- Add `errorSelector` to simplify accessing app's error state

### Tested

Successfully completed a verification from scratch.
Successfully completed a verification after killing app half-way. 
Attempted to paste in dupe code but was successfully prevented.
Retrieved analytics logs from console.

### Related issues

- Fixes #37 
- Fixes #199
- Implements profiling for #208

### Backwards compatibility

App is compatible but this does change the schema for our verification related analytics events.

ver-continued

### CODE REVIEW

File: packages/mobile/src/alert/reducer.ts [hunk 1]
```diff
@@ -26,3 +27,7 @@ export const reducer = (state: State | null = initialState, action: ActionTypes)
       return state
   }
 }
+
+export const errorSelector = (state: RootState) => {
+  return state.alert ? state.alert.underlyingError || null : null
```
Comment (jeanregisser) [inline packages/mobile/src/alert/reducer.ts:32]: 👍

File: packages/mobile/src/verify/Verifying.tsx [hunk 2]
```diff
@@ -118,15 +131,19 @@ export class Verifying extends React.Component<Props, State> {
...
 
   componentDidMount() {
     this.startVerification()
   }
 
-  componentDidUpdate() {
+  componentDidUpdate(prevProps: Props) {
     if (this.isVerificationComplete()) {
-      this.finishVerification()
+      return this.finishVerification()
```
Comment (jeanregisser) [inline packages/mobile/src/verify/Verifying.tsx:143]: Is `return` intentional here?

**Review by jeanregisser — APPROVED** [review]
Looks great 👍 

Wondering if we should use a monotonic clock like [performance.now](https://caniuse.com/#search=performance.now) to track elapsed time in sub events and be immune to system time changes while tracking those?

File: packages/mobile/src/verify/Verifying.tsx (hunk 2 above)
Comment (jmrossy) [reply packages/mobile/src/verify/Verifying.tsx:143]: yep yep!

File: packages/mobile/src/identity/verification.ts [hunk 3]
```diff
@@ -166,6 +187,11 @@ export function* doVerificationFlow() {
     // This needs to go before revealing the attesttions because that depends on the public data key being set.
```
Comment (nambrot) [inline packages/mobile/src/identity/verification.ts:187]: I do not believe this is the case, in fact `setAccount` can be done in parallel

File: packages/react-components/analytics/CeloAnalytics.tsx [hunk 4]
```diff
@@ -82,26 +87,70 @@ class CeloAnalytics {
...
+        continue
+      }
+      durations[subEventName] = timestamp - prevEventTime
+      prevEventTime = timestamp
+    }
+
+    durations.__totalTime__ = Date.now() - subEvents.get('__startTrackingTime__')!
+    this.activeEvents.delete(eventName)
+
+    this.track(eventName, { ...eventProperties, ...durations })
```
Comment (nambrot) [inline packages/react-components/analytics/CeloAnalytics.tsx:153]: Would it be possible to maintain the original timestamps?

File: packages/react-components/analytics/CeloAnalytics.tsx [hunk 5]
```diff
@@ -82,26 +87,70 @@ class CeloAnalytics {
...
+      return this.Logger.warn(TAG, 'stopTracking called for event without subEvents. Ignoring.')
     }
+
+    const durations: { [subEventName: string]: number } = {}
+    let prevEventTime = subEvents.get('__startTrackingTime__')!
+    for (const [subEventName, timestamp] of subEvents) {
+      if (subEventName === '__startTrackingTime__') {
+        continue
+      }
+      durations[subEventName] = timestamp - prevEventTime
```
Comment (nambrot) [inline packages/react-components/analytics/CeloAnalytics.tsx:146]: How does this logic work with parallel events like reveals or verify. If I understand correctly, we will record the maximum time of each event? It would be useful to have access to the individual timing of each reveal/verify

**Review by nambrot — APPROVED** [review]
Wahoo thanks! Just a minor request for timing data in the payload

File: packages/react-components/analytics/CeloAnalytics.tsx (hunk 4 above)
Comment (jmrossy) [reply packages/react-components/analytics/CeloAnalytics.tsx:153]: why do you want the timestamps?

File: packages/react-components/analytics/CeloAnalytics.tsx (hunk 5 above)
Comment (jmrossy) [reply packages/react-components/analytics/CeloAnalytics.tsx:146]: Correct. Just a limitation of this simple design. We _could_ register separate events and subevents to track that 3 reveal/complete txs but seemed like overkill

File: packages/react-components/analytics/CeloAnalytics.tsx (hunk 4 above)
Comment (nambrot) [reply packages/react-components/analytics/CeloAnalytics.tsx:153]: I want to compare it to other data points such as when we receive the transaction on a transaction node, when it was mined, when a validator made an http request, when twilio claims it sent a text message
