### PR TITLE
[Wallet] UI improvements on iOS (safe area, keyboard, and more)

### LINKED ISSUE #1153: UI should be usable on iOS
### Expected Behavior

UI should respect the safe area, keyboard shouldn't hide important elements, and should only be in portrait mode.

### Current Behavior

UI is quite broken. Doesn't respect the safe area (impacts devices with a notch). Keyboard hides important elements. UI adapts to landscape.

### LINKED ISSUE #1161: iOS app should be able to request permission to access contacts
### Expected Behavior

iOS app should be able to request permission to access contacts.

### Current Behavior

iOS app cannot access contacts. An error is raised when trying to request permission.

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This PR makes the UI usable on iOS by respecting the safe area and handling the keyboard properly.

Proper safe area handling was implemented using [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) (lower level lib) and [react-native-safe-area-view](https://github.com/react-native-community/react-native-safe-area-view) (simple high level abstraction).
It does support iOS, Android, Web using the right APIs.
Though I haven't enabled it yet, this would allow us to handle the notch on Android too. See https://dev.to/brunolemos/adding-notch-support-to-your-react-native-android-app-3ci3

Unlike on Android, when the keyboard is up, the window is not resized and we have to listen to keyboard events to adapt to it so no elements are blocked behind it.
This behavior was wrapped in `KeyboardSpacer` and a new `KeyboardAwareScrollView`.

### Tested

- Updated tests
- Went through all screens on iOS/Android

### Other changes

- Fixed contacts access on iOS
- Added default app icon on iOS
- Styled native launch screen on iOS
- Made alert banner use `TouchableWithoutFeedback` instead of `TouchableOpacity`. The opacity change on touch looked wrong/unexpected.
- Set default team to `C Labs` in the Xcode project
- Added some missing Firebase modules in Podfile (firebase still disabled though as it throws an exception when initialization the db)
- Added required `Info.plist` keys for `NSCameraUsageDescription`, `NSContactsUsageDescription`, `NSLocationAlwaysUsageDescription`, `NSLocationWhenInUseUsageDescription` to pass TestFlight automated checks. I think we should be able to remove the one about geolocation usage as we don't actually use/need location but the simple presence of the `RCTGeolocation` module made them necessary.
- Fixed RNRandomBytes main queue setup warning

### Related issues

- Fixes #1153
- Fixes #1161
- #1157
- #1158
- #1159

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/ios/Podfile [hunk 1]
```diff
@@ -61,8 +61,13 @@ target 'celo' do
   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
   pod 'CeloBlockchain', :path => '../../../node_modules/@celo/client/CeloBlockchain.podspec'
   pod 'RNSecureKeyStore', :path => '../../../node_modules/react-native-secure-key-store/ios'
+  pod 'react-native-safe-area-context', :path => '../../../node_modules/react-native-safe-area-context'
```
Comment (jmrossy) [inline packages/mobile/ios/Podfile:64]: just curious, does the RN link command work for iOS or is that still broken and we do these by hand?

File: packages/mobile/src/backup/BackupPhrase.tsx [hunk 2]
```diff
@@ -1,12 +1,14 @@
 import Button, { BtnTypes } from '@celo/react-components/components/Button'
+import KeyboardAwareScrollView from '@celo/react-components/components/KeyboardAwareScrollView'
```
Comment (jmrossy) [inline packages/mobile/src/backup/BackupPhrase.tsx:2]: Once this PR is merged, please post a summary in eng-wallet about the right way to use the new KeyboardAwareScrollView, KeyboardSpacer, and SafeAreaView :)

File: packages/mobile/src/shared/BackupPrompt.test.tsx [hunk 3]
```diff
@@ -1,14 +1,13 @@
-import { shallow } from 'enzyme'
 import * as React from 'react'
-import * as renderer from 'react-test-renderer'
+import { render } from 'react-native-testing-library'
```
Comment (jmrossy) [inline packages/mobile/src/shared/BackupPrompt.test.tsx:2]: 👍

File: packages/mobile/src/transactions/TransactionReviewScreen.tsx [hunk 4]
```diff
@@ -75,11 +77,19 @@ class TransactionReviewScreen extends React.PureComponent<Props> {
...
+        <ReviewFrame HeaderComponent={this.renderHeader} navigateBack={navigateBack}>
+          {this.renderCard(type, confirmationProps)}
+        </ReviewFrame>
+      </SafeAreaView>
     )
   }
 }
 
+const styles = StyleSheet.create({
+  container: {
```
Comment (jmrossy) [inline packages/mobile/src/transactions/TransactionReviewScreen.tsx:90]: Nit: Seeing a few of these, perhaps it could just be a shared style here:
https://github.com/celo-org/celo-monorepo/blob/master/packages/react-components/styles/styles.ts#L7

File: packages/mobile/src/utils/contacts.ts [hunk 5]
```diff
@@ -1,18 +1,53 @@
-import { getMinimal, MinimalContact } from 'react-native-contacts'
-import { checkContactsPermission } from 'src/utils/androidPermissions'
+import { Platform } from 'react-native'
+import { getAll, getMinimal, MinimalContact } from 'react-native-contacts'
 import Logger from 'src/utils/Logger'
+import { checkContactsPermission } from 'src/utils/permissions'
 
 const TAG = 'utils/contacts'
 
+// Stop gap solution since getMinimal is not yet implement on iOS
```
Comment (jmrossy) [inline packages/mobile/src/utils/contacts.ts:8]: Please open an issue to track this. We found that on android it gave a 3-5x import speedup :)

File: packages/mobile/src/utils/permissions.ios.ts [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+        reject(err)
+      } else {
+        resolve(permission === 'authorized')
+      }
+    })
+  })
+}
+
+export async function checkCameraPermission() {
+  throw new Error('Unsupported method')
```
Comment (jmrossy) [inline packages/mobile/src/utils/permissions.ios.ts]: Are these no possible on iOS or just not yet implemented?

File: packages/react-components/components/KeyboardAwareScrollView.tsx [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+    })
+  }
+
+  componentWillUnmount() {
+    if (this.showListener) {
+      this.showListener.remove()
+    }
+  }
+
+  scrollRef() {
```
Comment (jmrossy) [inline packages/react-components/components/KeyboardAwareScrollView.tsx]: Nit: consider rename to  `getScrollRef`

File: packages/react-components/components/KeyboardAwareScrollView.tsx [hunk 8]
```diff
@@ -0,0 +1,96 @@
+import * as React from 'react'
```
Comment (jmrossy) [inline packages/react-components/components/KeyboardAwareScrollView.tsx:1]: If we're implementing our own version of this, can we remove the old one from mobile's dependencies?

File: packages/verifier/__mocks__/react-native-safe-area-context.ts [hunk 9]
```diff
@@ -0,0 +1,8 @@
+export function useSafeArea() {
```
Comment (jmrossy) [inline packages/verifier/__mocks__/react-native-safe-area-context.ts:1]: I realize you just added these to make the test pass but just in case we haven't mentioned this yet:
The verifier is android-only because the SMS-related permissions it needs aren't available on iOS

**Review by jmrossy — APPROVED** [review]
Excellent work! 
A few small comments below but overall looks good. It would have been better to separate things out into separate PRs (like the contact changes for example) instead of one monolith but I'm def guilty of putting up big PRs sometimes too.

I'm approving but it would be great to have @cmcewen look over the iOS build related changes since I'm unfamiliar with that area.

File: packages/mobile/ios/Podfile (hunk 1 above)
Comment (jeanregisser) [reply packages/mobile/ios/Podfile:64]: Still broken, I think it's because it doesn't like our monorepo. I think autolinking should avoid this problem.

File: packages/mobile/src/backup/BackupPhrase.tsx (hunk 2 above)
Comment (jeanregisser) [reply packages/mobile/src/backup/BackupPhrase.tsx:2]: Good idea!

File: packages/mobile/src/utils/permissions.ios.ts (hunk 6 above)
Comment (jeanregisser) [reply packages/mobile/src/utils/permissions.ios.ts]: Good catch, I need to rename them to `not implemented`

File: packages/react-components/components/KeyboardAwareScrollView.tsx (hunk 8 above)
Comment (jeanregisser) [reply packages/react-components/components/KeyboardAwareScrollView.tsx:1]: We'll be able to remove the old one. I didn't want to touch too much yet 😄 
I'll open an issue.

File: packages/mobile/src/utils/contacts.ts (hunk 5 above)
Comment (jeanregisser) [reply packages/mobile/src/utils/contacts.ts:8]: Yep, opened #1246

File: packages/react-components/components/KeyboardAwareScrollView.tsx (hunk 8 above)
Comment (jeanregisser) [reply packages/react-components/components/KeyboardAwareScrollView.tsx:1]: Opened #1247
