### PR TITLE
flakey protocol test beforeEach fix 

### LINKED ISSUE #4570: [FLAKEY SETUP] protocol-test -> protocol -> Contract: Attestations-> "before each" hook for "should delete the unselected request"
1) Contract: Attestations
       "before each" hook for "should delete the unselected request":
     Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (/home/circleci/app/node_modules/web3-core-helpers/src/errors.js:42:16)
      at XMLHttpRequest.request.onreadystatechange (/home/circleci/app/node_modules/web3-providers-http/src/index.js:98:32)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
      at XMLHttpRequest._setReadyState (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
      at XMLHttpRequest._onHttpRequestError (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
      at ClientRequest.<anonymous> (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
      at Socket.socketOnEnd (_http_client.js:426:9)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

### PR DESCRIPTION
**Pull request by alecps**
### Description

- This change should fix the flakey `error: Invalid JSON RPC response: ""` error that we often see in the protocol test beforeEach hooks (particularly those for the Attestations contract). 

- Implements a custom beforeEachWithRetries hook for the protocol tests package that will optionally retry beforeEach hooks and add sleep in between retries. This is necessary to avoid flakiness that seems to be caused by port exhaustion in CI and a mishandling of the error by web3. (See https://github.com/ethereum/web3.js/issues/3425 and https://github.com/ethereum/web3.js/issues/926).

- I've only added `beforeEachWithRetries` to the Attestations tests because this error appears there the most. We can add it elsewhere in the future as needed.

### Other changes

None

### Tested

To see that this works, search logs for "retry" in https://circleci.com/gh/celo-org/celo-monorepo/248635

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/4570

### Backwards compatibility

Not applicable

### CODE REVIEW

File: packages/protocol/test/customHooks.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
+import { sleep } from '../lib/test-utils'
+
+// Handles flakey `error: Invalid JSON RPC response: ""` error that seems to be caused by port exhaustion in CI.
+// See https://github.com/ethereum/web3.js/issues/3425 and https://github.com/ethereum/web3.js/issues/926.
+export const beforeEachWithRetries = (
```
Comment (nambrot) [inline packages/protocol/test/customHooks.ts:5]: What do you think about using the function we already have in utils? https://github.com/celo-org/celo-monorepo/blob/master/packages/utils/src/async.ts#L12

Comment (gastonponti) [reply packages/protocol/test/customHooks.ts:5]: +1 (didn't knew we have that, tbh)

Comment (alecps) [reply packages/protocol/test/customHooks.ts:5]: Great idea!

File: packages/protocol/test/customHooks.ts [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+  title: string,
+  numRetries: number,
+  sleepMs: number,
+  fn: () => any
+) =>
+  beforeEach(title, async () => {
```
Comment (nambrot) [inline packages/protocol/test/customHooks.ts:11]: Optional Nit: This is super minor, but since retryAsync effectively, you should be able to just do 

`beforeEach(title, retryAsync(fn, numRetries, [], sleepMs))`

**Review by nambrot — APPROVED** [review]
