### PR TITLE
Set a Cap on stable token tank size 

### LINKED ISSUE #5849: [Protocol Economics] Cap on cUSD CP-DOTO tank size
### Expected Behavior

As a safeguard against oracle manipulation or other issues related to an incorrect cUSD/CELO exchange rate, there should be a cap on the cUSD tank size. The rationale is that if other safeguards fail, the impact is limited

### Current Behavior

There is no cap.

### Definition of Done

- We have a design doc detailing why the cap is necessary and how we come up with a value for it 
- Cap is implemented and live on mainnet.

### PR DESCRIPTION
**Pull request by ninabarbakadze**
### Description

Adds a maximum size to the stableToken bucket of CP-DOTO.

The cap is a function of the current supply of stableToken, and it's calculated as follows:

maxStableBucketSize = stableTokenSupply* stableBucketFractionCap. If the calculated cap after a rebalancing is bigger than the cap, then the goldBucket shall be downsized accordingly.

For that to work, the stableTokenSupply needs to be big enough to generate a usable stableTokenBucket size, and it is unusable if a token has a zero supply (because the bucket will be always capped at zero). minSupplyForStableBucketCap is introduced for that, and the bucket will always be capped such that it's always bigger than minSupplyForStableBucketCap* stableBucketFractionCap

### Tested

Unit tests

### Related issues

- Fixes #5849

### CODE REVIEW

File: packages/protocol/test/stability/exchange.ts [hunk 1]
```diff
@@ -686,6 +763,63 @@ contract('Exchange', (accounts: string[]) => {
             })
           })
 
+          describe.only('when stableBucket needs to be capped', () => {
```
Comment (ninabarbakadze) [inline packages/protocol/test/stability/exchange.ts:766]: @martinvol this is the test suit

File: packages/protocol/contracts/stability/Exchange.sol [hunk 2]
```diff
@@ -2,6 +2,7 @@ pragma solidity ^0.5.13;
```
Comment (martinvol) [inline packages/protocol/contracts/stability/Exchange.sol:2]: I think version update is missing (see CI)

File: packages/protocol/contracts/stability/Exchange.sol [hunk 3]
```diff
@@ -84,16 +90,21 @@ contract Exchange is
    * updates
    * @param _minimumReports The minimum number of fresh reports that need to be
    * present in the oracle to update buckets
-   * commit to the gold bucket
+   * commit to the gold bucket
```
Comment (bowd) [inline packages/protocol/contracts/stability/Exchange.sol]: remove white space

File: packages/protocol/contracts/stability/Exchange.sol [hunk 4]
```diff
@@ -313,6 +340,20 @@ contract Exchange is
...
+  /**
+    * @notice Allows owner to set the minSupplyForStableBucketCap,
+    *  the minimal stableToken supply considered for the stableToken cap
+    * @param newMinSupplyForStableBucketCap The new value for the minSupplyForStableBucketCap
+    */
+  function setMinSupplyForStableBucketCap(uint256 newMinSupplyForStableBucketCap) public onlyOwner {
+    minSupplyForStableBucketCap = newMinSupplyForStableBucketCap;
+    require(
+      newMinSupplyForStableBucketCap > 0,
+      "min supply for stable bucket cap must be greather than 0"
```
Comment (bowd) [inline packages/protocol/contracts/stability/Exchange.sol]: Given the intent of this variable - to combat the tank size being too low if it relies only on the supply - I'm wondering if it makes sense to also hardcode a lower limit for what it can be set. Cose effectively this could be set to `1` effectively making it redundant. Might be overkill but just a thought cc @martinvol

File: packages/protocol/test/stability/exchange.ts [hunk 5]
```diff
@@ -686,6 +762,58 @@ contract('Exchange', (accounts: string[]) => {
...
+
+            it('has the right price after the cap', async () => {
+              const [tradableGold, mintableStable] = await exchange.getBuyAndSellBuckets(false)
+
+              assertEqualBN(
+                new BigNumber(mintableStable.dividedBy(tradableGold)),
+                new BigNumber('4000')
+              )
+            })
+          })
```
Comment (bowd) [inline packages/protocol/test/stability/exchange.ts]: Feels like there's an assertion missing here to me. The describe says "when stableBucket has been capped" but the test only assets the ratio, which would hold true even if the cap kicked in or not? Maybe I'm missing something.

Comment (bowd) [reply packages/protocol/test/stability/exchange.ts]: Ok now looking at both tests I think the intent here is that the stableToken supply is 0 by default at the beginning of the test? I would restructure the specs into something like 3 blocks:

- Test lower bound capping => when stableToken supply < minSupplyForStableBucketCap 
- Test for no capping => when stableToken supply > minSupplyForStableBucketCap and updatedBucketSize < cap 
- Test for upper bound capping => when updatedBucketSize > cap

I think that would make the specs more readable if I understand things.

**Review by bowd — APPROVED** [review]
Looks good overall, made some optional comments about test structure.

File: packages/protocol/contracts/stability/Exchange.sol (hunk 4 above)
Comment (martinvol) [reply packages/protocol/contracts/stability/Exchange.sol]: The problem with hardcoding a lower is that the unit basis is different for all the stables, so the Chilean peso vs the Euro, so harcoding a number probably wont work.

File: packages/protocol/contracts/stability/Exchange.sol [hunk 6]
```diff
@@ -303,6 +316,20 @@ contract Exchange is
...
 
+  /**
+    * @notice Allows owner to set the Stable Bucket Fraction Cap
+    * @param newStableBucketMaxFraction The new value for the Stable Bucket Fraction CAP
+    */
+  function setStableBucketMaxFraction(uint256 newStableBucketMaxFraction) public onlyOwner {
+    stableBucketMaxFraction = FixidityLib.wrap(newStableBucketMaxFraction);
+    require(
+      stableBucketMaxFraction.lt(FixidityLib.fixed1()),
+      "bucket fraction must be smaller than 1"
```
Comment (martinvol) [inline packages/protocol/contracts/stability/Exchange.sol]:
```suggestion
      "Bucket fraction must be smaller than 1"
```

File: packages/protocol/contracts/stability/Exchange.sol (hunk 4 above)
Comment (martinvol) [inline packages/protocol/contracts/stability/Exchange.sol]:
```suggestion
      "Min supply for stable bucket cap must be greather than 0"
```

File: packages/protocol/contracts/stability/Exchange.sol [hunk 7]
```diff
@@ -393,9 +434,28 @@ contract Exchange is
     uint256 updatedStableBucket = exchangeRateNumerator.mul(updatedGoldBucket).div(
       exchangeRateDenominator
     );
+    uint256 maxStableBucketSize = getStableBucketCap();
+    // check if the bucket is bigger
```
Comment (martinvol) [inline packages/protocol/contracts/stability/Exchange.sol]:
```suggestion
    // Check if the bucket is bigger that the cap
```

File: packages/protocol/contracts/stability/Exchange.sol [hunk 8]
```diff
@@ -393,9 +434,28 @@ contract Exchange is
...
+    if (updatedStableBucket > maxStableBucketSize) {
+      // resize Celo bucket
```
Comment (martinvol) [inline packages/protocol/contracts/stability/Exchange.sol]:
```suggestion
      // Resize down CELO bucket
```

File: packages/protocol/migrationsConfig.js [hunk 9]
```diff
@@ -87,6 +87,8 @@ const DefaultConfig = {
     updateFrequency: 5 * MINUTE,
     minimumReports: 1,
     frozen: false,
+    minSupplyForStableBucketCap: '1000000000000000000000000', // 1e24 = 1M
```
Comment (martinvol) [inline packages/protocol/migrationsConfig.js:90]:
```suggestion
    minSupplyForStableBucketCap: 1000000000000000000000000, // 1e24 = 1M
```

File: packages/dev-utils/src/migration-override.json [hunk 10]
```diff
@@ -7,7 +7,9 @@
   },
   "exchange": {
     "frozen": false,
-    "minimumReports": 1
+    "minimumReports": 1,
+    "minSupplyForStableBucketCap": 1000000000000000000000000,
```
Comment (martinvol) [inline packages/dev-utils/src/migration-override.json]:
```suggestion
    "minSupplyForStableBucketCap": "1000000000000000000000000",
```

File: packages/protocol/migrationsConfig.js [hunk 11]
```diff
@@ -87,6 +87,8 @@ const DefaultConfig = {
     updateFrequency: 5 * MINUTE,
     minimumReports: 1,
     frozen: false,
+    minSupplyForStableBucketCap: 1000000000000000000000000, // 1e24 = 1M
```
Comment (martinvol) [inline packages/protocol/migrationsConfig.js]:
```suggestion
    minSupplyForStableBucketCap: '1000000000000000000000000', // 1e24 = 1M
```

**Comment by ninabarbakadze** [comment]
This pr should not be merged until the core contracts release process gets finalised

File: packages/protocol/test-sol/stability/Exchange.t.sol [hunk 12]
```diff
@@ -269,13 +280,94 @@ contract Exchange_initializeAndSetters is ExchangeTest {
   }
 }
 
+contract ExchangeTest_setStableBucketMaxFractionAndSupply is ExchangeTest {
```
Comment (bayological) [inline packages/protocol/test-sol/stability/Exchange.t.sol]: I think you should move these tests to Exchange_initializeAndSetters for consistency.

Comment (bayological) [inline packages/protocol/test-sol/stability/Exchange.t.sol]: I'd suggest renaming test methods, where possible, to follow this convention:
test_[methodBeingTested] _ [stateUnderTest] _ [expectedBehaviour]
This should help future dev diagnose any failures and explicitly shows the intention of the test.

File: packages/protocol/contracts/stability/Exchange.sol [hunk 13]
```diff
@@ -54,6 +57,9 @@ contract Exchange is
   uint256 public updateFrequency;
   uint256 public minimumReports;
 
+  uint256 public minSupplyForStableBucketCap;
+  FixidityLib.Fraction public stableBucketMaxFraction;
+
   bytes32 public stableTokenRegistryId;
```
Comment (martinvol) [inline packages/protocol/contracts/stability/Exchange.sol]:
```suggestion
  bytes32 public stableTokenRegistryId;
  
  uint256 public minSupplyForStableBucketCap;
  FixidityLib.Fraction public stableBucketMaxFraction;
```

In the proxy pattern that we use, new variables must always be added at the bottom. https://blog.openzeppelin.com/proxy-patterns/

Comment (ninabarbakadze) [reply packages/protocol/contracts/stability/Exchange.sol]: @martinvol thanks
