### PR TITLE
Unlock: adding a check whether account is voting

### LINKED ISSUE #2835: When unlocking, check that account is not currently voting
### Expected Behavior

When unlocking, test if the account is currently voting.

### Current Behavior

`Error: Returned error: gas required exceeds allowance (20000000) or always failing transaction` etc.

### PR DESCRIPTION
**Pull request by mrsmkl**
### Description

When trying to unlock funds, now tests if the account is voting.

### Tested

Only manual testing, and only tested that it still works while not voting.

### Related issues

- Fixes #2835

### CODE REVIEW

File: packages/cli/src/utils/checks.ts [hunk 1]
```diff
@@ -259,6 +259,13 @@ class CheckBuilder {
       `${address} is not registered as an account. Try running account:register`
     )
 
+  isNotVoting = (address: Address) =>
+    this.addCheck(
+      `${address} is not currently voting`,
+      this.withGovernance((gov) => negate(gov.isVoting(address))),
+      `${address} is currently voting. Wait until the referendum ends.`
```
Comment (nategraf) [inline packages/cli/src/utils/checks.ts]: Upvotes would cause the same effect, in which case the action is different.
```suggestion
      `${address} is currently voting in governance. Revoke your upvotes or wait for the referendum to end.`
```

File: packages/cli/src/utils/checks.ts [hunk 2]
```diff
@@ -259,6 +259,13 @@ class CheckBuilder {
       `${address} is not registered as an account. Try running account:register`
     )
 
+  isNotVoting = (address: Address) =>
+    this.addCheck(
+      `${address} is not currently voting`,
```
Comment (nategraf) [inline packages/cli/src/utils/checks.ts]: It is good to distinguish this case from voting for validator groups
```suggestion
      `${address} is not currently voting on a governance proposal`,
```

**Review by nategraf — APPROVED** [review]
Just a comment about the wording of the error message
