### PR TITLE
Simplify contracts release tooling git gymnastics

### LINKED ISSUE #7310: Contracts check-versions fails on unrelated files
### Expected Behavior

Never fails

### Current Behavior

```
yarn check-versions -a celo-core-contracts-v2.mainnet -b celo-core-contracts-v3.rc0 -r "release3_report.json"
- Build contract artifacts ...
 - Return to original git ref
error: Your local changes to the following files would be overwritten by checkout:
	packages/mobile/src/images/simplex.png
```

### PR DESCRIPTION
**Pull request by yorhodes**
### Description

`git checkout -- contracts` to avoid headaches with other monorepo files/build systems/tools

### Other changes

Define `build_tag` bash function to be used across bash scripts

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #7310

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

File: packages/protocol/scripts/bash/release-lib.sh [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+  BRANCH="$1"
+  LOG_FILE="$2"
+
+  echo " - Checkout contracts source code at $BRANCH"
+  BUILD_DIR=$(echo build/$(echo $BRANCH | sed -e 's/\//_/g'))
+  git checkout --no-overlay $BRANCH -- contracts 2>>$LOG_FILE >> $LOG_FILE
+
+  echo " - Build contract artifacts at $BUILD_DIR"
+  mv build/contracts build/contracts_tmp
+  yarn build:sol >> $LOG_FILE
```
Comment (nambrot) [inline packages/protocol/scripts/bash/release-lib.sh:13]: Are we sure that this will work? I already lost track of all the issues we have faced so far and it might have been during tooling building instead

**Review by nambrot — APPROVED** [review]
Just one quick q, and I would probably recommend testing this against at least 1 release boundary of the past as well

**Comment by yorhodes** [comment]
cc @nambrot 
```
yarn check-versions -a celo-core-contracts-v1.mainnet -b celo-core-contracts-v2.mainnet -r "release2_report.json"
yarn run v1.22.10
$ ./scripts/bash/check-versions.sh -a celo-core-contracts-v1.mainnet -b celo-core-contracts-v2.mainnet -r release2_report.json
 - Checkout contracts source code at celo-core-contracts-v1.mainnet
 - Build contract artifacts at build/celo-core-contracts-v1.mainnet
WARNING: MetaTransactionWalletProxy artifact could not be fetched. Maybe it doesn't exist?
WARNING: MetaTransactionWalletDeployerProxy artifact could not be fetched. Maybe it doesn't exist?
WARNING: MetaTransactionWalletDeployer artifact could not be fetched. Maybe it doesn't exist?
 - Checkout contracts source code at celo-core-contracts-v2.mainnet
 - Build contract artifacts at build/celo-core-contracts-v2.mainnet
$ /Users/yorhodes/celo/celo-monorepo/node_modules/.bin/ts-node scripts/check-backward.ts sem_check --old_contracts build/celo-core-contracts-v1.mainnet/contracts --new_contracts build/celo-core-contracts-v2.mainnet/contracts --exclude '.*Test|Mock.*|I[A-Z].*|.*Proxy|.*LinkedList.*|MultiSig.*|ReleaseGold|MetaTransactionWallet|SlasherUtil|FixidityLib|Signatures|Proposals|UsingPrecompiles' --output_file release2_report.json
Running storage report...Done
Running code report...Done
Running library linking...Done
Generating backward report...Done
Writing compatibility report to release2_report.json ...Done
Success! Actual version numbers match expected
✨  Done in 114.46s.
```
