### PR TITLE
[Wallet] Hotfix local currency

### LINKED ISSUE #1461: Application crashes when changing the local currency
Sentry Issue: [CELO-MOBILE-18C](https://sentry.io/organizations/celo/issues/1294207967/?referrer=github_integration)

```
Invariant Violation: Invariant Violation: Invariant Violation: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

This error is located at:
    in L
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in LoadNamespace(Component)
    in RCTView
    in u
    in RCTView
    in z
    in _
    in n
    in _
    in n
    in t
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in LoadNamespace(t)
    in _
    in k
    in ForwardRef(WithAnalytics(Connect(LoadNamespace(t))))
    in u
    in RCTView
    in u
    in RCTScrollContentView
    in RCTScrollView
    in T
    in z
    in I
    in R
    in u
    in RCTView
    in u
    in n
    in n
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in LoadNamespace(n)
    in _
    in k
    in ForwardRef(WithAnalytics(Connect(LoadNamespace(n))))
    in h
    in _
    in v
    in RCTView
    in RCTView
    in l
    in RCTView
    in n
    in RCTView
    in n
    in _
    in k
    in v
    in RCTView
    in RCTView
    in RCTView
    in u
    in RCTView
    in u
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in u
    in PanGestureHandler
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in v
    in c
    in k
    in k
    in RCTView
    in n
    in _
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in WrappedNavigator
    in l
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in LoadNamespace(l)
    in c
    in RNCSafeAreaView
    in Unknown
    in f
    in n
    in n
    in RCTView
    in RCTView
    in c

This error is located at:
    in k
    in RCTView
    in n
    in _
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in WrappedNavigator
    in l
    in t
    in u
    in WithMergedOptions(t)
    in C
    in u
    in LoadNamespace(l)
    in c
    in RNCSafeAreaView
    in Unknown
    in f
    in n
    in n
    in RCTView
    in RCTView
    in c
  File "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js", line 34, in invariant
    condition = Error(
  File "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js", line 3146, in renderWithHooks
    invariant(
  File "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js", line 3756, in updateFunctionComponent
    Component = renderWithHooks(
  File "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js", line 6233, in performUnitOfWork
    var next = beginWork(
  File "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js", line 6275, in renderRoot
    nextUnitOfWork = performUnitOfWork(nextUnitOfWork);
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Fixed some regressions introduced by #1325
- crash when changing the local currency from the settings (caused by incorrect usage of react hooks)
- incorrect exchange rate values displayed for exchanges
- gold received from faucet showing as local currency

This will probably need further refactoring, the logic is easy to break given the different use cases.

### Tested

image
image
image
image
image
image

### Other changes

N/A

### Related issues

- Fixes #1461

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/localCurrency/SelectLocalCurrency.tsx [hunk 1]
```diff
@@ -14,6 +14,7 @@ const DEFAULT_CURRENCY_CODE = LocalCurrencyCode.USD
 const keyExtractor = (item: LocalCurrencyCode) => item
 
 function SelectLocalCurrency() {
+  // tslint:disable-next-line: react-hooks-nesting
   const selectedCurrencyCode = useLocalCurrencyCode() || DEFAULT_CURRENCY_CODE
```
Comment (jeanregisser) [inline packages/mobile/src/localCurrency/SelectLocalCurrency.tsx:18]: false positive because we're using `|| DEFAULT_CURRENCY_CODE`

File: packages/mobile/src/send/TransferConfirmationCard.tsx [hunk 2]
```diff
@@ -67,11 +67,12 @@ const renderTopSection = (props: Props) => {
 const renderAmountSection = (props: Props) => {
   const { currency, type, value } = props
 
+  // tslint:disable react-hooks-nesting
```
Comment (jeanregisser) [inline packages/mobile/src/send/TransferConfirmationCard.tsx:70]: false positive because this function is called inside another render function and that lint rules can't figure it out.

**Review by jmrossy — APPROVED** [review]
