### PR TITLE
[web] Faucet and Invite Improvements

### LINKED ISSUE #63: Users SBAT see good Faucet /Invite feedback on website
### Expected Behavior

It tells you what is going on

### Current Behavior

It only gives back Complete or Failed

### PR DESCRIPTION
**Pull request by aaronmgdr**
### Description

At a high level this changes how the browser express and firebase client interact and makes UI improvements that are backed by those changes. 

Functional Changes 
A) Changes express to respond as soon as we have a key returned from firebase client (rather than waiting for entire faucet/invite request to complete or fail 
B) Use this key in browser to subscribe to updates from firebase about status of request
C) give more granular feedback in the UI based on this extra info

Refactors 
A) combine our Invite and Fauceting components into RequestFunds component
B) combine our /invite and /faucet controllers 
C) remove `start*Request` convenience functions as they were less convenient once i combined the route handlers

### Tested
with my own number and with my testnet address

see #faucet chanel in slack for videos
https://celo-org.slack.com/archives/CJUGMBSSX/p1563562806223000
### Other changes
added a background to Phone Illo

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/63

### Backwards compatibility

Internally not compatible (front and back end must both be deployed together) but externally shouldnt change anything

### CODE REVIEW

File: packages/web/server/FirebaseClient.ts [hunk 1]
```diff
@@ -10,12 +10,17 @@ function getFirebase() {
...
+  return getFirebase().database()
+}
+
 // Don't do this. It hangs next.js build process: https://github.com/zeit/next.js/issues/6824
 // const db = firebase.database()
 
 const NETWORK = 'alfajores'
 
 export type Address = string
+type E164Number = string
```
Comment (mcortesi) [inline packages/web/server/FirebaseClient.ts]: `export` maybe

File: packages/web/server/FirebaseClient.ts [hunk 2]
```diff
@@ -30,56 +35,39 @@ export enum RequestType {
...
-      const record = snap.val() as RequestRecord
-      onChange(record)
-
-      if (record.status === RequestStatus.Done || record.status === RequestStatus.Failed) {
-        ref.off('value', listener)
-        resolve(record)
-      }
-    })
-  })
+  return ref.key
```
Comment (mcortesi) [inline packages/web/server/FirebaseClient.ts:56]: I think there's actually a `path` or `ref` property which is better, since later you can use that, without need to remeber the rest of the path.

something like `getDb().ref(pathHere)`

File: packages/web/src/fauceting/MicroComponents.tsx [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+    !isFaucet && textStyles.invert,
+    BAD_STATES.has(requestState) && textStyles.error,
+  ]
+
+  const text = isFaucet ? faucetText({ requestState, t }) : inviteText({ requestState, t })
+
+  return <Text style={contextStyle}>{text}</Text>
+}
+
+export function HashingStatus({ isFaucet, dollarTxHash, goldTxHash, escrowTxHash, t, done }) {
```
Comment (mcortesi) [inline packages/web/src/fauceting/MicroComponents.tsx]: add types

File: packages/web/src/fauceting/MicroComponents.tsx [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+      text={buttonText({ requestState, t })}
+      onPress={onSubmit}
+      iconLeft={icon}
+      align={'flex-start'}
+      size={isFaucet ? SIZE.normal : SIZE.big}
+    />
+  )
+}
+
+function buttonText({ requestState, t }) {
```
Comment (mcortesi) [inline packages/web/src/fauceting/MicroComponents.tsx]: types

File: packages/web/src/fauceting/MicroComponents.tsx [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+    case RequestState.Working:
+      return ''
+    case RequestState.Completed:
+      return t('done')
+    default:
+      return t('getStarted')
+  }
+}
+
+function faucetText({ requestState, t }) {
```
Comment (mcortesi) [inline packages/web/src/fauceting/MicroComponents.tsx]: types

File: packages/web/src/fauceting/MicroComponents.tsx [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+  return (
+    {
+      [RequestState.Failed]: t('faucetError'),
+      [RequestState.Invalid]: t('invalidAddress'),
+      [RequestState.BadChecksum]: t('badChecksum'),
+    }[requestState] || `eg. ${EXAMPLE_ADDRESS}`
+  )
+}
+
+function inviteText({ requestState, t }) {
```
Comment (mcortesi) [inline packages/web/src/fauceting/MicroComponents.tsx]: types :D

File: packages/web/src/fauceting/RequestFunds.tsx [hunk 7]
```diff
@@ -0,0 +1,185 @@
...
+class RequestFunds extends React.PureComponent<Props & I18nProps, State> {
+  state: State = {
+    beneficiary: '',
+    requestState: RequestState.Initial,
+    captchaOK: false,
+  }
+
+  recaptchaRef = React.createRef<ReCAPTCHA>()
+
+  setBeneficiary = ({ nativeEvent }) => {
```
Comment (mcortesi) [inline packages/web/src/fauceting/RequestFunds.tsx]: types

**Review by mcortesi — CHANGES_REQUESTED** [review]

**Comment by mcortesi** [comment]
we should enable `noImplicitAny` on tsconfig

File: packages/web/src/fauceting/RequestFunds.tsx [hunk 8]
```diff
@@ -0,0 +1,185 @@
...
+  }
+  resetCaptcha = () => {
+    this.recaptchaRef.current.reset()
+  }
+  getCaptchaToken = () => {
+    return this.recaptchaRef.current.getValue()
+  }
+
+  checkCheckSum = () => {
+    // TODO check checksum if bad this.setState({requestState: RequestState.BadChecksum}) but dont abort
```
Comment (trianglesphere) [inline packages/web/src/fauceting/RequestFunds.tsx]: this check can be done with `checkAddressChecksum` from `web3-utils`

File: packages/web/src/fauceting/RequestFunds.tsx [hunk 9]
```diff
@@ -0,0 +1,185 @@
...
+  }
+
+  onSubmit = async () => {
+    if (!validateBeneficary(this.state.beneficiary, this.props.kind)) {
+      this.setState({ requestState: RequestState.Invalid })
+      return
+    }
+    this.checkCheckSum()
```
Comment (trianglesphere) [inline packages/web/src/fauceting/RequestFunds.tsx]: Let's only do this on addresses and not phone numbers

File: packages/web/static/locales/en/faucet.json [hunk 10]
```diff
@@ -31,5 +31,13 @@
   "hittingIssuesText": "",
   "askQustionsOnForum": "Get Help from the Celo Community.",
   "findAnswers": "Find answers and ask questions in the Forum",
-  "testnetForum": "Alfajores Testnet Forum"
+  "testnetForum": "Alfajores Testnet Forum",
+  "testnetAddress": "Testnet Address",
+  "getStarted": "Get Started",
+  "done": "Done",
+  "inviteError": "Unable to complete - double check your number",
+  "invalidNumber": "Must be a valid E.164 number",
```
Comment (trianglesphere) [inline packages/web/static/locales/en/faucet.json:39]: Works for now, but not as user friendly as it could be

File: packages/web/src/fauceting/utils.ts [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+  } else {
+    return `+${number}`
+  }
+}
+
+export const EXAMPLE_ADDRESS = 'a0000aaa00a0000...a00a0a0000a00a00aa'
+
+// This is only a basic validation
+function validateAddress(address: string) {
+  return /^(0x)?[0-9a-f]{40}$/i.test(address)
```
Comment (trianglesphere) [inline packages/web/src/fauceting/utils.ts:37]: This should work for hex addresses, can also use `isAddress(address.toLower())` from `web3-utils`. (Lower case it to avoid checksum test.)

File: packages/web/src/fauceting/RequestFunds.tsx (hunk 7 above)
Comment (aaronmgdr) [reply packages/web/src/fauceting/RequestFunds.tsx]: this was a tricky one!

File: packages/web/server/FirebaseClient.ts (hunk 2 above)
Comment (aaronmgdr) [reply packages/web/server/FirebaseClient.ts:56]: what are the benefits there?  i guess you're thinking about if NETWORK changes?

i can do `ref.path.toToString()` to get the path but it the `@types` don't have it so it feels kinda hacky. Of course we could add a type augmentation, but im hesitant to use something that seems less supported over something that is right there in the docs.

File: packages/web/src/fauceting/RequestFunds.tsx (hunk 8 above)
Comment (aaronmgdr) [reply packages/web/src/fauceting/RequestFunds.tsx]: the more i think about this the more im wondering how important it is to do a specific checksum check.

Comment (trianglesphere) [reply packages/web/src/fauceting/RequestFunds.tsx]: We could ignore it. `isAddress` from web3-utils could also work well (it only tests the checksum if it thinks the address is checksum'd, if it's not checksum'd, it just checks the length)

**Review by mcortesi — DISMISSED** [review]

**Comment by aaronmgdr** [comment]
Re checksum, we decided not needed at this time

**Review by mcortesi — APPROVED** [review]
