### PR TITLE
[Wallet] Secure Send Navigation Bug Fix

### LINKED ISSUE #4226: Submit button is not functioning on “Confirm Account Number” screen when send secure flow trigger again after tapping on edit button from sending screen
**Frequency:** 100%
**Repro App version:** Celo Integration Wallet build v1.8.2 (40)
**Repro on device:** iphone 11(13.3)

**Pre-condition:** 
- Make sure user B should created two account using one phone number  
- Make sure user has completed send secure flow once for this user

**Repro Steps:**
1) Launch the app and login to test account 
2)  Tap on Send button. 
3) Select user B who has two account with one number. 
4) Enter an amount and tap on Review button. 
5) tap on Edit button shown next to phone number on sending screen. 
6) Enter last 4 digit account number of User B. 
7) Tap on Submit button and observed. 

**Current Behavior:** Submit button is not functioning. 
**Expected Behavior:** Submit button should functioning. 
 **Impact:** User is not able to proceed for send secure flow again by tapping on edit button. 
**Investigation:** Submit button is function when send secure flow is trigger first time  
**Attachment:**[ EditButtonIshown&SubmitbuttonIssue.MP4](https://drive.google.com/file/d/1ws7u3V1m1diCTQWkM3wXgcKF5cwwWbSo/view?usp=sharing)(Bug observed at 43 sec)

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Fixes a bug where repeatedly cycling through "edit" for secure send would cause navigation to stall. See tagged issue for context.

### Other changes
Minor refactoring to further consolidate secure send properties into the mapping object.

### Tested
Wrote new tests.

### Related issues
- Closes #4226

### Backwards compatibility
Yes

### CODE REVIEW

File: packages/mobile/src/navigator/Screens.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ export enum Screens {
   TransactionReview = 'TransactionReview',
   UpgradeScreen = 'UpgradeScreen',
   ValidateRecipientIntro = 'ValidateRecipientIntro',
-  ValidateRecipientAccount = 'ValidatemRecipientAccount',
+  ValidateRecipientAccount = 'ValidateRecipientAccount',
```
Comment (jeanregisser) [inline packages/mobile/src/navigator/Screens.tsx:63]: 👍

File: packages/mobile/src/send/ValidateRecipientAccount.tsx [hunk 2]
```diff
@@ -88,11 +95,22 @@ export class ValidateRecipientAccount extends React.Component<Props, State> {
...
+    const { e164PhoneNumber } = this.props.recipient
+    if (e164PhoneNumber) {
+      this.props.validateRecipientAddressReset(e164PhoneNumber)
+    }
+  }
+
+  componentDidUpdate = () => {
+    const { validationSuccessful, isOutgoingPaymentRequest, transactionData } = this.props
+
+    if (validationSuccessful) {
```
Comment (jeanregisser) [inline packages/mobile/src/send/ValidateRecipientAccount.tsx]: We should check `validationSuccessful` actually changed, otherwise we risk triggering this path unnecessarily as the code evolves and other updates are triggered.

File: packages/mobile/test/schemas.ts [hunk 3]
```diff
@@ -312,7 +312,6 @@ export const v1Schema = {
       total: 0,
     },
     matchedContacts: {},
-    isValidRecipient: false,
```
Comment (jeanregisser) [inline packages/mobile/test/schemas.ts:315]: Looks like we need a migration to remove `isValidRecipient` and add `validationSuccessful` to existing `secureSendPhoneNumberMapping`.

**Review by jeanregisser — CHANGES_REQUESTED** [review]
Looking almost good, see comments below.

File: packages/mobile/src/send/ValidateRecipientAccount.tsx (hunk 2 above)
Comment (tarikbellamine) [reply packages/mobile/src/send/ValidateRecipientAccount.tsx]: You're right, better to be safe on this.

File: packages/mobile/test/schemas.ts (hunk 3 above)
Comment (tarikbellamine) [reply packages/mobile/test/schemas.ts:315]: The issue is that we now have a `validationSuccessful` property for each phone number entry within the `secureSendPhoneNumberMapping` but we only had one universal `isValidRecipient`. In this case, what kind of migration is appropriate?

I wasn't sure so I just deleted `isValidRecipient` from the test schema and added `validationSuccessful` to the `SecureSendDetails` type. I don't think this would break any compatibility with older builds.

**Review by jmrossy — COMMENTED** [review]
Looks okay to me, please see Jean's comments

File: packages/mobile/test/schemas.ts (hunk 3 above)
Comment (jeanregisser) [reply packages/mobile/test/schemas.ts:315]: Yes this isn't going to break existing users.
If you decide not to add a migration, the type for `validationSuccessful` should be changed to `boolean | undefined` for correctness.

**Review by jeanregisser — APPROVED** [review]
Awesome 🎉

**Comment by ValoraQA** [comment]
Hey @tarikbellamine   I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47) & observed that issue is still reproduced. User not able to proceed by submitting last 4 digit codes again from Send secure flow screen.
**Verified on devices:** Samsung Galaxy A5(7.0),iPhone SE (13.4.1)
**Attachment:** [NotProceedBySubmitting4CodesAgain.mp4](https://drive.google.com/file/d/1nltd6ClMJxf6yErUi9gtenRAoELIw5L2/view?usp=sharing)

**Comment by jeanregisser** [comment]
Thanks, could you open a new bug for this?

**Comment by ValoraQA** [comment]
Sure @jeanregisser we will raise a new issue for this, Thanks!

**Comment by ValoraQA** [comment]
Hi @jeanregisser We have raised new issue https://github.com/celo-org/wallet/issues/106.
