### PR TITLE
Upvote cli fix

### LINKED ISSUE #10064: Cli can't upvote proposals in upvote stage when other proposals are ready for dequeuing
### Expected Behavior

Any proposal in the upvote stage can be upvoted. Proposals ready for dequeuing should be dequeued when attempting to upvote.

### Current Behavior

Assuming these are the the proposals in upvote stage:
(id, upvotes)
#1 0
#2 1
#3 1
#4 1

If the cli tries to upvote #1 it will fail with 
```
Running Checks:
   ✔  0x... is vote signer or registered account
   ✔  1 is an existing proposal
   ✔  1 is in stage Queued
Sending Transaction: upvoteTx... failed: Error: execution reverted: invalid lesser key
    Error: Error: execution reverted: invalid lesser key
```

If it tries to upvote #2, #3 or #4, it will get:

```
Retrieving derivation Paths [ 0 ]
Running Checks:
   ✔  0x... is vote signer or registered account
   ✔  2 is an existing proposal
   ✔  2 is in stage Queued
Sending Transaction: upvoteTx... failed: Error: execution reverted: cannot upvote a proposal not in the queue
    Error: Error: execution reverted: cannot upvote a proposal not in the queue
```

### PR DESCRIPTION
**Pull request by pahor167**
### Description

Fixes Cli when upvoting. Currently when proposal can be dequeued while upvoting, smart contract will revert. This change proactively dequeues proposals and only if the proposal way not dequeued, it will upvote it.

### Other changes

No other changes

### Tested

Added Upvote tests

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/10064

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/cli/src/commands/governance/upvote.ts [hunk 1]
```diff
@@ -29,6 +30,43 @@ export default class Upvote extends BaseCommand {
       .runChecks()
 
     const account = await (await this.kit.contracts.getAccounts()).voteSignerToAccount(signer)
-    await displaySendTx('upvoteTx', await governance.upvote(id, account), {}, 'ProposalUpvoted')
+
+    const consideredProposals = await this.dequeueAllPossibleProposals(governance as any)
+
+    if (!consideredProposals.some((k) => k.id === id)) {
+      await displaySendTx('upvoteTx', await governance.upvote(id, account), {}, 'ProposalUpvoted')
```
Comment (martinvol) [inline packages/cli/src/commands/governance/upvote.ts:38]: Would add a log statement that the tx were dequeued and no upvoting was needed/possible.

File: packages/cli/src/commands/governance/upvote.ts [hunk 2]
```diff
@@ -29,6 +30,43 @@ export default class Upvote extends BaseCommand {
...
+            .slice(0, concurrentProposals)
+            .map((p) => p.proposalID)
+            .map(async (id) => {
+              const expired = await governance.isQueuedProposalExpired(id)
+              return { id: id.toString(), expired }
+            })
+        )
+      ).filter((k) => k.expired === false)
+
+      await displaySendTx('dequeue', governance.dequeueProposalsIfReady(), {})
```
Comment (martinvol) [inline packages/cli/src/commands/governance/upvote.ts:74]: has this to be inside of the loop? Because on-chain one tx should be enough to dequeue them all, this function should only check if there's on that needs to be dequeued.

This is specially hurtful if the user is using a ledger.

File: packages/cli/src/commands/governance/upvote.ts (hunk 1 above)
Comment (pahor167) [reply packages/cli/src/commands/governance/upvote.ts:38]: Logging added

File: packages/cli/src/commands/governance/upvote.ts (hunk 2 above)
Comment (pahor167) [reply packages/cli/src/commands/governance/upvote.ts:74]: This cycle is there only for safety purposes (in 99.9% of times it will not be run more than once). 

The reason behind this cycle is as follows:

1. Someone will DDoS our proposals (eg 100+)
2. All these proposals will expire 
3. DequeueProposalsIfReady will always try to dequeue first n proposals but if all of them will be expired it will just remove them from queue.
4. Since none of the proposals were actually dequeued, next call will allow to dequeue again
5. Upvote function will try to dequeue again and possibly it will hit the proposal and bug that we have

Since this case is extremely unlikely we didn't consider it before at all. Now it would cause some inconvenience but it will behave deterministically. 

In general I believe it is extremely unlikely that this use case should happen, but it felt like a little work to cover it just in case.

Comment (pahor167) [reply packages/cli/src/commands/governance/upvote.ts:74]: I added this explanation to method description

File: packages/cli/src/commands/governance/upvote.ts [hunk 3]
```diff
@@ -29,6 +31,52 @@ export default class Upvote extends BaseCommand {
...
+    const queue = await governance.getQueue()
+    const originalLastDequeue = await governance.lastDequeue()
+
+    let consideredProposals
+
+    for (let index = 0; index < queue.length / concurrentProposals + 1; index++) {
+      consideredProposals = (
+        await Promise.all(
+          queue
+            .slice(0, concurrentProposals)
```
Comment (aaronmgdr) [inline packages/cli/src/commands/governance/upvote.ts]: trying to understand this. 

first run `concurrentProposals` would be `undefined`. second run it would be array of non expired proposals. 

but passing an array to slice like `[1,2,3,4].slice(0, [1,2,3])` results in `[]`

i think this line should be 

```suggestion
            .slice(0, concurrentProposals?.length)
```

Comment (aaronmgdr) [reply packages/cli/src/commands/governance/upvote.ts]: has this been tested for the edge case it was written for?

**Review by aaronmgdr — CHANGES_REQUESTED** [review]
pretty sure i found a bug see comment in context: EDIT the bug was in my head

File: packages/cli/src/commands/governance/upvote.ts (hunk 3 above)
Comment (pahor167) [reply packages/cli/src/commands/governance/upvote.ts]: Hey, 
`concurrentProposals` variable is of type number (it is not array). I introduced tests in upvote.test.ts.

Comment (aaronmgdr) [reply packages/cli/src/commands/governance/upvote.ts]: oh bad reading i mixed up considered and current

nit: call it `currentProposalCount`

**Review by aaronmgdr — APPROVED** [review]
