### PR TITLE
Fix QR scan for requests

### LINKED ISSUE #4059: “Send” screen is open even though scanning the QR code from Request screen
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (35)
**Repro on device:** iphone 6+ (12.4.5)
**Repro Steps:** 
1) Launch app and sign up in the app
2) Tap on Request button. 
3) Tap on QR code icon. 
4) Tap on Scan code button. 
5) Scan the other user’s QR code. 
6) Observe 
 
**Current Behavior:**Send Screen is open instead Request screen 
**Expected Behavior:** Request screen should be shown 
**Attachment:**[RequestscreenIssue..mp4 ](https://drive.google.com/file/d/1KWKqMK8SXKsNXyxAien_Y7cvfY2cg7gC/view?usp=sharing)

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Fixed bug where QR scan for a request would take you into the send flow.

### Other changes
None

### Tested
On device

### Related issues
- Closes #4059 

### Backwards compatibility
Yes

### CODE REVIEW

File: packages/mobile/src/send/utils.ts [hunk 1]
```diff
@@ -126,7 +126,11 @@ export function showLimitReachedError(
   return showError(ErrorMessages.PAYMENT_LIMIT_REACHED, ALERT_BANNER_DURATION, translationParams)
 }
 
-export function* handleSendPaymentData(data: UriData, cachedRecipient?: RecipientWithContact) {
+export function* handleSendPaymentData(
+  data: UriData,
+  cachedRecipient?: RecipientWithContact,
+  isOutgoingPaymentRequest?: true
```
Comment (yorhodes) [inline packages/mobile/src/send/utils.ts:132]: should this be true by default?

**Review by yorhodes — APPROVED** [review]
lgtm
1 qq

File: packages/mobile/src/send/utils.ts (hunk 1 above)
Comment (tarikbellamine) [reply packages/mobile/src/send/utils.ts:132]: The type for `isOutgoingPaymentRequest` can only be `undefined` or `true` so I opted to just be a little more specific than using `boolean`.

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser i have verified task using Test flight build v1.1.0 (21) & & Valora internal build V1.1.0(1004294309)

**Test scenarios:**

1. Verify user is able to see the Request button on home page 
2. Verify user should redirect to Request contact page by tapping on request button 
3. Verify user should able to see the scanner icon on top right corner in request contact page 
4. Verify scanner page should open when user tap on scanner icon 
5. Verify user should able to scan the other user Qr code 
6. Verify verify user should redirect to Request amount page after scanning other user QR code 
7. Verify Review button should enable when user enter valid amount
8. Verify user should redirect to send request page after tapping on Review button
9. Verify request sent message should show when user tap on request button 
10. Verify Waiting for payment notification should show on home page 
11. Verify other user should receive the request notification 

**Devices:** iPhone 6+ (12.4.5), Google pixel Xl 8.1

**Fixed issues:**

#4059 



Please let me know if any thing else i need to verify for this task.
Thanks !
