### PR TITLE
[Wallet] Fix redux store persistence

### LINKED ISSUE #6313: App reset after close
### Expected Behavior

App should not reset its state.

### Current Behavior

App reset its state after closing it and relaunching. This happened to Denisse and Daniel during today's bugapalooza testing v1.7. Both on Android.

See logs: 
- https://groups.google.com/a/clabs.co/g/support/c/pwzJnCAR-8E/m/SsjNSU6oAwAJ
- https://groups.google.com/a/clabs.co/g/support/c/pwzJnCAR-8E/m/rrPOsI6oAwAJ

We recently changed the persistence mechanism in #6273 to fix #5792, which is likely revealing this new form of the bug.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

The error was that when reading the state from the filesystem the `JSON.parse` function failed. Upon further inspection, we noticed that the json being stored wasn't valid. What happened is that we first stored a json string and then, when overwriting with a smaller string, the previous text was not deleted, it was just written over. An example of how this looked like is the following:
```
[...] ,"_persist":"{\"version\":7,\"rehydrated\":true}"}mentRequests\":[],\"outgoingPaymentRequests\":[]}","_persist":"{\"version\":7,\"rehydrated\":true}"}
```
Notice that the string should end just before the `mentRequests` thing.

The error comes from the `react-native-fs` library. When writing, it is using a `w` file, which behaved as expected on Android lower than 10. On Android 10 though, they changed it so that it doesn't erase data on the file before writing. We had to add a `t` flag to get that behaviour. This is a known issue of the library and [there's a PR ready since June](https://github.com/itinance/react-native-fs/pull/890) but it hasn't been merged yet, so [we had to fork the library](https://github.com/celo-org/react-native-fs) and [redux-persist-fs-storage](https://github.com/celo-org/redux-persist-fs-storage) in order to get the fix.

### Other changes

Added an extra log or two.

### Tested

Yes

### Related issues

- Fixes #6313

### Backwards compatibility

Yup

### CODE REVIEW

File: packages/mobile/src/navigator/Navigator.tsx [hunk 1]
```diff
@@ -95,12 +95,15 @@ import ValidateRecipientIntro, {
 } from 'src/send/ValidateRecipientIntro'
 import SetClock from 'src/set-clock/SetClock'
 import TransactionReview from 'src/transactions/TransactionReview'
+import Logger from 'src/utils/Logger'
```
Comment (etuleu) [inline packages/mobile/src/navigator/Navigator.tsx:98]: this change seems unrelated. probably just a leftover right?

File: packages/mobile/src/redux/store.ts [hunk 2]
```diff
@@ -37,6 +37,11 @@ const persistConfig: any = {
     }
     return stringifiedData
   },
+  deserialize: (data: string) => {
```
Comment (etuleu) [inline packages/mobile/src/redux/store.ts:40]: good idea to match the serialize!

File: packages/mobile/package.json [hunk 3]
```diff
@@ -109,7 +109,7 @@
     "react-native-email-link": "^1.9.1",
     "react-native-exit-app": "^1.1.0",
     "react-native-flag-secure-android": "git://github.com/kristiansorens/react-native-flag-secure-android#e234251",
-    "react-native-fs": "^2.16.6",
+    "react-native-fs": "git+https://github.com/celo-org/react-native-fs#aa6db0f",
```
Comment (etuleu) [inline packages/mobile/package.json:112]: maybe we can add a short comment here why we are forking it

**Review by etuleu — APPROVED** [review]
great work!

File: packages/mobile/package.json [hunk 4]
```diff
@@ -143,7 +143,7 @@
     "react-redux": "^7.2.0",
     "redux": "^4.0.5",
     "redux-persist": "^6.0.0",
-    "redux-persist-fs-storage": "^1.3.0",
+    "redux-persist-fs-storage": "git+https://github.com/celo-org/redux-persist-fs-storage#54ffc50",
```
Comment (jeanregisser) [inline packages/mobile/package.json]: Instead of forking this, we could use a yarn resolution to ensure all our dependencies use our patched react-native-fs.
What do you think?

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (gnardini) [reply packages/mobile/src/navigator/Navigator.tsx:98]: It was a leftover, but I figured it's a useful log to have regardless (I was looking for something like this in the past), so I left it on purpose.

**Review by jeanregisser — APPROVED** [review]
Wow scary bug! Great job 👏

File: packages/mobile/package.json (hunk 3 above)
Comment (gnardini) [reply packages/mobile/package.json:112]: Since it's a json I don't think we can leave comments :( I can add a link to this PR on the README of the forks so if someone's wondering they can go there to see why we forked them.

File: packages/mobile/package.json (hunk 4 above)
Comment (etuleu) [reply packages/mobile/package.json]: or a patch?

Comment (gnardini) [reply packages/mobile/package.json]: I didn't know about resolutions, this sounds like the perfect use case for it, I'll do that and delete the fork 😄

**Comment by Lss-Ankit** [comment]
Hi @etuleu @gnardini I have verified this issue using Android internal build V1.7.2(1004294329) & Test Flight Build V1.7.2(39) and observed that issue is still reproduced.
**Repro on devices:** Samsung Galaxy A5(7.0), iPhone 8(14.2)

**Comment by gnardini** [comment]
@Lss-Ankit are you sure this is reproducing? This was not happening on iOS in the first place. Could you check again and share a video if it happens please?

**Comment by Lss-Ankit** [comment]
Hi @gnardini I have verified  this issue on latest android internal build V1.7.2(1004294329) and observed the followings.

- User redirect to Home screen when user kill & relaunch app multiple times (30+ times ) if user is sign in & on Home screen. 

- User redirect to Home screen if user kill & relaunch app on Setting page. 
Let me know is it expected?
Attachment: [AppRestartFromFirstAfterRelaucn.mp4](https://drive.google.com/file/d/1Wq8eS65yBkT1TkfO_QEoR0931_yF_KfS/view?usp=sharing)

- User redirect to "Valora is a new way to send and receive value worldwide" welcome screen display when app is auto launch afer reset the valora app. 
Attachment: [WelcomeScreenAfterResettingAccount.mp4](https://drive.google.com/file/d/1GhQPlVYEnxaGhY_fSI9CSJDOyyj7FG0p/view?usp=sharing)

**Verified on devices:** Samsung Galaxy A5(7.0), Google Pixel XL (8.1), Samsung Galaxy M40(10.0)
Let me know if anything else need to check.
Thanks!!
