### PR TITLE
[Wallet] Fix stale escrow reclaim payment notifications

### LINKED ISSUE #953: Escrow Payments are not showing up correctly
### Expected Behavior

A user should only be prompted to resend or redeem if the person they invited has not verified

### Current Behavior

Even if an Escrowed payment is sent, the option to redeem it (in some cases for only $.05, in some cases for the full amount even though per bug reporter, the payment had been successfully redeemed)

### LINKED ISSUE #1089: Escrow payment notification reminder SMS is empty
### Expected Behavior

Not empty sms

### Current Behavior

Sends empty sms:
https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx#L34

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

- Fix stale escrow reclaim payment notifications
- Fix escrow reminder sms content

### Tested

Sent an invite, reclaimed it.
Sent a reminder, checked content

### Related issues

- Fixes #953 
- Fixes #1089 

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx [hunk 1]
```diff
@@ -22,25 +22,25 @@ type Props = OwnProps & WithNamespaces
...
         onPress: () => {
           CeloAnalytics.track(CustomEventNames.clicked_escrowed_payment_send_message)
           // TODO: open up whatsapp/text message slider with pre populated message
           try {
             if (Platform.OS === 'android') {
-              SendIntentAndroid.sendSms(recipientPhoneNumber, '')
+              SendIntentAndroid.sendSms(recipientPhoneNumber, t('escrowedPaymentReminderSms'))
             } else {
-              Linking.openURL(`sms:${recipientPhoneNumber}`)
+              Linking.openURL(`sms:${recipientPhoneNumber}&body=${t('escrowedPaymentReminderSms')}`)
```
Comment (jeanregisser) [inline packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx]: `body` argument used to work, but doesn't anymore.
See https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html
And https://stackoverflow.com/questions/16558187/iphone-url-scheme-with-content-body-to-sms

I guess just leave a comment about using `MFMessageComposeViewController` instead.

**Review by jeanregisser — APPROVED** [review]
Looking good! 👍  just a small issue with iOS.

File: packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx (hunk 1 above)
Comment (jmrossy) [reply packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx]: Will do!
