### PR TITLE
[Wallet] Fix firebase initialization error on iOS after reinstalling the app

### LINKED ISSUE #1420: Firebase initialization error while redeeming an invite code on iOS
### Expected Behavior

Firebase should initialize without an error when redeeming an invite code on iOS.

### Current Behavior

Firebase initialization triggers an error when redeeming an invite code on iOS.
This ends up displaying the error banner with `Couldn't connect to notification service`.

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Reset iOS keychain on first app run to fix firebase initialization error after reinstalling the app.

Here's what happened:
- on the very first run, redeeming an invite code worked successfully and
firebase could initialize correctly
- after the app is deleted and reinstalled, redeeming an invite code led to a firebase initialization error (permission error in the db)
- the reason for this is the firebase auth user for both session was the same since Firebase stores the auth credentials in the keychain which is not cleared when the app is uninstalled
- this had the consequence of the app referencing the old address in the `/users/$uid` path in the db, and hence causing subsequent permission errors as the rules for changing `/registrations/$address` or reading `/pendingRequests/$address` could not be satisfied (you can only read/write them if the address matches the address set in `/users/$uid`)

The fix here makes sure the keychain is cleared after a reinstall of the app and before we configure firebase (that's when it reads the persisted auth info from the keychain).

Note that react-native-secure-key-store is already ensuring the keychain is cleared on app reinstall but it's run too late (after firebase configure has been called).

### Tested

1. Reset the simulator completely
1. redeem an invite code, -> firebase initializes successfully
1. delete the app and reinstall it,
1. redeem an invite code, -> firebase initializes successfully (firebase auth user id is a new one)

### Other changes

N/A

### Related issues

- Fixes #1420

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/firebase/firebase.ts [hunk 1]
```diff
@@ -21,6 +21,10 @@ export const initializeAuth = async (app: Firebase, address: string) => {
   await userRef.child(user.user.uid).transaction((userData) => {
     if (userData == null) {
       return { address }
+    } else if (userData.address !== undefined && userData.address !== address) {
+      // This shouldn't happen! If this is thrown it means the firebase user is reused
+      // with different addresses (which we don't want) or the db was incorrectly changed remotely!
+      throw new Error("User address in the db doesn't match persisted address")
```
Comment (jmrossy) [inline packages/mobile/src/firebase/firebase.ts:27]: Just want to confirm that it was intentional to throw here instead of returning undefined? This callback is what will run on the db to modify the data. I don't think the error will propagate to the app, but I could be wrong. I'm uncertain what happens if we throw here.

Comment (jeanregisser) [reply packages/mobile/src/firebase/firebase.ts:27]: Good question! 
It triggers a red screen in dev, and it's not captured by the saga promise flow. 
It's logged by Sentry and crashes the app. Which is what I intended as I see it like a logic error which shouldn't happen.

**Review by jmrossy — APPROVED** [review]
