### PR TITLE
[contractkit] Fix signature with 0 padding

### LINKED ISSUE #3568: celocli releasegold:locked-gold failing with ledger
celocli v0.0.44

### Expected Behavior

`celocli releasegold:locked-gold --contract $CELO_VALIDATOR_GROUP_RG_ADDRESS --action lock --value 10000000000000000000000 --useLedger --ledgerCustomAddresses "[1]"`

Should work.

### Current Behavior
```
celocli releasegold:locked-gold --contract $CELO_VALIDATOR_GROUP_RG_ADDRESS --action lock --value 10000000000000000000000 --useLedger --ledgerCustomAddresses "[1]"
Retrieving derivation Paths [ 1 ]
Running Checks:
   :heavy_check_mark:  0x01b2b83fDf26aFC3Ca7062C35Bc68c8DdE56dB04 is a registered Account
   :heavy_check_mark:  Is not revoked
Running Checks:
   :heavy_check_mark:  Account has at least 10000 cGLD
Sending Transaction: lockedGoldLock... !
Error: Invalid JSON RPC response: {"id":16,"jsonrpc":"2.0"}
    at Object.InvalidResponse (~/.nvm/versions/node/v12.16.2/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:42:16)
    at ~/.nvm/versions/node/v12.16.2/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:144:36
    at decoratedCallback (~/.nvm/versions/node/v12.16.2/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/providers/celo-provider.js:101:13)
    at ~/.nvm/versions/node/v12.16.2/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/lib/utils/rpc-caller.js:50:13
```

### PR DESCRIPTION
**Pull request by gastonponti**
## Description

Fix: the s, and r fields of the signature can't be send it in the encode raw transaction without removing the 0 padding

## Related issues

Fixes #3568

### CODE REVIEW

File: packages/contractkit/src/utils/signing-utils.ts [hunk 1]
```diff
@@ -32,6 +32,32 @@ export function getHashFromEncoded(rlpEncode: string): string {
   return Hash.keccak256(rlpEncode)
 }
 
+function trimLeadingZero(hex: string) {
+  while (hex && hex.startsWith('0x0')) {
+    hex = '0x' + hex.slice(3)
```
Comment (codyborn) [inline packages/contractkit/src/utils/signing-utils.ts]: Can use `ensureLeading0x()` for this

**Review by codyborn — APPROVED** [review]

File: packages/contractkit/src/utils/signing-utils.ts (hunk 1 above)
Comment (gastonponti) [reply packages/contractkit/src/utils/signing-utils.ts]: Done
