### PR TITLE
[Wallet] Fix web3 syncing sagas

### LINKED ISSUE #808: Wait for web3 doesn't work when web3 false reports sync done

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

The current web3 sync saga would sometimes allow sagas waiting for web3 ready to proceed even before web3 is really ready, causing tx errors. This fixes that issue and cleans up a bit, particularly around the related redux state.

### Tested

Synced to Alfajores and sent a tx. Confirmed logs look right.

### Related issues

- Fixes #808 

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/networkInfo/saga.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export function* waitForRehydrate() {
 
 export function* waitWeb3LastBlock() {
   yield waitForGethConnectivity()
-  yield checkWeb3Sync()
+  yield waitForWeb3Sync()
```
Comment (jmrossy) [inline packages/mobile/src/networkInfo/saga.ts:20]: @cmcewen IIRC you recommended calling this `check` but `wait` is what it's really doing. Mind if we rename?

File: packages/mobile/src/web3/reducer.ts [hunk 2]
```diff
@@ -1,11 +1,10 @@
 import { getRehydratePayload, REHYDRATE, RehydrateAction } from 'src/redux/persist-helper'
-import { Actions, ActionTypes, UpdateWeb3SyncProgressAction } from 'src/web3/actions'
+import { Actions, ActionTypes } from 'src/web3/actions'
 
 export interface State {
-  syncProgress: number
-  syncProgressData: {
+  syncProgress: {
+    startingBlock: number
```
Comment (jmrossy) [inline packages/mobile/src/web3/reducer.ts:6]: @martinvol I aligned this to the names web3 uses, which you also use in `actions.ts`

File: packages/mobile/src/web3/saga.test.ts [hunk 3]
```diff
@@ -1,19 +1,13 @@
...
-  getLatestBlock,
-  setLatestBlockNumber,
-  setSyncProgress,
-  updateWeb3SyncProgress,
-} from 'src/web3/actions'
-import {
-  _CHECK_SYNC_PROGRESS_TIMEOUT,
-  _checkWeb3SyncProgressClaim,
-  checkWeb3Sync,
+  checkWeb3SyncProgress,
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.test.ts:7]: @martinvol I do like the convention of `_` before functions only exported to test, but until this VSCode bug gets fixed, it just causes a headache :(
https://github.com/prettier/prettier-vscode/issues/716
We'd need to either disable VS code import organizing entirely (would not recommend) or fix this file manually before lint will pass.
Suggest we table this convention for now.

File: packages/mobile/src/web3/saga.ts [hunk 4]
```diff
@@ -36,68 +34,67 @@ const MNEMONIC_BIT_LENGTH = (ETH_PRIVATE_KEY_LENGTH * 8) / 2
 
 const TAG = 'web3/saga'
 // The timeout for web3 to complete syncing and the latestBlock to be > 0
-const CHECK_SYNC_PROGRESS_TIMEOUT = 60000
+export const SYNC_TIMEOUT = 60000
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:37]: Renamed this mostly because of the same VScode import ordering bug mentioned above

File: packages/mobile/src/web3/saga.ts [hunk 5]
```diff
@@ -36,68 +34,67 @@ const MNEMONIC_BIT_LENGTH = (ETH_PRIVATE_KEY_LENGTH * 8) / 2
...
       if (error.toString().toLowerCase() === BLOCK_CHAIN_CORRUPTION_ERROR.toLowerCase()) {
         CeloAnalytics.track(CustomEventNames.blockChainCorruption, {}, true)
         const deleted = yield call(deleteChainData)
         if (deleted) {
           navigateToError('corruptedChainDeleted')
         }
-        throw new Error('Corrupted chain data encountered')
       } else {
-        Logger.error(TAG, `checking web3 sync progress: ${error}`)
+        Logger.error(TAG, 'Unexpected sync error', error)
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:73]: @martinvol it's better to provide the error as the 3rd param to Logger.error, which has special logic to extract and format the error message nicely

File: packages/mobile/src/web3/saga.ts [hunk 6]
```diff
@@ -36,68 +34,67 @@ const MNEMONIC_BIT_LENGTH = (ETH_PRIVATE_KEY_LENGTH * 8) / 2
...
       }
+      return false
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:75]: @martinvol previously, you were not throwing or returning false in this case, which allowed the calling function to finish as though syncing were done.

File: packages/mobile/src/web3/saga.ts [hunk 7]
```diff
@@ -36,68 +34,67 @@ const MNEMONIC_BIT_LENGTH = (ETH_PRIVATE_KEY_LENGTH * 8) / 2
...
+
+      // isSyncing returns a syncProgress object when it's still syncing, false otherwise
+      const syncProgress = yield web3.eth.isSyncing()
 
-        yield put(setSyncProgress(100))
-        return true
+      if (typeof syncProgress === 'boolean' && !syncProgress) {
+        Logger.debug(TAG, 'checkWeb3SyncProgress', 'Sync maybe complete, checking')
+
+        const latestBlock: Block = yield call(getLatestBlock)
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:52]: @martinvol I now check this here in the loop, to ensure the block number is correct before syncing is considered done. Previously, you did log an error but didn't actually stop the wrapper function from finishing (thus allowing other sagas to proceed)

File: packages/mobile/src/networkInfo/saga.ts (hunk 1 above)
Comment (cmcewen) [reply packages/mobile/src/networkInfo/saga.ts:20]: Volpe and I had a discussion about this - the reason I don't like using wait is that it actually makes a call to get the latest block to the geth node. Since I think we treat the `waitFor` generators as free in terms of cost, I would be wary of someone just adding this elsewhere and we end up doing a bunch of duplicate polling. I think `waitFor` should imply solely waiting on state changes.

File: packages/mobile/src/web3/saga.test.ts (hunk 3 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.test.ts:7]: Cool, no problem. Disabling VS code import organizing might not be a bad a idea since the pre-commit hook also sorts imports.

File: packages/mobile/src/web3/saga.ts [hunk 8]
```diff
@@ -36,68 +34,67 @@ const MNEMONIC_BIT_LENGTH = (ETH_PRIVATE_KEY_LENGTH * 8) / 2
 
 const TAG = 'web3/saga'
 // The timeout for web3 to complete syncing and the latestBlock to be > 0
-const CHECK_SYNC_PROGRESS_TIMEOUT = 60000
+export const SYNC_TIMEOUT = 60000
 const BLOCK_CHAIN_CORRUPTION_ERROR = "Error: CONNECTION ERROR: Couldn't connect to node on IPC."
```
Comment (martinvol) [inline packages/mobile/src/web3/saga.ts:38]: Can you remove this to a json as nice to have?

**Review by martinvol — APPROVED** [review]

File: packages/mobile/src/web3/saga.test.ts (hunk 3 above)
Comment (jmrossy) [reply packages/mobile/src/web3/saga.test.ts:7]: Yeah but the way it de-dupes imports for you and removes unused ones is really nice
