### PR TITLE
[Wallet] Fee fixes/refactor

### LINKED ISSUE #36: Pay request shows invalid total amount in some cases
### Current Behavior

When opting to pay X's request the below total amount showed as 0. After requesting a payment from someone and going through with that and then opening the pay request from X's again it is now showing the total correctly.

Screenshot_20190716-111958

### PR DESCRIPTION
**Pull request by jeanregisser**
This PR is relatively big, sorry for this 🙏 
Thanks @jmrossy for the discussions and early feedback that helped shape this PR!

### Description

**The problem**:
There is a single `suggestedFee` in the redux store used for both send and invite. 
Its value is not updated at appropriate times, or not at all, leading to issues like #36.
Also in `SendAmount`, the fee can be calculated too many times.

**This solution**:
The main idea is to have different types of (cached) estimated fees (right now for `send` and `invite`, later on for `exchange` and `escrow`) and trigger their update very infrequently depending on what flow the user is starting.
Then only when going to the `SendConfirmation` or `ReclaimPaymentConfirmationScreen` screens the actual fee is calculated once. Showing some feedback while it does it.

### Tested

Added/Updated tests.

Updated UI with loading/error feedback:
Screenshot_1564563361
Screenshot_1564650868
Screenshot_1564563456_censored(1)
Screenshot_1564762306
Screenshot_1564762309

### Other changes

N/A

### Related issues

- Fixes #36, #83, #113

### Backwards compatibility

Backward compatible.

### CODE REVIEW

**Comment by jeanregisser** [comment]
I haven't tackled the hardcoded fee in `InviteReview`
https://github.com/celo-org/celo-monorepo/blob/f272bc826af3bf73843f9d06cfe2da181e63cc1c/packages/mobile/src/account/InviteReview.tsx#L64-L65
and in `getInvitationVerificationFee`
https://github.com/celo-org/celo-monorepo/blob/f272bc826af3bf73843f9d06cfe2da181e63cc1c/packages/mobile/src/invite/saga.ts#L57-L60

I want to address those in a subsequent PR.

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+  params: Args,
+  showErrorFunction: typeof showError
+): UseAsyncReturn<R, Args> {
+  const asyncResult = useAsync(asyncFunction, params)
+
+  useEffect(
+    () => {
+      // Generic error banner
+      if (asyncResult.error) {
+        showErrorFunction(ErrorMessages.CALCULATE_FEE_FAILED, ERROR_BANNER_DURATION)
```
Comment (jmrossy) [inline packages/mobile/src/fees/CalculateFee.tsx:77]: This is a fine approach, just curious if there's a way to have the showError function be used directly here rather than passed in?

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+    },
+    [asyncResult.error]
+  )
+
+  return asyncResult
+}
+
+const CalculateInviteFee: FunctionComponent<DispatchProps & InviteProps> = (props) => {
+  const asyncResult = useAsyncShowError(getInvitationVerificationFee, [], props.showError)
+  return props.children(asyncResult)
```
Comment (jmrossy) [inline packages/mobile/src/fees/CalculateFee.tsx]: Leave a TODO here for doing this part? Can you create a Github issue to track please :)

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+}
+
+const CalculateSendFee: FunctionComponent<DispatchProps & SendProps> = (props) => {
+  const asyncResult = useAsyncShowError(
+    async (account: string, recipientAddress: string, amount: BigNumber, comment: string) =>
```
Comment (jmrossy) [inline packages/mobile/src/fees/CalculateFee.tsx]: Why is this function async? We don't seem to use await. If getSendFee returns a promise maybe return that directly

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+      return <CalculateInviteFee {...props} />
+    case FeeType.SEND:
+      return <CalculateSendFee {...props} />
+    case FeeType.RECLAIM_ESCROW:
+      return <CalculateReclaimEscrowFee {...props} />
+    case FeeType.EXCHANGE:
+      return null
+  }
+
+  return null
```
Comment (jmrossy) [inline packages/mobile/src/fees/CalculateFee.tsx]: Consider throwing an error here. We have an error boundary set up for the app

File: packages/mobile/src/fees/actions.ts [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+}
+
+export enum FeeType {
+  INVITE = 'invite',
+  SEND = 'send',
+  EXCHANGE = 'exchange',
+  RECLAIM_ESCROW = 'reclaim-escrow',
+}
+
+export interface UpdateDefaultFeeAction {
```
Comment (jmrossy) [inline packages/mobile/src/fees/actions.ts]: The term `Default` is confusing me a bit here. What do you mean by default fee?

File: packages/mobile/src/fees/saga.test.ts [hunk 6]
```diff
@@ -0,0 +1,32 @@
+import { expectSaga } from 'redux-saga-test-plan'
+import { call } from 'redux-saga/effects'
+import { defaultFeeUpdated, FeeType, updateDefaultFee } from 'src/fees/actions'
+import { watchUpdateDefaultFee } from 'src/fees/saga'
+import { getInvitationVerificationFee } from 'src/invite/saga'
+
+// jest.mock('src/utils/time', () => ({
```
Comment (jmrossy) [inline packages/mobile/src/fees/saga.test.ts]: Remove dead code here

File: packages/mobile/src/fees/saga.ts [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+import { getSendFee } from 'src/send/saga'
+import { CeloDefaultRecipient } from 'src/send/Send'
+import Logger from 'src/utils/Logger'
+
+const TAG = 'fees/saga'
+
+export function* updateDefaultFeeSaga({ feeType }: UpdateDefaultFeeAction) {
+  Logger.debug(TAG + '@updateDefaultFeeSaga', 'updating for ', feeType)
+
+  // TODO: skip fee update if it was calculated recently
```
Comment (jmrossy) [inline packages/mobile/src/fees/saga.ts:15]: Yeah I think we should also store a timestamp for each fee type and check that here

File: packages/mobile/src/fees/selectors.ts [hunk 8]
```diff
@@ -0,0 +1,47 @@
+import BigNumber from 'bignumber.js'
+import { createSelector } from 'reselect'
+import { FeeType } from 'src/fees/actions'
+import { RootState } from 'src/redux/reducers'
+import { divideByWei } from 'src/utils/formatting'
+
+const getInviteFeeEstimate = (state: RootState) => state.fees.invite.feeInWei
```
Comment (jmrossy) [inline packages/mobile/src/fees/selectors.ts]: For clarity, can we append `InWei` to these names?

**Review by jmrossy — COMMENTED** [review]
Very nice!! Just some small comments/questions below

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 1 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx:77]: Yes using `react-redux >= 7.1.0` and its support for [hooks](https://react-redux.js.org/api/hooks#usedispatch), I wanted to do that first but held off as I felt this PR was too big already to couple with a major update of `react-redux`

File: packages/mobile/src/fees/actions.ts (hunk 5 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/actions.ts]: I agree. I think Estimate is appropriate.
What do you think?

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 3 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: Good catch, `async` is unnecessary here.

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 2 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: I'm not following, which part?

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 4 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: Sounds good!

File: packages/mobile/src/fees/saga.test.ts (hunk 6 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/saga.test.ts]: Yep!

File: packages/mobile/src/fees/selectors.ts (hunk 8 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/selectors.ts]: Yes!

File: packages/mobile/src/fees/saga.ts (hunk 7 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/saga.ts:15]: Yes! Do you mind if I do it in another PR?

Comment (jmrossy) [reply packages/mobile/src/fees/saga.ts:15]: Another Pr makes sense :)

File: packages/mobile/src/fees/actions.ts (hunk 5 above)
Comment (jmrossy) [reply packages/mobile/src/fees/actions.ts]: Estimate sgtm

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 2 above)
Comment (jmrossy) [reply packages/mobile/src/fees/CalculateFee.tsx]: My bad, misunderstood this line. Nvm

File: packages/mobile/locales/es-AR/global.json [hunk 9]
```diff
@@ -82,5 +82,6 @@
   "qrFailedNoAddress":
     "Código QR no se pudo leer. Motivo: no se encontró la dirección de la billetera.",
   "qrFailedInvalidAddress":
-    "Código QR no se pudo leer. Razón: la dirección de la cartera no es válida."
+    "Código QR no se pudo leer. Razón: la dirección de la cartera no es válida.",
+  "calculateFeeFailed": "No se pudo calcular la tarifa"
```
Comment (martinvol) [inline packages/mobile/locales/es-AR/global.json]: "la tarifa" -> "la comisión"

Comment (jeanregisser) [reply packages/mobile/locales/es-AR/global.json]: Thanks @martinvol :+1:

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 1 above)
Comment (jmrossy) [reply packages/mobile/src/fees/CalculateFee.tsx:77]: Agreed

**Comment by jeanregisser** [comment]
I addressed all existing comments.

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 10]
```diff
@@ -0,0 +1,133 @@
...
+import { connect } from 'react-redux'
+import { showError } from 'src/alert/actions'
+import { ErrorMessages } from 'src/app/ErrorMessages'
+import { ERROR_BANNER_DURATION } from 'src/config'
+import { getReclaimEscrowFee } from 'src/escrow/saga'
+import { FeeType } from 'src/fees/actions'
+import { getInvitationVerificationFee } from 'src/invite/saga'
+import { getSendFee } from 'src/send/saga'
+
+export type CalculateFeeChildren = (asyncResult: UseAsyncReturn<BigNumber, never>) => any
```
Comment (cmcewen) [inline packages/mobile/src/fees/CalculateFee.tsx]: Will `React.ReactNode` work here instead of any?

File: packages/mobile/src/send/SendAmount.tsx [hunk 11]
```diff
@@ -241,6 +233,10 @@ export class SendAmount extends React.PureComponent<Props, State> {
     }
 
     const confirmationInput = this.getConfirmationInput()
+    if (!confirmationInput) {
+      return
```
Comment (cmcewen) [inline packages/mobile/src/send/SendAmount.tsx]: what could cause a failure case here? should we throw?

File: packages/mobile/src/send/SendConfirmation.tsx [hunk 12]
```diff
@@ -176,34 +181,34 @@ class SendConfirmation extends React.Component<Props, State> {
...
-    const userHasEnough = amountWithFees.isLessThanOrEqualTo(currentBalance)
+    const fee = asyncFee.result && getFeeDollars(asyncFee.result)
+    const amountWithFee = new BigNumber(numeral(amount).value()).plus(fee || 0)
+    const userHasEnough = !asyncFee.loading && amountWithFee.isLessThanOrEqualTo(currentBalance)
     const { isPaymentRequest } = this.getNavParams()
     let primaryBtnInfo = {
       action: this.onSendButtonClick,
       text: t('send'),
-      disabled: isSending || !userHasEnough || !appConnected,
+      disabled: isSending || !userHasEnough || !appConnected || !!asyncFee.error,
```
Comment (cmcewen) [inline packages/mobile/src/send/SendConfirmation.tsx]: dupe logic with below - assign to a variable

File: packages/mobile/src/send/SendConfirmation.tsx [hunk 13]
```diff
@@ -176,34 +181,34 @@ class SendConfirmation extends React.Component<Props, State> {
...
-    const { amount, reason, recipient, recipientAddress, fee } = this.getConfirmationInput()
+    const { amount, reason, recipient, recipientAddress } = this.getConfirmationInput()
 
     const currentBalance = this.props.dollarBalance
-    const amountWithFees = new BigNumber(numeral(amount).value()).plus(
-      this.props.suggestedFeeDollars
-    )
-    const userHasEnough = amountWithFees.isLessThanOrEqualTo(currentBalance)
+    const fee = asyncFee.result && getFeeDollars(asyncFee.result)
+    const amountWithFee = new BigNumber(numeral(amount).value()).plus(fee || 0)
```
Comment (cmcewen) [inline packages/mobile/src/send/SendConfirmation.tsx:190]: just to be clear - the intention here would be to show the amount the user has already entered while we are calculating the fee, and then update once the fee has been calculated? just wondering if seeing a number jump would be a bad UX, and we should just show loading instead (which is maybe covered by that isLoadingFee?)

File: packages/mobile/src/send/SendConfirmation.tsx [hunk 14]
```diff
@@ -248,6 +255,21 @@ class SendConfirmation extends React.Component<Props, State> {
       </View>
     )
   }
+
+  render() {
+    const { account } = this.props
+    if (!account) {
+      throw Error('Account is required')
```
Comment (cmcewen) [inline packages/mobile/src/send/SendConfirmation.tsx:263]: Similar question on error handling - when will we ever reach this state?

**Review by cmcewen — COMMENTED** [review]
Very nice! Would you feel comfortable walking the team through this one at some point as an optional intro to hooks?

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 10 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: Let me try.

File: packages/mobile/src/send/SendAmount.tsx (hunk 11 above)
Comment (jeanregisser) [reply packages/mobile/src/send/SendAmount.tsx]: Good catch I don't need this anymore. I had to add this when `fee` was part of `ConfirmationInput`. But I've now removed it.

File: packages/mobile/src/send/SendConfirmation.tsx (hunk 12 above)
Comment (jeanregisser) [reply packages/mobile/src/send/SendConfirmation.tsx]: Yep 👍

File: packages/mobile/src/send/SendConfirmation.tsx (hunk 13 above)
Comment (jeanregisser) [reply packages/mobile/src/send/SendConfirmation.tsx:190]: Good point. 
What's happening right now is the send fee is so small it displays as `$0.0000` after loading and the total doesn't change.
The invite fee though is more but since it's [currently hardcoded](https://github.com/celo-org/celo-monorepo/blob/f272bc826af3bf73843f9d06cfe2da181e63cc1c/packages/mobile/src/invite/saga.ts#L57-L60), there's no loading indicator happening.

With the way the UI is done currently, I think the fact that the total can change after the fee has loaded shouldn't be surprising for the user.
But we need to confirm this. If it's a problem we can tweak this.

File: packages/mobile/src/send/SendConfirmation.tsx (hunk 14 above)
Comment (jeanregisser) [reply packages/mobile/src/send/SendConfirmation.tsx:263]: This could never happen to our users (unless we mess something and `SendConfirmation` is displayed before an account is created 😸)

Do you have another way to handle this?

**Comment by jeanregisser** [comment]
@cmcewen I'll have a better example of hooks soon which will be short and simple and would convey the advantage of using them.

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 10 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: Here it is: https://github.com/celo-org/celo-monorepo/commit/fcbc7ab871bf9f43876722957006fa311f4188f6
It caused another type issue, which I worked around with a cast.
Anyway definitely better with `ReactNode` 👍

**Comment by jeanregisser** [comment]
Latest master with reclaim escrowed has been merged and tested end-to-end successfully! (updated the screenshots in the description).

It's all looking good to me here.

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 15]
```diff
@@ -0,0 +1,135 @@
...
+  switch (props.feeType) {
+    case FeeType.INVITE:
+      return <CalculateInviteFee {...props} />
+    case FeeType.SEND:
+      return <CalculateSendFee {...props} />
+    case FeeType.RECLAIM_ESCROW:
+      return <CalculateReclaimEscrowFee {...props} />
+  }
+
+  // @ts-ignore
```
Comment (jmrossy) [inline packages/mobile/src/fees/CalculateFee.tsx]: Why ts-ignore here?

File: packages/mobile/src/fees/CalculateFee.tsx [hunk 16]
```diff
@@ -0,0 +1,135 @@
...
+  throw new Error(`Unsupported feeType: ${props.feeType}`)
+
+  return null
```
Comment (jmrossy) [inline packages/mobile/src/fees/CalculateFee.tsx]: no need for return after throw

File: packages/mobile/src/fees/saga.ts [hunk 17]
```diff
@@ -0,0 +1,50 @@
...
+        recipientAddress: CeloDefaultRecipient.address,
+        amount: '1',
+        comment: 'Coffee or Tea?',
+      })
+      break
+    case FeeType.EXCHANGE:
+      // TODO
+      break
+    case FeeType.RECLAIM_ESCROW:
+      // TODO
```
Comment (jmrossy) [inline packages/mobile/src/fees/saga.ts]: Did you mean to leave this as TODO? It looks like you more or less implemented it already

File: packages/mobile/src/send/SendConfirmation.tsx (hunk 14 above)
Comment (jmrossy) [reply packages/mobile/src/send/SendConfirmation.tsx:263]: We generally don't do much invariant checking in our render functions. And account is something that we can generally rely on being set up properly. I'd recommend just removing this check

**Review by jmrossy — COMMENTED** [review]
A few small questions/comments but mostly LGTM

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 15 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: TypeScript complains about `feeType` not being present, though it's present on all types of the distinct union. I think I can improve this a little bit and get rid of `@ts-ignore`.

File: packages/mobile/src/fees/saga.ts (hunk 17 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/saga.ts]: True. Though we're not yet using the estimate for this fee type, I'll add it for completeness.

File: packages/mobile/src/send/SendConfirmation.tsx (hunk 14 above)
Comment (jeanregisser) [reply packages/mobile/src/send/SendConfirmation.tsx:263]: We can't really remove it otherwise TS complains about `account` which can be null.

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 15 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: Hum looks like it doesn't complain anymore. I guess it was a specific condition in a previous iteration that made me add that.

File: packages/mobile/src/fees/CalculateFee.tsx (hunk 16 above)
Comment (jeanregisser) [reply packages/mobile/src/fees/CalculateFee.tsx]: Indeed, removing it.

**Review by jmrossy — APPROVED** [review]
Ship it!

**Comment by isabellewei** [comment]
I think this also fixes #112 and #110 ?

**Comment by jeanregisser** [comment]
Not directly, the fee for the invite is still using the [hardcoded values](https://github.com/celo-org/celo-monorepo/pull/276#issuecomment-517271997).
