### PR TITLE
Validate Attestation Requests

### LINKED ISSUE #1073: Users SNBAT send duplicated messages to the attestation service
### Expected Behavior

There should be some intelligent behavior around this

- [ ] Protect by normalizing/verifying e164 and account address format

### Current Behavior

Users can simply send the same attestation request multiple times and it would result in multiple text messages

### LINKED ISSUE #1074: Users SNBAT send invalid attestation requests
### Expected Behavior

Users should get a 401

### Current Behavior

Users can send invalid attestation requests

### LINKED ISSUE #1075: Users SBAT receive proper HTTP codes for errors
### Expected Behavior

We should only process requests that are well-formed and return 422.
If an exception occurs we should return 500

### Current Behavior

There is no proper parsing of request parameters.
When exceptions happen, we don't send anything back either.

### PR DESCRIPTION
**Pull request by nambrot**
### Description

This PR adds more validation of attestation requests. Specifcally it checks for:
- well formed requests
- validity of the requests on the `Attestations` contracts
- check if we already sent the SMS before

### Tested

- Ran locally with attestation requests on integration

### Related issues

- Fixes #1073 
- Fixes #1074
- Fixes #1075

### CODE REVIEW

File: packages/attestation-service/src/attestation.ts [hunk 1]
```diff
@@ -1,38 +1,128 @@
...
+  return process.env.ATTESTATION_KEY
+}
+
+async function validateAttestationRequest(request: AttestationRequest) {
+  // check if it exists in the database
+  if (
+    (await existingAttestationRequest(request.phoneNumber, request.account, request.issuer)) !==
+    null
+  ) {
+    throw new Error('Attestation already sent')
```
Comment (jmrossy) [inline packages/attestation-service/src/attestation.ts:34]: So this implies users cannot request another delivery if the SMS did not arrive?

File: packages/attestation-service/src/attestation.ts [hunk 2]
```diff
@@ -1,38 +1,128 @@
...
-  // TODO: Should parse request appropriately
-
-  // TODO: Should validate request here
-  // const attestations = await kit.contracts.getAttestations()
-
-  // Produce attestation
-  const attestationCode = signAttestation(req.body.phoneNumber, req.body.account)
-  const textMessage = createAttestationTextMessage(attestationCode)
+export async function handleAttestationRequest(
+  _req: express.Request,
```
Comment (jmrossy) [inline packages/attestation-service/src/attestation.ts:91]: why the underscore?

File: packages/attestation-service/src/attestation.ts [hunk 3]
```diff
@@ -1,38 +1,128 @@
...
-  // Send the SMS
-  await retryAsyncWithBackOff(sendSms, 10, [req.body.phoneNumber, textMessage], 1000)
+  try {
+    const textMessage = createAttestationTextMessage(attestationCode)
+    await persistAttestationRequest(
+      attestationRequest.phoneNumber,
+      attestationRequest.account,
+      attestationRequest.issuer
+    )
+    await retryAsyncWithBackOff(sendSms, 10, [attestationRequest.phoneNumber, textMessage], 1000)
```
Comment (jmrossy) [inline packages/attestation-service/src/attestation.ts:113]: Nit: wrapping the phone number and txt message in an array seems odd to me

File: packages/attestation-service/src/attestation.ts [hunk 4]
```diff
@@ -1,38 +1,128 @@
...
+  } catch (error) {
+    console.error(error)
+    res
+      .status(500)
+      .json({
+        success: false,
+        error: 'Something went wrong while attempting to send SMS, try again later',
+      })
+      .status(422)
```
Comment (jmrossy) [inline packages/attestation-service/src/attestation.ts]: did you mean to include this here?

File: packages/attestation-service/src/db.ts [hunk 5]
```diff
@@ -20,3 +20,21 @@ export function initializeKit() {
     kit = newKit(fetchEnv('CELO_PROVIDER'))
   }
 }
+
+export async function existingAttestationRequest(
+  phoneNumber: string,
+  account: string,
+  issuer: string
+): Promise<AttestationStatic | null> {
+  const AttestationTable = await Attestation(sequelize!)
```
Comment (jmrossy) [inline packages/attestation-service/src/db.ts]: Don't know anything about sequelize, just wondering if it'd be better to cache this AttestationTable object instead of recreating it? maybe a  non-issue

File: packages/attestation-service/src/models/index.js [hunk 6]
```diff
@@ -0,0 +1,36 @@
+'use strict'
```
Comment (jmrossy) [inline packages/attestation-service/src/models/index.js]: This looks like a compiled file. Why is this here?

File: packages/attestation-service/src/request.ts [hunk 7]
```diff
@@ -0,0 +1,83 @@
+import { isE164NumberStrict } from '@celo/utils/lib/phoneNumbers'
+import { isValidAddress } from '@celo/utils/lib/signatureUtils'
+import express from 'express'
+import { either, isLeft } from 'fp-ts/lib/Either'
+import * as t from 'io-ts'
+
+export function parseRequest<T>(
```
Comment (jmrossy) [inline packages/attestation-service/src/request.ts]: Is this some kind of fp-ts pattern? This structure of a function that returns a function which uses another function as a param seems more complex than it has to be.

File: packages/attestation-service/src/attestation.ts (hunk 1 above)
Comment (nambrot) [reply packages/attestation-service/src/attestation.ts:34]: Correct, not at this moment, though we could consider circumstances in which the user could re-request.

File: packages/attestation-service/src/attestation.ts (hunk 2 above)
Comment (nambrot) [reply packages/attestation-service/src/attestation.ts:91]: In typescript (and many other languages), a leading underscore indicates the parameter not being used. Not prefixing is I believe a lint violation (or maybe even compiler?)

File: packages/attestation-service/src/attestation.ts (hunk 3 above)
Comment (nambrot) [reply packages/attestation-service/src/attestation.ts:113]: That's our current interface into `retryAsyncWithBackOff` which I don't think we have much alternative to unless we convert all our functions to only take one argument?

File: packages/attestation-service/src/attestation.ts (hunk 4 above)
Comment (nambrot) [reply packages/attestation-service/src/attestation.ts]: I did not!

File: packages/attestation-service/src/db.ts (hunk 5 above)
Comment (nambrot) [reply packages/attestation-service/src/db.ts]: I personally don't like global caching too much so eventually there should probably be a cache manager, but I figured for now it's no big deal

File: packages/attestation-service/src/models/index.js (hunk 6 above)
Comment (nambrot) [reply packages/attestation-service/src/models/index.js]: It's a generated file by sequelize scaffold. It looks like it is supposed to give unified access to all the models, but since we are not using that, I will remove the file

File: packages/attestation-service/src/request.ts (hunk 7 above)
Comment (nambrot) [reply packages/attestation-service/src/request.ts]: I actually tried to minimize the style impact of fp-ts here, so this should mostly be a single-level function composition. Basically, when one writes an express handler, a developer would have to do some amount of logic to validate that the request has the right payload, types, etc.

To avoid that duplicated logic, a developer could use `parseRequest(RequestType, processor)` to receive the parsed request as a third argument. So IMO you get the benefit of declarative routes in https://github.com/celo-org/celo-monorepo/pull/1468/files#diff-8b9f369026f23d51728f7ad563386fdcR22, while the actual request handler has to not deal with the validation of the request payload and can just rely on it been validated by `parseRequest` https://github.com/celo-org/celo-monorepo/pull/1468/files#diff-881b8cc344bdb8ee0e96c73fb379ee6fR94

File: packages/attestation-service/src/attestation.ts (hunk 1 above)
Comment (jmrossy) [reply packages/attestation-service/src/attestation.ts:34]: Re-requesting is a pretty useful debugging tool for verification atm. I'd say (anecdotally) half the time I get 2/3, the third comes if I retry verification. So a better alternative here would be a retry threshold, which could be just 1 time for now. But I understand that's a fair bit more complexity here so open to deferring that to another PR if you prefer

File: packages/attestation-service/src/attestation.ts (hunk 2 above)
Comment (jmrossy) [reply packages/attestation-service/src/attestation.ts:91]: huh, didn't know that!

File: packages/attestation-service/src/attestation.ts (hunk 3 above)
Comment (jmrossy) [reply packages/attestation-service/src/attestation.ts:113]: if we make change to signature to move up the delay param and then have `...args` for the rest, we won't need to wrap the params. But it's nbd

File: packages/attestation-service/src/db.ts (hunk 5 above)
Comment (jmrossy) [reply packages/attestation-service/src/db.ts]: If you but it above in the global scope, it's not actually global caching, it's module level caching, which is totally fine. If you don't export the cache var, it won't pollute your global scope. I think the bias against is mostly a holdover from browser days when the polluting the global scope was a big issue. 
But yeah really nbd, just a thought.

File: packages/attestation-service/src/attestation.ts [hunk 8]
```diff
@@ -1,38 +1,125 @@
...
+  }
+
+  const attestations = await kit.contracts.getAttestations()
+  const state = await attestations.getAttestationState(
+    request.phoneNumber,
+    request.account,
+    request.issuer
+  )
+
+  console.info(state)
```
Comment (jmrossy) [inline packages/attestation-service/src/attestation.ts]: Should this be here?

File: packages/attestation-service/src/request.ts (hunk 7 above)
Comment (jmrossy) [reply packages/attestation-service/src/request.ts]: Okay seems reasonable. I guess I may just have been thrown off by the names them. Maybe `handler` is a more conventional name for `processor` and `createValidatedHandler` is a more accurate name than `parseRequest`? Unless these are fp-ts terms

File: packages/attestation-service/src/db.ts (hunk 5 above)
Comment (nambrot) [reply packages/attestation-service/src/db.ts]: I changed it to module level caching!

File: packages/attestation-service/src/request.ts (hunk 7 above)
Comment (nambrot) [reply packages/attestation-service/src/request.ts]: Nope, they are just @nambrot™ , so changed them to your suggestion!

File: packages/attestation-service/src/attestation.ts (hunk 8 above)
Comment (nambrot) [reply packages/attestation-service/src/attestation.ts]: Nope (at least not in this form)

File: packages/attestation-service/src/attestation.ts (hunk 1 above)
Comment (nambrot) [reply packages/attestation-service/src/attestation.ts:34]: Would prefer to keep this out for another PR. Raised https://github.com/celo-org/celo-monorepo/issues/1502 for it.

**Review by jmrossy — APPROVED** [review]
