### PR TITLE
[WIP][ContractKit]Add ability to do local signing

### LINKED ISSUE #186: User SBAT to transfer Celo Gold/Celo Dollars via ContractKit using locally signed transactions
### Expected Behavior

User SBAT to transfer Celo Gold/Celo Dollars via ContractKit using locally signed transactions. This allows the wallet to operate in an infura-like setup.

### Current Behavior

1. ~~The code is there but is currently broken.~~  - The code was correct. The test was broken and that has been fixed. 
2. The API can be improved.

### LINKED ISSUE #477: New ContractKit SBAT support locally signed transactions
### Expected Behavior

Port locally signed tx support from walletkit

Some additions:
 * Support more than one account
 * Change signing logic. See 0x subprovider sign function and adapt it
 * contractkit should have a method to add new accoutns

### Current Behavior

Only exists in walletkit

### LINKED ISSUE #811: Bug: tx-signing test leave open web3 polling connection
### Expected Behavior

When we run `yarn test` in contractkit, test should run & stop. 

### Current Behavior

Test don't stop. and start outputing invalid JSON response errors. 

Related to #810

### PR DESCRIPTION
**Pull request by ashishb**
### Description

1. Add the ability to do a local signing
2. Add ability to send signed transactions
3. Stop `Web3ProviderEngine` after the test, instead of `forceExit`
4. Minor code cleanup

### Tested

`jest src/utils/tx-signing.test.ts` 

### Related issues

- Fixed #186 
- Fixes #477
- Fixed #811

### CODE REVIEW

File: packages/contractkit/src/utils/web3-utils.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ import { CeloProvider } from './tx-signing'
 const debug = debugFactory('kit:web3:utils')
 
 // This web3 has signing ability.
-export async function addLocalAccount(web3: Web3, privateKey: string): Promise<Web3> {
+export function addLocalAccount(web3: Web3, privateKey: string): Web3 {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts:8]: nice.. you removed the async

File: packages/contractkit/src/kit.ts [hunk 2]
```diff
@@ -67,6 +73,38 @@ export class ContractKit {
     return toTxResult(promiEvent)
   }
 
+  async sendSignedTransaction(tx: Tx): Promise<TransactionResult> {
```
Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: i don't like this.
IMO, tx signing should be transparent, not something that you "say explicitly". You are already saying that when you use `from` with a local account

Comment (ashishb) [reply packages/contractkit/src/kit.ts]: > You are already saying that when you use from with a local account

Not exactly true, as of now, someone might still want to have an account in both web3 as well as a locally running geth node and would want to sign to using the geth node. I can merge these two into one but I am sure someone later is going to demand the other use-case.

Comment (mcortesi) [reply packages/contractkit/src/kit.ts]: why would something want like.. I think that's kind of a contrived example.

One should be able to do:

```ts
const stableToken = kit.contract.getStableToken()

const tx = await stableToken.transfer(value, to).send()

```

and that `send()` use a local account or not, depending on the `from`. which in this example is the default, but you can also do `.send({from: someAccount})`

File: packages/contractkit/src/kit.ts [hunk 3]
```diff
@@ -67,6 +73,38 @@ export class ContractKit {
...
+    const gasFeeRecipient = await this.web3.eth.getCoinbase()
```
Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: this should happen on the provider, not at `kit` level.
so, if i use web3 directly, i can still send a tx

Comment (mcortesi) [reply packages/contractkit/src/kit.ts]: forget about this.... can happen either place! :P

File: packages/contractkit/src/test-utils/ganache-test.ts [hunk 4]
```diff
@@ -1,10 +1,20 @@
+import { Web3ProviderEngine } from '@0x/subproviders'
 import Web3 from 'web3'
 import { JsonRPCResponse } from 'web3/providers'
 import { injectDebugProvider } from '../providers/debug-provider'
 
 export function jsonRpcCall<O>(web3: Web3, method: string, params: any[]): Promise<O> {
   return new Promise<O>((resolve, reject) => {
-    web3.currentProvider.send(
+    let currentProvider = web3.currentProvider
```
Comment (mcortesi) [inline packages/contractkit/src/test-utils/ganache-test.ts]: this shouldn't be addressed here....
for `jsonRpcCall` a provider is always a provider and all provider follow the same interface :P

File: packages/contractkit/src/utils/tx-signing.ts [hunk 5]
```diff
@@ -22,17 +29,65 @@ function getPrivateKeyWithout0xPrefix(privateKey: string) {
...
     this.celoPrivateKey = '0x' + getPrivateKeyWithout0xPrefix(privateKey)
+    this.accountAddress = generateAccountAddressFromPrivateKey(this.celoPrivateKey).toLowerCase()
+  }
+
+  public getAccounts(): string[] {
+    return [this.accountAddress]
+  }
+
+  // Note: This method is async since it over-rides the parent async method.
+  public async getAccountsAsync(): Promise<string[]> {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.ts]: why this?

File: packages/contractkit/src/utils/tx-signing.ts [hunk 6]
```diff
@@ -22,17 +29,65 @@ function getPrivateKeyWithout0xPrefix(privateKey: string) {
...
+  }
+
+  public async handleRequest(
+    payload: JSONRPCRequestPayload,
+    next: Callback,
+    end: ErrorCallback
+  ): Promise<void> {
+    let signingRequired = false
+    switch (payload.method) {
+      case 'eth_sendTransaction': // fallthrough
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.ts]: style: do `signingRequired = ['a','b','c'...].includes(method)`

File: packages/contractkit/src/utils/web3-utils.ts [hunk 7]
```diff
@@ -12,24 +12,95 @@ import { CeloProvider } from './tx-signing'
...
+    providerEngine = createNewProviderWithLocalAccount(existingProvider, celoProvider)
+    web3.setProvider(providerEngine)
+  }
+
+  providerEngine.start()
+  debug('Providers configured')
+  return web3
+}
+
+function addLocalAccountToExistingProvider(
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: I think we can do this whole design better...

We can have:
`web3.currentProvider instanceOf CeloProvider`

And then create a CeloProvider, that internally proxies everything to the ProviderEngine, has a reference to the Transport/original provider. Knows the accounts, has a `addAccount()` method... etc.

Comment (mcortesi) [reply packages/contractkit/src/utils/web3-utils.ts]: the current code seems unnecessarily complex

File: packages/contractkit/src/utils/tx-signing.ts (hunk 6 above)
Comment (ashishb) [reply packages/contractkit/src/utils/tx-signing.ts]: Done

File: packages/contractkit/src/utils/tx-signing.ts (hunk 5 above)
Comment (ashishb) [reply packages/contractkit/src/utils/tx-signing.ts]: Not required, I added it for brevity. Since I added a `sync` version. I am going to replace this with just a comment, how about that?

File: packages/contractkit/src/utils/web3-utils.ts (hunk 7 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: Good point. I am changing `CeloProvider` to `CeloPrivateKeyWalletProvider` and adding a new `CeloProvider` which hides all this complexity.

File: packages/contractkit/src/test-utils/ganache-test.ts (hunk 4 above)
Comment (ashishb) [reply packages/contractkit/src/test-utils/ganache-test.ts]: Fair point. I moved this ugliness back into `tx-signing.test.ts`

File: packages/contractkit/src/kit.ts (hunk 3 above)
Comment (ashishb) [reply packages/contractkit/src/kit.ts]: Added them to `signTransactionAsync`. Also, removed `sendSignedTransaction` and added `gasFeeRecipient` calculation to `sendTransaction`. This makes that method async though.

File: packages/contractkit/src/kit.ts (hunk 2 above)
Comment (ashishb) [reply packages/contractkit/src/kit.ts]: I removed `sendSignedTransaction` completely. It should not be required at all (as confirmed by the unittest ts-signing.test.ts as well)

File: packages/contractkit/src/utils/tx-signing.ts (hunk 5 above)
Comment (ashishb) [reply packages/contractkit/src/utils/tx-signing.ts]: Also changes `getAccounts` to be `getAccount` why return a singleton array.

File: packages/contractkit/src/kit.ts [hunk 8]
```diff
@@ -49,24 +51,47 @@ export class ContractKit {
...
+    addLocalAccount(this.web3, privateKey)
+  }
+
   setGasCurrencyAddress(address: Address) {
     this._defaultOptions.gasCurrency = address
   }
 
-  sendTransaction(tx: Tx): TransactionResult {
+  async sendTransaction(tx: Tx): Promise<TransactionResult> {
+    const gasFeeRecipient = await this.web3.eth.getCoinbase()
```
Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: we should avoid doing all this work if the tx is not locally signed. since the node will on that case fill the gap. Neither should we fail if it's not a locally signed tx

File: packages/contractkit/src/kit.ts [hunk 9]
```diff
@@ -49,24 +51,47 @@ export class ContractKit {
...
+      // @ts-ignore
+      gasFeeRecipient: this.defaultOptions.gasFeeRecipient,
       // TODO needed for locally signed tx, ignored by now (celo-blockchain with set it)
       // gasFeeRecipient: this.defaultOptions.gasFeeRecipient,
       ...tx,
     })
     return toTxResult(promiEvent)
   }
 
+  async getGasPrice(gasCurrency: string | undefined): Promise<string | undefined> {
```
Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: use `getGasPrice(gasCurrency?: string)` instead of using `undefined`

Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: Add a jsdoc stating what it means to use gasCurrency parameter or not

File: packages/contractkit/src/kit.ts [hunk 10]
```diff
@@ -49,24 +51,47 @@ export class ContractKit {
...
+    // Gold Token
+    if (gasCurrency === undefined) {
+      return String(await this.web3.eth.getGasPrice())
```
Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: why the `String()`?

File: packages/contractkit/src/kit.ts (hunk 9 above)
Comment (mcortesi) [inline packages/contractkit/src/kit.ts]: when is `undefined` a valid return type???

File: packages/contractkit/src/test-utils/ganache-test.ts (hunk 4 above)
Comment (mcortesi) [reply packages/contractkit/src/test-utils/ganache-test.ts]: i still see the ugliness :P
```ts
if (currentProvider instanceof Web3ProviderEngine) {
      const providerEngine = web3.currentProvider as Web3ProviderEngine
      // @ts-ignore-next-line - I have to access private `_providers` variable
      currentProvider = providerEngine._providers.slice(-1)[0]._provider
    }
```

File: packages/contractkit/src/utils/tx-signing.ts [hunk 11]
```diff
@@ -20,38 +27,144 @@ function getPrivateKeyWithout0xPrefix(privateKey: string) {
   return privateKey.toLowerCase().startsWith('0x') ? privateKey.substring(2) : privateKey
 }
 
-export class CeloProvider extends PrivateKeyWalletSubprovider {
+function isNullOrUndefined(value: any): boolean {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.ts]: style: unnecessary. In js, we use `x == null` to test this. In fact, that's the only valid use of `==` vs `===`.

File: packages/contractkit/src/utils/tx-signing.ts [hunk 12]
```diff
@@ -20,38 +27,144 @@ function getPrivateKeyWithout0xPrefix(privateKey: string) {
...
+      'eth_sendTransaction',
+      'eth_signTransaction',
+      'eth_sign',
+      'personal_sign',
+      'eth_signTypedData',
+    ].includes(payload.method)
+    // Either signing is not required or
+    // signing is required and this class is the correct one to sign
+    const shouldPassToSuperClassForHandling =
+      !signingRequired || payload.params[0].from.toLowerCase() === this.accountAddress
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.ts]: utils/address has as `eqAddress()`

File: packages/contractkit/src/utils/tx-signing.ts [hunk 13]
```diff
@@ -20,38 +27,144 @@ function getPrivateKeyWithout0xPrefix(privateKey: string) {
...
+    } else {
+      // Pass it to the next handler to sign
+      next()
+    }
   }
 
   public async signTransactionAsync(txParams: CeloPartialTxParams): Promise<string> {
     debug('signTransactionAsync: txParams are %o', txParams)
-    if (txParams.chainId === undefined || txParams.chainId === null) {
+    if (txParams.from.toLowerCase() !== this.accountAddress) {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.ts]: use `eqAddress`

File: packages/contractkit/src/utils/tx-signing.ts [hunk 14]
```diff
@@ -20,38 +27,144 @@ function getPrivateKeyWithout0xPrefix(privateKey: string) {
...
+      const result = await this.emitPayloadAsync({
         method: 'net_version',
         params: [],
       })
-      this._chainId = parseInt(chainIdResult.result.toString(), 10)
-      debug('getChainId chain result ID is %s', this._chainId)
+      this.chainId = parseInt(result.result.toString(), 10)
+      debug('getChainId chain result ID is %s', this.chainId)
+    }
+    return this.chainId!
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.ts]: maybe check chainId != null and fail, instead of using `!`

File: packages/contractkit/src/utils/web3-utils.ts [hunk 15]
```diff
@@ -2,32 +2,32 @@ import {
...
+  return new Web3().eth.accounts.privateKeyToAccount(privateKey).address
+}
 
-  debug('Setting up providers...')
-  providerEngine.addProvider(wrappingSubprovider)
-  providerEngine.start()
+// Return the modified web3 object for chaining
+export function addLocalAccount(web3: Web3, privateKey: string): Web3 {
+  const existingProvider = web3.currentProvider
+  const providerEngine: CeloProvider =
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: change the var name to `celoProvider`?

File: packages/contractkit/src/utils/web3-utils.ts [hunk 16]
```diff
@@ -71,3 +71,68 @@ class WrappingSubprovider extends Subprovider {
...
+    providerEngine.addProvider(wrappingSubprovider)
+    return providerEngine
+  }
+
+  private web3ProviderEngine: Web3ProviderEngine
+  private signingProviders: CeloPrivateKeyWalletProvider[]
+  private signingAddresses: string[]
+
+  constructor(readonly existingProvider: Provider) {
+    this.web3ProviderEngine = CeloProvider.createNewProviderWithLocalAccount(existingProvider)
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: maybe it's me, style: a bit weird to call a private static method from a constructor.

File: packages/contractkit/src/utils/web3-utils.ts [hunk 17]
```diff
@@ -71,3 +71,68 @@ class WrappingSubprovider extends Subprovider {
...
+    this.signingAddresses = []
+  }
+
+  addAccount(privateKey: string): CeloProvider {
+    if (this.signingAddresses.includes(privateKey)) {
+      debug('Account is already added')
+      return this
+    }
+
+    const localAccountProvider = new CeloPrivateKeyWalletProvider(privateKey)
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: imo, a better strategy to is have just ONE `CeloPrivateKeyWalletProvider` that handles many accounts. There a couple of things/state that they share (liked cached values for chainId and others).

This also avoids modifying the providerEngine providers list, mantain a list of providers, etc...

In fact, we can even store the accounts in the CeloProvider and pass a `getAccounts()` fn to the CeloPrivateKeyWalletProvider

File: packages/contractkit/src/utils/web3-utils.ts [hunk 18]
```diff
@@ -71,3 +71,68 @@ class WrappingSubprovider extends Subprovider {
...
+  }
+
+  sendAsync(
+    payload: JSONRPCRequestPayload,
+    callback: (error: null | Error, response: JSONRPCResponsePayload) => void
+  ): void {
+    this.web3ProviderEngine.sendAsync(payload, callback)
+  }
+
+  start(callback?: () => void): void {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: let's turn this into a promise

File: packages/contractkit/src/utils/web3-utils.ts [hunk 19]
```diff
@@ -71,3 +71,68 @@ class WrappingSubprovider extends Subprovider {
...
+    localAccountProvider.setEngine(this.web3ProviderEngine)
+    this.signingAddresses.push(localAccountProvider.getAccount())
+    return this
+  }
+
+  on(event: string, handler: () => void): void {
+    this.web3ProviderEngine.on(event, handler)
+  }
+
+  send(payload: JSONRPCRequestPayload): void {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: don't we miss a callback/promise here? how do i get the response?

File: packages/contractkit/src/utils/web3-utils.ts [hunk 20]
```diff
@@ -71,3 +71,68 @@ class WrappingSubprovider extends Subprovider {
...
+    // I could not find a better way to do this, so, I had to
+    // access the private `_providers` field of providerEngine
+    // @ts-ignore-next-line
+    this.web3ProviderEngine._providers.splice(0, 0, localAccountProvider)
+    localAccountProvider.setEngine(this.web3ProviderEngine)
+    this.signingAddresses.push(localAccountProvider.getAccount())
+    return this
+  }
+
+  on(event: string, handler: () => void): void {
```
Comment (mcortesi) [inline packages/contractkit/src/utils/web3-utils.ts]: we should be smarter here.
IPC and WS provider have `on`, and thus "support subscriptions" in web3js terms, while HTTP doesn't. If we set this provider, web3js will understand that WE support subscriptions always

**Review by mcortesi — CHANGES_REQUESTED** [review]

File: packages/contractkit/src/test-utils/ganache-test.ts (hunk 4 above)
Comment (ashishb) [reply packages/contractkit/src/test-utils/ganache-test.ts]: My bad. Removed.

File: packages/contractkit/src/kit.ts (hunk 8 above)
Comment (ashishb) [reply packages/contractkit/src/kit.ts]: This code has been removed.

File: packages/contractkit/src/kit.ts (hunk 9 above)
Comment (ashishb) [reply packages/contractkit/src/kit.ts]: As discussed. This code has been removed.

Comment (ashishb) [reply packages/contractkit/src/kit.ts]: As discussed. This code has been removed.

File: packages/contractkit/src/kit.ts (hunk 10 above)
Comment (ashishb) [reply packages/contractkit/src/kit.ts]: As discussed. This code has been removed.

File: packages/contractkit/src/kit.ts (hunk 9 above)
Comment (ashishb) [reply packages/contractkit/src/kit.ts]: As discussed. This code has been removed.

File: packages/contractkit/src/utils/web3-utils.ts (hunk 17 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: Done. Changed CeloPrivateKeyWalletProvider to CeloPrivateKeysWalletProvider and this will take care of signing with the right key or doing nothing if it does not have the key.

File: packages/contractkit/src/utils/web3-utils.ts (hunk 16 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: Removed.

File: packages/contractkit/src/utils/web3-utils.ts (hunk 20 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: Good catch. I didn't know that. As discussed changed to initializing it conditionally. One minor issue is that I  couldn't figure out the type of `on`, so, it is

`public readonly on: null | any`

I tried `public readonly on: null | (string, () => void)` but that doesn't seem to work.

All other delegates are created unconditionally.

File: packages/contractkit/src/utils/web3-utils.ts (hunk 19 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: I am just writing a delegate, so, the signature will match `web3ProviderEngine.send`

File: packages/contractkit/src/utils/web3-utils.ts (hunk 18 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: Why?
I am just writing a delegate, so, why not keep the signature same as `web3Provider.start` for now?

File: packages/contractkit/src/utils/web3-utils.ts (hunk 15 above)
Comment (ashishb) [reply packages/contractkit/src/utils/web3-utils.ts]: Done.

File: packages/contractkit/src/utils/web3-utils.ts (hunk 20 above)
Comment (mcortesi) [reply packages/contractkit/src/utils/web3-utils.ts]: solved

File: packages/contractkit/src/utils/web3-utils.ts (hunk 19 above)
Comment (mcortesi) [reply packages/contractkit/src/utils/web3-utils.ts]: solved. must match sendAsync for web3 to work

**Comment by mcortesi** [comment]
I think what's missing is digging deeper into providerEngine start() and what it actually does.

Also, we need to manage disconnection for the wrapping subprovider and do it when we do `stop`.
In fact, we can do that in `CeloProvider.stop()` impl,

**Comment by ashishb** [comment]
> Also, we need to manage disconnection for the wrapping subprovider and do it when we do stop. In fact, we can do that in CeloProvider.stop() impl,

Added
```
    try {
      if (this.underlyingProvider.hasOwnProperty('stop')) {
        // @ts-ignore
        this.underlyingProvider.stop()
      }
  
      // Close the web3 connection or the CLI hangs forever.
      if (this.underlyingProvider && this.underlyingProvider.hasOwnProperty('connection')) {
        // @ts-ignore
        const connection = this.underlyingProvider.connection
        if (connection.hasOwnProperty('_connection')) {
          connection._connection.close()
        }
      }
    } catch (error) {
      debug(`Failed to close the connection: ${error}`)
    }
```

**Comment by ashishb** [comment]
> I think what's missing is digging deeper into providerEngine start() and what it actually does.

It seems to me that it is for polling block afterwards to primarily continuously track the latest block. I think I can disable it by passing `opts` with `blockTracker` object. https://github.com/MetaMask/web3-provider-engine/blob/master/index.js#L26

**Comment by mcortesi** [comment]
> > I think what's missing is digging deeper into providerEngine start() and what it actually does.
> 
> It seems to me that it is for polling block afterwards to primarily continuously track the latest block. I think I can disable it by passing `opts` with `blockTracker` object. https://github.com/MetaMask/web3-provider-engine/blob/master/index.js#L26

what about completely replacing ProviderEngine?

For what i see, there not much going one there... it emits a couple of event nobody cares about, it add this start/stop behaviour that we don't like. And the subprovider that we use only needs to call `sendAsync()`

File: packages/contractkit/src/providers/celo-private-keys-subprovider.ts [hunk 21]
```diff
@@ -0,0 +1,192 @@
...
+
+  constructor(privateKey: string) {
+    // This won't accept a privateKey with 0x prefix and will call that an invalid key.
+    super(getPrivateKeyWithout0xPrefix(privateKey))
+    this.addAccount(privateKey)
+  }
+
+  public addAccount(privateKey: string) {
+    // Prefix 0x here or else the signed transaction produces dramatically different signer!!!
+    privateKey = '0x' + getPrivateKeyWithout0xPrefix(privateKey)
```
Comment (mcortesi) [inline packages/contractkit/src/providers/celo-private-keys-subprovider.ts:40]: celo/utils has or should have an `ensure0x` (if it's not in utils it's celotool and should be ported)

Comment (ashishb) [reply packages/contractkit/src/providers/celo-private-keys-subprovider.ts:40]: It is in celotool and it is broken `export const ensure0x = (hexstr: string) => (hexstr.startsWith('0x') ? hexstr : '0x' + hexstr)` since it will miss a string which starts with `0X`. The consquence of that would be a disaster. Let's fix that in a separate PR, so that, 5 unrelated files are not impacted.

```
 $ rg ensure0x
celotool/src/lib/generate_utils.ts
12:import { ensure0x, strip0x } from '@celo/celotool/src/lib/utils'
77:  return new Web3.modules.Eth().accounts.privateKeyToAccount(ensure0x(privateKey)).address

celotool/src/lib/utils.ts
146:export const ensure0x = (hexstr: string) => (hexstr.startsWith('0x') ? hexstr : '0x' + hexstr)

celotool/geth_tests/src/lib/utils.ts
11:import { ensure0x } from '@celo/celotool/src/lib/utils'
333:    validatorPrivateKeys.map(ensure0x).join(','),

celotool/src/cmds/geth/get_gold_balance.ts
5:  ensure0x,
41:  account = ensure0x(account)

celotool/src/cmds/geth/run.ts
5:import { addCeloGethMiddleware, ensure0x, validateAccountAddress } from 'src/lib/utils'
80:      (minerAddress: string) => (minerAddress === null ? null : ensure0x(minerAddress))

celotool/src/cmds/deploy/initial/contracts.ts
6:import { ensure0x, execCmd } from '@celo/celotool/src/lib/utils'
24:    return ensure0x(OG_ACCOUNTS[0].address)
34:    return OG_ACCOUNTS.map((account) => account.privateKey).map(ensure0x)
40:    ).map(ensure0x)
```

Comment (mcortesi) [reply packages/contractkit/src/providers/celo-private-keys-subprovider.ts:40]: sure, let's do that! do you want to create and issue or do that after this pr?

File: packages/contractkit/src/utils/tx-signing.test.ts [hunk 22]
```diff
@@ -1,56 +1,81 @@
...
+  expect(recoveredSigner).toEqual(from)
 }
 
 testWithGanache('Transaction Utils', (web3: Web3) => {
-  // describe('Transaction Utils', () => {
-  describe.skip('Signer Testing', () => {
-    it('should be able to sign and get the signer back', async () => {
+  let originalProvider: Provider
+  beforeEach(() => {
+    originalProvider = web3.currentProvider
```
Comment (mcortesi) [inline packages/contractkit/src/utils/tx-signing.test.ts:46]: I'm a bit lost here.. but I'm missing the part were we set the web3.currentProvider to CeloProvider. Where does that happen?

**Review by mcortesi — APPROVED** [review]

**Comment by mcortesi** [comment]
@ashishb approved. Great Job.

I think what's missing is:
 - disable block tracker on provider engine

then we can do some improvements, but we can do that in another time ;)

File: packages/contractkit/src/providers/celo-private-keys-subprovider.ts (hunk 21 above)
Comment (ashishb) [reply packages/contractkit/src/providers/celo-private-keys-subprovider.ts:40]: I will send a follow-on PR to fix `ensure0x`. Let's not worry about de-duplicating this function for now.

File: packages/contractkit/src/utils/tx-signing.test.ts (hunk 22 above)
Comment (ashishb) [reply packages/contractkit/src/utils/tx-signing.test.ts:46]: see `addLocalAccount` in web3-utils.ts - https://github.com/celo-org/celo-monorepo/pull/798/files#diff-728b956ec7d19ed74a7cb0a6beb7be98

We change to CeloProvider when the first local account is added.
