### PR TITLE
[Wallet] Add identity metadata to outgoing payments

### LINKED ISSUE #1335: [Android] ‘cUSD’ balance is not updated automatically when user receives an amount from other users.
**App version:** Zero - sync  build v1.5.0, Play store build v1.5.0
**Repro on:** Samsung Galaxy S6 (7.0), Samsung Galaxy S7 (8.0.0)
**Testing Account:**  680 208 0265/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app and register into the app as User A from device1. 
2) Register into the app as User B from device2.
3) User A sends a ‘cUSD’ to user B. 
4) Make sure the transaction process successful. 
5) Observe on user B from device 2 ‘cUSD’ balance amount is not get updated automatically

**Investigation:** 
1) ‘cUSD’ balance is shown updated after user sending ‘cUSD’ to other users. 
2) ‘cUSD’ and ‘cGLD’ balance is shown updated when user exchange ‘cUSD’ to ‘cGLD’ or ‘cGLD’ to ‘cUSD’.
3) Balance amount is shown updated after refresh the balance.

**Impact:** User is not updated with the current balance without refreshing the page.  
**Current Behavior:**  ‘cUSD’ balance is not updated automatically 
**Expected Behavior:** “cUSD” balance should update automatically. 
**Attachment:** [Android_CeloDollarsUpdateIssue.mov](https://drive.google.com/file/d/1hpn8LVpSHaS8eb9lOAxLLpjHloQQGWbX/view?usp=sharing) (Bug observe after 44  sec)

### LINKED ISSUE #2647: [Wallet] Sync incoming transaction and balance update
This issue is a result of discussion started here: https://github.com/celo-org/celo-monorepo/pull/2548#issuecomment-579541351

### Expected Behavior

When user receives incoming transaction, we need to show it on the list and also update the balance. We should present these two actions to a user at the same time or explicitly communicate in the UI, that one of them is about to get refreshed. Exact behavior TBD (@nityas @coreycelo)

### Current Behavior

When user receives incoming transaction, first user would see it in the list and a couple of seconds later balance would update itself.

### LINKED ISSUE #2878: Wallet should refresh balance on receiving payment notification
### Expected Behavior

Refreshed balance

### Current Behavior

Stale balance, and autorefresh wasn't working for some reason (tested in Nigeria on my iPhone)

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

The main goal of this changeset is to add identity metadata (phone number and salt) to outgoing payment in the encrypted comments. This enables recipients to find corresponding contact information without having to do mass lookups. To achieve this, several changes where required / beneficial:

- Improve type handling of Solidity `bytes` in ContractKit
- Reduce duplication of utils in ContractKit
- Confirm users are truly 'verified' in contact mapping
- Add transaction feed query watcher
- Trigger balance refresh on tx feed update
- Scan new tx feed items for identity metadata in the comments
- Persist useful identity metadata to the phone number mappings 
- Fix some edge cases that break comment decryption memoization
- Update contractKit docs
- Some related refactoring and cleanup

### Tested

- Sent btwn two verified numbers on two phones and confirmed txs get labelled with contact info correctly.
- Confirmed from logs behavior is correct
- Added lots of new unit tests

### Related issues

- Fixes #2878
- Fixes #2647
- Fixes #1335 
- Fixes ##3624
- Fixes https://github.com/celo-org/celo-labs/issues/473

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/home/saga.ts [hunk 1]
```diff
@@ -43,13 +45,6 @@ export function* refreshBalances() {
   yield put(fetchSentEscrowPayments())
 }
 
-export function* refreshBalancesWithLoadingSaga() {
```
Comment (jmrossy) [inline packages/mobile/src/home/saga.ts:46]: Removed because its unused and redundant with `watchRefreshBalances`

File: packages/mobile/src/identity/commentEncryption.ts [hunk 2]
```diff
@@ -0,0 +1,316 @@
+// Wallet utilities for comment encryption and comment key management
```
Comment (jmrossy) [inline packages/mobile/src/identity/commentEncryption.ts:1]: The file is actually a rename of the `identity/commentKey.ts` but it's been mostly rewritten.
It handles comment key management tasks, encryption/decryption, and extracting identity metadata from comments

File: packages/mobile/src/identity/commentEncryption.test.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
+import {
```
Comment (jmrossy) [inline packages/mobile/src/identity/commentEncryption.test.ts:8]: Actually a rename of `identity/commentKey.ts` but I'll be significantly increasing the coverage we had there before merging this.

File: packages/mobile/src/identity/contactMapping.ts [hunk 4]
```diff
@@ -109,19 +109,15 @@ function* updateRecipientsCache(
 export function* fetchAddressesAndValidateSaga({ e164Number }: FetchAddressesAndValidateAction) {
```
Comment (jmrossy) [inline packages/mobile/src/identity/contactMapping.ts:110]: Changes in this file are just a bit of restructuring to allow some useful code to be leverage by `identity/commentEncryption.ts` too

File: packages/mobile/src/qrcode/QRScanner.tsx [hunk 5]
```diff
@@ -85,7 +88,7 @@ class QRScanner extends React.Component<Props> {
               }}
               style={styles.preview}
               type={RNCamera.Constants.Type.back}
-              onBarCodeRead={memoize(this.onBarCodeDetected, (qr) => qr.data)}
```
Comment (jmrossy) [inline packages/mobile/src/qrcode/QRScanner.tsx:88]: The way it was before, we were creating a new memoize function on each render, defeating the purpose of memoization I believe.

File: packages/mobile/src/transactions/actions.ts [hunk 6]
```diff
@@ -16,81 +16,97 @@ export enum Actions {
   ADD_HASH_TO_STANDBY_TRANSACTIONS = 'TRANSACTIONS/ADD_HASH_TO_STANDBY_TRANSACTIONS',
   TRANSACTION_CONFIRMED = 'TRANSACTIONS/TRANSACTION_CONFIRMED',
   TRANSACTION_FAILED = 'TRANSACTIONS/TRANSACTION_FAILED',
+  NEW_TRANSACTIONS_IN_FEED = 'TRANSACTIONS/NEW_TRANSACTIONS_IN_FEED',
 }
 
-export interface AddStandbyTransaction {
+export interface AddStandbyTransactionAction {
```
Comment (jmrossy) [inline packages/mobile/src/transactions/actions.ts:22]: I renamed the action interfaces for consistency with our others

File: packages/mobile/src/transactions/reducer.ts [hunk 7]
```diff
@@ -1,60 +1,43 @@
-import { TokenTransactionType } from 'src/apollo/types'
-import { CURRENCY_ENUM } from 'src/geth/consts'
+import { getRehydratePayload, REHYDRATE, RehydrateAction } from 'src/redux/persist-helper'
+import { RootState } from 'src/redux/reducers'
 import { Actions, ActionTypes } from 'src/transactions/actions'
-
-export interface ExchangeStandby {
```
Comment (jmrossy) [inline packages/mobile/src/transactions/reducer.ts:5]: Moved to `transactions/types.ts`

File: packages/contractkit/src/wrappers/Attestations.ts [hunk 8]
```diff
@@ -223,23 +213,15 @@ export class AttestationsWrapper extends BaseWrapper<Attestations> {
...
     identifier: string,
     account: Address,
-    numAttestationsRequired: number = DEFAULT_NUM_ATTESTATIONS_REQUIRED,
-    attestationThreshold: number = DEFAULT_ATTESTATION_THRESHOLD
-  ): Promise<AttestationsStatus> {
+    numAttestationsRequired?: number,
+    attestationThreshold?: number
+  ) {
     const attestationStats = await this.getAttestationStat(identifier, account)
-    const numAttestationsRemaining = numAttestationsRequired - attestationStats.completed
```
Comment (jmrossy) [inline packages/contractkit/src/wrappers/Attestations.ts:230]: This stuff was moved to `utils/src/attestations.ts` to make it easier to use in certain parts of the wallet

File: packages/mobile/src/transactions/TransactionsList.tsx [hunk 9]
```diff
@@ -209,28 +209,7 @@ function mapInvite(tx: FeedItem): FeedItem {
   return tx
 }
 
-function getTransactions(data: UserTransactionsQuery | undefined) {
```
Comment (jmrossy) [inline packages/mobile/src/transactions/TransactionsList.tsx:212]: Moved to transferFeedUtils

File: packages/mobile/src/transactions/TransactionsList.tsx [hunk 10]
```diff
@@ -209,28 +209,7 @@ function mapInvite(tx: FeedItem): FeedItem {
...
-  return data?.tokenTransactions?.edges.map((edge) => edge.node).filter(isPresent) ?? []
-}
-
 export class TransactionsList extends React.PureComponent<Props> {
-  txsFetched = (data: UserTransactionsQuery | undefined) => {
```
Comment (jmrossy) [inline packages/mobile/src/transactions/TransactionsList.tsx:217]: Moved to the tx feed watcher saga which can handle this stuff more elegantly

**Review by nambrot — APPROVED** [review]
attestation ck changes look good to me!

File: packages/contractkit/src/wrappers/BaseWrapper.ts [hunk 11]
```diff
@@ -50,19 +50,22 @@ export const valueToInt = (input: BigNumber.Value) =>
...
+// Hopefull this will improve in the future, at which point we can make improvements here
+type SolidityBytes = string | number[]
+export const stringToSolidityBytes = (input: string) => ensureLeading0x(input) as SolidityBytes
+export const bufferToSolidityBytes = (input: Buffer) => stringToSolidityBytes(bufferToHex(input))
+export const solidityBytesToString = (input: SolidityBytes): string => {
+  if (input === null || input === undefined || typeof input === 'string') {
+    return input
+  } else if (Array.isArray(input)) {
+    let hex = ''
+    input.map((num) => (hex += num))
```
Comment (gastonponti) [inline packages/contractkit/src/wrappers/BaseWrapper.ts]: (Detail)
Although this work, you are using a `map` as an iterator, and the essence is different.
You can use `forEach` instead of `map` for the same result, or even `reduce`
```
const hex = input.reduce((accum, num) => accum + num, '')
```
With reduce it's clearer that you are transforming an array into a result

Comment (gastonponti) [inline packages/contractkit/src/wrappers/BaseWrapper.ts]: This is not a detail, haha
What characteristic has each number? it's always a one-digit?
Otherwise, if every number it's a two-digit, you should handle the zero padding
```
hex +=  num.toString().padStart(2, '0')
```
Otherwise [88, 1, 50] will be '88150', and probably should be '880150'

File: packages/mobile/src/identity/commentEncryption.test.ts [hunk 12]
```diff
@@ -0,0 +1,259 @@
...
+const simpleCommentEnc =
+  'BNFXzyIGjZqqNyq6r35aV2HlMMqUbGnIqboReD77MwAlI5IyzqLQ99WF5B1bsZSVS1K+7trtJtKGhIdI1vbSJSsBAQEBAQEBAQEBAQEBAQEBCVYJWqi/TZNXbAR9ziyX5MJCtfdulxA1tjlvHR/xpE6WnlC/kyXAfKIMqgKGJXchBNFXzyIGjZqqNyq6r35aV2HlMMqUbGnIqboReD77MwAlI5IyzqLQ99WF5B1bsZSVS1K+7trtJtKGhIdI1vbSJSsBAQEBAQEBAQEBAQEBAQEBBhjruDecYg9fsrPNcQbI3AkcvWra1MHIeOZlcycn7Vqtx+UVNR59A3kqdIDbLuGiAQEBAQEBAQEBAQEBAQEBAQ13jJ/iheQ05aIkSedfLcnSa3Rtr4dsbNt59TAZsQqGxPClubtekbOKaHz7lE5zyI803qP65frfyyCxuQ=='
+const simpleCommentWithMetadata = 'Simple comment~+14155550000piWqRHHYWtfg9'
+const simpleCommentWithMetadataEnc =
+  'BNFXzyIGjZqqNyq6r35aV2HlMMqUbGnIqboReD77MwAlI5IyzqLQ99WF5B1bsZSVS1K+7trtJtKGhIdI1vbSJSsBAQEBAQEBAQEBAQEBAQEBCVYJWqi/TZNXbAR9ziyX5MJCtfdulxA1tjlvHR/xpE6WnlC/kyXAfKIMqgKGJXchBNFXzyIGjZqqNyq6r35aV2HlMMqUbGnIqboReD77MwAlI5IyzqLQ99WF5B1bsZSVS1K+7trtJtKGhIdI1vbSJSsBAQEBAQEBAQEBAQEBAQEBBhjruDecYg9fsrPNcQbI3AkcvWra1MHIeOZlcycn7Vqtx+UVNR59A3kqdIDbLuGiAQEBAQEBAQEBAQEBAQEBAQ13jJ/iheQ05aIkSedfLcnSa3Rtr4dsbNt59TBTlRnqnaAoz0HyOyScr6ckQczlhtxwBqKgGuXE9OnjyeH4PIJ9yutViWOO+glrLIFjpDyl+7FebiJv/p9Ay21LHpUd7b5lSV4PWPDxamBMp6MHRdA='
+const complexComment = 'long comment with emoji 😇🤠👳🏽‍♂️~ test TEST test'
```
Comment (gastonponti) [inline packages/mobile/src/identity/commentEncryption.test.ts:45]: Always be prepared ❤️

**Review by gastonponti — COMMENTED** [review]
The padding with zero probably is a bug, but all the other stuff lgtm

File: packages/contractkit/src/wrappers/BaseWrapper.ts (hunk 11 above)
Comment (gastonponti) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: oh, and even more, this won't handle the `10` as `A`
Probably we have to check this, but I think the real solution is:
```
hex +=  num.toString(16).padStart(2, '0')
```
And [23, 1, 10, 15] will be '17010A0F'

Comment (jmrossy) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: Good questions here. Unfortunately, I'm not sure what the actual format of the data is when web3 gives a `number[]`. It doesn't seem to be documented and I've just pieced together some information based on these discussions:
https://github.com/ethereum-ts/TypeChain/issues/98
https://github.com/ethereum-ts/TypeChain/pull/153
https://github.com/ethereum-ts/TypeChain/issues/123

Comment (jmrossy) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: And in my testing, I've only seen it return string. Maybe we should log and throw an error here until we find a situation that actually hits this case? Then we can inspect the number[] and see how this should be implemented. WDYT?

Comment (jmrossy) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: I'm not a big fan of `reduce` in JS, i find the interface unintuitive, but agreed in this case it would work nicely. I'll make that change when we decide what to do with this section

Comment (gastonponti) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: Ok, reading some other questions, I think that this case is happening when is used an array of `bytes` in solidity.
And it would probably be a `number` for every `byte`, so I'm 98% sure (haha) that this:
`hex +=  num.toString(16).padStart(2, '0')` will work, otherwise it's impossible to have a letter in the hex, and that would be really weird.

This was probably not working before. My only problem with adding something that will fail if the array was used, is that we don't know if the user will know how to handle that.

In my point of view, in these cases, I prefer to follow what could be a convention in transforming array of numbers into hex, and if we are doing something wrong, this would be an issue from some functionality using it.

Comment (gastonponti) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: I found something. The lib `eth-lib` that we use, has this function:
```
const fromArray = arr => {
  let hex = "0x";
  for (let i = 0, l = arr.length; i < l; ++i) {
    let b = arr[i];
    hex += (b < 16 ? "0" : "") + b.toString(16);
  }
  return hex;
}
```
that basically transform an array of integers, the same way we are saying.
If I have to strictly think of an array of numbers how it turns to a hex, this is the only way possible.

Comment (jmrossy) [reply packages/contractkit/src/wrappers/BaseWrapper.ts]: Thanks for investigating! I'll go ahead and use a hex conversion approach similar to your suggestion and that snippet :)

**Review by trianglesphere — COMMENTED** [review]
The comment changes look good. I like the change from `encrypted` -> `success`.
The unit tests look good and are great to have, but (nit) if how the tx feed gets populated hasn't changed too much (from a specialized service, and not local geth), it's nice to make sure the emojis are working end to end.

File: packages/contractkit/src/wrappers/Governance.ts [hunk 13]
```diff
@@ -107,7 +111,7 @@ export interface Votes {
 export type HotfixParams = Parameters<Governance['methods']['executeHotfix']>
 export const hotfixToParams = (proposal: Proposal, salt: Buffer): HotfixParams => {
   const p = proposalToParams(proposal, '') // no description URL for hotfixes
-  return [p[0], p[1], p[2], p[3], bufferToString(salt)]
+  return [p[0], p[1], p[2], p[3], bufferToHex(salt)]
```
Comment (aslawson) [inline packages/contractkit/src/wrappers/Governance.ts:114]: we loose the `ensureLeading0x` check by changing this to bufferToHex -- not a large concern, but if anyone uses this without the `0x` and it will break for them.

File: packages/mobile/src/config.ts [hunk 14]
```diff
@@ -32,7 +32,7 @@ export const DEV_SETTINGS_ACTIVE_INITIALLY = stringToBoolean(
 // VALUES
 export const GAS_INFLATION_FACTOR = 1.5 // Used when estimating gas for txs
 export const GAS_PRICE_INFLATION_FACTOR = 5 // Used when getting gas price, must match what Geth does
-export const BALANCE_OUT_OF_SYNC_THRESHOLD = 5 * 60 // 5 minutes
+export const BALANCE_OUT_OF_SYNC_THRESHOLD = 1 * 60 // 1 minute
```
Comment (aslawson) [inline packages/mobile/src/config.ts:35]: is this change intentional or did you just lower it for manual testing?

File: packages/mobile/src/identity/commentEncryption.test.ts (hunk 12 above)
Comment (aslawson) [reply packages/mobile/src/identity/commentEncryption.test.ts:45]: 🤠

File: packages/mobile/src/identity/commentEncryption.ts [hunk 15]
```diff
@@ -0,0 +1,309 @@
...
+  return newIdentityData
+}
+
+// Verify the metadata claims (they could be spoofed)
+// Returns set of metadata objects with invalid ones filtered out
+function* verifyIdentityMetadata(data: IdentityMetadataInTx[]) {
+  // This function looks a bit convoluted because:
+  // 1. Data could have dupes in it
+  // 2. Some duped phone hashes could be true, others false
+  // 3. And a given phoneHash could legitimately have multiple addresses
```
Comment (annakaz) [inline packages/mobile/src/identity/commentEncryption.ts:233]: 👍

File: packages/mobile/src/identity/contactMapping.ts [hunk 16]
```diff
@@ -81,7 +82,7 @@ function* doImportContacts() {
   yield call(updateRecipientsCache, e164NumberToRecipients, otherRecipients)
 }
 
-// Find the user's contact among those important and save useful bits
+// Find the user's own contact among those imported and save useful bits
```
Comment (annakaz) [inline packages/mobile/src/identity/contactMapping.ts:85]: 🎨

File: packages/mobile/src/identity/commentEncryption.ts [hunk 17]
```diff
@@ -0,0 +1,309 @@
...
+    contractKit.contracts.getAccounts,
+  ])
+  const hexString: string = yield call(accountsWrapper.getDataEncryptionKey, address)
+  return !hexString ? null : hexToBuffer(hexString)
+}
+
+export function* encryptComment(
+  comment: string | null,
+  toAddress: string | null,
+  fromAddress: string | null,
```
Comment (aslawson) [inline packages/mobile/src/identity/commentEncryption.ts:65]: when are these null?

File: packages/mobile/src/transactions/saga.ts [hunk 18]
```diff
@@ -1,25 +1,133 @@
...
+  }
+}
+
+// Remove standby txs from redux state when the real ones show up in the feed
+function* cleanupStandbyTransacitons(newFeedTransactions: TransactionFeedFragment[]) {
+  const standbyTxs: StandbyTransaction[] = yield select(standbyTransactionsSelector)
+  const newFeedTxHashes = new Set(newFeedTransactions.map((tx) => tx?.hash))
+  // const inQueryTxs = (tx: StandbyTransaction) =>
+  //   tx.hash && queryDataTxHashes.has(tx.hash) && tx.status !== TransactionStatus.Failed
+  // const filteredStandbyTxs = this.props.standbyTransactions.filter(inQueryTxs)
```
Comment (annakaz) [inline packages/mobile/src/transactions/saga.ts]: Remove commented out lines or add TODO?

**Review by annakaz — APPROVED** [review]
LGTM on the wallet side!

The refactor of how standby transactions are removed once confirmed may also close #3624 and #2704 😁

File: packages/mobile/src/identity/commentEncryption.ts [hunk 19]
```diff
@@ -0,0 +1,309 @@
...
+}
+
+export function extractPhoneNumberMetadata(commentData: string) {
+  const phoneNumMetadata = commentData.match(PHONE_METADATA_REGEX)
+  if (!phoneNumMetadata || phoneNumMetadata.length < 4) {
+    return { comment: commentData }
+  }
+
+  return {
+    comment: phoneNumMetadata[1],
```
Comment (aslawson) [inline packages/mobile/src/identity/commentEncryption.ts:162]: I'm not super knowledgable about regex, but would the comment not be index 0 here?

Comment (aslawson) [reply packages/mobile/src/identity/commentEncryption.ts:162]: also wondering how this solution would scale if we add more metadata and perhaps some of it is missing.  feels almost like we should send json or some type:value in the metadata for more foolproof parsing

File: packages/mobile/src/qrcode/QRScanner.tsx (hunk 5 above)
Comment (aslawson) [reply packages/mobile/src/qrcode/QRScanner.tsx:88]: interesting -- nice catch

File: packages/mobile/src/transactions/saga.ts (hunk 18 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/saga.ts]: Ah good catch, thanks!

File: packages/mobile/src/identity/commentEncryption.ts (hunk 19 above)
Comment (jmrossy) [reply packages/mobile/src/identity/commentEncryption.ts:162]: No, index 0 would be the full string. 
This scheme would not work well for generalized metadata but we can cross that bridge when we come to it :)

File: packages/mobile/src/identity/commentEncryption.ts (hunk 17 above)
Comment (jmrossy) [reply packages/mobile/src/identity/commentEncryption.ts:65]: Practically speaking, when the user didn't get verified so never registered a DEK

File: packages/mobile/src/config.ts (hunk 14 above)
Comment (jmrossy) [reply packages/mobile/src/config.ts:35]: intentional :)

File: packages/contractkit/src/wrappers/Governance.ts (hunk 13 above)
Comment (jmrossy) [reply packages/contractkit/src/wrappers/Governance.ts:114]: Good catch here! I guess you mean we add the `ensureLeading0x`? I'm inclined to leave it as is, since long-term it'd be good for hex values to be properly prefixed, but if it causes trouble for anyone I'm happy to revert this.

File: packages/mobile/src/home/saga.ts (hunk 1 above)
Comment (tarikbellamine) [reply packages/mobile/src/home/saga.ts:46]: good catch!

File: packages/mobile/src/identity/commentEncryption.ts [hunk 20]
```diff
@@ -0,0 +1,309 @@
...
+}
+
+export function* encryptComment(
+  comment: string | null,
+  toAddress: string | null,
+  fromAddress: string | null,
+  includePhoneNumMetadata: boolean = false
+) {
+  Logger.debug(TAG + 'encryptComment', 'Encrypting comment')
+  if (!features.USE_COMMENT_ENCRYPTION || !comment || !toAddress || !fromAddress) {
```
Comment (tarikbellamine) [inline packages/mobile/src/identity/commentEncryption.ts:69]: I believe you've already raised this, but this is what you meant when you said comment encryption was only possible between two verified accounts, right?

File: packages/mobile/src/identity/commentEncryption.ts [hunk 21]
```diff
@@ -0,0 +1,309 @@
...
+    return comment
+  }
+
+  let commentToEncrypt = comment
+  if (features.PHONE_NUM_METADATA_IN_TRANSFERS && includePhoneNumMetadata) {
+    Logger.debug(TAG + 'encryptComment', 'Including phone number metadata in comment')
+    const selfPhoneDetails: PhoneNumberHashDetails | undefined = yield call(
+      getUserSelfPhoneHashDetails
+    )
+    commentToEncrypt = embedPhoneNumberMetadata(comment, selfPhoneDetails)
```
Comment (tarikbellamine) [inline packages/mobile/src/identity/commentEncryption.ts:95]: Out of curiosity, why is embedding phone number metadata necessary?

File: packages/mobile/src/identity/commentEncryption.ts (hunk 20 above)
Comment (jmrossy) [reply packages/mobile/src/identity/commentEncryption.ts:69]: Currently, yes that's right. We should explore options for bringing this to more users

File: packages/mobile/src/identity/commentEncryption.ts (hunk 21 above)
Comment (jmrossy) [reply packages/mobile/src/identity/commentEncryption.ts:95]: We used to lookup a user's whole address book on-chain to see who's verified. It was slow but it worked. Now that's not possible because of PGPNP. So we include the metadata in comments, enabling the recipient to connect the dots

File: packages/mobile/src/identity/commentEncryption.ts [hunk 22]
```diff
@@ -0,0 +1,309 @@
...
+}
+
+// Check all transaction comments for metadata
+function findIdentityMetadataInComments(
+  transactions: TransactionFeedFragment[],
+  commentKeyPrivate: string
+) {
+  const newIdentityData: IdentityMetadataInTx[] = []
+  for (const tx of transactions) {
+    if (tx.__typename !== 'TokenTransfer' || tx.type !== TokenTransactionType.Received) {
```
Comment (tarikbellamine) [inline packages/mobile/src/identity/commentEncryption.ts:210]: Do we want to skip `TokenTransactionType.Sent`?

Comment (jmrossy) [reply packages/mobile/src/identity/commentEncryption.ts:210]: We do, no sense decrypting and processing your own identity data as you send it out :)

File: packages/mobile/src/send/saga.ts [hunk 23]
```diff
@@ -154,12 +153,9 @@ function* sendPaymentOrInviteSaga({
...
     }
 
-    const ownAddress = yield select(currentAccountSelector)
-    const comment = features.USE_COMMENT_ENCRYPTION
-      ? yield call(encryptComment, reason, recipientAddress, ownAddress)
-      : reason
-
+    const ownAddress: string = yield select(currentAccountSelector)
     if (recipientAddress) {
+      const comment = yield call(encryptComment, reason, recipientAddress, ownAddress, true)
```
Comment (tarikbellamine) [inline packages/mobile/src/send/saga.ts]: Nit: consider renaming the result `encryptedComment`. As someone new to the codebase, the difference between `comment` and `reason` was already confusing to me.

Definitely optional but I think it would be useful if downstream references were also renamed `encryptedComment` so it is clear when we are dealing with a raw comment vs an encrypted one

File: packages/mobile/src/transactions/TransactionsList.tsx [hunk 24]
```diff
@@ -209,28 +209,7 @@ function mapInvite(tx: FeedItem): FeedItem {
   return tx
 }
 
-function getTransactions(data: UserTransactionsQuery | undefined) {
-  return data?.tokenTransactions?.edges.map((edge) => edge.node).filter(isPresent) ?? []
-}
-
 export class TransactionsList extends React.PureComponent<Props> {
```
Comment (tarikbellamine) [inline packages/mobile/src/transactions/TransactionsList.tsx:215]: Nit: can this be refactored to be a functional component now?

File: packages/mobile/src/transactions/saga.ts [hunk 25]
```diff
@@ -1,25 +1,130 @@
...
+}
+
+// Remove standby txs from redux state when the real ones show up in the feed
+function* cleanupStandbyTransacitons(newFeedTransactions: TransactionFeedFragment[]) {
+  const standbyTxs: StandbyTransaction[] = yield select(standbyTransactionsSelector)
+  const newFeedTxHashes = new Set(newFeedTransactions.map((tx) => tx?.hash))
+  for (const standbyTx of standbyTxs) {
+    if (
+      standbyTx.hash &&
+      standbyTx.status !== TransactionStatus.Failed &&
```
Comment (tarikbellamine) [inline packages/mobile/src/transactions/saga.ts:39]: Is there value in keeping failed transactions? If timestamp is easily accessible, maybe we can safely cleanup any failed transactions of a certain age or older?

**Review by tarikbellamine — COMMENTED** [review]
Nice work! Left a few minor comments/questions

File: packages/mobile/src/identity/commentEncryption.ts (hunk 22 above)
Comment (tarikbellamine) [reply packages/mobile/src/identity/commentEncryption.ts:210]: Haha good point!

File: packages/mobile/src/apollo/types.ts [hunk 26]
```diff
@@ -161,6 +161,10 @@ export enum TokenTransactionType {
   NetworkFee = 'NETWORK_FEE',
 }
 
+export function isTokenTxTypeSent(type: TokenTransactionType) {
+  return type === TokenTransactionType.Sent || type === TokenTransactionType.EscrowSent
+}
+
```
Comment (jeanregisser) [inline packages/mobile/src/apollo/types.ts]: This file is generated by graphql-codegen.
We should move this somewhere else.

File: packages/mobile/src/home/WalletHome.tsx [hunk 27]
```diff
@@ -113,7 +110,7 @@ export class WalletHome extends React.Component<Props> {
   }
 
   componentDidMount() {
-    this.props.resetStandbyTransactions()
+    // TODO find a better home for this, its unrelated to wallet home
```
Comment (jeanregisser) [inline packages/mobile/src/home/WalletHome.tsx:113]: 👍

File: packages/mobile/src/transactions/TransactionFeed.tsx [hunk 28]
```diff
@@ -59,7 +59,7 @@ export class TransactionFeed extends React.PureComponent<Props> {
     `,
   }
 
-  renderItem = (commentKeyBuffer: Buffer | null, kind: FeedType) => ({
+  renderItem = (commentKey: string | null, kind: FeedType) => ({
```
Comment (jeanregisser) [inline packages/mobile/src/transactions/TransactionFeed.tsx]: Looks like we don't need the `renderItem` factory indirection anymore (function returning another function).
`commentKey` and `kind` can be taken from props directly.

File: packages/mobile/src/transactions/TransactionsList.test.tsx [hunk 29]
```diff
@@ -294,11 +294,6 @@ it('ignores pending standby transactions that are completed in the response and
   const feed = await waitForElement(() => getByType(TransactionFeed))
   expect(feed.props.data.length).toEqual(2)
   expect(toJSON()).toMatchSnapshot()
-
-  expect(store.getActions()).toEqual([
-    { type: 'HOME/REFRESH_BALANCES' },
-    { type: 'TRANSACTIONS/REMOVE_STANDBY_TRANSACTION', idx: 'a-standby-tx-id' },
-  ])
```
Comment (jeanregisser) [inline packages/mobile/src/transactions/TransactionsList.test.tsx:301]: nit: we could keep that and check the array is empty.

File: packages/mobile/src/transactions/reducer.ts [hunk 30]
```diff
@@ -85,7 +68,20 @@ export const reducer = (state: State | undefined = initialState, action: ActionT
           }
         }),
       }
+    case Actions.NEW_TRANSACTIONS_IN_FEED:
+      const newKnownFeedTransactions = { ...state.knownFeedTransactions }
+      action.transactions.map((tx) => (newKnownFeedTransactions[tx.hash] = true))
```
Comment (jeanregisser) [inline packages/mobile/src/transactions/reducer.ts]: nit: this is more a `forEach`

File: packages/utils/src/attestations.ts [hunk 31]
```diff
@@ -92,6 +95,54 @@ export function extractAttestationCodeFromMessage(message: string) {
...
+  completed: number
+}
+
+interface AttestationStat {
+  completed: number
+  total: number
+}
+
+/**
+ * Returns true if an AttetationStat is considered verified using the given factors,
```
Comment (jeanregisser) [inline packages/utils/src/attestations.ts]: typo `AttestationStat`

File: packages/mobile/src/transactions/saga.ts [hunk 32]
```diff
@@ -1,25 +1,130 @@
...
+      'Error proccesing user tx query channel event',
+      error
+    )
+  } finally {
+    Logger.debug(`${TAG}/watchUserTransactionQueryChannel`, 'User tx channel terminated')
+  }
+}
+
+// Remove standby txs from redux state when the real ones show up in the feed
+function* cleanupStandbyTransacitons(newFeedTransactions: TransactionFeedFragment[]) {
```
Comment (jeanregisser) [inline packages/mobile/src/transactions/saga.ts]: typo `Transactions`

File: packages/mobile/src/transactions/saga.ts [hunk 33]
```diff
@@ -1,25 +1,130 @@
...
+            transactionFeedFragments: getTxsFromUserTxQuery(queryResult.data),
+          })
+        },
+        error: (e) => console.error(e),
+      })
+
+    return querySubscription.unsubscribe
+  })
+  yield spawn(watchUserTxQueryChannel, userTxQueryChannel)
+}
```
Comment (jeanregisser) [inline packages/mobile/src/transactions/saga.ts]: This feels disconnected from what's happening at the component level.
It looks like it's working for both cUSD and cGLD feeds because there's a link between them.
But this is gonna create differences, and probably one extra query when the local currency is changed for instance.

What do you think of instead of trying to replicate the query here we would dispatch the new transactions from the `onComplete` function at the component level in `TransactionsList`?

File: packages/mobile/src/identity/commentEncryption.test.ts [hunk 34]
```diff
@@ -0,0 +1,259 @@
...
+  'BNFXzyIGjZqqNyq6r35aV2HlMMqUbGnIqboReD77MwAlI5IyzqLQ99WF5B1bsZSVS1K+7trtJtKGhIdI1vbSJSsBAQEBAQEBAQEBAQEBAQEBCVYJWqi/TZNXbAR9ziyX5MJCtfdulxA1tjlvHR/xpE6WnlC/kyXAfKIMqgKGJXchBNFXzyIGjZqqNyq6r35aV2HlMMqUbGnIqboReD77MwAlI5IyzqLQ99WF5B1bsZSVS1K+7trtJtKGhIdI1vbSJSsBAQEBAQEBAQEBAQEBAQEBBhjruDecYg9fsrPNcQbI3AkcvWra1MHIeOZlcycn7Vqtx+UVNR59A3kqdIDbLuGiAQEBAQEBAQEBAQEBAQEBATJ3ip/hhfM0qaIiSahfI8nQa3xtrId9bJV59jBElUbqxKA8zxXyYyTGr/gkHcz1htGoMXyuwrUZoDHHFawgk1046uFz352n+l1rPoFhpHal6vE9k3lR9wF0GN/aWTe2L2g/hp8QQdlwuCgsZnjOVB7hDjSvOZ68mz7WqNk29RT57sb3nMkV'
+
+const phoneDetails: PhoneNumberHashDetails = {
+  e164Number: mockE164Number,
+  salt: mockE164NumberSalt,
+  phoneHash: 'hash',
+}
+
+describe('Encrypt Comment', () => {
+  it('Empty comment', async () => {
```
Comment (jeanregisser) [inline packages/mobile/src/identity/commentEncryption.test.ts]: nit: no big deal but we are inconsistently naming tests in this file.
From what I've seen, we usually try to use a verb after `it` in most other test files.

**Review by jeanregisser — CHANGES_REQUESTED** [review]
Awesome work!! 💯 

I'm mostly concerned about the disconnect introduced by the Tx query watcher in the saga and would prefer we change it before merging this. See comment below.

File: packages/mobile/src/transactions/TransactionsList.tsx (hunk 24 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/TransactionsList.tsx:215]: Maybe but I'll avoid temptation to make this PR bigger :)

File: packages/mobile/src/send/saga.ts (hunk 23 above)
Comment (jmrossy) [reply packages/mobile/src/send/saga.ts]: Will do!

File: packages/mobile/src/transactions/saga.ts (hunk 25 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/saga.ts:39]: Hmm, good question. In theory, this case never happens b.c. if the tx failed, it'll never show up in blockscout and therefore the feed. But I'm not 100% sure so I'd rather keep the logic we had for this (previously in TransactionList)

File: packages/mobile/src/transactions/TransactionsList.test.tsx (hunk 29 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/TransactionsList.test.tsx:301]: There are no expected store actions now, not sure what you mean

File: packages/mobile/src/transactions/TransactionFeed.tsx (hunk 28 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/TransactionFeed.tsx]: Good idea!

File: packages/mobile/src/apollo/types.ts (hunk 26 above)
Comment (jmrossy) [reply packages/mobile/src/apollo/types.ts]: Will do!

File: packages/mobile/src/transactions/saga.ts (hunk 33 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/saga.ts]: Can you clarify what you mean by creating differences? I don't follow.

The problem with the onComplete is that
1) It seems to be less reliable than this watcher
2) It forces us to pollute the component with this business logic

As for creating a new query, this will pull data from the cache first so if the component already queried, it won't use additional bandwidth.

File: packages/mobile/src/identity/commentEncryption.test.ts (hunk 34 above)
Comment (jmrossy) [reply packages/mobile/src/identity/commentEncryption.test.ts]: Will fix :)

File: packages/mobile/src/transactions/saga.ts (hunk 33 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/saga.ts]: To clarify what I mean by unreliable, issues #2647, #1335,  #3624 and #2704 shouldn't be happening if the onComplete was working as expected. My suspicion in that only having it run when the component is mounted contributes to these issues.

File: packages/mobile/src/transactions/TransactionsList.tsx [hunk 35]
```diff
@@ -276,14 +272,17 @@ export class TransactionsList extends React.PureComponent<Props> {
         query={TRANSACTIONS_QUERY}
         pollInterval={POLL_INTERVAL}
         variables={{ address: queryAddress, token, localCurrencyCode }}
-        onCompleted={this.txsFetched}
         children={UserTransactions}
+        onCompleted={this.onTxsFetched}
+        // Adding this option because the onCompleted doesn't work properly without it.
+        // It causes the onCompleted to trigger too often but that's okay.
+        // https://github.com/apollographql/react-apollo/issues/2293
+        notifyOnNetworkStatusChange={true}
```
Comment (jeanregisser) [inline packages/mobile/src/transactions/TransactionsList.tsx:280]: 👍

**Review by jeanregisser — APPROVED** [review]
Awesome!! 💯 🎉

**Comment by ValoraQA** [comment]
Hey @jmrossy I have verified this issue using Android internal build V1.15.1 & Test flight build V1.15.1 & observed that user is able to receive cUSD balance after completion of transaction successfully.
**Verified On Devices:** Samsung Galaxy J5 Prime(8.0.0), Samsung Galaxy A5 (7.0)
**Attachment:** [AbleToReceivecUSDInUserB'sAccount.wmv](https://drive.google.com/file/d/1FzlzAdstcCIv5VhpJAORW7Kw4oYdWEZi/view?usp=sharing)
