### PR TITLE
GasPriceMinimum backward compatibility fix

### LINKED ISSUE #10923: Support 0.8 Solidity in our backward check tooling

### PR DESCRIPTION
**Pull request by pahor167**
### Description

Last release we added support for solidity 0.8 to our tooling. When checking current release against the last release we need to consider also those 0.8 contracts.

### Other changes

No other changes

### Tested

Ci testing

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/10923
- FIxes #10922

### CODE REVIEW

File: packages/protocol/lib/compatibility/ast-code.ts [hunk 1]
```diff
@@ -246,25 +246,31 @@ function generateASTCompatibilityReport(oldContract: ZContract, oldArtifacts: Bu
 /**
  * Runs an ast code comparison and returns the spotted changes from the built artifacts given.
  *
- * @param oldArtifacts
+ * @param oldArtifactsSet
  * @param newArtifacts
```
Comment (martinvol) [inline packages/protocol/lib/compatibility/ast-code.ts]:
```suggestion
 * @param newArtifactsSets
```

**Review by martinvol — APPROVED** [review]

**Review by soloseng — APPROVED** [review]
🚀
