### PR TITLE
Granda Mento env test, small env test refactor and fixes

### LINKED ISSUE #8065: Granda Mento env test
### Expected Behavior

Create new [env test](https://github.com/celo-org/celo-monorepo/tree/master/packages/env-tests/src/tests) that has the following test cases:
1. an exchange proposal is created from an account that subsequently cancels it, refunding the deposit
2. an exchange proposal is created, the approver approves it, and then governance (or whatever account is the owner) vetoes/cancels it (should opt-out of this when running against mainnet)
3. an exchange proposal is created, the approver approves it, and the veto period elapses, and then an account executes the exchange proposal (should opt-out of this when running against mainnet)

### Current Behavior

No env test for granda mento

### PR DESCRIPTION
**Pull request by tkporter**
### Description

This includes:
* An env test for GrandaMento that tests selling and buying CELO for: (1) creating & immediately cancelling an exchange proposal and (2) creating and executing an exchange proposal.
* Small refactor of env-tests to use contractkit's `StableToken` & related functions for stable token specific things
* Added CELO fauceting in env-tests
* Some small changes to the GrandaMento contractkit wrapper
* Added stable token exchange limits to the GrandaMento migrations

### Other changes

* Small fix to testnet helm chart

### Tested

Ran against a testnet I created

### Related issues

- Fixes #8065 

### Backwards compatibility

They are backward compatible

### Documentation

n/a

### CODE REVIEW

File: packages/env-tests/src/scaffold.ts [hunk 1]
```diff
@@ -102,8 +130,8 @@ export async function clearAllFundsToRoot(context: EnvTestContext, stableTokensT
     if (celoBalance.gt(maxBalanceBeforeCollecting)) {
       await goldToken
         .transfer(
-          root.address,
-          celoBalance.times(0.99).integerValue(BigNumber.ROUND_DOWN).toString()
+          validator0.address,
+          celoBalance.times(0.999).integerValue(BigNumber.ROUND_DOWN).toString()
```
Comment (bowd) [inline packages/env-tests/src/scaffold.ts]: Maybe we'd rather do something like `celoBalance.minus(0.0015)` or something of that nature, rather than scaling it down, presuming this is ment to cover gas costs?

File: packages/env-tests/src/scaffold.ts [hunk 2]
```diff
@@ -77,15 +100,20 @@ export enum TestAccounts {
...
 
 export const ONE = new BigNumber('1000000000000000000')
 
-export async function clearAllFundsToRoot(context: EnvTestContext, stableTokensToClear: string[]) {
+export async function clearAllFundsToOriginalAddress(
+  context: EnvTestContext,
+  stableTokensToClear: StableToken[]
+) {
   const accounts = Array.from(
     new Array(Object.keys(TestAccounts).length / 2),
```
Comment (bowd) [inline packages/env-tests/src/scaffold.ts:111]: Probably out of scope but it's unclear to me why we're using half of the length of the TestAccounts enum - I think the intent here isn't clear, maybe we can write this in a differnet way that makes more sense.

File: packages/env-tests/src/scaffold.ts [hunk 3]
```diff
@@ -116,11 +144,14 @@ export async function clearAllFundsToRoot(context: EnvTestContext, stableTokensT
...
     }
     for (const stableToken of stableTokensToClear) {
-      const stableTokenInstance = await initStableTokenFromRegistry(stableToken, context.kit)
+      const stableTokenInstance = await context.kit.celoTokens.getWrapper(stableToken)
       const balance = await stableTokenInstance.balanceOf(account.address)
       if (balance.gt(maxBalanceBeforeCollecting)) {
         await stableTokenInstance
-          .transfer(root.address, balance.times(0.99).integerValue(BigNumber.ROUND_DOWN).toString())
+          .transfer(
+            root.address,
```
Comment (bowd) [inline packages/env-tests/src/scaffold.ts:153]: Previously `root` was replaced with `validator0` but it's unclear to me if this should happen here as well?

File: packages/env-tests/src/scaffold.ts [hunk 4]
```diff
@@ -141,20 +172,17 @@ export async function clearAllFundsToRoot(context: EnvTestContext, stableTokensT
...
-  const exchangeContract = newExchange(kit.web3, exchangeAddress)
-  return new ExchangeWrapper(kit, exchangeContract)
+  for (const stableTokenStr of stableTokenStrs) {
+    if (validStableTokens.includes(stableTokenStr as StableToken)) {
+      stableTokens.push(stableTokenStr as StableToken)
+    } else {
+      throw Error(`String ${stableTokenStr} not a valid StableToken`)
+    }
+  }
+  return stableTokens
```
Comment (bowd) [inline packages/env-tests/src/scaffold.ts]: nit: Give that we're throwing on any invalid item in the list it's probably safe to avoid constructing the extra array and just do `return stableTokenStrs as StableToken[]` at the end and inside the for loop just throw if any of them is invalid.

File: packages/env-tests/src/tests/granda-mento.ts [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+import {
+  fundAccountWithCELO,
+  fundAccountWithStableToken,
+  getKey,
+  ONE,
+  TestAccounts,
+} from '../scaffold'
+
+export function runGrandaMentoTest(context: EnvTestContext, stableTokensToTest: StableToken[]) {
+  const celoAmountToFund = ONE.times(61000)
```
Comment (bowd) [inline packages/env-tests/src/tests/granda-mento.ts:19]: Given the tests also run on mainnet, does this mean we'll be moving around 61k celo to run the tests?

File: packages/env-tests/src/tests/granda-mento.ts [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+              })
+            const minedCancelTx = await context.kit.web3.eth.getTransaction(
+              cancelReceipt.transactionHash
+            )
+
+            logger.debug(
+              {
+                proposalId,
+              },
+              'Cancelled exchange proposal'
```
Comment (yerdua) [inline packages/env-tests/src/tests/granda-mento.ts:165]: Should there also be a test for the exchange being approved and completed?

Caveat: I'm not 100% clear on the scope and limitations of env-tests.

**Review by bowd — APPROVED** [review]
Given the title "Granda Mento basic env test" will we add more advanced tests in a separate PR? Can we add ones with approval at least on the testnets (I imagine simulating approval on mainnet would be impossible unless we do it on a separate instance of GrandaMento which defeats the purpose).

Do we have a nice way to say something like don't run this test on this chainId?

File: packages/env-tests/src/scaffold.ts (hunk 3 above)
Comment (tkporter) [reply packages/env-tests/src/scaffold.ts:153]: Just added a comment explaining why, it's because `validator0` is used for CELO funding and `root` is used for stable token funding

File: packages/env-tests/src/tests/granda-mento.ts (hunk 6 above)
Comment (tkporter) [reply packages/env-tests/src/tests/granda-mento.ts:165]: Hmm I've been flip-flopping on a couple other test cases because they require waiting long periods of time and I'm not sure if env-tests are well suited for that.
* Approving & governance vetoing - passing a governance proposal to veto requires waiting between stages
* Approving & executing - requires waiting the veto period before the proposal is able to execute

I'll chat with Nam to see what his take is given he probably has the most context on env-tests, but I think these may need to be manually tested on a testnet

File: packages/env-tests/src/tests/granda-mento.ts (hunk 5 above)
Comment (tkporter) [reply packages/env-tests/src/tests/granda-mento.ts:19]: I've been going under the assumption this would be tested on staging/alfajores/baklava when we test the governance proposal to activate GrandaMento prior to mainnet activation. Testing on mainnet doesn't feel super practical because the minimum exchange quantities will be pretty large (eg buying/selling 50k cUSD will probably be the min amount). Plus the `env-tests` make strong assumptions about funds being accessible in sorta-insecure keys that are derived from the mnemonic, which probably don't have real funds on mainnet

Comment (tkporter) [reply packages/env-tests/src/tests/granda-mento.ts:19]: Confirmed this will not be ran on mainnet

File: packages/env-tests/src/tests/granda-mento.ts (hunk 6 above)
Comment (tkporter) [reply packages/env-tests/src/tests/granda-mento.ts:165]: Ended up adding that test case

**Review by yerdua — APPROVED** [review]
