### PR TITLE
[Wallet] Fix escrow failing randomly with local currency

### LINKED ISSUE #3000: Error transferring to escrow when using local currency
### Expected Behavior

No error due to decimal places

### Current Behavior

Sometimes when using local currency, for certain amounts, the transfer to escrow fails with this error:
```
escrow/saga@transferToEscrow/ Approving escrow Transfer
escrow/saga@transferToEscrow/ Error transferring to escrow:[ethjs-unit] too many decimal places in toWei
```

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This PR fixes sending an invite with an escrowed payment failing randomly when using a local currency.

See details in #3000

### Other changes

- Fixed dynamic link generation never returning and leaving the UI in loading state indefinitely (underlying error was `Invalid domainURIPrefix scheme. Scheme needs to be https`)

### Tested

Added new test. Invite with escrow works.

### Related issues

- Fixes #3000

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/localCurrency/convert.ts [hunk 1]
```diff
@@ -48,5 +48,5 @@ export function convertLocalAmountToDollars(
 //   If the user enters `2.99` cUSD, this function has no impact
 //   and `2.99` is still displayed in the confirmation screen.
 export function convertDollarsToMaxSupportedPrecision(amount: BigNumber) {
-  return new BigNumber(amount.toPrecision(18, BigNumber.ROUND_UP))
+  return new BigNumber(amount.toFixed(18, BigNumber.ROUND_UP))
```
Comment (jeanregisser) [inline packages/mobile/src/localCurrency/convert.ts:51]: This was all my bad, I misunderstood the behavior of `toPrecision` when I implemented this.

It doesn't limit the number to X decimals, but to X significant digits.
See https://mikemcl.github.io/bignumber.js/#toP and https://en.wikipedia.org/wiki/Significant_figures#Significant_figures_rules_explained

`toFixed` does what we want.

**Review by gnardini — APPROVED** [review]

**Review by jmrossy — APPROVED** [review]
Nice catch!

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser  i have tried to repro issue on test flight build v1.1.0 (21) and able to repro issue. 
Also, i have  verified issue using latest  Android build v1.1.0 (1004294311) and IOS test flight build v1.1.0(23) and found that issue is fixed. 
- User is able  to send invitation with decimal escrow payment with selected local currency. 
Note: i have verified task with selecting CAD and EUR currency. 

Please let me know if you want to  verify anything else.
