### PR TITLE
[Wallet] Local currency everywhere

### LINKED ISSUE #1261: Users SBAT see switched currency order on home screen
### Expected Behavior

[Figma](https://www.figma.com/file/Pp1N48FwfpBzb4b2ggpsjR/Local-Currency?node-id=0%3A1) (includes examples)

**Wallet Balance**
balance
Changes:
* "Celo Dollar" text removed
* Local currency and CUSD swapped in priority

Note: The local currency mockup shows both the currency symbol (€) and acronym (EUR). This is a bit redundant for Euro, but not so with $/MXN. 
Some options: 
* Only show acronym
* Be dynamic based on country (sometimes show symbol, sometimes show both)
* Always show both

**Transaction Feed** 
feed
Changes:
* CUSD value is removed
* Local currency elevated
* Currency symbol added

**Transaction Drilldown**
drilldown
Changes:
* CUSD balance added for Non-USD local currency
* Text weight for text displaying comment went from Light -> Regular

### Current Behavior
- cUSD on top
- both currencies in feed
- no cUSD in drilldown

### LINKED ISSUE #2278: [Wallet] Users SBAT see consistently rounded standby and confirmed transactions
### Expected Behavior

Numbers displayed in activity feed are the same before and after the transaction has been confirmed

### Current Behavior

Numbers can differ by 0.01
This may be fixed through https://github.com/celo-org/celo-monorepo/issues/1484

### LINKED ISSUE #2329: Amount in “Payments You’ve Requested” and “Requests from Others” sections are not converted into a selected currency.
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (18)
**Repro on:** iPhone 7 (13.3), iPhone 7+ (12.4)

Precondition: 
User should select Currency options other than the USD. 
User should have  “Payments You’ve Requested” and “Requests from Others” sections 

**Repro Steps:** 
1) Launch the app. 
2) Tap on Cog icon 
3) Tap on Currency option. 
4) Select any currency other than the USD. 
5) Navigate to wallet > Payment you’ve requested section

**Current Behavior:** Amount in “Payments You’ve Requested” and “Requests from Others” sections are not converted into a selected currency amount.
**Expected Behavior:** Amount should be shown in the selected currency. 

**Investigation:** Issue does not repro on "Pay request" screen. 

**Attachment:** IOS_CurrencyIssue_PaymentRequest.png
IOS_CurrencyIssue_PaymentRequest

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This PR migrates all remaining places displaying money amounts to use `<CurrencyDisplay />`.
- `<CurrencyDisplay />` now covers all our existing use cases.
- local currency is now correctly used for all kind of notifications (invites, incoming/outgoing requests).
- payment, request and invite screens now use a similar style as introduced in the new gold flow (line items spanning the screen width, all amounts in the local currency, total amount in cUSD is only shown under the Total item when local currency is not USD).
- security fee is now calculated in the `InviteReview` screen.
- exchange rate drill down now supports local currency.
- fixes standby exchanges (unconfirmed) showing incorrect amounts.
- fixes a regression introduced in #2965 when USD local currency is selected: in some places, USD code would be displayed.
- various smaller style tweaks.

#### EmptyWallet (USD)

**before/after**

#### Send or request (USD)

**before/after**

#### Send or request (EUR)

**before/after**

#### Payment Review (USD)

**before/after**

#### Payment Review (EUR)

**before/after**

#### Request (USD)

**before/after**

#### Request (EUR)

**before/after**

#### Invite and send (USD)

**before/after**

#### Invite and send (EUR)

**before/after**

#### Invite (no funds) (USD)

**before/after**

#### Invite (no funds) (EUR)

**before/after**

#### Buy gold review (USD)

**before/after**

#### Buy gold review (EUR)

**before/after**

#### Escrow single (USD)

**before/after**

#### Escrow single (EUR)

**before/after**

#### Escrow multiple (USD)

**before/after**

#### Escrow multiple (EUR)

**before/after**

#### Escrow screen multiple (USD)

**before/after**

#### Escrow screen multiple (EUR)

**before/after**

#### Reclaim Payment (USD)

**before/after**

#### Reclaim Payment (EUR)

**before/after**

#### Sent payment drill down (USD)

**before/after**

#### Sent payment drill down (EUR)

**before/after**

#### Faucet drilldown (USD)

**before/after**

#### Faucet drilldown (EUR)

**before/after**

#### cUSD -> cGLD Exchange drilldown (USD)

**before/after**

#### cUSD -> cGLD Exchange drilldown (EUR)

**before/after**

#### cGLD -> cUSD Exchange drilldown  (USD)

**before/after**

#### cGLD -> cUSD Exchange drilldown (EUR)

**before/after**

#### Incoming Payment Request single (USD)

**before/after**

#### Incoming Payment Request single (EUR)

**before/after**

#### Incoming Payment Request multiple (USD)

**before/after**

#### Incoming Payment Request multiple (EUR)

**before/after**

#### Incoming Payment Request screen multiple (USD)

**before/after**

#### Incoming Payment Request screen multiple (EUR)

**before/after**

#### Outgoing Payment Request single (USD)

**before/after**

#### Outgoing Payment Request single (EUR)

**before/after**

#### Outgoing Payment Request multiple (USD)

**before/after**

#### Outgoing Payment Request multiple (EUR)

**before/after**

#### Outgoing Payment Request screen multiple (USD)

**before/after**

#### Outgoing Payment Request screen multiple (EUR)

**before/after**

### Related issues

- Epic #2744
- Fixes #1261
- Fixes #2329
- Fixes #2278

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/components/LineItemRow.tsx [hunk 1]
```diff
@@ -1,56 +1,60 @@
...
   titleIcon?: React.ReactNode
   isLoading?: boolean
   hasError?: boolean
 }
 
-function LineItemRow({
-  currencySymbol,
+export default function LineItemRow({
+  style,
+  textStyle: passedTextStyle,
```
Comment (jmrossy) [inline packages/mobile/src/components/LineItemRow.tsx]: Nit: rename to `textStyleProp` for clarity?

File: packages/mobile/src/components/TotalLineItem.tsx [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+        amount={<CurrencyDisplay amount={amount} />}
+      />
+      {localCurrencyCode !== LocalCurrencyCode.USD && localCurrencyExchangeRate && (
+        <LineItemRow
+          title={
+            <Trans i18nKey="totalInDollars" ns={Namespaces.global}>
+              Celo Dollars (@{' '}
+              <CurrencyDisplay
+                amount={{
+                  value: new BigNumber(localCurrencyExchangeRate).pow(-1).toString(),
```
Comment (jmrossy) [inline packages/mobile/src/components/TotalLineItem.tsx]: Would it be a pain to have CurrencyDisplay's MoneyAmount accept BigNumbers or strings so we don't have to .toString() in places like this?

File: packages/mobile/src/navigator/Headers.tsx [hunk 3]
```diff
@@ -47,31 +48,57 @@ export const headerWithCancelButton = {
...
+            <CurrencyDisplay
+              amount={{
+                value: balance,
+                currencyCode: CURRENCIES[token].code,
+              }}
+            />{' '}
+            available
+          </Trans>
+        ) : (
+          i18n.t('global:loading')
```
Comment (jmrossy) [inline packages/mobile/src/navigator/Headers.tsx:78]: Not sure we can be certain the balance is loading just because it's null here. Maybe just leave a TODO or comment here mentioning that?

**Review by jmrossy — APPROVED** [review]
Outstanding! Thanks for tackling this. A few optional minor comments but lgtm

File: packages/mobile/src/components/LineItemRow.tsx (hunk 1 above)
Comment (jeanregisser) [reply packages/mobile/src/components/LineItemRow.tsx]: Yep much better 👍

File: packages/mobile/src/components/TotalLineItem.tsx (hunk 2 above)
Comment (jeanregisser) [reply packages/mobile/src/components/TotalLineItem.tsx]: Yeah would be nicer! 
The `MoneyAmount` type originally came from the GraphQL api changes where we have to serialize as string.
I think there's an easy way to change it to `BigNumber.Value`.

File: packages/mobile/src/navigator/Headers.tsx (hunk 3 above)
Comment (jeanregisser) [reply packages/mobile/src/navigator/Headers.tsx:78]: Agreed!
