### PR TITLE
Fix support for validator key rotation, add end-to-end test

### LINKED ISSUE #1627: End-to-end tests for validator key rotation
### Expected Behavior

End-to-end tests of validators authorizing validating keys, updating BLS keys, etc.

### Current Behavior

No end-to-end tests of this.

### PR DESCRIPTION
**Pull request by asaj**
### Description

This PR fixes support for validator key rotation, and tests it in the end-to-end governance tests. 

### Tested

- Updates the governance end-to-end tests to test that key rotation works by using the account as the validator signer in epoch N, an authorized validator signer in epoch N+1, and a second authorized validator signer in epoch N+2

### Other changes
- Refactor `publicKeysData` logic to split out the various components, not store the proof-of-possession.
- Updated end-to-end governance tests to ensure no IBFT round changes by inferring the random proposer order and asserting blocks are proposed in that order 
- Fix small bug in end-to-end tests where private keys written to the same file
- Update `account:authorize` CLI command so that we don't assume account and signing keys are managed by the same node, add `account:proof-of-possession` command
- Make name optional in `account:register`
- Small changes to naming in `Accounts.sol`
- Reorder functions in `Accounts.sol`
- Move some logic from `protocol` into `utils`
 
### Related issues

- Fixes #1627 

### Backwards compatibility

Not backwards compatible

### CODE REVIEW

File: packages/cli/src/utils/command.ts [hunk 1]
```diff
@@ -4,14 +4,24 @@ import { IArg, ParseFn } from '@oclif/parser/lib/args'
...
-    throw new CLIError(`${input} is not a public key`)
+    throw new CLIError(msg)
   }
 }
+
+const parseEcdsaPublicKey: ParseFn<string> = (input) => {
+  parseBytes(input, 64, `${input} is not an ECDSA public key`)
+}
+const parseBlsPublicKey: ParseFn<string> = (input) => {
+  parseBytes(input, 48, `${input} is not a BLS public key`)
```
Comment (kobigurk) [inline packages/cli/src/utils/command.ts]: Can we pull these numbers from a common place? Especially since they might change soon.

File: packages/protocol/contracts/common/UsingPrecompiles.sol [hunk 2]
```diff
@@ -123,16 +177,20 @@ contract UsingPrecompiles {
...
-   * @param proofOfPossessionBytes The public key and signature of the proof of possession.
+   * @param sender The address signed by the BLS key to generate the proof of possession.
+   * @param blsKey The BLS public key that the validator is using for consensus, should pass proof
+   *   of possession. 48 bytes.
+   * @param blsPop The BLS public key proof-of-possession, which consists of a signature on the
+   *   account address. 96 bytes.
    * @return True upon success.
    */
-  function checkProofOfPossession(address sender, bytes memory proofOfPossessionBytes)
+  function checkProofOfPossession(address sender, bytes memory blsKey, bytes memory blsPop)
```
Comment (kobigurk) [inline packages/protocol/contracts/common/UsingPrecompiles.sol:133]: I'm very happy you were able to separate it into two values! Previously, this caused the contract to have more than the maximum code size. How did you get around it?

File: packages/utils/src/bls.ts [hunk 3]
```diff
@@ -35,3 +36,21 @@ export const blsPrivateKeyToProcessedPrivateKey = (privateKeyHex: string) => {
...
+  const blsPrivateKeyBytes = blsPrivateKeyToProcessedPrivateKey(privateKeyHex.slice(2))
+  return blsPrivateKeyBytes
+}
+
+export const getBlsPublicKey = (privateKeyHex: string) => {
+  const blsPrivateKeyBytes = getBlsPrivateKey(privateKeyHex)
+  return '0x' + bls12377js.BLS.privateToPublicBytes(blsPrivateKeyBytes).toString('hex')
+}
+
+export const getBlsPoP = (address: string, privateKeyHex: string) => {
```
Comment (kobigurk) [inline packages/utils/src/bls.ts:53]: We should probably verify address is a valid address.

File: packages/contractkit/src/wrappers/Accounts.ts [hunk 4]
```diff
@@ -69,44 +71,75 @@ export class AccountsWrapper extends BaseWrapper<Accounts> {
...
+    )
   }
 
   /**
    * Authorizes an address to sign consensus messages on behalf of the account.
-   * @param account Address of the active account.
-   * @param validationSigner The address of the signing key to authorize.
+   * @param signer The address of the signing key to authorize.
+   * @param proofOfSigningKeyPossession The account address signed by the signer address.
+   * @param proofOfBlsKeyPossession Proof-of-possession generated for the corresponding BLS key. Only needed if a validator has been registered.
```
Comment (kobigurk) [inline packages/contractkit/src/wrappers/Accounts.ts]: This is currently not implemented?

File: packages/protocol/contracts/common/Accounts.sol [hunk 5]
```diff
@@ -85,102 +133,191 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
-   * @param voter The address of the vote signing key to authorize.
+   * @param signer The address of the signing key to authorize.
    * @param v The recovery id of the incoming ECDSA signature.
    * @param r Output value r of the ECDSA signature.
    * @param s Output value s of the ECDSA signature.
-   * @dev v, r, s constitute `voter`'s signature on `msg.sender`.
+   * @dev v, r, s constitute `signer`'s signature on `msg.sender`.
    */
-  function authorizeVoteSigner(address voter, uint8 v, bytes32 r, bytes32 s) external nonReentrant {
+  function authorizeVoteSigner(address signer, uint8 v, bytes32 r, bytes32 s)
```
Comment (kobigurk) [inline packages/protocol/contracts/common/Accounts.sol:142]: Is this where the BLS rotation will be implemented?

Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:142]: Nope! This is actually unrelated, and allows you to specify a different ECDSA key for voting in governance in validator elections.

BLS rotation is implemented in `Validators.updateBlsKey`

File: packages/protocol/contracts/common/UsingPrecompiles.sol (hunk 2 above)
Comment (asaj) [reply packages/protocol/contracts/common/UsingPrecompiles.sol:133]: We upped the max code size 😄

File: packages/contractkit/src/wrappers/Accounts.ts (hunk 4 above)
Comment (asaj) [reply packages/contractkit/src/wrappers/Accounts.ts]: Whoops! This was accidentally left over from the coupled-key implementation. BLS key rotation now happens in `Validators`

File: packages/protocol/contracts/common/UsingPrecompiles.sol (hunk 2 above)
Comment (kobigurk) [reply packages/protocol/contracts/common/UsingPrecompiles.sol:133]: :D

File: packages/protocol/contracts/common/Accounts.sol (hunk 5 above)
Comment (kobigurk) [reply packages/protocol/contracts/common/Accounts.sol:142]: OK! I understand it better now.

File: packages/protocol/contracts/common/Accounts.sol [hunk 6]
```diff
@@ -85,102 +133,211 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
+   * @dev Fails if the `signer` is not an account or currently authorized attestation signer.
    * @return The associated account.
    */
-  function activeAttesttationSignerToAccount(address accountOrAttestationSigner)
-    external
-    view
-    returns (address)
-  {
-    address authorizingAccount = authorizedBy[accountOrAttestationSigner];
+  function activeAttesttationSignerToAccount(address signer) external view returns (address) {
```
Comment (nambrot) [inline packages/protocol/contracts/common/Accounts.sol]: Typo

File: packages/protocol/contracts/common/Accounts.sol [hunk 7]
```diff
@@ -73,6 +79,48 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
     setWalletAddress(walletAddress);
   }
 
+  /**
```
Comment (nambrot) [inline packages/protocol/contracts/common/Accounts.sol:82]: Why did you move the functions up here? I thought external functions go above public ones?

File: packages/celotool/src/e2e-tests/governance_tests.ts [hunk 8]
```diff
@@ -128,31 +136,115 @@ describe('governance tests', () => {
...
-      }
-      await initAndStartGeth(context.hooks.gethBinaryPath, groupInstance)
-      allValidators = await getValidatorGroupMembers()
-      assert.equal(allValidators.length, 5)
+      const groupPrivateKey = await getValidatorGroupPrivateKey()
+      const rotation0PrivateKey =
+        '0xa42ac9c99f6ab2c96ee6cae1b40d36187f65cd878737f6623cd363fb94ba7087'
+      const rotation1PrivateKey =
+        '0x4519cae145fb9499358be484ca60c80d8f5b7f9c13ff82c88ec9e13283e9de1a'
+      const additionalNodes: any[] = [
```
Comment (nategraf) [inline packages/celotool/src/e2e-tests/governance_tests.ts]: `GethInstanceConfig` from `src/e2e-tests/util` would be more specific
```suggestion
      const additionalNodes: GethInstanceConfig[] = [
```

File: packages/celotool/src/e2e-tests/governance_tests.ts [hunk 9]
```diff
@@ -34,7 +37,7 @@ describe('governance tests', () => {
   let goldToken: any
   let registry: any
   let validators: any
-  let accounts: AccountsWrapper
+  let accounts: any
```
Comment (nambrot) [inline packages/celotool/src/e2e-tests/governance_tests.ts:43]: Why are we not using the Wrapper anymore?

File: packages/celotool/src/e2e-tests/governance_tests.ts [hunk 10]
```diff
@@ -128,31 +136,115 @@ describe('governance tests', () => {
...
+  ) => {
+    const validator = (await validatorWeb3.eth.getAccounts())[0]
+    const signer = (await signerWeb3.eth.getAccounts())[0]
+    await unlockAccount(validator, validatorWeb3)
+    await unlockAccount(signer, signerWeb3)
+    const pop = await (await newKitFromWeb3(
+      signerWeb3
+    ).contracts.getAccounts()).generateProofOfSigningKeyPossession(validator, signer)
+    const validatorKit = newKitFromWeb3(validatorWeb3)
+    const validatorAccounts = await validatorKit._web3Contracts.getAccounts()
```
Comment (nambrot) [inline packages/celotool/src/e2e-tests/governance_tests.ts]: What about using the ContractKit wrapper? That would avoid you having to estimate gas etc.

File: packages/celotool/src/e2e-tests/governance_tests.ts [hunk 11]
```diff
@@ -501,10 +657,10 @@ describe('governance tests', () => {
         // Assert equal to 10 decimal places due to rounding errors.
```
Comment (nategraf) [inline packages/celotool/src/e2e-tests/governance_tests.ts]:
```suggestion
         // Assert equal to 9 decimal places due to rounding errors.
```

File: packages/protocol/contracts/common/Accounts.sol [hunk 12]
```diff
@@ -73,6 +79,48 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
+
+  /**
+   * @notice Setter for the data encryption key and version.
+   * @param dataEncryptionKey secp256k1 public key for data encryption. Preferably compressed.
+   */
+  function setAccountDataEncryptionKey(bytes memory dataEncryptionKey) public {
+    require(dataEncryptionKey.length >= 33, "data encryption key length <= 32");
+    accounts[msg.sender].dataEncryptionKey = dataEncryptionKey;
+    emit AccountDataEncryptionKeySet(msg.sender, dataEncryptionKey);
+  }
```
Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol:122]: The most common compression for public keys is 257 bits = 33 bytes if I am not mistaken. https://cryptobook.nakov.com/asymmetric-key-ciphers/elliptic-curve-cryptography-ecc#ecc-keys

File: packages/protocol/contracts/common/Accounts.sol [hunk 13]
```diff
@@ -85,102 +133,211 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
+    address signer,
+    bytes calldata ecdsaKey,
+    uint8 v,
+    bytes32 r,
+    bytes32 s
+  ) external nonReentrant {
+    Account storage account = accounts[msg.sender];
+    authorize(signer, v, r, s);
+    account.signers.validator = signer;
+    require(getValidators().updateEcdsaKey(msg.sender, signer, ecdsaKey));
```
Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol]: I think changing the signer with the previous overload could break the invariant that stored `ecdsa` key correspond to the authorized signing address.

Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol]: Does this need `require(!getValidators().isValidator(msg.sender));`

```suggestion
    require(!getValidators().isValidator(msg.sender));
    require(getValidators().updateEcdsaKey(msg.sender, signer, ecdsaKey));
```

File: packages/protocol/contracts/common/Accounts.sol [hunk 14]
```diff
@@ -85,102 +133,211 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
-  function activeAttesttationSignerToAccount(address accountOrAttestationSigner)
-    external
-    view
-    returns (address)
-  {
-    address authorizingAccount = authorizedBy[accountOrAttestationSigner];
+  function activeAttesttationSignerToAccount(address signer) external view returns (address) {
+    address authorizingAccount = authorizedBy[signer];
+    if (authorizingAccount != address(0)) {
+      require(accounts[authorizingAccount].signers.attestation == signer);
```
Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol:218]: If I am not mistaken, if this `require` ever fails, there is a bug. It may be worth adding a comment here on that.

File: packages/protocol/contracts/common/Accounts.sol [hunk 15]
```diff
@@ -85,102 +133,211 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
+    }
+  }
+
+  /**
+   * @notice Returns the account associated with `signer`.
+   * @param signer The address of the account or previously authorized vote signer.
+   * @dev Fails if the `signer` is not an account or previously authorized vote signer.
+   * @return The associated account.
+   */
+  function voteSignerToAccount(address signer) external view returns (address) {
```
Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol:249]: When would someone want to use this instead of `activeVoteSignerToAccount`? Also If I am not mistaken, this will return an account which is authorized as a validator or attester, which is confusing because the name mentions `vote`. You might consolidate the next three functions into one `signerToAccount` function

File: packages/protocol/contracts/common/Accounts.sol [hunk 16]
```diff
@@ -420,31 +423,38 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
+  function authorize(address authorized, uint8 v, bytes32 r, bytes32 s) private {
+    require(isAccount(msg.sender) && isNotAccount(authorized) && isNotAuthorizedSigner(authorized));
 
     address signer = Signatures.getSignerOfAddress(msg.sender, v, r, s);
-    require(signer == current);
+    require(signer == authorized);
 
-    authorizedBy[previous] = address(0);
-    authorizedBy[current] = msg.sender;
+    authorizedBy[authorized] = msg.sender;
```
Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol:427]: It seems that with this change, it seems once an authorization is replaced, the previously authorized address can never again become an authorized signer. Is that the intention? If so could you add some comments to that effect were relevant.

File: packages/protocol/contracts/common/Accounts.sol [hunk 17]
```diff
@@ -420,31 +423,38 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
-   * @param previous The previous authorized address.
+   * @notice Authorizes some role of of `msg.sender`'s account to another address.
+   * @param authorized The address to authorize.
    * @param v The recovery id of the incoming ECDSA signature.
    * @param r Output value r of the ECDSA signature.
    * @param s Output value s of the ECDSA signature.
    * @dev Fails if the address is already authorized or is an account.
    * @dev v, r, s constitute `current`'s signature on `msg.sender`.
    */
-  function authorize(address current, address previous, uint8 v, bytes32 r, bytes32 s) private {
```
Comment (nategraf) [inline packages/protocol/contracts/common/Accounts.sol:441]: In my pass through this file I didn't see a way to clear authorizations (i.e. set `account.signer.* = address(0)`) Did I miss it? If not, that seems like an important function to add.

File: packages/protocol/contracts/governance/Validators.sol [hunk 18]
```diff
@@ -470,46 +477,82 @@ contract Validators is
...
+    onlyRegisteredContract(ACCOUNTS_REGISTRY_ID)
+    returns (bool)
+  {
     require(isValidator(account));
     Validator storage validator = validators[account];
-    _updatePublicKeysData(validator, publicKeysData);
-    emit ValidatorPublicKeysDataUpdated(account, publicKeysData);
+    require(_updateEcdsaKey(validator, signer, ecdsaKey));
+    emit ValidatorEcdsaKeyUpdated(account, ecdsaKey);
     return true;
```
Comment (nategraf) [inline packages/protocol/contracts/governance/Validators.sol:538]: Why does this function return a bool if it reverts on failure?

File: packages/celotool/src/e2e-tests/governance_tests.ts [hunk 19]
```diff
@@ -249,39 +411,39 @@ describe('governance tests', () => {
...
-          (await validators.methods.getValidator(validator).call({}, blockNumber))[3]
+          (await validators.methods.getValidator(validator).call({}, blockNumber)).score
         )
         const previousScore = new BigNumber(
-          (await validators.methods.getValidator(validator).call({}, blockNumber - 1))[3]
+          (await validators.methods.getValidator(validator).call({}, blockNumber - 1)).score
         )
-        assert.isNotNaN(score)
-        assert.isNotNaN(previousScore)
+        assert.isFalse(score.isNaN())
```
Comment (nambrot) [inline packages/celotool/src/e2e-tests/governance_tests.ts:409]: Looks like `chai` has a function for this `assert.isNotNaN(score)`

File: packages/protocol/contracts/governance/Validators.sol [hunk 20]
```diff
@@ -258,27 +260,32 @@ contract Validators is
...
+    returns (bool)
+  {
+    address account = getAccounts().activeValidatorSignerToAccount(msg.sender);
     require(!isValidator(account) && !isValidatorGroup(account));
     uint256 lockedGoldBalance = getLockedGold().getAccountTotalLockedGold(account);
     require(lockedGoldBalance >= validatorLockedGoldRequirements.value);
     Validator storage validator = validators[account];
-    _updatePublicKeysData(validator, publicKeysData);
-    validator.publicKeysData = publicKeysData;
+    address signer = getAccounts().getValidatorSigner(account);
```
Comment (nategraf) [inline packages/protocol/contracts/governance/Validators.sol:283]: Is this not always equal to `msg.sender` by virtue of having obtained `account` via `activeValidatorSignerToAccount`?

File: packages/cli/src/commands/account/proof-of-possession.ts [hunk 21]
```diff
@@ -0,0 +1,28 @@
...
+  static description = 'Generate proof-of-possession to be used to authorize a signer'
+
+  static flags = {
+    ...BaseCommand.flags,
+    signer: Flags.address({ required: true }),
+    account: Flags.address({ required: true }),
+  }
+
+  static examples = [
+    'proof-of-possession --account 0x5409ed021d9299bf6814279a6a1411a7e866a631 --signer 0x6ecbe1db9ef729cbe972c83fb886247691fb6beb',
```
Comment (nambrot) [inline packages/cli/src/commands/account/proof-of-possession.ts:16]: As naming czar, I wonder what you think about `prove-possession` as our commands are generally actions/verbs?

File: packages/protocol/contracts/governance/Validators.sol [hunk 22]
```diff
@@ -706,19 +749,39 @@ contract Validators is
...
+   * @notice Returns the validator BLS key.
+   * @param signer The account that registered the validator or its authorized signing address.
+   * @return The validator BLS key.
+   */
+  function getValidatorBlsKeyFromSigner(address signer)
+    external
+    view
+    returns (bytes memory blsKey)
+  {
+    address account = getAccounts().validatorSignerToAccount(signer);
```
Comment (nategraf) [inline packages/protocol/contracts/governance/Validators.sol]: Is there a reason this is `validatorSignerToAccount` instead of `activeValidatorSignerToAccount`?

File: packages/contractkit/src/wrappers/Accounts.test.ts [hunk 23]
```diff
@@ -0,0 +1,83 @@
...
+  const registerAccountWithLockedGold = async (account: string) => {
+    if (!(await accountsInstance.isAccount(account))) {
+      await accountsInstance.createAccount().sendAndWaitForReceipt({ from: account })
+    }
+    await lockedGold.lock().sendAndWaitForReceipt({ from: account, value: minLockedGoldValue })
+  }
+
+  const getParsedSignatureOfAddress = async (address: string, signer: string) => {
+    const addressHash = web3.utils.soliditySha3({ type: 'address', value: address })
+    console.log('account', address)
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Accounts.test.ts]: Should these be here?

File: packages/contractkit/src/wrappers/Accounts.test.ts [hunk 24]
```diff
@@ -0,0 +1,83 @@
...
+    console.log('addressHash', addressHash)
+    const signature = await web3.eth.sign(addressHash, signer)
+    return parseSignature(addressHash, signature, signer)
+  }
+
+  beforeAll(async () => {
+    accounts = await web3.eth.getAccounts()
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Accounts.test.ts:43]: in `test-utils/ganache.setup.ts` we have the list of accounts as well

File: packages/contractkit/src/wrappers/Accounts.test.ts [hunk 25]
```diff
@@ -0,0 +1,83 @@
...
+    lockedGold = await kit.contracts.getLockedGold()
+    accountsInstance = await kit.contracts.getAccounts()
+  })
+
+  const setupValidator = async (validatorAccount: string) => {
+    const publicKey = await addressToPublicKey(validatorAccount, web3)
+    await registerAccountWithLockedGold(validatorAccount)
+    await validators
+      .registerValidator(
+        // @ts-ignore
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Accounts.test.ts]: Should these fit on a single line?

File: packages/contractkit/src/wrappers/Accounts.ts [hunk 26]
```diff
@@ -9,11 +14,12 @@ import {
   toTransactionObject,
 } from '../wrappers/BaseWrapper'
 
-enum SignerRole {
-  Attestation,
-  Validation,
-  Vote,
+export interface Signature {
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Accounts.ts]: You should be able to import this from ` '@celo/utils/lib/signatureUtils`

File: packages/protocol/contracts/common/Accounts.sol [hunk 27]
```diff
@@ -85,102 +133,211 @@ contract Accounts is IAccounts, ReentrancyGuard, Initializable, UsingRegistry {
...
+    emit ValidatorSignerAuthorized(msg.sender, signer);
   }
 
   /**
-   * @notice Check if an address has been authorized by an account for voting or validating.
-   * @param account The possibly authorized address.
-   * @return Returns `true` if authorized. Returns `false` otherwise.
+   * @notice Authorizes an address to sign consensus messages on behalf of the account.
+   * @param signer The address of the signing key to authorize.
+   * @param ecdsaKey The ECDSA key corresponding to `signer`.
```
Comment (nambrot) [inline packages/protocol/contracts/common/Accounts.sol]: I'm not too familiar with the terminology, but does `ECDSA key` always imply the public key? In my naive reading I would have assumed private key

File: packages/protocol/test/governance/validators.ts [hunk 28]
```diff
@@ -1016,53 +1068,116 @@ contract('Validators', (accounts: string[]) => {
...
-      describe('when the public keys data is too long', () => {
+      describe('when the public key is not 48 bytes', () => {
         it('should revert', async () => {
           // @ts-ignore Broken typechain typing for bytes
-          await assertRevert(validators.updatePublicKeysData(newPublicKeysData + '00'))
+          await assertRevert(validators.updateBlsKey(newBlsPublicKey + '01', newBlsPoP))
         })
       })
 
-      describe('when the public keys data is too short', () => {
```
Comment (nategraf) [inline packages/protocol/test/governance/validators.ts:1062]: It would be helpful to also have a check to make sure we revert if the PoP is invalid (e.g using `newBlsPoP.slice(0, -2) + '01'`)

File: packages/contractkit/src/wrappers/Accounts.ts [hunk 29]
```diff
@@ -168,25 +228,14 @@ export class AccountsWrapper extends BaseWrapper<Accounts> {
...
-    [SignerRole.Attestation]: this.contract.methods.authorizeAttestationSigner,
-    [SignerRole.Validation]: this.contract.methods.authorizeValidationSigner,
-    [SignerRole.Vote]: this.contract.methods.authorizeVoteSigner,
-  }
-
-  private async authorizeSigner(role: SignerRole, account: Address, signer: Address) {
-    const sig = await this.getParsedSignatureOfAddress(account, signer)
-    // TODO(asa): Pass default tx "from" argument.
-    return toTransactionObject(this.kit, this.authorizeFns[role](signer, sig.v, sig.r, sig.s))
+  parseSignatureOfAddress(address: Address, signer: string, signature: string) {
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Accounts.ts:226]: Optional Nit: is `signer` also an `Address`?

File: packages/contractkit/src/wrappers/Validators.test.ts [hunk 30]
```diff
@@ -52,12 +48,17 @@ testWithGanache('Validators Wrapper', (web3) => {
...
 
   const setupValidator = async (validatorAccount: string) => {
+    const publicKey = await addressToPublicKey(validatorAccount, web3)
     await registerAccountWithLockedGold(validatorAccount)
     // set account1 as the validator
     await validators
       .registerValidator(
         // @ts-ignore
-        publicKeysData
+        publicKey,
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Validators.test.ts]: Optional Nit: Fit on one line?

File: packages/protocol/contracts/common/Accounts.sol (hunk 12 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:122]: @nambrot 

This was just function re-ordering, so I'm not going to address in this PR if it's okay

File: packages/protocol/contracts/common/Accounts.sol (hunk 13 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol]: The intended invariant is slightly different, which is that if you're a registered validator, the stored `ecdsa` key corresponds to the validator signer (either the account key or an authorized validator signer)

Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol]: Actually, we want to `require(getValidators().isValidator(msg.sender));`, but `updateEcdsaKey` will do this check for us

File: packages/protocol/contracts/common/Accounts.sol (hunk 16 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:427]: Yeah that is the intention, will add comments.

File: packages/protocol/contracts/common/Accounts.sol (hunk 17 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:441]: Nice eye, indeed we do not support this. I think that's *okay*, but perhaps not ideal.

File: packages/protocol/contracts/governance/Validators.sol (hunk 18 above)
Comment (asaj) [reply packages/protocol/contracts/governance/Validators.sol:538]: Just following a common solidity pattern

File: packages/protocol/contracts/governance/Validators.sol (hunk 20 above)
Comment (asaj) [reply packages/protocol/contracts/governance/Validators.sol:283]: Not necessarily, `msg.sender` could be the account address

File: packages/protocol/contracts/governance/Validators.sol (hunk 22 above)
Comment (asaj) [reply packages/protocol/contracts/governance/Validators.sol]: Hmm, I'm not certain it matters in this case but I feel that `validatorSignerToAccount` here is safer. Wdyt?

File: packages/protocol/test/governance/validators.ts (hunk 28 above)
Comment (asaj) [reply packages/protocol/test/governance/validators.ts:1062]: Since we actually don't have this precompile in ganache we can't check this yet 🙁

File: packages/protocol/contracts/common/Accounts.sol (hunk 12 above)
Comment (nategraf) [reply packages/protocol/contracts/common/Accounts.sol:122]: Oh I misread this anyway. It's correct.

File: packages/protocol/contracts/common/Accounts.sol (hunk 13 above)
Comment (nategraf) [reply packages/protocol/contracts/common/Accounts.sol]: Ok I see now. The first overload is for if `msg.sender` is not a validator, and the second is for if they are. Thanks for clarifying.

File: packages/protocol/contracts/governance/Validators.sol (hunk 20 above)
Comment (nategraf) [reply packages/protocol/contracts/governance/Validators.sol:283]: I don't understand. Is it not true that `x == getValidatorSigner(activeValidatorSignerToAccount(x))`?

File: packages/protocol/contracts/governance/Validators.sol (hunk 22 above)
Comment (nategraf) [reply packages/protocol/contracts/governance/Validators.sol]: I don't think it is safer, but on second look I aggree that is generally doesn't matter. One thing is though that it might be assumed that the input needs to be the validators authorized signer for validation, but the result would be the same if the input signer was authorized for voting or attestation instead.

File: packages/utils/src/address.ts [hunk 31]
```diff
@@ -1,7 +1,35 @@
...
+  privateToPublic,
+  pubToAddress,
+  sha3,
+  toChecksumAddress,
+} from 'ethereumjs-util'
+import Web3 from 'web3'
 
 export type Address = string
 
+export async function addressToPublicKey(address: string, web3: Web3) {
```
Comment (nambrot) [inline packages/utils/src/address.ts]: The `utils` package currently does not specify `web3` as a dependency, thus generally what I did in `signatureUtils` is to pass the `web3.eth.sign` method as a parameter instead. That also highlights to the consumer of this function that there should be a web3 provider that can actually sign (vs. a web3 parameter that is used to make view calls for example).

Comment (nambrot) [reply packages/utils/src/address.ts]: Also would this make sense in signatureUtils instead?

File: packages/utils/src/address.ts [hunk 32]
```diff
@@ -1,7 +1,35 @@
...
+  const msg = new Buffer('dummy_msg_data')
+  const data = '0x' + msg.toString('hex')
+  // Note: Eth.sign typing displays incorrect parameter order
+  const sig = await web3.eth.sign(data, address)
+
+  const rawsig = fromRpcSig(sig)
+
+  const prefix = new Buffer('\x19Ethereum Signed Message:\n')
+  const prefixedMsg = sha3(Buffer.concat([prefix, new Buffer(String(msg.length)), msg]))
```
Comment (nambrot) [inline packages/utils/src/address.ts]: Probably use `hashMessageWithPrefix` in signatureUtils?

File: packages/utils/src/address.ts [hunk 33]
```diff
@@ -12,4 +40,9 @@ export const privateKeyToAddress = (privateKey: string) => {
   )
 }
 
+export const privateKeyToPublicKey = (privateKey: string) => {
+  return toChecksumAddress(
```
Comment (nambrot) [inline packages/utils/src/address.ts:18]: Did you mean to call toChecksumAddress here?

File: packages/cli/src/utils/command.ts (hunk 1 above)
Comment (asaj) [reply packages/cli/src/utils/command.ts]: Added constants in `@celo/utils/src/bls`

File: packages/protocol/contracts/common/Accounts.sol (hunk 14 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:218]: Ah so actually upon revisiting, this is not the case. If I authorize A as my attestation signer, and then B, and then call `activeAttestationSignerToAccount(A)`, we would hit this line.

File: packages/protocol/contracts/common/Accounts.sol (hunk 15 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:249]: +1 to `signerToAccount`

File: packages/protocol/contracts/governance/Validators.sol (hunk 20 above)
Comment (asaj) [reply packages/protocol/contracts/governance/Validators.sol:283]: That will be true if `x` is an authorized signer, but not if `x` is an account address.

File: packages/protocol/contracts/common/Accounts.sol (hunk 7 above)
Comment (asaj) [reply packages/protocol/contracts/common/Accounts.sol:82]: I think the more important constraint is `view` functions go last, but ultimately we should just turn linting back on for this

File: packages/celotool/src/e2e-tests/governance_tests.ts (hunk 9 above)
Comment (asaj) [reply packages/celotool/src/e2e-tests/governance_tests.ts:43]: Because we need to call functions at particular blocks

File: packages/celotool/src/e2e-tests/governance_tests.ts (hunk 19 above)
Comment (asaj) [reply packages/celotool/src/e2e-tests/governance_tests.ts:409]: Yeah that's what we used to use, and it's dangerous because the `BigNumber` representation of `NaN` is not considered `NaN` by chai

File: packages/cli/src/commands/account/proof-of-possession.ts (hunk 21 above)
Comment (asaj) [reply packages/cli/src/commands/account/proof-of-possession.ts:16]: I feel that's a bit misleading, since we're not actually proving possession here, but merely *generating* the pop. Wdyt?

File: packages/contractkit/src/wrappers/Accounts.test.ts (hunk 23 above)
Comment (asaj) [reply packages/contractkit/src/wrappers/Accounts.test.ts]: No they should not

File: packages/contractkit/src/wrappers/Accounts.test.ts (hunk 24 above)
Comment (asaj) [reply packages/contractkit/src/wrappers/Accounts.test.ts:43]: Leaving as-is if it's all the same to you

File: packages/utils/src/address.ts (hunk 33 above)
Comment (asaj) [reply packages/utils/src/address.ts:18]: Yeah, any reason not to?

File: packages/protocol/contracts/governance/Validators.sol (hunk 20 above)
Comment (nategraf) [reply packages/protocol/contracts/governance/Validators.sol:283]: Oh I see now. Thanks for explaining that.

File: packages/protocol/contracts/common/Accounts.sol (hunk 17 above)
Comment (nategraf) [reply packages/protocol/contracts/common/Accounts.sol:441]: I agree that this can wait until we see if anyone is missing it.

**Review by nategraf — APPROVED** [review]
Thanks for addressing all my comments 👍

File: packages/celotool/src/e2e-tests/governance_tests.ts (hunk 9 above)
Comment (nambrot) [reply packages/celotool/src/e2e-tests/governance_tests.ts:43]: @mcortesi Would be nice to expose that functionality on `proxyCall`?

File: packages/cli/src/commands/account/proof-of-possession.ts (hunk 21 above)
Comment (nambrot) [reply packages/cli/src/commands/account/proof-of-possession.ts:16]: sgtm, only thing I might add is `generate-pop`?

File: packages/utils/src/address.ts (hunk 33 above)
Comment (nambrot) [reply packages/utils/src/address.ts:18]: I thought checksums only apply to addresses, not public keys

File: packages/utils/src/signatureUtils.ts [hunk 34]
```diff
@@ -25,6 +27,34 @@ export interface Signer {
   sign: (message: string) => Promise<string>
 }
 
+export async function addressToPublicKey(
+  signer: string,
+  signFn: (message: string, signer: string) => Promise<string>
+) {
+  const msg = new Buffer('dummy_msg_data')
+  const data = '0x' + msg.toString('hex')
+  // Note: Eth.sign typing displays incorrect parameter order
```
Comment (nambrot) [inline packages/utils/src/signatureUtils.ts:36]: This note probably should be elsewhere now?

File: packages/utils/src/signatureUtils.ts [hunk 35]
```diff
@@ -25,6 +27,34 @@ export interface Signer {
...
+  const sig = await signFn(data, signer)
+
+  const rawsig = ethjsutil.fromRpcSig(sig)
```
Comment (nambrot) [inline packages/utils/src/signatureUtils.ts:39]: Optional Nit: Didn't know about `fromRpcSig`!! Could we streamline either that or our implementation (from below =`parseSignature`) here?

**Review by nambrot — APPROVED** [review]
Just nits!

File: .circleci/config.yml [hunk 36]
```diff
@@ -524,7 +524,7 @@ jobs:
           command: |
             set -e
             cd packages/celotool
-            ./ci_test_transfers.sh checkout master
+            ./ci_test_transfers.sh checkout asaj/key-rotation-plus-enode
```
Comment (jmrossy) [inline .circleci/config.yml:528]: do you intend to keep these pointing to your branch? Do you fix set it back in a follow-up PR once tests pass?

File: packages/utils/src/address.ts [hunk 37]
```diff
@@ -12,12 +12,18 @@ export const privateKeyToAddress = (privateKey: string) => {
...
-export const privateKeyToPublicKey = (privateKey: string) => {
-  return '0x' + privateToPublic(Buffer.from(privateKey.slice(2), 'hex')).toString('hex')
+export const publicKeyToAddress = (publicKey: string) => {
+  return toChecksumAddress(
+    '0x' + pubToAddress(Buffer.from(publicKey.slice(2), 'hex')).toString('hex')
+  )
 }
 
 export { toChecksumAddress } from 'ethereumjs-util'
+export { isValidAddress } from 'ethereumjs-util'
```
Comment (jmrossy) [inline packages/utils/src/address.ts:47]: Why are these re-exported here?
@nambrot FYI this conflicts with the changes you made in your Attestations svc PR

File: packages/utils/src/address.ts [hunk 38]
```diff
@@ -12,12 +12,18 @@ export const privateKeyToAddress = (privateKey: string) => {
...
+export const privateKeyToPublicKey = (privateKey: string) => {
+  return toChecksumAddress(
+    '0x' + privateToPublic(Buffer.from(privateKey.slice(2), 'hex')).toString('hex')
+  )
 }
 
-export const privateKeyToPublicKey = (privateKey: string) => {
-  return '0x' + privateToPublic(Buffer.from(privateKey.slice(2), 'hex')).toString('hex')
+export const publicKeyToAddress = (publicKey: string) => {
+  return toChecksumAddress(
```
Comment (jmrossy) [inline packages/utils/src/address.ts:24]: Leaving similar feedback I left for Nam on his PR that touches this:
Would be nice these methods confirmed the leading chars are '0x' before stripping them. So happens @yorhodes has added utils in this file for just this
https://github.com/celo-org/celo-monorepo/pull/1570

File: packages/utils/src/signatureUtils.ts (hunk 34 above)
Comment (jmrossy) [reply packages/utils/src/signatureUtils.ts:36]: Yeah, utils/address seems like a better place

File: packages/utils/src/signatureUtils.ts [hunk 39]
```diff
@@ -25,6 +27,34 @@ export interface Signer {
...
+    rawsig.s
+  )
+
+  const computedAddr = ethjsutil.pubToAddress(pubKey).toString('hex')
+  assert(eqAddress(computedAddr, signer), 'computed address !== signer')
+
+  return '0x' + pubKey.toString('hex')
+}
+
+export function eqAddress(a: Address, b: Address) {
```
Comment (jmrossy) [inline packages/utils/src/signatureUtils.ts]: There's an `areAddressesEqual` below in this file AND @yorhodes adds another one in his PR here: #1570 
I'll leave it to you two to coordinate but pretty sure we don't need another util method for this ;)

**Review by jmrossy — COMMENTED** [review]
Some small comments

File: .circleci/config.yml (hunk 36 above)
Comment (asaj) [reply .circleci/config.yml:528]: Yeah, you need to do it this way in order to run the end-to-end tests properly

File: packages/utils/src/address.ts (hunk 37 above)
Comment (asaj) [reply packages/utils/src/address.ts:47]: They're used elsewhere, allows us to only depend on`@celo/utils` in those places rather than also `ethereumjs-utils`

File: packages/utils/src/address.ts (hunk 38 above)
Comment (asaj) [reply packages/utils/src/address.ts:24]: `signatureUtils` has this functionality, suggest he use that.

File: packages/utils/src/signatureUtils.ts (hunk 39 above)
Comment (asaj) [reply packages/utils/src/signatureUtils.ts]: Must have been a merge conflict? This was supposed to move to address.ts
