### PR TITLE
[Wallet] Upgrade react-navigation libraries

### LINKED ISSUE #5524: NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null ob...
Sentry Issue: [CELO-MOBILE-20D](https://sentry.io/organizations/celo/issues/1841320671/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4942)
    at android.view.ViewGroup.removeViewAt(ViewGroup.java:4904)
    at androidx.fragment.app.l.i
    at androidx.fragment.app.l.a
    at androidx.fragment.app.l.b
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by etuleu**
### Description

This seems to fix the top crash we are currently experiencing.
Thanks @cmcewen for smelling the right fix here. We should also start a PR for upgrading all the other react packages, but I wanted to do this one as a smaller PR to make sure it fixes it and doesn't introduce anything new.

TODO: fix the any types that are added by asking @jeanregisser 

### Other changes

Added a new e2e test for opening the app using a dappkit url, which is the common source of crashes.

### Tested

Manually by opening the app with a deep link. Committed the script used also.

### Related issues

- Fixes #5524 

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/navigator/Navigator.tsx [hunk 1]
```diff
@@ -112,6 +112,7 @@ export const modalScreenOptions = ({ route, navigation }: NavigationOptions) =>
       gestureEnabled: true,
       cardOverlayEnabled: true,
       headerStatusBarHeight:
+        // @ts-ignore
```
Comment (etuleu) [inline packages/mobile/src/navigator/Navigator.tsx]: FIXME

File: packages/mobile/src/navigator/DrawerNavigator.tsx [hunk 2]
```diff
@@ -71,7 +71,7 @@ const TAG = 'NavigationService'
 const Drawer = createDrawerNavigator()
 
 type CustomDrawerItemListProps = Omit<DrawerContentOptions, 'contentContainerStyle' | 'style'> & {
-  state: DrawerNavigationState
+  state: DrawerNavigationState<any>
```
Comment (etuleu) [inline packages/mobile/src/navigator/DrawerNavigator.tsx]: FIXME

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (etuleu) [reply packages/mobile/src/navigator/Navigator.tsx]: leaving this with the ts-ignore for now because I think the library fixed it, but we need to test.

File: yarn.lock [hunk 3]
```diff
@@ -28165,11 +28182,16 @@ react-native-gesture-handler@^1.6.1:
...
+react-native-iphone-x-helper@^1.0.3:
   version "1.2.1"
   resolved "https://registry.yarnpkg.com/react-native-iphone-x-helper/-/react-native-iphone-x-helper-1.2.1.tgz#645e2ffbbb49e80844bb4cbbe34a126fda1e6772"
   integrity sha512-/VbpIEp8tSNNHIvstuA3Swx610whci1Zpc9mqNkqn14DkMbw+ORviln2u0XyHG1kPvvwTNGZY6QpeFwxYaSdbQ==
 
+react-native-iphone-x-helper@^1.3.0:
+  version "1.3.1"
+  resolved "https://registry.yarnpkg.com/react-native-iphone-x-helper/-/react-native-iphone-x-helper-1.3.1.tgz#20c603e9a0e765fd6f97396638bdeb0e5a60b010"
+  integrity sha512-HOf0jzRnq2/aFUcdCJ9w9JGzN3gdEg0zFE4FyYlp4jtidqU03D5X7ZegGKfT1EWteR0gPBGp9ye5T5FvSWi9Yg==
+
```
Comment (jeanregisser) [inline yarn.lock]: For some reason yarn duplicates these, but if you manually remove both and re-run `yarn` it will combine them again since they are compatible versions.

File: yarn.lock [hunk 4]
```diff
@@ -27776,6 +27784,15 @@ query-string@^6.1.0, query-string@^6.13.1:
...
 
+query-string@^6.13.6:
+  version "6.13.7"
+  resolved "https://registry.yarnpkg.com/query-string/-/query-string-6.13.7.tgz#af53802ff6ed56f3345f92d40a056f93681026ee"
+  integrity sha512-CsGs8ZYb39zu0WLkeOhe0NMePqgYdAuCqxOYKDR5LVCytDZYMGx3Bb+xypvQvPHVPijRXB0HZNFllCzHRe4gEA==
+  dependencies:
+    decode-uri-component "^0.2.0"
+    split-on-first "^1.0.0"
+    strict-uri-encode "^2.0.0"
+
```
Comment (jeanregisser) [inline yarn.lock]: Same yarn issue about duplicating `query-string` though versions are compatible.

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (jeanregisser) [reply packages/mobile/src/navigator/Navigator.tsx]: What's the error?

**Review by jeanregisser — COMMENTED** [review]
Looking great!! 👍

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (etuleu) [reply packages/mobile/src/navigator/Navigator.tsx]: `var route: Route<string, unknown>
Argument of type 'Route<string, unknown>' is not assignable to parameter of type 'NavigationRoute<StackParamList, Screens.AccountKeyEducation | Screens.BackupComplete | Screens.BackupIntroduction | Screens.BackupPhrase | Screens.BackupQuiz | Screens.DappKitAccountAuth | Screens.DappKitSignTxScreen | Screens.DappKitTxDataScreen | ... 57 more ... | Screens.WithdrawCeloScreen>'.
  Type 'Route<string, unknown>' is not assignable to type 'Readonly<{ key: string; name: Screens.AccountKeyEducation | Screens.BackupComplete | Screens.BackupIntroduction | Screens.BackupPhrase | Screens.BackupQuiz | Screens.DappKitAccountAuth | Screens.DappKitSignTxScreen | Screens.DappKitTxDataScreen | ... 57 more ... | Screens.WithdrawCeloScreen; }>'.
    Types of property 'name' are incompatible.
      Type 'string' is not assignable to type 'Screens.AccountKeyEducation | Screens.BackupComplete | Screens.BackupIntroduction | Screens.BackupPhrase | Screens.BackupQuiz | Screens.DappKitAccountAuth | Screens.DappKitSignTxScreen | Screens.DappKitTxDataScreen | Screens.Debug | ... 56 more ... | Screens.WithdrawCeloScreen'.ts(2345)
`

Comment (jeanregisser) [reply packages/mobile/src/navigator/Navigator.tsx]: Thanks, I can have a look tomorrow morning.

Comment (jeanregisser) [reply packages/mobile/src/navigator/Navigator.tsx]: Fixed 🙂

**Review by jeanregisser — APPROVED** [review]

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (etuleu) [reply packages/mobile/src/navigator/Navigator.tsx]: awesome! thank you!
