### PR TITLE
[Wallet] Witdraw CELO QR scan fixes

### LINKED ISSUE #4732: Review button is not getting enabled when a user scans the QR code of another user while withdrawing CELO.
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (11)
**Repro on device:** Google Pixel XL(8.1) , Vivo 1606 (6.0.1)  
**Test Account:** (680) 333-1978/ [Backup key.](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0) 
**Repro Steps:**
1. Launch the Application and sign in with test account
2. Tap on the Hamburger menu. 
3. Tap on CELO option
4. Tap on Withdraw CELO 
5. Tap on the QR code icon. 
6. Scan the valid QR code. 
7. Make sure other user’s Account no is shown in Account No field. 
8. Enter an amount in the Amount (CELO) field. 
9. Observe Review button. 

**Current Behavior:** Review button is not getting enabled
**Expected Behavior:** Review button should enable 
**Investigation:** Issue does not repro when the user sends CELO by pasting Account no. of other users. 
**Impact:** Users are blocked to proceed for sending CELO using QR code. 
**Attachment:** [Android_ReviewButton_CELO.mp4](https://drive.google.com/file/d/10lriPZNWf3hzLvLgHVTl5pYU5tC4ur43/view?usp=sharing) (Bug observe at 21 sec)

### PR DESCRIPTION
**Pull request by gnardini**
### Description

The withdraw CELO PR (https://github.com/celo-org/celo-monorepo/pull/4646) used the old QR format that was modified by another PR (https://github.com/celo-org/celo-monorepo/pull/4536/files). With the new format, scanning a QR is not returning the correct address. This PR fixes that and adds an error message if an invalid QR is scanned

### Tested

On an Android physical phone.

### Related issues

- Fixes #4732 and #4731

### CODE REVIEW

File: packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx [hunk 1]
```diff
@@ -22,7 +27,7 @@ type Props = StackScreenProps<StackParamList, Screens.WithdrawCeloQrScannerScree
 
 function fetchAddressFromQrData(data: string): string | null {
   try {
-    return JSON.parse(data).address
+    return uriDataFromUrl(data).address
```
Comment (annakaz) [inline packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx:30]: 👍

File: packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx [hunk 2]
```diff
@@ -31,13 +36,20 @@ function fetchAddressFromQrData(data: string): string | null {
...
       const qrData = qrCode.data
       Logger.debug(TAG, 'Bar code detected: ' + qrData)
       const address = fetchAddressFromQrData(qrData) || qrData
-      onAddressScanned(address)
-      navigateBack()
+      if (address.startsWith('0x') && address.length === 42) {
+        onAddressScanned(address)
+        navigateBack()
+      } else {
+        dispatch(showMessage(t(ErrorMessages.QR_FAILED_INVALID_ADDRESS)))
```
Comment (annakaz) [inline packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx]: Any reason to use showMessage over showError, so the red banner appears instead of blue?

File: packages/mobile/src/qrcode/utils.ts [hunk 3]
```diff
@@ -103,7 +104,7 @@ export function* handleBarcode(
   try {
     qrData = uriDataFromUrl(barcode.data)
   } catch (e) {
-    yield put(showMessage(ErrorMessages.QR_FAILED_INVALID_ADDRESS))
+    yield put(showMessage(i18n.t(`global:${ErrorMessages.QR_FAILED_INVALID_ADDRESS}`)))
```
Comment (annakaz) [inline packages/mobile/src/qrcode/utils.ts]: Not a new change but could use showError instead of showMessage?

File: packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx [hunk 4]
```diff
@@ -31,13 +36,20 @@ function fetchAddressFromQrData(data: string): string | null {
...
+  const dispatch = useDispatch()
+
   const onBarCodeDetected = memoize(
     (qrCode: QrCode) => {
       const qrData = qrCode.data
       Logger.debug(TAG, 'Bar code detected: ' + qrData)
       const address = fetchAddressFromQrData(qrData) || qrData
-      onAddressScanned(address)
-      navigateBack()
+      if (address.startsWith('0x') && address.length === 42) {
```
Comment (annakaz) [inline packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx]: Nit: defining 42 as address length constant to make it clear where it comes from

**Review by annakaz — APPROVED** [review]
Thanks for fixing this. Minor comment on using showError

I can cherry pick this commit to be included in the new build

Unrelated to changes in this PR but thinking out loud- right now CELO exchange providers Bittrex only allows for the address to be pasted (no QR), will want to make sure they use the same encoding scheme when they add QR support. cc @yorhodes

File: packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx (hunk 2 above)
Comment (gnardini) [reply packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx]: No reason, I just copied it from the saga, I'll change it in both :)
