### PR TITLE
[Wallet] Fix unable to redeem invite from referrer

### LINKED ISSUE #1283: Android] "Failure redeeming code" error is shown when the user tap on "Paste invite code!" from the "Enter Invite Code" screen when invited users install the app from received invite code.
**App version:** Play store build v1.5.0
**Does not repro:** v1.4.2
**Repro on:**  Samsung Galaxy S4 (5.0.1), Samsung j7 prime (6.0.1), Samsung Galaxy A8+ (8.0.0) 
**Priority:** Medium
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)

**Pre-condition:** User must have invitation code which is sent by other celo user. 
 
**Repro Steps:** 
1) Launch the app.
2) Install the  by tapping on received invitation code. 
3) Enter the Full name, Select country and enter phone number. 
4) Tap on Continue button. 
5) Set the PIN. 
6) Make sure is on “Enter Invite code” and “Paste invite code!” button is shown. 
7) Tap on  “Paste invite code!” button. 
8) Observe 

**Current Behavior:**  "Failure redeeming code" error is shown 
**Expected Behavior:** Users should be able to paste the invitation code. 
**Attachment:** [Android_PastInviteCodeButtonIssue.MOV](https://drive.google.com/file/d/1uumBGJD8RXJS0a5o7ZGwVX1XrfxF6FDb/view?usp=sharing) (Bug observe after 3:05 sec)

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Fix unable to redeem invite from referrer data as the extracted code in base64 format was directly fed to the redeem invite function which expected a valid hex private key.

The referrer data processing now accepts codes in both hex and base64 formats to follow the robustness principle ("Be conservative in what you send, be liberal in what you accept").

### Tested

Added new tests.

### Other changes

- Existing tests were relying on incorrect waiting logic
- The `utils.test.ts` suite got executed when running only `EnterInviteCode.test.tsx` because of the constants it was importing from it

### Related issues

- Fixes #1283

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/invite/utils.ts [hunk 1]
```diff
@@ -64,7 +64,12 @@ export const getInviteCodeFromReferrerData = async () => {
     )
     const inviteCode = params.get('invite-code')
     if (inviteCode) {
-      return inviteCode.replace(' ', '+')
+      const sanitizedCode = inviteCode.replace(' ', '+')
+      // Accept invite codes which are either base64 encoded or direct hex keys
+      if (isValidPrivateKey(sanitizedCode)) {
+        return sanitizedCode
+      }
+      return extractValidInviteCode(sanitizedCode)
```
Comment (jeanregisser) [inline packages/mobile/src/invite/utils.ts:72]: This is the actual fix.

**Review by jmrossy — APPROVED** [review]
Ship it!!
