### PR TITLE
Fix getting languages on Press page for client side

### LINKED ISSUE #5015: [web] TypeError: Cannot read property 'toLowerCase' of null
It looks like this is related to latest changes on press page. based on when this started showing up. 

Sentry Issue: [CELO-WEB-S9](https://sentry.io/organizations/celo/issues/1873789876/?referrer=github_integration)

```
TypeError: Cannot read property 'toLowerCase' of null
  at a.value (/_next/static/chunks/pages/press-629e27ca90b35e464e29.js:1:1346)
  at Ji (/_next/static/chunks/framework.c7f9f565e2e122ea20f6.js:1:94421)
  at Gi (/_next/static/chunks/framework.c7f9f565e2e122ea20f6.js:1:94214)
  at Ro (/_next/static/chunks/framework.c7f9f565e2e122ea20f6.js:1:129660)
  at zu (/_next/static/chunks/framework.c7f9f565e2e122ea20f6.js:1:113942)
...
(40 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by isabellewei**
### Description

When on client side, `languages` was a null object, it now fetches the correct data.

### Tested

navigated to press page from other page

### Related issues

- Fixes #5015 

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

File: packages/web/src/press/PressPage.tsx [hunk 1]
```diff
@@ -26,17 +26,20 @@ interface Props {
...
         press = await getpress.default()
         languages = context.req.headers['accept-language']
+          .toLowerCase()
+          .split(',')
+          .map((s) => s.substr(0, 2))
       } else {
         const res = await fetch(`/api/press`)
         press = await res.json()
-        languages = res.headers.get('accept-language')
+        languages = navigator.languages.map((s) => s.substr(0, 2))
```
Comment (aaronmgdr) [inline packages/web/src/press/PressPage.tsx]: because `navigator.languages` doesnt have 100% support can you make so even if its undefined this wont break? in that case our languages array would just be empty.

Comment (isabellewei) [reply packages/web/src/press/PressPage.tsx]: ok! I set it to an empty list if it's undefined, and then on line 56, it'll just use the i18n language instead

**Review by aaronmgdr — APPROVED** [review]
🧩
