### PR TITLE
[Wallet] Fix navigation init

### LINKED ISSUE #6434: Deep link send test fails in e2e
### Expected Behavior

Handle deep link for send screen should show up.

### Current Behavior

The app ends up on the home screen instead of the handle send screen.

https://app.circleci.com/pipelines/github/celo-org/celo-monorepo/31040/workflows/5660346b-00d5-48bf-954d-63e16ee27f30/jobs/382344/artifacts

### PR DESCRIPTION
**Pull request by etuleu**
### Description

Trying to fix the e2e test that fails on the deep link. Looking at the logs I see a navigation failure like this:

> [Wed Jan 13 2021 08:29:06.736]  INFO     NavigationService@navigate :: Navigation failure: Error: The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting. See https://reactnavigation.org/docs/navigating-without-navigation-prop#handling-initialization for more details. ::

The solution is described pretty well here: https://reactnavigation.org/docs/navigating-without-navigation-prop/

Basically we need to wait for the ready state in addition to the mounted state.

We should send some of the error messages that happen when we really don't expect them to to the backend to analyze. Maybe we can sample 1% or something like that.

### Tested

end to end DeepLinkSend.spec.js

### Related issues

- Fixes #6434 

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/navigator/NavigationService.ts [hunk 1]
```diff
@@ -19,14 +19,15 @@ const TAG = 'NavigationService'
 type SafeNavigate = typeof navigate
 
 export const navigationRef = createRef<NavigationContainerRef>()
+export const isReadyRef: MutableRefObject<boolean | null> = createRef()
 
 async function ensureNavigator() {
   let retries = 0
-  while (!navigationRef.current && retries < 3) {
+  while (!navigationRef.current && !isReadyRef.current && retries < 5) {
```
Comment (tarikbellamine) [inline packages/mobile/src/navigator/NavigationService.ts]: Can you please make the retries a constant that's defined at the top of the file?

File: packages/mobile/src/navigator/NavigationService.ts [hunk 2]
```diff
@@ -19,14 +19,15 @@ const TAG = 'NavigationService'
 type SafeNavigate = typeof navigate
 
 export const navigationRef = createRef<NavigationContainerRef>()
+export const isReadyRef: MutableRefObject<boolean | null> = createRef()
```
Comment (tarikbellamine) [inline packages/mobile/src/navigator/NavigationService.ts]: Can we name this something a little more descriptive? Maybe `navigatorIsReadyRef`?

File: packages/mobile/src/navigator/NavigatorWrapper.tsx [hunk 3]
```diff
@@ -132,6 +132,12 @@ export const NavigatorWrapper = () => {
     }
   }, [appState])
 
+  React.useEffect(() => {
```
Comment (tarikbellamine) [inline packages/mobile/src/navigator/NavigatorWrapper.tsx:135]: I think we can merge this into the `useEffect` on line 88 because that is also triggering on `componentDidMount`

File: packages/mobile/src/navigator/NavigatorWrapper.tsx [hunk 4]
```diff
@@ -175,6 +181,9 @@ export const NavigatorWrapper = () => {
   return (
     <NavigationContainer
       ref={navigationRef}
+      onReady={() => {
```
Comment (tarikbellamine) [inline packages/mobile/src/navigator/NavigatorWrapper.tsx]: I think this is what is causing your linting error. You can either ignore it or define the function outside of the component properties

**Review by tarikbellamine — COMMENTED** [review]
Looks good! Left some small comments

File: packages/mobile/src/navigator/NavigationService.ts (hunk 2 above)
Comment (gnardini) [inline packages/mobile/src/navigator/NavigationService.ts]: Can we also initialize in `false` so we don't have the `| null` on the type? It would also avoid the `useEffect` on the `NavigationWrapper`

Comment (jeanregisser) [reply packages/mobile/src/navigator/NavigationService.ts]: +1

**Review by jeanregisser — COMMENTED** [review]
Thanks! Looking good! 👍

File: packages/mobile/src/navigator/NavigationService.ts (hunk 2 above)
Comment (etuleu) [reply packages/mobile/src/navigator/NavigationService.ts]: I am not very familiar with the nuances of these functions but createRef doesn't seem to take an initial value. Should I be using something like useState?

Also setting the isReady ref to false is sometimes good when the component gets unmounted for example. It probably doesn't happen often that it gets unmounted but then mounted back but maybe on android with the back button it does so just to be safe let's keep it?

Comment (etuleu) [reply packages/mobile/src/navigator/NavigationService.ts]: Thanks to Gonza I now understand better how these effects work.

createRef does not take an initial value unfortunately so we just decided to init to false right under.

We also agreed to keep the effect separate since it looks cleaner and also we need it because it returns a function to be used on unmount.

File: packages/mobile/src/navigator/NavigatorWrapper.tsx (hunk 3 above)
Comment (etuleu) [reply packages/mobile/src/navigator/NavigatorWrapper.tsx:135]: Spoke with Gonza a bit about this because I wasn't sure how the effects work but we agreed to keep the effect separate since it looks cleaner, and also we are returning a function to be used on unmount.

**Review by gnardini — APPROVED** [review]
LGTM, thanks for looking into this 😄
