### PR TITLE
Prevent crash of `yarn run dev:android` when there are iOS files missing

### LINKED ISSUE #2282: [Wallet] Run app without some missing unnecessary files fails
### Expected Behavior

When a dev run `yarn run dev:android` without some iOS files, it should work

### Current Behavior

When a dev run `yarn run dev:android` without some iOS files fails because of missing files

### PR DESCRIPTION
**Pull request by Pedro-vk**
### Description

_Prevent crash of `yarn run dev:android` when there are iOS files missing_

### Tested

_On Linux command line_

### Related issues

- Fixes #2282

### CODE REVIEW

File: packages/mobile/scripts/run_app.sh [hunk 1]
```diff
@@ -63,8 +63,12 @@ sed -i.bak "s/DEV_RESTORE_NAV_STATE_ON_RELOAD=.*/DEV_RESTORE_NAV_STATE_ON_RELOAD
 # Set Firebase settings in google service config files
 ANDROID_GSERVICES_PATH="./android/app/src/debug/google-services.json"
 IOS_GSERVICES_PATH="./ios/GoogleService-Info.plist"
-sed -i.bak "s/celo-org-mobile-.*firebaseio.com/celo-org-mobile-$NETWORK.firebaseio.com/g" $ANDROID_GSERVICES_PATH
-sed -i.bak "s/celo-org-mobile-.*firebaseio.com/celo-org-mobile-$NETWORK.firebaseio.com/g" $IOS_GSERVICES_PATH
+if [ $PLATFORM = "android" ]; then
```
Comment (jmrossy) [inline packages/mobile/scripts/run_app.sh]: I would prefer to have them both still be set in case the user is actually running both at the same time, as we sometimes do.
Can you instead check if the files exist and then run sed?

**Review by jmrossy — COMMENTED** [review]
Thanks for looking into this!

File: packages/mobile/scripts/run_app.sh (hunk 1 above)
Comment (Pedro-vk) [reply packages/mobile/scripts/run_app.sh]: Done :+1:

**Review by jmrossy — APPROVED** [review]
