### PR TITLE
[Wallet] Fix slow activity feed tx confirmations

### LINKED ISSUE #1741: [Wallet] Users on 3g network SBAT get tx receipts more reliably
### Expected Behavior

We always get tx receipts and handle properly

### Current Behavior

Sometimes the app will be waiting for a tx to go through even though it was successful. Example - user gets three texts, app submits the txs, but the last one hangs for multiple minutes. User restarts the app and the verification flow is completed right away without any other txs

User sends money, tx appears hanging in feed for a long time and a duplicated transaction shows up

WhatsApp Image 2019-11-15 at 2 20 18 PM

### PR DESCRIPTION
**Pull request by annakaz**
### Description

Currently, the activity feed can be slow to update transactions in the activity from "confirming..." to "confirmed", especially when on a 3g connection. Balances update but the "confirming..." is still there, along with a duplicate "confirmed" transaction. 

Now, the activity feed removes the "confirming..." transactions promptly and never renders "confirming..." and "confirmed" at the same time. 

### Tested

Updated jest tests
Tested on pixel 2, throttling to 3g speeds using Charles, also using normal wifi. Confirmed that transaction confirmations for send, exchange and invite come in at the same time that the balance is updated

### Other changes

Created Transaction type to align Standby and confirmed (from graphQL) transactions
Updated some logging

### Related issues

- Fixes #1741 

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/escrow/saga.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ function* registerStandbyTransaction(id: string, value: string, address: string)
       id,
       type: TransactionTypes.ESCROW_SENT,
       status: TransactionStatus.Pending,
-      value,
+      value: +value,
```
Comment (annakaz) [inline packages/mobile/src/escrow/saga.ts:90]: Note that storing StandbyTransaction as `number` instead of `string` does not impact precision, as the confirmed transaction value is stored as a `number` anyway. Did not want to modify graphQL to change both to strings so as not to overlap with @jeanregisser 's local currency work

File: packages/mobile/src/transactions/reducer.ts [hunk 2]
```diff
@@ -61,6 +46,24 @@ type TransferTransactionTypes =
   | TransactionTypes.INVITE_RECEIVED
   | TransactionTypes.NETWORK_FEE
 
+export const isTransferType = (txType: TransactionTypes) => {
```
Comment (annakaz) [inline packages/mobile/src/transactions/reducer.ts:49]: Couldn't find a cleaner way to check multiple types but lmk if you think of one

File: packages/mobile/src/apollo/__mockData__.ts [hunk 3]
```diff
@@ -1,93 +1,81 @@
...
 import { SENTINEL_INVITE_COMMENT } from 'src/invite/actions'
-import { TransactionTypes } from 'src/transactions/reducer'
+import { TransactionTypes, TransferTransactionTypes } from 'src/transactions/reducer'
 
 export const invitedAddress = '0x1b173'
 
 const exchangeDollar: HomeExchangeFragment = {
-  __typename: EventTypeNames.Exchange,
-  type: 'EXCHANGE' as TransactionTypes,
+  type: 'EXCHANGE' as TransactionTypes.EXCHANGE,
```
Comment (cmcewen) [inline packages/mobile/src/apollo/__mockData__.ts]: Why not just use the enum's actual value? (not sure who did this originally)

File: packages/mobile/src/apollo/types.ts [hunk 4]
```diff
@@ -1,41 +1,51 @@
 import { Query } from 'react-apollo'
-import { TransactionTypes } from 'src/transactions/reducer'
+import { CURRENCY_ENUM } from 'src/geth/consts'
```
Comment (cmcewen) [inline packages/mobile/src/apollo/types.ts:2]: I just tried it and it doesn't work right now, but i think this file originally came from running `yarn run build:gen-graphql-types` with the blockchain api running locally

File: packages/mobile/src/transactions/ExchangeFeedItem.test.tsx [hunk 5]
```diff
@@ -28,8 +27,7 @@ describe('ExchangeFeedItem', () => {
       <Provider store={createMockStore({})}>
         <ExchangeFeedItem
           status={TransactionStatus.Complete}
-          __typename={EventTypeNames.Exchange}
-          type={'EXCHANGE' as TransactionTypes}
+          type={'EXCHANGE' as TransactionTypes.EXCHANGE}
```
Comment (cmcewen) [inline packages/mobile/src/transactions/ExchangeFeedItem.test.tsx:30]: same enum comment

File: packages/mobile/src/transactions/reducer.ts (hunk 2 above)
Comment (cmcewen) [reply packages/mobile/src/transactions/reducer.ts:49]: sometimes i will make an array here and then just check if the string is contained in the array

**Review by cmcewen — COMMENTED** [review]
woot woot woot

File: packages/mobile/src/apollo/__mockData__.ts (hunk 3 above)
Comment (annakaz) [reply packages/mobile/src/apollo/__mockData__.ts]: I think this is a more realistic mock of what would be returned?

File: packages/mobile/src/transactions/ExchangeFeedItem.test.tsx (hunk 5 above)
Comment (annakaz) [reply packages/mobile/src/transactions/ExchangeFeedItem.test.tsx:30]: Same as above

File: packages/mobile/src/apollo/types.ts (hunk 4 above)
Comment (annakaz) [reply packages/mobile/src/apollo/types.ts:2]: Kk are you saying we should avoid modifying this generated file?

File: packages/mobile/src/transactions/reducer.ts (hunk 2 above)
Comment (annakaz) [reply packages/mobile/src/transactions/reducer.ts:49]: Kk I find the function cleaner than the array so will keep as is

File: packages/mobile/src/apollo/types.ts (hunk 4 above)
Comment (jmrossy) [reply packages/mobile/src/apollo/types.ts:2]: This file *was* originally made that way but most of that auto gen code has been changed over time. I've made modifications here too.

Comment (jmrossy) [reply packages/mobile/src/apollo/types.ts:2]: I believe we diverged away from the auto gen types because of the differing shapes of our standby tx and graphql txs

File: packages/mobile/src/apollo/__mockData__.ts (hunk 3 above)
Comment (jmrossy) [reply packages/mobile/src/apollo/__mockData__.ts]: I think Connors point is that `TransactionTypes.Exchange` === 'EXCHANGE' so why hardcode the value here?
And I think the reason it was originally hard coded in the first place is that the auto-gen typing tool did it this way

File: packages/mobile/src/apollo/__mockData__.ts [hunk 6]
```diff
@@ -1,93 +1,81 @@
...
   value: 0.3,
-  symbol: 'Celo Gold',
+  symbol: 'Celo Gold' as CURRENCY_ENUM,
   timestamp: Date.now(),
   address: '0x423043cca38e75d7913504fedfd1dd4539cc55b3',
   comment: 'FAKE FAKE FAKE',
   hash: '01010',
 }
 const verificationReward: HomeTransferFragment = {
-  __typename: EventTypeNames.Transfer,
```
Comment (jmrossy) [inline packages/mobile/src/apollo/__mockData__.ts:87]: Why don't we need these graphQL provided __typename properties anymore? Is it cause @jeanregisser split the home feed and exchange feed queries in bc-api?

File: packages/utils/src/phoneNumbers.ts [hunk 7]
```diff
@@ -153,7 +153,9 @@ export function parsePhoneNumber(
         }
       : null
   } catch (error) {
-    console.debug(`phoneNumbers/parsePhoneNumber/Failed to parse phone number, error: ${error}`)
+    console.debug(
+      `phoneNumbers/parsePhoneNumber/Failed to parse phone number ${phoneNumberRaw}, error: ${error}`
```
Comment (jmrossy) [inline packages/utils/src/phoneNumbers.ts]: We intentionally excluded the phone number for privacy reasons, as the logs get uploaded to firebase

**Review by jmrossy — COMMENTED** [review]
Thanks for tackling this! Can you clarify how this solves the problem exactly?

File: packages/mobile/src/transactions/reducer.ts (hunk 2 above)
Comment (jmrossy) [reply packages/mobile/src/transactions/reducer.ts]: Wondering if we can remove the duplication with TransferTransactionTypes here:
https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/transactions/reducer.ts#L52

File: packages/mobile/src/apollo/__mockData__.ts (hunk 6 above)
Comment (annakaz) [reply packages/mobile/src/apollo/__mockData__.ts:87]: Yeah we don't need them since we know the EventType from the transaction type

**Review by cmcewen — APPROVED** [review]

**Comment by annakaz** [comment]
> Thanks for tackling this! Can you clarify how this solves the problem exactly?

This solves the problem as the issue was that the "Confirming..." notification was not being removed once the confirmation came in. It was actually not a network issue of the transaction taking a long time to be confirmed- it was a UI issue of the PendingTransaction not going away (though it occurred more often when internet was slow, perhaps bc it took longer to query the notification feed?). After cleaning up `src/transactions/TransactionFeed.tsx` to treat PendingTransactions and Transactions as the same type, we know not to display the PendingTransaction if we see the matching Transaction item
