### PR TITLE
[Wallet] Disable keyboard suggestion when entering the account key

### LINKED ISSUE #602: Users SNBAT use autoCorrect when restoring their wallet
### Expected Behavior

autoCorrect should not be usable / show up when inputting a user's backup key.

### Current Behavior

autoCorrect works in certain the backup key is saved entirely in autocomplete options after manually typing it in once (using SwiftKey keyboard).  autoCorrect still shows [despite having the prop disabled](https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/import/ImportWallet.tsx#L168).

Using `keyboardType="visible-password"` does hide the auto complete options, but it does not work with multiline. (Backup key will be input in a single line)

restore_autocorrect

### LINKED ISSUE #6812: Obsolete wording about current app language needing to match the language of the seed words when restoring
### Expected Behavior

Highlighted paragraph is no longer valid and should be removed.

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This disables keyboard suggestion when entering the account key. We saw in #602 that the keyboard started learning the words after entering it a few times.

### Details

Went in a little rabbit hole to disable keyboard suggestions on Android when entering the account key.
I naively thought well `autoCorrect={false}`  and done...

...and I was wrong.

Though setting this attribute, correctly sets `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` on the underlying native text input, the keyboard now ignores this on some devices (emulator included).
Workaround is to set `keyboardType={Platform.OS === 'android' ? 'visible-password' : undefined}` which sets `InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD` on the native input.

This seems to work on the first look, but breaks multiline autoresize. Only workaround sofar is to set the number of lines :confused:

And lastly according to [this comment](https://stackoverflow.com/a/33227237/158525) it breaks Korean input to only ascii (which is ok I guess for us given we don't support Korean in the app for now).

### Other changes

- Removed obsolete wording about language requirements of the Account Key.

### Tested

**before/after iOS**

**before/after Android**

### Related issues

- Fixes #602
- Fixes #6812

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/import/ImportWallet.tsx [hunk 1]
```diff
@@ -33,6 +33,11 @@ import UseBackToWelcomeScreen from 'src/onboarding/UseBackToWelcomeScreen'
 import { RootState } from 'src/redux/reducers'
 import { isAppConnected } from 'src/redux/selectors'
 
+const AVERAGE_WORD_WIDTH = 80
+const AVERAGE_SEED_WIDTH = AVERAGE_WORD_WIDTH * 24
+// Estimated number of lines needed to enter the account key
+const NUMBER_OF_LINES = Math.ceil(AVERAGE_SEED_WIDTH / Dimensions.get('window').width)
```
Comment (gnardini) [inline packages/mobile/src/import/ImportWallet.tsx:39]: We don't really use the whole width of the screen, so could this make the account key not fit entirely? I guess it's not a huge issue in any case, but just wondering :)

File: packages/mobile/src/components/CodeInput.tsx [hunk 2]
```diff
@@ -93,6 +96,27 @@ export default function CodeInput({
                 }
                 onChangeText={onInputChange}
                 multiline={multiline}
+                // This disables keyboard suggestions on iOS, but unfortunately NOT on Android
+                // Though `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` is correctly set on the native input,
+                // most Android keyboards ignore it :/
```
Comment (gnardini) [inline packages/mobile/src/components/CodeInput.tsx:101]: It's unfortunate that we need this because of the Android fragmentation, but great job finding a solution 😄

**Review by gnardini — APPROVED** [review]
🚀

File: packages/mobile/src/import/ImportWallet.tsx (hunk 1 above)
Comment (jeanregisser) [reply packages/mobile/src/import/ImportWallet.tsx:39]: True. This estimate is quite conservative though with 80 pt for each word.

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser , @isabellewei we have verified this on latest android internal build 1.10.0(1004294335) & Testflight build 1.10.0(45) and observe the following.
- Suggestions text is not shown when user entering the account on Restore account key page.

**Devices:** iPhone 6+ (12.4.5), Vivo V11 pro (10)
