### PR TITLE
Fixing flaky governance test

### LINKED ISSUE #1142: E2E Governance tests should work reliably
https://circleci.com/gh/celo-org/celo-monorepo/35806
https://circleci.com/gh/celo-org/celo-monorepo/36017

### PR DESCRIPTION
**Pull request by mrsmkl**
### Description

Reading the correct block number from events instead of builtin variable.

### Tested

Let's see if this works better...

### Related issues

- Fixes #1142

### CODE REVIEW

**Comment by asaj** [comment]
@mrsmkl can you please move the test back to its original location in the file to make the diff easier to read?

File: packages/celotool/src/e2e-tests/governance_tests.ts [hunk 1]
```diff
@@ -323,6 +340,55 @@ describe('governance tests', () => {
     return tx.send({ from: account, ...txOptions, gas })
   }
 
+  describe('when adding any block', () => {
```
Comment (ashishb) [inline packages/celotool/src/e2e-tests/governance_tests.ts]: Nit: Can you move this test below `Validators.numberValidatorsInCurrentSet()` to minimize the diff size?

**Review by ashishb — APPROVED** [review]

**Comment by mrsmkl** [comment]
Looks like there is more flakiness. I'll investigate further.
