### PR TITLE
[Wallet] Redeem Invite wrap in setTimeout

### LINKED ISSUE #240: Redeem invite should be wrapped in a timeout
### Expected Behavior

Wrapped in timeout like verification saga

### Current Behavior

Can run forever in certain failed cases

### PR DESCRIPTION
**Pull request by rohit-dua**
### Description

Wrap redeem invite in setTimeout _(5 minutes)_. 
_(similar to verify number)_

### Tested

Passed local test cases.

### Related issues

- Fixes #240

### CODE REVIEW

File: packages/mobile/src/invite/saga.ts [hunk 1]
```diff
@@ -48,6 +48,8 @@ import { currentAccountSelector } from 'src/web3/selectors'
 
 const TAG = 'invite/saga'
 export const TEMP_PW = 'ce10'
+export const REDEEM_INVITE_TIMEOUT = 5 * 60 * 1000 // 5 minutes
```
Comment (jmrossy) [inline packages/mobile/src/invite/saga.ts]: Let's use 1 minute here.

File: packages/mobile/src/invite/saga.ts [hunk 2]
```diff
@@ -48,6 +48,8 @@ import { currentAccountSelector } from 'src/web3/selectors'
...
+export const ERROR_DURATION = 5000 // 5 seconds
```
Comment (jmrossy) [inline packages/mobile/src/invite/saga.ts]: No need to redefine this here. Just import the existing ALERT_BANNER_DURATION

File: packages/mobile/src/invite/saga.ts [hunk 3]
```diff
@@ -198,6 +200,25 @@ function* redeemSuccess(name: string, account: string) {
...
 export function* redeemInviteSaga(action: RedeemInviteAction) {
+  Logger.debug(TAG, 'Starting Redeem Invite')
+
+  const { result, timeout } = yield race({
+    result: call(doRedeemInvite, action),
+    timeout: delay(REDEEM_INVITE_TIMEOUT),
+  })
+
+  if (result === true) {
+    Logger.debug(TAG, 'Verification completed successfully')
```
Comment (jmrossy) [inline packages/mobile/src/invite/saga.ts]: Please add some analytics events here similar to verification :)

**Review by jmrossy — COMMENTED** [review]
Nice! This is the right approach, just some small comments

File: packages/mobile/src/invite/saga.ts (hunk 2 above)
Comment (jmrossy) [reply packages/mobile/src/invite/saga.ts]: Looks like verification redefines it too, would be good to fix that :)

**Review by jmrossy — APPROVED** [review]
Looks good!
