### PR TITLE
[Wallet] Update Account Key backup prompt

### LINKED ISSUE #4085: Users account is not getting frozen even though user get “Get backup key” Blue color header when user has not set up their account key.
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Does not repro:** app store build v1.8.0
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)

**Pre-Condition:** Get back up key blue banner is shown after some times when user has not set up their back up key. 

**Repro Steps:** 
1) Launch app and sign up with new account
2) Wait for few hrs and remained logged in account. 
3) Make sure user will see “Get Back up” blue banner on Home screen. 
4) Tap on Get backup key button from blue banner. 
5) Tap on Hamburger menu and observed. 

 **Current Behavior:** Account is not getting frozen when Get backup key blue banner is shown. 
**Expected Behavior:** Account should froze when get back up key blue banner is shown. 
**Impact:** User is able to use the application even though user has not set up account key 
**Attachment:**  [GetbackupKeyIssue.mp4](https://drive.google.com/file/d/1jgNqnjigWYg7WYvOHwPIwCN6R6MjBWoZ/view?usp=sharing) (Bug observed at  sec)

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Changed the backup prompt for a full screen thing [following the design on Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=2995%3A33668)

Screen Shot 2020-11-23 at 18 53 25

### Tested

Manually on iOS and Android

### Related issues

- Fixes #4085

### CODE REVIEW

File: packages/mobile/src/app/actions.ts [hunk 1]
```diff
@@ -84,6 +75,11 @@ interface InviteModalAction {
   inviteModalVisible: boolean
 }
 
+interface ActiveScreenChangedAction {
+  type: Actions.ACTIVE_SCREEN_CHANGED
+  activeScreen: string
```
Comment (etuleu) [inline packages/mobile/src/app/actions.ts]: can we use the Screens enum here?

**Review by etuleu — APPROVED** [review]
looks great!

File: packages/mobile/locales/en-US/backupKeyFlow6.json [hunk 2]
```diff
@@ -3,6 +3,8 @@
   "introTitle": "Your Account Key",
   "introBody": "Your Account Key is the most important part of your account.\n\nPlease find a private place to set up your key. It takes about five minutes.",
   "introPrimaryAction": "Set Up Now",
+  "backupSetupTitle": "Set Up Your Account Key",
+  "backupSetupBody": "To protect your funds, you're required to set up your Account Key before you can continue using Valora.",
```
Comment (jeanregisser) [inline packages/mobile/locales/en-US/backupKeyFlow6.json]:
```suggestion
  "backupSetupBody": "To protect your funds, you're required to set up your Account Key before you can continue using {{appName}}.",
```

File: packages/mobile/locales/es-419/backupKeyFlow6.json [hunk 3]
```diff
@@ -3,6 +3,8 @@
   "introTitle": "La Clave de Cuenta",
   "introBody": "La clave de tu cuenta es la parte más importante de tu cuenta. Configurarla toma cinco minutos",
   "introPrimaryAction": "Configurar Ahora",
+  "backupSetupTitle": "Configura Tu Clave De Cuenta",
+  "backupSetupBody": "Para proteger tus fondos, debes configurar tu Clave de Cuenta antes de poder continuar usando Valora.",
```
Comment (jeanregisser) [inline packages/mobile/locales/es-419/backupKeyFlow6.json]:
```suggestion
  "backupSetupBody": "Para proteger tus fondos, debes configurar tu Clave de Cuenta antes de poder continuar usando {{appName}}.",
```

File: packages/mobile/src/backup/BackupForceScreen.tsx [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+    ValoraAnalytics.track(OnboardingEvents.backup_start)
+    navigate(Screens.AccountKeyEducation)
+  }
+
+  // Prevent back button on Android
+  useEffect(() => {
+    const backPressListener = () => true
+    BackHandler.addEventListener('hardwareBackPress', backPressListener)
+    return () => BackHandler.removeEventListener('hardwareBackPress', backPressListener)
+  }, [])
```
Comment (jeanregisser) [inline packages/mobile/src/backup/BackupForceScreen.tsx:35]: We also need to prevent swipe back on iOS.

https://reactnavigation.org/docs/preventing-going-back/

File: packages/mobile/src/backup/BackupForceScreen.tsx [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+  // Prevent swiping back on iOS
+  gestureEnabled: false,
+  headerLeft: () => null,
+  headerRight: () => <DelayButton />,
+}
+
+const styles = StyleSheet.create({
+  container: {
+    flex: 1,
+    flexDirection: 'column',
```
Comment (jeanregisser) [inline packages/mobile/src/backup/BackupForceScreen.tsx]: nit: this is the default already.
```suggestion
```

File: packages/mobile/src/backup/BackupForceScreen.tsx [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+    backgroundColor: colors.light,
+  },
+  content: {
+    flex: 1,
+    flexDirection: 'column',
```
Comment (jeanregisser) [inline packages/mobile/src/backup/BackupForceScreen.tsx]: nit: this is the default already.
```suggestion
```

**Review by jeanregisser — CHANGES_REQUESTED** [review]
Great! Mostly small things 👍

File: packages/mobile/src/backup/BackupForceScreen.tsx (hunk 4 above)
Comment (gnardini) [reply packages/mobile/src/backup/BackupForceScreen.tsx:35]: We are, the navigation options have a `gestureEnabled: false,` that prevents it.

I tried using the `beforeRemove` above but it didn't really prevent the swiping, it just reverted it. Like I swiped and after I lifted my finger from the screen it swiped back to the original position. The result was the same but it looked a bit strange imo. The `gestureEnabled: false` just prevents swiping in the first place.

File: packages/mobile/src/backup/BackupForceScreen.tsx (hunk 5 above)
Comment (gnardini) [reply packages/mobile/src/backup/BackupForceScreen.tsx]: Yeah, I know. I just always put the direction when it's important because it helps imo to have that sort of things explicit, but I can see how one might think it's unnecessary. Removed.

File: packages/mobile/src/backup/BackupForceScreen.tsx (hunk 4 above)
Comment (jeanregisser) [reply packages/mobile/src/backup/BackupForceScreen.tsx:35]: Right, missed that, what you did has much better UX 💯

File: packages/mobile/src/backup/BackupForceScreen.tsx (hunk 5 above)
Comment (jeanregisser) [reply packages/mobile/src/backup/BackupForceScreen.tsx]: Yes no worry, fine to keep it too 👍

**Review by jeanregisser — APPROVED** [review]
Great! 🚢
