### PR TITLE
[Wallet] Fix a several of onboarding flow bugs and UX issues

### LINKED ISSUE #210: Verification should in some cases not be required after importing a wallet
### Expected Behavior

If a user imports a wallet and the phone number they provided is the same as the one already mapped to that address, skip verification

### Current Behavior

Users must always redo verification

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

- Skip verification if user is already verified to inputted number
- Improve UX of import wallet screen and make it consistent with new designs
- Reduce duplication of navigation header related code
- Add error handling support to import contacts screen
- Properly remove event listener on EnterInvite screen
- Skip escrow withdrawals when user imports a wallet
- A bit of renaming functions for clarity

### Tested

Tested full onboarding flow with redeeming invite code
Tested full onboarding flow with importing wallet
Testing importing contacts
Testing skipping importing contacts

### Related issues

- Fixes #210 

### Backwards compatibility

Yes

import-wal
import-contacts
ver-education

### CODE REVIEW

File: packages/mobile/src/identity/contactMapping.ts [hunk 1]
```diff
@@ -226,7 +226,7 @@ export enum VerificationStatus {
   UNKNOWN = 2,
 }
 
-export function getPhoneNumberAddress(
+export function getAddressFromPhoneNumber(
```
Comment (cmcewen) [inline packages/mobile/src/identity/contactMapping.ts:229]: lots of good function name improvements 🥇

File: packages/mobile/locales/en-US/nuxNamePin1.json [hunk 2]
```diff
@@ -92,7 +92,7 @@
     "1":
       "Importing your contacts allows you to easily send and request payments from your community and see who is already using Celo.",
     "enable": "Enable Contact Access",
-    "loading": "Importing your contacts..."
+    "loading": "Finding friends on Celo..."
```
Comment (cmcewen) [inline packages/mobile/locales/en-US/nuxNamePin1.json:95]: Not sure if you did this already, but usually would just give a heads up to Nitya/Corey

File: packages/mobile/src/navigator/Headers.tsx [hunk 3]
```diff
@@ -0,0 +1,23 @@
+import * as React from 'react'
+import { View } from 'react-native'
+import BackButton from 'src/components/BackButton'
+import DisconnectBanner from 'src/shared/DisconnectBanner'
+
+export const nuxNavigationOptions = {
```
Comment (cmcewen) [inline packages/mobile/src/navigator/Headers.tsx:6]: nice 👍

File: packages/utils/src/signatureUtils.ts [hunk 4]
```diff
@@ -77,13 +77,19 @@ export function isValidAddress(address: string) {
   )
 }
 
-export function compareAddresses(address1: string, address2: string) {
-  address1 = stripHexLeader(address1.toLowerCase())
-  address2 = stripHexLeader(address2.toLowerCase())
+export function areAddressesEqual(address1: string | null, address2: string | null) {
```
Comment (cmcewen) [inline packages/utils/src/signatureUtils.ts:80]: I'm not sure if this will actually happen, but you could have `null === null` here - so maybe return false in that case?

**Review by cmcewen — APPROVED** [review]
