### PR TITLE
[Wallet] QR Request Bug + Android Activity Monitor Bug

### LINKED ISSUE #4059: “Send” screen is open even though scanning the QR code from Request screen
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (35)
**Repro on device:** iphone 6+ (12.4.5)
**Repro Steps:** 
1) Launch app and sign up in the app
2) Tap on Request button. 
3) Tap on QR code icon. 
4) Tap on Scan code button. 
5) Scan the other user’s QR code. 
6) Observe 
 
**Current Behavior:**Send Screen is open instead Request screen 
**Expected Behavior:** Request screen should be shown 
**Attachment:**[RequestscreenIssue..mp4 ](https://drive.google.com/file/d/1KWKqMK8SXKsNXyxAien_Y7cvfY2cg7gC/view?usp=sharing)

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Fixed bug where clicking the QR icon from the request flow would send you into the send flow after a successful scan.

Also fixed two bugs regarding incoming payment requests:
- Android can't render non-text elements within a text element
- The lifecycle method on `IncomingPaymentRequestItem` would get inadvertently triggered when address fetches were done elsewhere in the app

### Other changes
No

### Tested
Yes

### Related issues
- Closes #4059 

### Backwards compatibility
Yes

### CODE REVIEW

File: packages/react-components/components/CallToActionsBar.tsx [hunk 1]
```diff
@@ -15,16 +15,25 @@ interface Props {
...
-        <TextButton
-          testID={`${testID}/${cta.text}/Button`}
-          key={i}
-          style={styles.action}
-          onPress={cta.onPress}
-        >
-          {cta.text}
-        </TextButton>
-      ))}
+      {callToActions.map((cta, i) => {
```
Comment (tarikbellamine) [inline packages/react-components/components/CallToActionsBar.tsx:18]: New logic because Android can't display non-text inside of text elements

File: packages/react-components/components/CallToActionsBar.tsx [hunk 2]
```diff
@@ -37,5 +46,7 @@ const styles = StyleSheet.create({
     fontSize: 14,
     lineHeight: 16,
     marginRight: 24,
+    minWidth: 48,
```
Comment (tarikbellamine) [inline packages/react-components/components/CallToActionsBar.tsx:49]: Needed to fix width/height so shift from text to spinner didnt cause components to move around

File: packages/mobile/src/send/Send.tsx [hunk 3]
```diff
@@ -100,8 +100,17 @@ export const sendScreenNavOptions = ({
 }: {
   route: RouteProp<StackParamList, Screens.Send>
 }) => {
-  const goQr = () => navigate(Screens.QRNavigator)
-  const title = route.params?.isRequest
+  const isOutgoingPaymentRequest = route.params?.isOutgoingPaymentRequest
+
+  const goToQRScanner = () =>
```
Comment (tarikbellamine) [inline packages/mobile/src/send/Send.tsx:105]: Navigating directly to the scanner with a param that lets us know if it's for a payment request

File: packages/mobile/src/send/SendAmount.tsx [hunk 4]
```diff
@@ -225,7 +224,11 @@ function SendAmount(props: Props) {
 
     dispatch(hideAlert())
 
-    if (addressValidationType !== AddressValidationType.NONE) {
+    if (
```
Comment (tarikbellamine) [inline packages/mobile/src/send/SendAmount.tsx:227]: Extra logic to ensure that secure send is not triggered for QR code or direct address transactions

File: packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx [hunk 5]
```diff
@@ -92,6 +92,11 @@ export default function IncomingPaymentRequestListItem({ id, amount, comment, re
   }
 
   React.useEffect(() => {
+    // Need this to make sure it's only triggered on click
+    if (!isLoading) {
```
Comment (tarikbellamine) [inline packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx:96]: `isLoading` is true whenever the "send" button is clicked. This was sometimes triggering when lookups were being done as part of other flows so adding a condition that the button must have been clicked

File: packages/react-components/components/CallToActionsBar.tsx [hunk 6]
```diff
@@ -15,16 +15,25 @@ interface Props {
...
+              key={i}
+              style={styles.action}
+              onPress={cta.onPress}
+            >
+              {cta.text}
+            </TextButton>
+          )
+        }
+        return (
+          <View key={i} style={styles.action}>
```
Comment (aaronmgdr) [inline packages/react-components/components/CallToActionsBar.tsx:32]: this doesnt need to have onPress?

Comment (tarikbellamine) [reply packages/react-components/components/CallToActionsBar.tsx:32]: Nope it's a JSX element (activity spinner)

File: packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx (hunk 5 above)
Comment (aaronmgdr) [reply packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx:96]: wouldnt you want to add this to the deps array?

**Review by cmcewen — APPROVED** [review]

File: packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx (hunk 5 above)
Comment (aaronmgdr) [reply packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx:96]: it also looks like is oading is only true when there is an e164 number.

Comment (tarikbellamine) [reply packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx:96]: I didn't add to the dependency array because I don't actually want that effect to run when `isLoading` changes, only when there are is an update to `secureSendDetail` or `error`. `isLoading` will be `true` whenever those variables change in the vast majority of cases so that check is just to cover edge cases

Comment (tarikbellamine) [reply packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx:96]: And when there isn't an `e164PhoneNumber` then the lifecycle function is irrelevant because we will immediately navigate to the next screen
