### PR TITLE
changed isValidAddress

### LINKED ISSUE #3576: Problem with account:claim-attestation-service-url
### Expected Behavior

The command succeeds.

### Current Behavior

When `address` in metadata is not prefixed by 0x, it cannot be read by the metadata reader
```
celocli account:create-metadata ./metadata.json --from 2bdc5ccda08a7f821ae0df72b5fda60cd58d6353
celocli account:claim-attestation-service-url ./metadata.json --url $CELO_ATTESTATION_SERVICE_URL --from $CELO_ATTESTATION_SIGNER_ADDRESS
Read Metadata from ./metadata.json... done
Error: is not a valid address
```

See also https://github.com/celo-org/celo-monorepo/pull/3575

### PR DESCRIPTION
**Pull request by mrsmkl**
## Description

Metadata reader and CLI use different validation of addresses, changed both to use the same.

## Related issues

- Fixes #3576

### CODE REVIEW

**Review by jmrossy — APPROVED** [review]
Lgtm

File: packages/contractkit/src/identity/claims/attestation-service-url.ts [hunk 1]
```diff
@@ -57,10 +57,9 @@ export async function validateAttestationServiceUrl(
 
     const attestationKeyAddress = await accounts.getAttestationSigner(address)
 
-    // Uncomment this once we opt in by specifying an attestation key
```
Comment (mrsmkl) [inline packages/contractkit/src/identity/claims/attestation-service-url.ts:60]: @nambrot can you check if this should be uncommented now?

Comment (nambrot) [reply packages/contractkit/src/identity/claims/attestation-service-url.ts:60]: Yup should be good now
