### PR TITLE
[wallet] UX fixes for native phone number

### LINKED ISSUE #1699: [Wallet] Users SBAT enter own phone number on Welcome screen without error being thrown
### Expected Behavior

On the Welcome page, a user can select "None of the above" when prompted with phone numbers to verify, then enter their own phone number. 

### Current Behavior

A "Could not request phone number" error is thrown if a user selects "None of the above" as their phone number. 

Screenshot_20191113-134745
Screenshot_20191113-134438

### LINKED ISSUE #1701: [Wallet] US phone number users SBAT have number recognized as US, not Canada
### Expected Behavior

Users with US phone numbers who select their phone number when prompted on the Welcome screen should have "United States" selected as the corresponding country. 

Not sure how hard it will be to differentiate between US and Canada phone numbers (which both start with +1) but a quick fix would be to default to US instead of to Canada, as we currently have more users in the US than in Canada. 

### Current Behavior

Users with US phone numbers who select their phone number when prompted on the Welcome screen have "Canada" selected as the corresponding country, as Canada and US share the country code +1.

Screenshot_20191113-143011

### LINKED ISSUE #1703: [Wallet] Users SBAT choose country corresponding to phone number if it is incorrect
### Expected Behavior

When the "Country" field has already been filled in, when a user taps the Country field, they can choose the country of their choice.

### Current Behavior

When the user clicks Country, the Native Phone Number modal pops up. This does not make sense when a user has already selected a phone number, as they are tapping the Country field to change the country. The user must select their phone number again from the modal, then update the country.

Screenshot_20191113-143011 (1)
After user taps Canada:
Screenshot_20191113-143533

### PR DESCRIPTION
**Pull request by martinvol**
### Description

* Changed logging from `error` to `info` to prevent red screen when user dismiss the modal
* Don't trigger the modal if there's text in the input
* Differentiate between US and Canada phone numbers to show the right country.

### Tested

- Manually and added tests.

### Other changes

-

### Related issues

- Fixes #1699
- Fixes #1703 
- Fixes #1701

### Backwards compatibility

-

### CODE REVIEW

**Review by jmrossy — DISMISSED** [review]
Can you set a more clear description for this before you merge it?

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 1]
```diff
@@ -90,7 +90,7 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
         this.onChangeCountryQuery(displayName)
       }
     } catch (error) {
-      console.error(`${TAG}/triggerPhoneNumberRequestAndroid`, 'Could not request phone', error)
+      console.info(`${TAG}/triggerPhoneNumberRequestAndroid`, 'Could not request phone', error)
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx:85]: This info message seems to be thrown even if able to request the phone number, but the user chooses to input a different number- can you differentiate between these cases, or use a message that would encapsulate both?

**Comment by jmrossy** [comment]
Removing automerge, see @annakaz 's comment

**Comment by martinvol** [comment]
Thanks to @jeanregisser I figured out a way to differentiate USA vs Canada and should be working fine now.

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 2]
```diff
@@ -69,40 +69,56 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
     }
   }
 
+  async getPhoneNumberFromNativePicker() {
+    // linter doesn't allow following code without splitting this code in two lines
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx]: Why? What's the error?

Comment (annakaz) [reply packages/react-components/components/PhoneNumberInput.tsx]: Does `return SmsRetriever.requestPhoneNumber()` work? There will be an implicit await in the return because it's an async function. That should fix it if it was the `no-return-await` rule

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 3]
```diff
@@ -69,40 +69,56 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
     try {
-      const phone = await SmsRetriever.requestPhoneNumber()
-      const phoneNumber = parsePhoneNumber(phone, '')
+      let phone
+      try {
+        phone = await this.getPhoneNumberFromNativePicker()
+      } catch (error) {
+        console.info(
+          `${TAG}/triggerPhoneNumberRequestAndroid`,
+          'Could not request phone. This might be thrown if the user dismissed the modal',
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx:79]: Can you differentiate the case when the user dismissed the modal based on the error message thrown by the NativePicker?

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 4]
```diff
@@ -69,40 +69,56 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
+    return number
+  }
+
   async triggerPhoneNumberRequestAndroid() {
     try {
-      const phone = await SmsRetriever.requestPhoneNumber()
-      const phoneNumber = parsePhoneNumber(phone, '')
+      let phone
+      try {
+        phone = await this.getPhoneNumberFromNativePicker()
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx]: Any reason to use a function here rather than just directly using `SmsRetriever.requestPhoneNumber()`?

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 5]
```diff
@@ -69,40 +69,56 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
         this.onChangeCountryQuery(displayName)
       }
     } catch (error) {
-      console.error(`${TAG}/triggerPhoneNumberRequestAndroid`, 'Could not request phone', error)
+      console.info(`${TAG}/triggerPhoneNumberRequestAndroid`, 'Could not request phone', error)
     }
   }
 
   async triggerPhoneNumberRequest() {
+    if (this.state.phoneNumber || this.state.countryQuery) {
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx]: Could this logic be in `onCountryFocus` so that `triggerPhoneNumberRequest` is only called if necessary?

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 6]
```diff
@@ -69,40 +69,56 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
-        // TODO known issue, the country code is not enough to
-        // get a country, e.g. +1 could be USA or Canada
-        const displayName = this.state.countries.getCountryByPhoneCountryCode(
-          '+' + phoneNumber.countryCode.toString()
-        ).displayName
+      const regionCode = phoneNumber.regionCode
 
+      if (regionCode) {
+        const displayName = this.state.countries.getCountryByCode(regionCode).displayName
         this.onChangeCountryQuery(displayName)
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx]: Nit: perhaps rename `onChangeCountryQuery`? It was confusing to see this used when the countryQuery is not being changed in terms of user input

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 7]
```diff
@@ -69,40 +69,56 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
-
       this.setState({ phoneNumber: phoneNumber.displayNumber.toString() })
 
-      if (phoneNumber.countryCode) {
-        // TODO known issue, the country code is not enough to
-        // get a country, e.g. +1 could be USA or Canada
-        const displayName = this.state.countries.getCountryByPhoneCountryCode(
-          '+' + phoneNumber.countryCode.toString()
-        ).displayName
+      const regionCode = phoneNumber.regionCode
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx:105]: Can you add a brief comment explaining region code/country code?

File: packages/react-components/components/PhoneNumberInput.tsx (hunk 4 above)
Comment (martinvol) [reply packages/react-components/components/PhoneNumberInput.tsx]: To make mocking different results easier

File: packages/react-components/components/PhoneNumberInput.tsx (hunk 3 above)
Comment (martinvol) [reply packages/react-components/components/PhoneNumberInput.tsx:79]: Unfortunately when the modal is dismissed `SmsRetriever.requestPhoneNumber()` throws a generic `There was an error trying to get the phone number` error :/

File: packages/react-components/components/PhoneNumberInput.tsx (hunk 2 above)
Comment (martinvol) [reply packages/react-components/components/PhoneNumberInput.tsx]: oh, cool, didn't know the `await` was implicit!

**Comment by martinvol** [comment]
Should be good to go! @annakaz

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 8]
```diff
@@ -126,10 +122,13 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
     }
-    await this.triggerPhoneNumberRequest()
+
+    if (!(this.state.phoneNumber || this.state.countryQuery)) {
+      return this.triggerPhoneNumberRequest()
+    }
   }
 
-  onChangeCountryQuery = (countryQuery: string) => {
+  ChangeCountryQuery = (countryQuery: string) => {
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx]: nit: changeCountryQuery no caps?

Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx]: nit: changeCountryQuery no caps?

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 9]
```diff
@@ -53,33 +53,31 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
     if (this.props.defaultPhoneNumber) {
       this.onChangePhoneNumber(this.props.defaultPhoneNumber)
     }
   }
 
-  async getPhoneNumberFromNativePicker() {
-    // linter doesn't allow following code without splitting this code in two lines
-    const number = await SmsRetriever.requestPhoneNumber()
-    return number
+  async _getPhoneNumberFromNativePickerAndroid() {
```
Comment (annakaz) [inline packages/react-components/components/PhoneNumberInput.tsx]: Haven't seen the _ used in other parts of our codebase, ok to just keep as `getPhoneNumberFromNativePickerAndroid`?

**Review by annakaz — APPROVED** [review]
A couple minor comments, but LGTM!
