### PR TITLE
[Wallet] Fixing navigation related bugs

### LINKED ISSUE #3878: Nothing happens when the user taps on the “Cancel” button on verification flow.
**Frequency:** 100%
** Repro App version:** Android build v1.8.0 (104994308)
**Repro on device:** Google pixel XL (8.1),  Samsung Galaxy A50 (9.0),

**Repro Steps:** 
1) Launch app and start the onboarding process
2) Make sure user is able to complete the process up to invite flow. 
3) Tap on verify Phone number button 
4) Make sure is on Verification screen 
5) Tap the Cancel button and observe. 

**Current Behavior:** Nothing happen when user taps on cancel button
**Expected Behavior:** Verification page should close when user taps on Cancel button
**Attachment:** [CancelButtonIssue.mp4](https://drive.google.com/file/d/1oXOklwTmeJt4MX4buz9y0lIlCD1-Jwcy/view?usp=sharing) (Bug observe at 08 sec)

### LINKED ISSUE #4030: Nothing happen when user taps on “Hamburger” from Your Account Key is set up’” screen
**Frequency:** 100%
** Repro App version:** Celo Integration build v1.8.2 (34)
**Repro on device:** iphone 6+ (12.4.5)
**Tested Account** 503 447 5958 / back up key
**Repro Steps:** 
1) Launch the app and login with tested account
2) Tap on Hamburger menu. 
3) Tap on Setting option. 
4) tap on back up key & recovery option. 
5) Enter security PIN. 
6) Tap on Hamburger Menu and observe. 
 
**Current Behavior:**  Nothing happen when user taps on hamburger menu. 
**Expected Behavior:** Hamburger menu should open when user taps on it. 
**Impact:** User will not able to open hamburger menu from particular screens. 
**Attachment:** [Hamburgerissue.mp4](https://drive.google.com/file/d/1FsqrjmlB3NTP4xjuLVzC5e0kNwTNcqZf/view?usp=sharing) (Bug observe at 12 sec)

### LINKED ISSUE #4033: “Back” and “Cancel” button both are shown on “Verifying” screen while verifying phone number.
**Frequency:** 100%
** Repro App version:** Play store v1.8.2
**Tested Account:** 503 447 5958 / Backup key 
**Repro Steps:** 
1) Launch app and login with tested account
2) Tap on Hamburger menu. 
3) Tap on Setting option
4) Tap on Verify Phone Number option. 
5) Tap on Start Verification button. 
6) Observe. 
 
**Current Behavior:** Back and cancel button both are shown.
**Expected Behavior:** Only one button should show either cancel or 

**Attachment:** Back&CancelIssue.png
Back cancelButtonIssue

### LINKED ISSUE #4092: “Hamburger” and “<” back arrow both are shown on Celo setting screen after editing user name
**Frequency:** 100%
** Repro App version:** Celo integration build v1.8.2 (36)
**Does not repro version** app store build v1.8.0
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5)
**Tested Account:** 503 447 5958 / Backup Key
**Repro Steps:** 
1) Launch app and login in the app
2) Tap on Hamburger menu. 
3) Tap on Setting option. 
4) Tap on Edit Name option. 
5) Tap on Edit Name field. 
6) Edit the Name 
7) Observe user redirect to Setting page with two Hamburger and < back arrow. 
 
**Current Behavior:**  “Hamburger” and “<” back arrow both are shown
**Expected Behavior:** Only hamburger menu should show
**Investigation:** Nothing happen when user taps on Hamburger menu.  
**Attachment:**  [EditNameIssue.mp4](https://drive.google.com/file/d/1muF9ndRFZAZibQWxVUiW08Zma9FJwKKk/view?usp=sharing) (Bug observed at 13 sec)

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
- Adding back button to Pincode screen
- Fixed backwards navigation when previous screen is Pincode screen (back button should never take you to the Pincode screen)
- Fixed broken menu burger navigation from the Account screen
- Eliminated some duplicate navigation bars
- Removed duplicate Hamburger icon
- Standardized use of a copy-able Address component across tx drilldown and drawer (fixed issue of drawer account number cutting off)
- Adding tx feed item padding to avoid emoji cutoffs
- Made navigation top bar transparent to avoid weird coloring while redesign underway
- Changed devtool to toggle backup state instead of just resetting it

### Tested
Yes

### Related issues
- Part of #3988
- Closes #3878
- Closes #4092
- Closes #4033 
- Closes #4030

### Backwards compatibility
Yes

### CODE REVIEW

File: packages/mobile/src/backup/BackupIntroduction.tsx [hunk 1]
```diff
@@ -31,18 +33,29 @@ interface DispatchProps {
...
     backupCompleted: state.account.backupCompleted,
   }
 }
 
-export const navOptionsForAccount: StackNavigationOptions = {
-  ...drawerHeader,
-  headerTitle: '',
-  headerRight: () => <DelayButton />,
+export const navOptionsForAccount = ({ route }: NavigationProps) => {
+  if (route.params?.fromAccountScreen) {
```
Comment (cmcewen) [inline packages/mobile/src/backup/BackupIntroduction.tsx:46]: would this be better as a more generic "showBackButton" or something?

File: packages/mobile/src/account/reducer.ts [hunk 2]
```diff
@@ -144,10 +144,10 @@ export const reducer = (
         ...state,
         socialBackupCompleted: true,
       }
-    case Actions.RESET_BACKUP_STATE:
+    case Actions.TOGGLE_BACKUP_STATE:
       return {
         ...state,
-        backupCompleted: false,
+        backupCompleted: !state.backupCompleted,
```
Comment (cmcewen) [inline packages/mobile/src/account/reducer.ts:150]: ✨

File: packages/mobile/src/components/AccountNumber.tsx [hunk 3]
```diff
@@ -2,31 +2,58 @@ import colors from '@celo/react-components/styles/colors.v2'
 import fontStyles from '@celo/react-components/styles/fonts.v2'
 import { getAddressChunks } from '@celo/utils/src/address'
 import React from 'react'
-import { StyleSheet, Text, View } from 'react-native'
+import { useTranslation } from 'react-i18next'
```
Comment (cmcewen) [inline packages/mobile/src/components/AccountNumber.tsx:5]: Nothing to do with your PR but just noting that `src/components` gives us no information 😄

File: packages/mobile/src/components/AccountNumber.tsx [hunk 4]
```diff
@@ -2,31 +2,58 @@ import colors from '@celo/react-components/styles/colors.v2'
...
+      </View>
+    )
+  }
+
   return (
-    <View style={styles.container}>
-      <Text style={styles.text}>0x </Text>
-      <Text style={styles.text}>{formattedAddress}</Text>
-    </View>
+    <TouchableOpacity style={styles.container} onPress={onPressAddress}>
```
Comment (cmcewen) [inline packages/mobile/src/components/AccountNumber.tsx]: not a huge deal, but in the interest of DRY you could do a ternary instead of the if statement:
`touchDisabled ? <View... : <Touchable...`

File: packages/mobile/src/language/Language.tsx [hunk 5]
```diff
@@ -12,20 +12,23 @@ import { CustomEventNames } from 'src/analytics/constants'
...
   const dispatch = useDispatch()
   const { t, i18n } = useTranslation(Namespaces.accountScreen10)
 
   function onSelect(language: string, code: string) {
     CeloAnalytics.track(CustomEventNames.language_select, { language, selectedAnswer: code })
-    const nextScreen = route.params?.nextScreen ?? Screens.JoinCelo
     dispatch(setLanguage(code))
-    navigation.navigate(nextScreen)
+    // If came from Account screen, should navigate back using back button
+    if (!route.params?.fromAccountScreen) {
```
Comment (cmcewen) [inline packages/mobile/src/language/Language.tsx]: I do like that nextScreen is more generic here - you could flip them so the onboarding version has a nextScreen but the account screen doesn't?

File: packages/mobile/src/navigator/DrawerNavigator.tsx [hunk 6]
```diff
@@ -79,16 +80,8 @@ function CustomDrawerContent(props: DrawerContentComponentProps<DrawerContentOpt
...
           <View style={styles.accountInnerContainer}>
-            <Text style={styles.smallLabel}>{`${account?.slice(2, 6)} ${account?.slice(
-              6,
-              10
-            )} ${account?.slice(10, 14)} ${account?.slice(14, 18)}`}</Text>
-            <Text style={styles.smallLabel}>{`${account?.slice(18, 22)} ${account?.slice(
-              22,
-              26
-            )} ${account?.slice(26, 30)} ${account?.slice(30, 34)}`}</Text>
+            <AccountNumber address={account || ''} />
```
Comment (cmcewen) [inline packages/mobile/src/navigator/DrawerNavigator.tsx:84]: 🙏

File: packages/mobile/src/navigator/NavigationService.ts [hunk 7]
```diff
@@ -115,14 +115,16 @@ async function ensurePincode(): Promise<boolean> {
...
   return true
 }
 
 export const navigateProtected: SafeNavigate = (...args) => {
   ensurePincode()
     .then((ensured) => {
       if (ensured) {
-        navigate(...args)
+        const [routeName, params] = args
+        navigationRef.current?.dispatch(StackActions.replace({ routeName, params }))
```
Comment (cmcewen) [inline packages/mobile/src/navigator/NavigationService.ts]: This looks like it should take two arguments (https://reactnavigation.org/docs/stack-actions/#replace) - how does it work?

File: packages/mobile/src/navigator/types.tsx [hunk 8]
```diff
@@ -89,9 +93,11 @@ export type StackParamList = {
     recipient: Recipient
   }
   [Screens.JoinCelo]: undefined
-  [Screens.Language]: {
-    nextScreen?: keyof StackParamList
-  }
+  [Screens.Language]:
+    | {
```
Comment (cmcewen) [inline packages/mobile/src/navigator/types.tsx:97]: prettier is weird eh?

File: packages/mobile/src/navigator/Navigator.tsx [hunk 9]
```diff
@@ -140,6 +148,7 @@ const verificationScreens = (Navigator: typeof Stack) => {
       <Navigator.Screen
         name={Screens.VerificationLoadingScreen}
         component={VerificationLoadingScreen}
+        options={headerWithCancelButton}
```
Comment (cmcewen) [inline packages/mobile/src/navigator/Navigator.tsx]: I believe we want to actually cancel verification here. There's a `handleBackButton` in `VerificationLoadingScreen` which I think you want to look at

File: packages/mobile/src/backup/BackupIntroduction.tsx (hunk 1 above)
Comment (tarikbellamine) [reply packages/mobile/src/backup/BackupIntroduction.tsx:46]: yeah good call

File: packages/mobile/src/navigator/NavigationService.ts (hunk 7 above)
Comment (tarikbellamine) [reply packages/mobile/src/navigator/NavigationService.ts]: I hesitate to say it, but maybe their documentation is wrong? Anecdotally, it works as expected in the current setup.

Here's how the `StackActions.replace` method  is defined in the package:
```
export declare function replace({ routeName, params, key, newKey, action, }: {
    routeName: string;
    params?: object;
    key?: string;
    newKey?: string;
    action?: never;
}): StackActionType;
```

File: packages/mobile/src/navigator/types.tsx (hunk 8 above)
Comment (tarikbellamine) [reply packages/mobile/src/navigator/types.tsx:97]: indeed

File: packages/mobile/src/language/Language.tsx (hunk 5 above)
Comment (tarikbellamine) [reply packages/mobile/src/language/Language.tsx]: I couldn't figure out exactly why, but navigating to the the `Account` screen through the previous design was causing the `onPress` method of the `DrawerTopBar` to break. Given there are only two reachable destinations from this screen, I opted to go for a less extensible quick fix.

If you feel like it's worth figuring out right now, I can dive a little deeper.

File: packages/mobile/src/components/AccountNumber.tsx (hunk 3 above)
Comment (tarikbellamine) [reply packages/mobile/src/components/AccountNumber.tsx:5]: Sorry I don't follow

File: packages/mobile/src/components/AccountNumber.tsx (hunk 4 above)
Comment (tarikbellamine) [reply packages/mobile/src/components/AccountNumber.tsx]: Yep good call

File: packages/mobile/src/navigator/Navigator.tsx (hunk 9 above)
Comment (tarikbellamine) [reply packages/mobile/src/navigator/Navigator.tsx]: Oh I see, for some reason I thought the listener would take care of that but I see now that it's only for the hardware back button. Will revert the changes here and replace with `noHeader`

File: packages/mobile/src/navigator/NavigationService.ts (hunk 7 above)
Comment (tarikbellamine) [reply packages/mobile/src/navigator/NavigationService.ts]: I just realized we have a `replace` function defined (the same way) in the same file, so I am now using that instead

File: packages/mobile/src/components/AccountNumber.tsx (hunk 3 above)
Comment (cmcewen) [reply packages/mobile/src/components/AccountNumber.tsx:5]: haha i just want to get rid of our `src/components` folder because it is not a helpful name - basically everything is a component

File: packages/mobile/src/language/Language.tsx (hunk 5 above)
Comment (cmcewen) [reply packages/mobile/src/language/Language.tsx]: So in onSelect we call navigate to nextScreen - in this case when you come from account, we want you to navigate back because the language screen gets pushed onto the stack. When you're finished, we should push it off the stack from account, but during onboarding we want to push a new screen onto the stack. So I think the way I would model this is something like:`nextScreen: Screens | 'GO_BACK'`. That way you can either know to push a new screen onto the stack, or pop the current one off.

File: packages/mobile/src/navigator/NavigationService.ts (hunk 7 above)
Comment (cmcewen) [reply packages/mobile/src/navigator/NavigationService.ts]: ahhhh. we are importing from `@react-navigation/compat`instead of `@react-navigation/native`

Comment (tarikbellamine) [reply packages/mobile/src/navigator/NavigationService.ts]: oh interesting, didnt notice that!

File: packages/mobile/src/account/Invite.tsx [hunk 10]
```diff
@@ -152,9 +152,7 @@ class Invite extends React.Component<Props, State> {
 
   render() {
     return (
-      // Intentionally not using SafeAreaView here as RecipientPicker
-      // needs fullscreen rendering
-      <View style={style.container}>
+      <SafeAreaView style={style.container}>
```
Comment (i1skn) [inline packages/mobile/src/account/Invite.tsx:155]: Looking at the comment, which was here previously I assume: "RecipientPicker DOES NOT need fullscreen rendering anymore". Is this correct?

File: packages/mobile/src/language/Language.test.tsx [hunk 11]
```diff
@@ -22,7 +22,9 @@ describe('Language', () => {
     })
 
     fireEvent.press(getByText('Español (América Latina)'))
-    expect(mockNavigation.navigate).toHaveBeenCalledWith(Screens.JoinCelo)
+    // Run timers, because Touchable adds some delay
```
Comment (i1skn) [inline packages/mobile/src/language/Language.test.tsx]: I guess, we can remove this now, cause https://github.com/celo-org/celo-monorepo/pull/4102 is merged 🙂

File: packages/mobile/src/navigator/types.tsx (hunk 8 above)
Comment (i1skn) [reply packages/mobile/src/navigator/types.tsx:97]: It is actually pretty cool! I think they took this syntax from Elm 👍

**Review by i1skn — COMMENTED** [review]
Overall, great work! Thanks for the effort on addressing so many bugs 💪 ! See just a couple comments I've left.

File: packages/mobile/src/account/Invite.tsx (hunk 10 above)
Comment (tarikbellamine) [reply packages/mobile/src/account/Invite.tsx:155]: Yes!

File: packages/mobile/src/language/Language.test.tsx (hunk 11 above)
Comment (tarikbellamine) [reply packages/mobile/src/language/Language.test.tsx]: Yep good catch

**Review by cmcewen — APPROVED** [review]
