### PR TITLE
[wallet] Added native phone picker

### LINKED ISSUE #654: User phone numbers and country should be input automatically
### Expected Behavior

read both the country and phone number automatically, present both as a placeholder so the user can edit if incorrect.

If there are multiple phone numbers detected, present the default modal with options to prompt the user to select the correct one.

We use the Android hint picker so people don't have to type as much
https://developers.google.com/identity/sms-retriever/request (though apparently there are some bugs https://github.com/googlesamples/android-credentials/issues/27)

### Current Behavior

Everyone has to type

### PR DESCRIPTION
**Pull request by martinvol**
### Description

`JoinCelo` screen now request phone number + country code so that the user can select from there and not type.

### Tested

- Manually
- e2e still green (as the emulator doesn't have a phone number set up)

### Other changes

* Deleted a obsolete files `packages/mobile/locales/en.json` and `packages/mobile/locales/es.json`
* Fixed wrong mocks and spapshots
* ~Upgraded `react-native-device-info` in `verifier` and `wallet` to get access to `getBaseOS()`~ Done after upgrading to RN 61

### Related issues

- Fixes #654

### Backwards compatibility

-

### CODE REVIEW

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 1]
```diff
@@ -65,6 +71,33 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
+        })
+
+        this.onChangeCountryQuery(
+          this.state.countries.getCountryByPhoneCountryCode(
+            '+' + phoneNumber.countryCallingCode.toString()
+          ).displayName
+        )
+      }
+    } catch (error) {
+      // Logger.error(TAG, 'Could not request phone', error)
```
Comment (martinvol) [inline packages/react-components/components/PhoneNumberInput.tsx]: Any way I can access the logger from here?

File: packages/mobile/locales/en.json [hunk 2]
```diff
@@ -6,7 +6,6 @@
     "2": "Verify your phone number so other Celo users can find you and send you value"
   },
   "progressBarText": "Syncing with Network",
-  "Welcome to Celo": "Welcome to Celo",
```
Comment (jmrossy) [inline packages/mobile/locales/en.json:9]: Pretty sure we can remove this file entirely

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 3]
```diff
@@ -3,12 +3,17 @@ import ValidatedTextInput, {
...
 import colors from '@celo/react-components/styles/colors'
+import SmsRetriever from '@celo/react-native-sms-retriever'
 import { Countries } from '@celo/utils/src/countries'
 import { ValidatorKind } from '@celo/utils/src/inputValidation'
 import { getRegionCodeFromCountryCode, parsePhoneNumber } from '@celo/utils/src/phoneNumbers'
+import { parsePhoneNumberFromString } from 'libphonenumber-js'
 import * as React from 'react'
 import { Platform, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
 import Autocomplete from 'react-native-autocomplete-input'
+// import Logger from 'src/utils/Logger'
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx]: Did you mean to leave this here?

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 4]
```diff
@@ -3,12 +3,17 @@ import ValidatedTextInput, {
   PhoneValidatorProps,
 } from '@celo/react-components/components/ValidatedTextInput'
 import colors from '@celo/react-components/styles/colors'
+import SmsRetriever from '@celo/react-native-sms-retriever'
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx:6]: If you're going to add a dependency to this here in react-components, you should modify its package.json

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 5]
```diff
@@ -65,6 +71,33 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
     }
   }
 
+  async triggerPhoneNumberRequest() {
+    try {
+      const phone = await SmsRetriever.requestPhoneNumber()
+      const phoneNumber = parsePhoneNumberFromString(phone, undefined)
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx]: Please use the existing utils in `@celo/utils/src/phoneNumbers` which add a bunch of error handling and handle special cases we've encountered for certain countries

File: packages/react-components/components/PhoneNumberInput.tsx (hunk 1 above)
Comment (jmrossy) [reply packages/react-components/components/PhoneNumberInput.tsx]: console.error is fine for react-components

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 6]
```diff
@@ -65,6 +71,33 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
+      if (phoneNumber) {
+        this.setState({
+          phoneNumber: phoneNumber.nationalNumber.toString(),
+        })
+
+        this.onChangeCountryQuery(
+          this.state.countries.getCountryByPhoneCountryCode(
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx]: How would this work given that a phone country code can be shared between countries (e.g Canada and US both +1)

Comment (martinvol) [reply packages/react-components/components/PhoneNumberInput.tsx]: I'm not completely sure we can identify if a number is American or Canadian just with the phone number. I just looked up the number of the Toronto Tower and it says the phone number region is CA: https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+416-868-6937

File: packages/mobile/src/i18n.ts [hunk 7]
```diff
@@ -28,11 +26,9 @@ export enum Namespaces {
 
 const availableResources = {
   'en-US': {
-    common: en_US,
```
Comment (jmrossy) [inline packages/mobile/src/i18n.ts]: 👍

File: packages/react-components/components/PhoneNumberInput.test.tsx [hunk 8]
```diff
@@ -97,4 +104,30 @@ describe('PhoneNumberInput', () => {
       )
     })
   })
+
+  describe('Native phone picker', () => {
+    it('can read phone', async () => {
+      const wrapper = shallow<PhoneNumberInput>(
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.test.tsx:57]: This is okay, but FYI we prefer to use `react-native-testing-library` instead of enzyme for these kinds of tests.
Both are okay but we've found RNTL is easier to use :)

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 9]
```diff
@@ -65,6 +69,37 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
     }
   }
 
+  async triggerPhoneNumberRequest() {
+    try {
+      const phone = await SmsRetriever.requestPhoneNumber()
+      const phoneNumber = parsePhoneNumber(phone, '')
+
+      if (phoneNumber) {
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx]: Small Nit: we can invert this if:
`if (phoneNumber){ return`

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 10]
```diff
@@ -65,6 +69,37 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
+    } catch (error) {
+      console.debug(`${TAG}/Could not request phone`)
+    }
+  }
+
+  onCountryFocus = async () => {
+    if (this.props.onInputFocus) {
+      await this.props.onInputFocus()
+    }
+    await this.triggerPhoneNumberRequest()
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx:115]: If this functionality only works on android, you should probably check the platform here and only call this if we're on android

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 11]
```diff
@@ -65,6 +69,37 @@ export default class PhoneNumberInput extends React.Component<Props, State> {
...
+    try {
+      const phone = await SmsRetriever.requestPhoneNumber()
+      const phoneNumber = parsePhoneNumber(phone, '')
+
+      if (phoneNumber) {
+        this.setState({
+          phoneNumber: phoneNumber.displayNumber.toString(),
+        })
+        if (phoneNumber.countryCode) {
+          // TODO known issue, the country code is not enough to
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx]: How should we handle this?
Should we pick the first one and use that? Should we not autofill country when there's ambiguity?
Also what does `getCountryByPhoneCountryCode` return when there's ambiguity? an array?

Comment (martinvol) [reply packages/react-components/components/PhoneNumberInput.tsx]: It's typed as `LocalizedCountry`, so we only get one, the result is arbitrary based on `getCountryByPhoneCountryCode ` implementation.  The `getCountryByPhoneCountryCode` function is conceptually wrong because it claims doing something that's not possible returning just one value. Apparently USA and Canada are the only two countries that share this problem.

Comment (martinvol) [reply packages/react-components/components/PhoneNumberInput.tsx]: I researched a little bit more and it looks like to do the differentiation is possible but 
`libphonenumber` does not support it in js: 

`PhoneNumberOfflineGeocoder - provides geographical information related to a phone number.` https://github.com/ruimarinho/google-libphonenumber/blob/master/README.md#installation

Comment (jmrossy) [reply packages/react-components/components/PhoneNumberInput.tsx]: Ok. if it's only US and Canada then it's probably okay to leave the TODO and circle back to this later. I can look at it when I'm in Canada ;)

File: packages/react-components/components/PhoneNumberInput.test.tsx [hunk 12]
```diff
@@ -1,7 +1,20 @@
...
+
+jest.mock('react-native-device-info', () => {
+  return {
+    getBaseOs: jest.fn(() => 'Android'),
+  }
+})
+
 describe('PhoneNumberInput', () => {
   describe('when defaultCountry is falsy', () => {
     it.skip('renders an AutoComplete and a country can be selected', () => {
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.test.tsx]: It looks like @cmcewen added a skip to my new test here. Can you please remove it?
I fixed the tests here to work without needing the `__mocks__/country-data.ts`file, which I removed but I guess he added back. Would be nice to remove that mock again and just test with the real data

File: packages/react-components/components/PhoneNumberInput.tsx [hunk 13]
```diff
@@ -3,12 +3,16 @@ import ValidatedTextInput, {
   PhoneValidatorProps,
 } from '@celo/react-components/components/ValidatedTextInput'
 import colors from '@celo/react-components/styles/colors'
+import SmsRetriever from '@celo/react-native-sms-retriever'
```
Comment (jmrossy) [inline packages/react-components/components/PhoneNumberInput.tsx:6]: Have you confirmed that this doesn't break the verifier? Because it doesn't have this package set up so I assume the import would fail. Please run the verifier and double check the phone input screen is okay

**Review by jmrossy — APPROVED** [review]
