### PR TITLE
Make governance CLI more usable

### LINKED ISSUE #1587: Support governance proposals/hotfixes in CLI
### Expected Behavior

Use cases:
* I'm a validator or approver. I want to whitelist a hotfix
* I'm a committer trying to get this hot fix done. I want to prepare+execute the hot fix.
* I'm a committer/organizer trying to make sure we get the validators that need to whitelist to do so. I want to see who has and hasn't yet committed to find out who to chase.

Add CLI methods to whitelist and execute governance hotfixes -- something like

```
governance:execute-hotfix [--account address] --hash H --bytecode B  # general transaction bytecode to prepare+execute
governance:execute-hotfix [--account address] --hash H --repoint name --to address  # repoint registry-managed contract X to contract deployed at address
governance:whitelist-hotfix [--account address] --hash H   # whitelist 
governance:show-whitelisted-hotfix [--account address] --hash H   [--not-yet]   # show the addresses of validators that have (or have not yet with --not-yet) whitelisted the hot fix in the current epoch
```

### LINKED ISSUE #2334: Add CLI commands for viewing status of (ongoing) governance hotfixes/proposals
### Expected Behavior

View utilities

### Current Behavior

No utilities

### LINKED ISSUE #2335: Emit proposalID upon `governance:propose`
### Expected Behavior

ProposalID is known to proposer

Should be parsed from event logs of propose transaction

### Current Behavior

Call on propose txo is broken

### PR DESCRIPTION
**Pull request by yorhodes**
### Description

Adds `governance:list`, `governance:view`, and `governance:viewhotfix` to assist in managing proposals and hotfixes

### Tested

WIP

### Other changes

Add example strings to all governance commands
Add ability to display events with `displaySendTx`

### Related issues

- Fixes #1587
- Fixes #2335
- Fixes #2334

### CODE REVIEW

File: packages/cli/src/commands/governance/list.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+    const governance = await this.kit.contracts.getGovernance()
+    const queue = await governance.getQueue()
+    const sortedQueue = governance.sortedQueue(queue)
+
+    console.log(chalk`{purple.bold Queued Proposals:}`)
+    sortedQueue.map(printValueMap)
+
+    const dequeue = await governance.getDequeue()
+    const stages = await concurrentMap(5, dequeue, (id) => governance.getProposalStage(id))
```
Comment (nambrot) [inline packages/cli/src/commands/governance/list.ts]: Optional nit: You can just pass through `governance.getProposalStage` without the lambda? (unless there is more than one parameter)

File: packages/contractkit/src/wrappers/Validators.ts [hunk 2]
```diff
@@ -473,4 +473,29 @@ export class ValidatorsWrapper extends BaseWrapper<Validators> {
...
     )
   }
+
+  /**
+   * Returns the current set of validator signer addresses
+   */
+  async currentSignerSet(): Promise<Address[]> {
+    const n = valueToInt(await this.contract.methods.numberValidatorsInCurrentSet().call())
+    const validators = []
+    for (let i = 0; i < n; i++) {
```
Comment (nambrot) [inline packages/contractkit/src/wrappers/Validators.ts]: What do you think about using concurrentMap here?

**Review by nambrot — APPROVED** [review]
