### PR TITLE
[Wallet] Don't allow going back after wallet is imported successfully

### LINKED ISSUE #4393: Disable backwards navigation after wallet is successfully restored
**Frequency:** 100%
**Repro App version:** Android Celo internal build 1.9.1 , IOS Test flight Celo interation build v1.9.1 (41) 
**Repro on device:** Samsung Galaxy A5 (7.0) , iPhone 6 (12.4.7)
**Repro Steps:**

1. Launch the App and start the sign up flow. 
2. Make sure user on Invite Code screen 
3. Tap on “Restore Existing Wallet” button 
4. Enter Account key and tap on restore button. 
5. Make sure user is redirect to Confirm Phone number screen after some time. 
6. Tap on < back arrow from Confirm Phone Number screen. 
7. Make sure user is on “Restore Existing Wallet” screen. 
8. Tap on Restore button and observe. 

**Current Behavior:** Error “ Importing Wallet Failed” message is shown
**Expected Behavior:** User should be able to restore account. 
**Impact:** User is blocked to go Confirm Phone number screen again. 
**Attachment:** [RestoreIssue.mp4 ](https://drive.google.com/file/d/1MTy-1duRyVG0X97SwHQhIH9z5doC90r9/view?usp=sharing)(Bug Observe at 29 sec)

### PR DESCRIPTION
**Pull request by gnardini**
### Description

After successfully restoring a wallet, it's not possible to go back anymore by swiping on iOS or using the back button on Android.

### Tested

Manually

### Related issues

- Fixes #4393

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/navigator/NavigationService.ts [hunk 1]
```diff
@@ -88,6 +88,28 @@ export function navigate<RouteName extends keyof StackParamList>(
     })
 }
 
+export function navigateClearingStack<RouteName extends keyof StackParamList>(
+  ...args: undefined extends StackParamList[RouteName]
+    ? [RouteName] | [RouteName, StackParamList[RouteName]]
+    : [RouteName, StackParamList[RouteName]]
+) {
```
Comment (jeanregisser) [inline packages/mobile/src/navigator/NavigationService.ts]: nit: avoids the (complex) type repetition.
```suggestion
export const navigateClearingStack : SafeNavigate = (...args) => {
```

**Review by jeanregisser — APPROVED** [review]
Great! 👍

**Comment by Lss-Ankit** [comment]
Hi @gnardini We have verified this issue on latest latest Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and observe the following
- There is no way to go back to  Restore wallet page after wallet is imported successfully.
Hence " Importing Wallet Failed” error message is not shown because we are not able to go back to restore wallet page 
 
**Verified on device:** iPhone 6+ (12.4.5), Vivo V11 pro (12.4.5) 

Can you please let us know if we need to test anything else.
