### PR TITLE
[Wallet] Fix splash screen green gap

### LINKED ISSUE #2986: [Wallet] Green screen on app open
When you launch the app:

### Expected Behavior

green splash screen with celo logo, wallet home

### Current Behavior

green splash screen with celo logo, green splash (no logo), wallet home

reported by @jeanregisser

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Fixed splash screen green gap (without Celo logo) by hiding it only after navigating away from the initial placeholder loading screen (AppLoading).

### Tested

Tested on both iOS and Android.

**before**

**after**

### Other changes

N/A

### Related issues

- Fixes #2986

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/app/App.tsx [hunk 1]
```diff
@@ -59,21 +58,13 @@ export class App extends React.Component {
...
-  }
-
   render() {
     return (
       // @ts-ignore Apollo doesn't like the typings
       <ApolloProvider client={apolloClient}>
         <Provider store={store}>
           <SafeAreaProvider>
-            <PersistGate
-              onBeforeLift={this.hideSplashScreen}
```
Comment (jmrossy) [inline packages/mobile/src/app/App.tsx:73]: Can you test this an android too. I vaguely remember needing to add this onBeforeLift for android

Comment (jeanregisser) [reply packages/mobile/src/app/App.tsx:73]: Yes works for Android too, I should have mentioned it ;)

**Review by jmrossy — APPROVED** [review]
