### PR TITLE
Return to preview view when Fee Education is closed

### LINKED ISSUE #895: Users SBAT return to reclaim review screen after fee education
### Expected Behavior

Closing the fee education screen should return to `ReclaimPaymentConfirmationScreen`.

### Current Behavior

Closing the fee education screen goes to send screen.

Steps to reproduce:

1. Hit "Reclaim Payment" on the home screen
2. Press the FeeIcon info button next to "Security Fee"
3. Close fee education screen by pressing the X or back button
4. Reach Send or Request screen

Should be a minor adjustment in the stack navigators as the `FeeEducation` screen is only in the send stack.

### PR DESCRIPTION
**Pull request by Pedro-vk**
### Description

_After go to Fee Education view and the user clicks on the close button, the app should navigate to the previous view. Before this change, it was to another view that was not related to the user interaction._

### Tested

_I used Android emulator to go to Reclaim Payment, then click on Security Fee info icon and finally close the Fee Education view ensuring that is redirecting to Security Fee_

### Related issues

- Fixes #895 

### Backwards compatibility

_This changes don't affect compatibility._

### CODE REVIEW

**Review by jeanregisser — CHANGES_REQUESTED** [review]
I think it would be simpler to move `FeeEducation` out of `SendStack` or add it to `AppStack` too.

File: packages/mobile/src/send/FeeEducation.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ class FeeEducation extends React.PureComponent<Props> {
           <Text style={[fontStyles.telephoneHeadline, styles.text]}>{t('feeEducation')}</Text>
         </View>
         <View style={styles.buttonContainer}>
-          <CircleButton onPress={navigateBack} solid={true} disabled={false} />
+          <CircleButton onPress={() => navigateBack(true)} solid={true} disabled={false} />
```
Comment (jmrossy) [inline packages/mobile/src/send/FeeEducation.tsx]: This will fail the lint checks, we don't allow lambda definitions in JSX.
In the future, you can run `yarn test:all` to see if your changes will pass CI gates.

**Review by jmrossy — COMMENTED** [review]
I agree with Jean, see his comment above

File: packages/mobile/src/send/FeeEducation.tsx (hunk 1 above)
Comment (Pedro-vk) [reply packages/mobile/src/send/FeeEducation.tsx]: Thanks for the tip about `test:all`. I fixed the lambda, but didn't push the changes, now is ok.

**Comment by Pedro-vk** [comment]
> I think it would be simpler to move `FeeEducation` out of `SendStack` or add it to `AppStack` too.

Can you provide more information about that? I suppose that is something related to the scope of the routing system, but I didn't work too much with React

**Comment by jeanregisser** [comment]
> Can you provide more information about that? I suppose that is something related to the scope of the routing system, but I didn't work too much with React

Yes it's specific to [React Navigation](https://reactnavigation.org/), when you navigate to a screen, if that screen is nested inside another stack navigator, it will open the intermediary stack too. And that was the bug here.
With your latest changes it looks good now.

**Review by jeanregisser — APPROVED** [review]
Looks good 👍

**Review by jmrossy — APPROVED** [review]
