### PR TITLE
Recover CELO from failed ReleaseGold script

### LINKED ISSUE #5453: Failed ReleaseGold deployments should be recoverable
We have a deployment that failed. 

Transactions that went through:

1. The MultiSigProxy was deployed
2. The MultiSigProxy implementation was set
3. The ReleaseGoldProxy was deployed at `A` with key `deployer`
4. The ReleaseGoldProxy implementation was set
5. The proxy was funded
6. Calling `_setAndInitializeImplementation` again failed

Thus, we want to write a script that recovers the funds by:
1. By setting the implementation to a 1/1 MultiSig with `deployer` being the signer
2. Calling the multisig via the proxy to return the funds to `deployer`

We probably want to create a test case that reproduces the situation and check that the script actually does fix that

### PR DESCRIPTION
**Pull request by AlexBHarley**
### Description

When a release gold deployment fails on `proxy._setAndInitializeImplementation` we can end up in a situation where the proxy has been funded but the implementation has not been set.

This script allows for recovering the funds in the proxy by setting the implementation to a 1/1 multi sig, and then transferring them out.

### Other changes

N/A

### Tested

Insert `throw new Error()` at line 51 of `/packages/protocol/lib/proxy-utils.ts` to simulate the error.

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/5453

### Backwards compatibility

N/A

### CODE REVIEW

File: packages/protocol/scripts/truffle/recover-funds.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+async function recoverFunds(proxyAddress: Address, from: Address) {
+  const ReleaseGoldMultiSig = artifacts.require('ReleaseGoldMultiSig')
+  const ReleaseGoldProxy = artifacts.require('ReleaseGoldProxy')
+
+  const releaseGoldProxy = await ReleaseGoldProxy.at(proxyAddress)
+  const balance = await web3.eth.getBalance(releaseGoldProxy.address)
+
+  const recoveryMultiSig = await retryTx(ReleaseGoldMultiSig.new, [{ from }])
+  await _setInitialProxyImplementation(
```
Comment (nambrot) [inline packages/protocol/scripts/truffle/recover-funds.ts]: Maybe add some log statements for the user

File: packages/protocol/scripts/truffle/recover-funds.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    },
+    [from],
+    1,
+    1
+  )
+
+  const proxiedMultisig = await ReleaseGoldMultiSig.at(proxyAddress)
+  await retryTx(proxiedMultisig.submitTransaction, [
+    from,
+    new BigNumber(balance).minus(new BigNumber(0.001)).dp(0),
```
Comment (nambrot) [inline packages/protocol/scripts/truffle/recover-funds.ts]: I'd probably extract this out as a constant

**Review by nambrot — APPROVED** [review]
🎉 Someone will be very glad that you did this :)

Would it be possible to add a quick test case for `recoverFunds`?

File: packages/protocol/test/common/proxy.ts [hunk 3]
```diff
@@ -222,4 +227,24 @@ contract('Proxy', (accounts: string[]) => {
...
+    await registry.setAddressFor(CeloContractName.Freezer, freezer.address)
+    await goldToken.initialize(registry.address)
+
+    await proxy._setImplementation(getSet.address)
+    await goldToken.transfer(proxy.address, 10)
+    const proxyBalance = await web3.eth.getBalance(proxy.address)
+    assert(proxyBalance === '10')
+
+    await recoverFunds(proxy.address, owner)
+    assert((await web3.eth.getBalance(proxy.address)) === '0')
```
Comment (nambrot) [inline packages/protocol/test/common/proxy.ts:256]: I think the most important assertion is that the owner actually got the money back :P

**Review by nambrot — APPROVED** [review]
Just a minor assertion that probably should be added
