### PR TITLE
[Wallet] Handle back button when entering PIN

### LINKED ISSUE #4396: Redirect user to Account Key Education if they press back while on the pin screen
**Frequency:** 100%
**Repro App version:** Android Celo internal build 1.9.1, IOS Test flight Celo integration build v1.9.1 (41)
**Repro on device:** Samsung Galaxy A5 (7.0, iPhone 6 (12.4.7),iPhone 11(14.0)
**Repro Steps:**

1. Launch the Application and Signup with new account 
2. Tap on Set Up Now button from Your Account key In-app notification
3. Make sure user will be navigated to Your Account key page tap on Set Up Now button
4. Navigate through all 4 walk-through screens 
5. Make Sure user will be navigated to Enter PIN screen after 4th walk-through screen
6. Now tap on “<” arrow of Enter PIN screen
7. Observe

**Investigation:** User redirected back to account key page when tapping on "<" button from enter pin screen

**Current Behavior:** Account key is not shown 
**Expected Behavior:** User should navigate to “Your Account key is a special kind of password” first walk-through screen on tapping “<” arrow
**Impact:** User will confused as Account key is shown on "Account Key " screen
**Attachment:** [EnterPINscreenbackArrowIssue.Mp4](https://drive.google.com/file/d/1cuAVPM34jgXl5sv9_JztyjUIDeEBZvce/view?usp=sharing)

### LINKED ISSUE #6127: Account key words missing after setting up account key
### Expected Behavior
After setting up account key, the user is taken to their account key screen

### Current Behavior
Account key screen has no account key

image

### LINKED ISSUE #6173: User SBAT tap words in their account key when resetting their account.
### Expected Behavior
User SBAT tap words in their account key when resetting their account.

### Current Behavior
The entire screen is blank except for the words "What's the first word of your Account Key"

This was reported by a user and the support agent was able to reproduce this bug after a few attempts to reset their account.

Possibly related to #6127 

[Sentry Report](https://sentry.io/organizations/celo/issues/2017790699/?end=2020-12-08T22%3A48%3A01&project=1250733&query=is%3Aunresolved&start=2020-12-08T22%3A09%3A42)

[Logs from support center agent](https://groups.google.com/a/clabs.co/d/msgid/support/3026D7F3-CD72-4B1B-90F0-6FB8EFB90F21%40icloud.com)

[Logs from user](https://groups.google.com/a/clabs.co/d/msgid/support/CAPQx-bFmQN16kXFsrsCK_oaSsz1KQUZ%2B%3D9uEvU6HTyX%2BLySrwg%40mail.gmail.com)

[Video](https://slack-files.com/T01EJ9REZPH-F01GUC3QCCR-68aaf19d89)

Screen Shot 2020-12-09 at 12 43 12 PM

### PR DESCRIPTION
**Pull request by gnardini**
### Description

This PR fixes a couple issues that all came from the fact that we were not handling the back button on the PIN screen. In some places we handled that as "Wrong PIN" and in others we just didn't handle it at all. This PR doesn't fix 100% of the cases, but the major ones that were reported and a few extras.

- The most important change is the one on the `packages/mobile/src/web3/saga.ts` file. It used to handle the request PIN as a binary success/failure. Now it supports a third option which is 'canceled'.
- The change on `packages/mobile/src/navigator/DrawerNavigator.tsx` is for the Account Key item in the drawer. If you pressed the back button when the PIN screen popped up it counted as a successful PIN and it redirected to the Account Key screen. If the account was already unlocked it showed the mnemonic, otherwise it asked for the PIN again. This change fixes all that and the only way to get to that screen is to input a correct PIN.
- The change in `packages/mobile/src/pincode/authentication.ts` was because the function could end up in an infinite loop since we were not setting the lock as `false` if the function failed for whatever reason (for example, pressing the back button on the PIN screen). Surprised this didn't come up sooner. Also, it's now caching the result for a few ms so that the user is not prompted for the PIN several times in a row.
- Changed a bunch of `if-else` for the use of the `showErrorOrFallback` function which does the same thing but better.
- When exchanging or withdrawing CELO, if you press the back button on the PIN screen you can now try again. You couldn't before and just got an error.

### Tested

Manually

### Related issues

- Fixes #4396 & #5863 & #5289 & #6229 & #6127

### Backwards compatibility

N/A

### CODE REVIEW

File: packages/mobile/src/exchange/saga.ts [hunk 1]
```diff
@@ -167,9 +168,10 @@ export function* exchangeGoldAndStableTokens(action: ExchangeTokensAction) {
   Logger.debug(TAG, `Exchanging ${makerAmount.toString()} of token ${makerToken}`)
   let context: TransactionContext | null = null
   try {
-    navigate(Screens.ExchangeHomeScreen) // Must navigate to final screen before getting unlocked account which prompts pin
     ValoraAnalytics.track(CeloExchangeEvents.celo_exchange_start)
     const account: string = yield call(getConnectedUnlockedAccount)
+    navigate(Screens.ExchangeHomeScreen)
```
Comment (i1skn) [inline packages/mobile/src/exchange/saga.ts:173]: Did me move this to after account being unlocked to allow enter PIN again if user has cancelled previous one?

File: packages/mobile/src/identity/verification.ts [hunk 2]
```diff
@@ -123,7 +128,13 @@ export function* fetchVerificationState(forceUnlockAccount?: boolean) {
       // we want to reset password before force unlock account
       clearPasswordCaches()
     }
-    yield call(unlockAccount, account, !!forceUnlockAccount)
+    const result: UnlockResult = yield call(unlockAccount, account, !!forceUnlockAccount)
+    if (result !== UnlockResult.SUCCESS) {
+      // This navigateBack has no effect if part of onboarding and returns to home or
+      // settings page if the user pressed on the back button when prompted for the PIN.
+      navigateBack()
```
Comment (i1skn) [inline packages/mobile/src/identity/verification.ts:137]: Why it has no effect when part of the onboarding?

**Review by i1skn — COMMENTED** [review]
Amazing work on this one! Thanks a lot for addressing it! See a couple of questions I've left in the code and also wanted to ask here: 
1. Regarding
>  If the account was already unlocked it showed the mnemonic

Last time I remember logic was to always ask user for PIN independently of account being unlocked already or not, can you check this with @nityas?
2. Have you tested the flow, when user sets in settings "Require PIN on app open", would we just exit the app if user press back?

File: packages/mobile/src/exchange/saga.ts (hunk 1 above)
Comment (gnardini) [reply packages/mobile/src/exchange/saga.ts:173]: Yes, exactly. Otherwise, if the user tapped the back button on the PIN they were still redirected to the `ExchangeHomeScreen` which was a bit weird. With this change, they remain in the review screen and can try again if they want to.

**Comment by gnardini** [comment]
@i1skn Thanks for reviewing! 

> 1. Last time I remember logic was to always ask user for PIN independently of account being unlocked already or not, can you check this with @nityas?

Yes, that was the intended behaviour and that's how it works with this PR. Previously, you got prompted for the PIN but you were still redirected to the Account Key screen if you pressed on the back button, so if the PIN had been entered recently you could see the mnemonic. It should no longer be possible to ever arrive at the Account Key screen without inputting the PIN.

> 2. Have you tested the flow, when user sets in settings "Require PIN on app open", would we just exit the app if user press back?

That's a good catch, looks like there is no back button in that screen if that option is enabled, so we should be fine:
Screen Shot 2020-12-10 at 13 47 47

File: packages/mobile/src/identity/verification.ts (hunk 2 above)
Comment (gnardini) [reply packages/mobile/src/identity/verification.ts:137]: When part of the onboarding there are two cases, and I see now that I missed an edge case:

1- This screen shows up just after setting the PIN, so the PIN is not asked again after that and there is no risk of pressing the back button. However, if a user waits a few minutes between setting the PIN and starting the verification process, the account might have been blocked so the PIN is requested again and the user would be redirected to the "Confirm PIN screen", which is unwanted. User shouldn't be able to navigate back from this screen (there is no back button but they can swipe back on iOS). I'll fix this.
2- This is the case I had previously tested, if the user kills the app when on the verification education screen, when they open it again they'll see the same screen again. This is where the `navigateBack` has no effect, since there is no screen to navigate back to.

Comment (gnardini) [reply packages/mobile/src/identity/verification.ts:137]: Pushed a fix to disallow going back from this screen, which was the original wanted behaviour

File: packages/mobile/src/pincode/authentication.ts [hunk 3]
```diff
@@ -46,6 +46,7 @@ export const PIN_LENGTH = 6
 // Pepper and pin not currently generalized to be per account
 // Using this value in the caches
 export const DEFAULT_CACHE_ACCOUNT = 'default'
+export const CANCELED_PIN_INPUT = 'CANCELED_PIN_INPUT'
```
Comment (jeanregisser) [inline packages/mobile/src/pincode/authentication.ts]: nit: Looks like `cancelled` is British English and `canceled` is US English, though we're using `cancelled` everywhere.
```suggestion
export const CANCELLED_PIN_INPUT = 'CANCELLED_PIN_INPUT'
```

File: packages/mobile/src/pincode/authentication.ts [hunk 4]
```diff
@@ -134,25 +137,42 @@ export async function getPassword(
 ) {
   while (passwordLock) {
     await sleep(100)
+    if (lastPassword) {
+      return lastPassword
+    }
+    if (lastError) {
+      throw lastError
+    }
```
Comment (jeanregisser) [inline packages/mobile/src/pincode/authentication.ts:145]: This can be wrong if the the call to `getPassword` passes a different account in the 500ms window.
Now it's probably not something we do now.

**Review by jeanregisser — COMMENTED** [review]
Great! 👍
 
I see `getPincode` unit tests are sadly [all commented out](https://github.com/celo-org/celo-monorepo/blob/4b6d9bf50d88da41935e7159798f47bd98f1269c/packages/mobile/src/pincode/authentication.test.ts#L36) (not your fault I know ;))

It seems it would be useful to cover it given the bug you found and the importance of this function.

Also would be nice to update the other unit tests (mainly the impacted sagas) to show they handle the "cancel" PIN case properly.

File: packages/mobile/src/pincode/authentication.ts (hunk 4 above)
Comment (gnardini) [reply packages/mobile/src/pincode/authentication.ts:145]: Is that something you think we might have in the future? Two different PINs for two different accounts? It looks to me like something we can handle in the future if we ever do want to implement something like that.

**Comment by gnardini** [comment]
@jeanregisser I added tests for the `getPincode` method and some of the sagas. Surprising to see most of them not having any tests :(

File: packages/mobile/src/pincode/authentication.ts (hunk 4 above)
Comment (jeanregisser) [reply packages/mobile/src/pincode/authentication.ts:145]: Related to this, I saw we started adding another Geth account for CIP8 to encrypt/decrypt/sign using the data encryption key. Not sure how we want to handle that. 
Would be nice to chat together about this (@isabellewei, @tarikbellamine, @nategraf).

**Review by jeanregisser — APPROVED** [review]
Thanks for adding more tests to this. 👍 
I still think `getPassword` coverage needs to be improved, with regard to the concurrent calls use case.
We can sync about that and follow up later.

**Review by i1skn — APPROVED** [review]
Once again - great work! LGTM!

**Comment by Lss-Ankit** [comment]
Hi @gnardini @jeanregisser  I have verified this issue using Play store build v1.6.0 & App store Build v1.6.0 and observed that 'Incorrect PIN' error message is displayed when user taps on < arrow on enter PIN screen.
**Repro on devices:** Samsung Galaxy A5(7.0) ,iPhone SE (14.2)

**Comment by gnardini** [comment]
This wasn't included on the 1.6 branch, it will be included on the 1.7 release

**Comment by Lss-Ankit** [comment]
Thanks  @gnardini for the information. We will verify this issue when we receive 1.7 build.

**Comment by Lss-Ankit** [comment]
Hi @gnardini  verified below issues using Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and updated the status in respective ticket : 

- https://github.com/celo-org/celo-monorepo/issues/6308 - Updated 
- https://github.com/celo-org/celo-monorepo/issues/6229 - Blocked updated ticket. 
- https://github.com/celo-org/celo-monorepo/issues/5289 -  Fixed
-  https://github.com/celo-org/celo-monorepo/issues/4393 - Fixed.
- https://github.com/celo-org/celo-monorepo/issues/4396 - Reopened 
- https://github.com/celo-org/celo-monorepo/issues/5863 - Reopened. 
-  https://github.com/celo-org/celo-monorepo/issues/6127 -  #4396 Duplicate 

Device: iPhone SE 2 (14.2) , Google Pixel XL (8.1)

Please let me know if I need to verify thing anything else 

Thanks!!
