### PR TITLE
[Wallet] Have payment requests pay back directly to requester's address

### LINKED ISSUE #412: Payment requests don't work for users verified more than once
Payment requests are paid back to the incorrect address for users verified more than once or users that skipped verification.

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

Have payment requests pay back directly to requester's address instead of resolving the phone number with the map. This makes requests work for unverified users or users verified more than once.

### Tested

Sent and received payment request that had a corresponding contact in recip cache
Sent and received payment request that did not have a corresponding contact in recip cache

### Other changes

Mark number as verified if user can correctly skip verification after importing contacts

### Related issues

- Fixes #412

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/paymentRequest/utils.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+  if (cachedRecipient) {
+    return {
+      ...cachedRecipient,
+      address: paymentRequest.requesterAddress,
+    }
+  } else {
+    return {
+      kind: RecipientKind.Address,
+      address: paymentRequest.requesterAddress,
+      displayName: paymentRequest.requesterAddress,
```
Comment (sallyjyl) [inline packages/mobile/src/paymentRequest/utils.ts]: How about using requester's phone number (if available, any request type other than request by address), and address if not (Request by address) for `displayName`?

**Review by sallyjyl — DISMISSED** [review]

File: packages/mobile/src/paymentRequest/utils.ts (hunk 1 above)
Comment (jmrossy) [reply packages/mobile/src/paymentRequest/utils.ts]: great idea! Done.

**Review by sallyjyl — APPROVED** [review]
Looks good!! :)
