### PR TITLE
Combiner-side fail open logging

### LINKED ISSUE #9836: Add pnp "fail-open" monitoring to combiner
Ensure we have monitoring in the combiner for fail-open logic since we don't have visibility into prometheus metrics for partner signers. The combiner monitoring should be based intelligently off of the warning messages returned by signers

https://github.com/celo-org/celo-monorepo/blob/f53dae76000d8d86f31149805e341d93a248c64d/packages/phone-number-privacy/signer/src/pnp/endpoints/sign/action.ts#L66

### PR DESCRIPTION
**Pull request by alecps**
### Description

Adds logging for fail-open logic
Renames logDiscrepencies to logSignerResponses to encompass both discrepancy and fail-open logging

### Other changes

NA

### Tested

Adds logging test files 

### Related issues

- Fixes #9836 

### Backwards compatibility

Common package not backwards compatible 

### Documentation

NA

### CODE REVIEW

File: packages/phone-number-privacy/common/src/utils/authentication.ts [hunk 1]
```diff
@@ -42,25 +42,22 @@ export async function authenticateUser(
...
-        logger.error(ErrorMessage.FAILING_CLOSED)
-        return false
+        return { success: false, failedOpen: false }
       }
     }
     if (!registeredEncryptionKey) {
       logger.warn({ account: signer }, 'Account does not have registered encryption key')
-      return false
+      return { success: false, failedOpen: false }
     } else {
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/common/src/utils/authentication.ts]: nit: consider removing the else (since we already returned in the if statement above) to flatten/unnest a bit

File: packages/phone-number-privacy/common/src/utils/authentication.ts [hunk 2]
```diff
@@ -42,25 +42,22 @@ export async function authenticateUser(
       // That is, it does not throw if the DEK is undefined or invalid
       logger.error({ err, shouldFailOpen }, ErrorMessage.FAILURE_TO_GET_DEK)
       if (shouldFailOpen) {
-        // TODO(2.0.0, release) add monitoring / alerting for these
-        logger.error(ErrorMessage.FAILING_OPEN)
-        return true
+        return { success: true, failedOpen: true }
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/common/src/utils/authentication.ts]: instead of the if/else consider: `return { success: shouldFailOpen, failedOpen: shouldFailOpen }` to unnest a bit

File: packages/phone-number-privacy/common/src/utils/authentication.ts [hunk 3]
```diff
@@ -42,25 +42,22 @@ export async function authenticateUser(
...
       } else {
-        logger.error(ErrorMessage.FAILING_CLOSED)
-        return false
+        return { success: false, failedOpen: false }
       }
     }
     if (!registeredEncryptionKey) {
       logger.warn({ account: signer }, 'Account does not have registered encryption key')
-      return false
+      return { success: false, failedOpen: false }
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/common/src/utils/authentication.ts]: optional nit: consider defining `failedOpen = false` after success with `getDataEncryptionKey`, so as to not manually define failedOpen: false everywhere below

File: packages/phone-number-privacy/common/test/utils/authentication.test.ts [hunk 4]
```diff
@@ -21,9 +21,9 @@ describe('Authentication test suite', () => {
       } as Request
       const mockContractKit = {} as ContractKit
 
-      const result = await auth.authenticateUser(sampleRequest, mockContractKit, logger)
+      const { success } = await auth.authenticateUser(sampleRequest, mockContractKit, logger)
 
-      expect(result).toBe(false)
+      expect(success).toBe(false)
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/common/test/utils/authentication.test.ts:35]: can you add assertions for the `failedOpen` results for all the authentication tests that don't currently have them, just as a sanity check?

File: packages/phone-number-privacy/combiner/src/pnp/endpoints/quota/io.ts [hunk 5]
```diff
@@ -64,7 +65,21 @@ export class PnpQuotaIO extends IO<PnpQuotaRequest> {
...
   async authenticate(request: Request<{}, {}, PnpQuotaRequest>, logger: Logger): Promise<boolean> {
-    return authenticateUser(request, this.kit, logger, this.config.shouldFailOpen)
+    const { success, failedOpen } = await authenticateUser(
+      request,
+      this.kit,
+      logger,
+      this.config.shouldFailOpen
+    )
+
+    if (failedOpen) {
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/combiner/src/pnp/endpoints/quota/io.ts]: wondering if it would be cleaner (and reduce code duplication across all of the PNP io `authenticate` functions) to have `authenticateUser` take in an optional `warnings` array and push the `FAILURE_TO_GET_DEK` warning there? I guess then we wouldn't need to deal with success vs. failing open everywhere else?

File: packages/phone-number-privacy/signer/src/pnp/endpoints/sign/io.ts [hunk 6]
```diff
@@ -66,9 +71,22 @@ export class PnpSignIO extends IO<SignMessageRequest> {
 
   async authenticate(
     request: Request<{}, {}, SignMessageRequest>,
+    warnings: string[],
     logger: Logger
   ): Promise<boolean> {
-    return authenticateUser(request, this.kit, logger, this.shouldFailOpen)
+    const { success, failedOpen } = await authenticateUser(
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/signer/src/pnp/endpoints/sign/io.ts]: same as the note referencing the combiner PNP io code

File: packages/phone-number-privacy/signer/src/pnp/endpoints/sign/action.ts [hunk 7]
```diff
@@ -60,14 +60,20 @@ export class PnpSignAction implements Action<SignMessageRequest> {
             // We fail open and service requests on full-node errors to not block the user.
             // Error messages are stored in the session and included along with the signature in the response.
             quotaStatus.totalQuota = Number.MAX_SAFE_INTEGER
-            session.logger.error(ErrorMessage.FAILING_OPEN)
+            session.logger.error(
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/signer/src/pnp/endpoints/sign/action.ts]: why not `session.logger.warn(...`? (may also make sense to add auditing our logging levels to the log auditing ticket, since I guess we've been not as precise as we maybe should have been?)

File: packages/phone-number-privacy/signer/src/pnp/endpoints/sign/action.ts [hunk 8]
```diff
@@ -60,14 +60,20 @@ export class PnpSignAction implements Action<SignMessageRequest> {
...
+              ErrorMessage.FAILING_OPEN
+            )
             Counters.requestsFailingOpen.inc()
             // TODO(2.0.0) Ensure we have monitoring in the combiner for this too,
             // since we don't have visibility into prometheus metrics for partner signers. The combiner monitoring
             // should be based intelligently off of the warning messages returned by signers
             // (https://github.com/celo-org/celo-monorepo/issues/9836)
           } else {
-            session.logger.error(ErrorMessage.FAILING_CLOSED)
+            session.logger.error(
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/signer/src/pnp/endpoints/sign/action.ts]: same re: logger.error vs. .warn

File: packages/phone-number-privacy/combiner/test/integration/pnp.test.ts [hunk 9]
```diff
@@ -538,6 +540,29 @@ describe('pnpService', () => {
...
+
+          const combinerConfigWithFailOpenDisabled: typeof combinerConfig = JSON.parse(
+            JSON.stringify(combinerConfig)
+          )
+          combinerConfigWithFailOpenDisabled.phoneNumberPrivacy.shouldFailOpen = false
+          const appWithFailOpenDisabled = startCombiner(combinerConfigWithFailOpenDisabled)
+          const res = await sendPnpSignRequest(req, authorization, appWithFailOpenDisabled)
+
+          expect(res.status).toBe(401)
+          expect(res.body).toMatchObject<SignMessageResponseFailure>({
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/combiner/test/integration/pnp.test.ts]: nit: `toStrictEqual`

File: packages/phone-number-privacy/combiner/src/pnp/services/logSignerResponses.ts [hunk 10]
```diff
@@ -106,4 +107,24 @@ export class PnpDiscrepanciesLogger {
       session.warnings.push(WarningMessage.INCONSISTENT_SIGNER_QUERY_MEASUREMENTS)
     }
   }
+
+  logFailOpenResponses(session: Session<PnpQuotaRequest> | Session<SignMessageRequest>): void {
+    session.responses.forEach((response) => {
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/combiner/src/pnp/services/logSignerResponses.ts]: do you think it's worth it to push one (or multiple) FAILING_OPEN errors to the `session.warnings` when logging these discrepancies? I am on the fence here: would be slightly more consistent with the discrepancy logging, but also not sure if we necessarily want to make it super obvious when ODIS is failing open?

**Review by eelanagaraj — COMMENTED** [review]
looks good, left some comments!

re: testing -- I think at this point for logging, it's probably sufficient to manually test via unit tests; i.e. check a few cases that it's logging things when expected & in the expected format. In the future, we could probably do something like configure a unit test logger to direct output to an object and then when desired for certain test cases, inspect certain logs stored in the object. (I think this is overkill for pre-merge though tbh)

File: packages/phone-number-privacy/combiner/src/pnp/services/logSignerResponses.ts (hunk 10 above)
Comment (alecps) [reply packages/phone-number-privacy/combiner/src/pnp/services/logSignerResponses.ts]: Yea, I don't think we should return the FAILING_OPEN warning to the client. The important thing is that we log it for ourselves

File: packages/phone-number-privacy/signer/src/pnp/endpoints/sign/io.ts (hunk 6 above)
Comment (alecps) [reply packages/phone-number-privacy/signer/src/pnp/endpoints/sign/io.ts:77]: See my comment above

File: packages/phone-number-privacy/common/src/utils/authentication.ts (hunk 2 above)
Comment (isabellewei) [inline packages/phone-number-privacy/common/src/utils/authentication.ts]: could you log the error directly here instead of passing `failedOpen` back to the `io` file? you could pass in the `warnings` and `config` variables as optional parameters to achieve the same effect
