### PR TITLE
[Wallet] Addresses UI issue when user enters send amount larger than 100,000 

### LINKED ISSUE #4960: Enter amount is overlapped on the keypad when the user enters a large amount while sending payment.
**Frequency:** 100%
**Repro App version:**  Android Valora Mainnet build v1.0.0 (16)
**Repro on device:** Google Pixel Xl (8.1) 
**Test Account:** Backup Key: (757) 699-9899. 
**Repro Steps:**
1. Launch the Application and sign in with test account
2. Tap on Send button. 
3. Enter a large amount. 
4. Observe. 

**Current Behavior:** Enter amount is overlapped on the keypad
**Expected Behavior:**  Amount should not overlap on keypad. 
**Investigation:** In ios, Amount is not overlapped on the keypad. 
**Attachment:** LargeAmountIssue.png 

LargeAmountIssue

### PR DESCRIPTION
**Pull request by michellewong793**
### Description
Current behavior: When user enters an amount greater than 100,000 on the Send Amount screen, the amount breaks out of the line container and overlaps the screen. 
This PR addresses the issue by making the font a smaller size to fit the container as the amount gets larger. 

### Tested

Tested via iOS simulator. 
A sample of what it looks like when the font shrinks: 
Simulator Screen Shot - iPhone 11 - 2021-02-05 at 14 40 33
What it looks like before the font gets smaller: 
Simulator Screen Shot - iPhone 11 - 2021-02-05 at 14 40 28

### Related issues

- Fixes #4960 
- https://github.com/celo-org/celo-monorepo/issues/4960

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/send/SendAmount.tsx [hunk 1]
```diff
@@ -353,14 +353,16 @@ const styles = StyleSheet.create({
...
-    flex: 1,
-    flexDirection: 'row',
-    justifyContent: 'center',
+   flex: 1,
+   flexDirection: 'row',
+   justifyContent: 'center',
   },
   amountContainer: {
     justifyContent: 'center',
+    maxWidth: 256,
```
Comment (jeanregisser) [inline packages/mobile/src/send/SendAmount.tsx]: This shouldn't be absolute, so it adapts better to different screen widths.
What about `'90%'` instead?

File: packages/mobile/src/send/SendAmount.tsx [hunk 2]
```diff
@@ -379,9 +381,7 @@ const styles = StyleSheet.create({
     marginLeft: 8,
   },
   amount: {
-    ...fontStyles.regular,
```
Comment (jeanregisser) [inline packages/mobile/src/send/SendAmount.tsx:382]: We can't keep our custom font?

File: packages/mobile/src/send/SendAmount.tsx [hunk 3]
```diff
@@ -353,14 +353,16 @@ const styles = StyleSheet.create({
...
     flex: 1,
+    width: Dimensions.get("window").width,
   },
   showAmountContainer: {
-    flex: 1,
-    flexDirection: 'row',
-    justifyContent: 'center',
+   flex: 1,
+   flexDirection: 'row',
+   justifyContent: 'center',
```
Comment (jeanregisser) [inline packages/mobile/src/send/SendAmount.tsx]: Looks like this was manually formatted. We should let prettier do this.
There's a default configuration with vscode that does it on save: https://github.com/celo-org/celo-monorepo/blob/fce3df17d1df43c37e59a3cc6918cc1a788a7dad/.vscode/settings.json#L38
The vscose prettier plugin needs to be installed too.

File: packages/mobile/src/send/SendAmount.tsx [hunk 4]
```diff
@@ -353,14 +353,16 @@ const styles = StyleSheet.create({
   },
   contentContainer: {
     flex: 1,
+    width: Dimensions.get("window").width,
```
Comment (jeanregisser) [inline packages/mobile/src/send/SendAmount.tsx]: Is this necessary?

**Review by jeanregisser — COMMENTED** [review]
Thanks! 👍

File: packages/mobile/src/send/SendAmount.tsx (hunk 4 above)
Comment (michellewong793) [reply packages/mobile/src/send/SendAmount.tsx]: i dont think so, i was thinking about how to use Dimensions.get("window") in a way that would work with different screen sizes but wasnt too sure. the 90% width change above will probably suffice!

File: packages/mobile/src/send/SendAmount.tsx (hunk 3 above)
Comment (michellewong793) [reply packages/mobile/src/send/SendAmount.tsx]: ahh! i have prettier installed but it doesnt always format on save. might just reinstall vscode since its been buggy

File: packages/mobile/src/send/SendAmount.tsx (hunk 2 above)
Comment (michellewong793) [reply packages/mobile/src/send/SendAmount.tsx:382]: oo my bad! i think the custom font and the regular font looked so similar i didnt realize this line stayed! will re-add

File: packages/mobile/src/send/SendAmount.tsx (hunk 1 above)
Comment (michellewong793) [reply packages/mobile/src/send/SendAmount.tsx]: for sure! ill try it out. makes sense

File: packages/mobile/src/send/SendAmount.tsx (hunk 2 above)
Comment (michellewong793) [reply packages/mobile/src/send/SendAmount.tsx:382]: oh i see, actually. the custom had a set line height that was messing up the display of the amount. also, since the line height changes as the font gets smaller, i think we should take it out. it looks like it still retains font family

Comment (jeanregisser) [reply packages/mobile/src/send/SendAmount.tsx:382]: yes let's keep the font and set `lineHeight: undefined` here then.

Comment (michellewong793) [reply packages/mobile/src/send/SendAmount.tsx:382]: sounds good!

**Review by jeanregisser — APPROVED** [review]
Awesome! 👍 
Before merging, please remove the questions from the PR template in the description.
For backward compatibility, you can mention "Yes" there.

**Comment by ValoraQA** [comment]
Hey @michellewong793 I have verified this issue using latest Android Internal Build V1.11.1(1004294339) & Test Flight Build V1.11.1(48) & observed following observations.
**Observations:**

- [x] It is observed that, if user enters too large amount then digits not get overlapped on keyboard.
- [ ] Also it is observed that digits size get smaller & Dollar symbol size increases when user continuous entering too large amount in field. Let me know is it expected ?
**Attachment:** [AmountAndDollarSymbolSizeChanges.mp4](https://drive.google.com/file/d/134dFpr7Ozj2__ct44jmYKhLxg9juyEZu/view?usp=sharing)

**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (14.2)
