### PR TITLE
[Wallet] Various bug fixes

### LINKED ISSUE #4031: “Placeholder” text is shown on Payment request notification section when user send payment request to  other user.
**Frequency:** 100%
** Repro App version:** Celo Integration build v1.8.2 (34)
**Repro on device:** iphone 6+ (12.4.5)
**Tested Account** 503 447 5958 / back up key
**Repro Steps:** 
1) Launch the app and login with tested account. 
2) Tap on Request button. 
3) Select any phone number 
4) Enter an amount. tap on review button. 
5) Enter Security PIN. 
6) Tap on request button. 
7) Navigate to Home tab and observe 
 
**Current Behavior:**  Placeholder Text is shown 
**Expected Behavior:** Reason of sent payment request should be shown
**Impact:** User B will not able to get reason why they receive payment request. 
**Attachment:** PlaceholderIssue.png
PlaceholderIssue

### LINKED ISSUE #4164: Nothing happen when user taps on "<" from Select language screen after launching the fresh installed app
**Frequency:** 100%
** Repro App version:** Celo Integration Wallet build v1.8.2 (39)
**Does not repro ON:** App store build v1.8.2 
**Repro on device:**iPhone XS max (13.1), iphone 6+ (12.4.5),iphone 11(13.3)

**Repro Steps:** 
1) Launch the fresh installed app 
2) Make sure Select language page is open
3) Click on < arrow top left corner on Select Language screen 
4) Observe nothing happen when user taps on < arrow. 

**Current Behavior:* Nothing happen when user taps  on < arrow
**Expected Behavior:** As it is first screen of application < arrow should not display. 
**Investigation:** back arrow is work on Select language screen when user open it from setting 
**Impact** Bad user experience
**Attachment:** BackArrowissue.png             
BackArrowIssue

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Issues resolved:
- Fixed bug where payment request fulfillment was allowing payment comments to be edited 
- Fixed navigation bug on Gold Home screen
- Fixed escrow withdraw error that occurs after verification when no funds are in escrow
- Added support for non-native email apps (current functionality is to use only use the new package when default email app isn't detected but it doesn't support attaching logs as an attachment)
- Fixed navigation errors that were happening on Support screen
- Fixed Account number bug that was sometimes causing overflow onto a third line
- Removed back arrow from Language when it's rendered as the first onboarding screen
- Fixed typo and standardized punctuation across notification headers

### Tested
Yes

### Related issues
- Closes #4031
- Closes #4164 

### Backwards compatibility
Yes

### CODE REVIEW

File: packages/mobile/src/navigator/Navigator.tsx [hunk 1]
```diff
@@ -447,6 +448,7 @@ const generalScreens = (Navigator: typeof Stack) => (
       component={TransactionReview}
       options={transactionReviewOptions}
     />
+    <Navigator.Screen name={Screens.GoldEducation} component={GoldEducation} options={noHeader} />
```
Comment (tarikbellamine) [inline packages/mobile/src/navigator/Navigator.tsx:456]: @i1skn wanted to flag that I am adding this back in. It was contributing to the bug we were seeing where clicking the Info Icon on the gold home screen wouldn't navigate correctly.

File: packages/mobile/src/account/SupportContact.tsx [hunk 2]
```diff
@@ -83,13 +106,26 @@ const SupportContact = (props: Props) => {
...
+      } else if (error) {
+        const emailSent = await sendEmailWithNonNativeApp(
+          emailSubject,
+          message,
+          deviceInfo,
+          combinedLogsPath
+        )
+        if (emailSent.success) {
+          navigateBack()
+          props.showMessage(t('contactSuccess'))
```
Comment (i1skn) [inline packages/mobile/src/account/SupportContact.tsx]: Can we have it as a separate method to avoid code duplication?

File: packages/mobile/src/language/Language.tsx [hunk 3]
```diff
@@ -54,6 +56,12 @@ export default function Language({ route }: Props) {
   )
 }
 
+Language.navigationOptions = ({ navigation }: ScreenProps) => {
+  return navigation.canGoBack() ? headerWithBackButton : emptyHeader
```
Comment (i1skn) [inline packages/mobile/src/language/Language.tsx:60]: This is pretty cool, I was not aware of `canGoBack` method. I solved this issue differently here https://github.com/celo-org/celo-monorepo/pull/4161/files#diff-f418c92450b21cbd54162b941cf091f0R82. But it feels, that your way is slightly better 🙂 So, if my PR will be merged earlier - feel free to resolve conflicts in favour of your approach.

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (i1skn) [reply packages/mobile/src/navigator/Navigator.tsx:456]: Is it because we navigate back from `info` via  `navigate(Screens.GoldEducation)`, right? Is it possible to use `navigateBack()` there instead?

File: packages/mobile/src/language/Language.tsx (hunk 3 above)
Comment (jeanregisser) [reply packages/mobile/src/language/Language.tsx:60]: Ahah we're all fixing it. I've fixed it too with this approach but applying it everywhere:
https://github.com/celo-org/celo-monorepo/pull/4213/files#diff-5992d9baf806b71ab634873ff02d6b60

Comment (tarikbellamine) [reply packages/mobile/src/language/Language.tsx:60]: Jean for the win lol

File: packages/mobile/src/navigator/Navigator.tsx (hunk 1 above)
Comment (tarikbellamine) [reply packages/mobile/src/navigator/Navigator.tsx:456]: I think `navigateBack` takes you back to WalletHome. Also, removing it from the stack eliminates the navigation headers and replaces it with a weird gray bar, so I think this is the way to go.

File: packages/mobile/src/account/SupportContact.tsx (hunk 2 above)
Comment (tarikbellamine) [reply packages/mobile/src/account/SupportContact.tsx]: Done!

File: packages/mobile/src/home/NotificationBox.tsx [hunk 4]
```diff
@@ -28,6 +27,8 @@ import { RootState } from 'src/redux/reducers'
 import { isBackupTooLate } from 'src/redux/selectors'
 import { navigateToVerifierApp } from 'src/utils/linking'
 
+const INVITE_NOTIFICATION_DISABLED = true
```
Comment (jmrossy) [inline packages/mobile/src/home/NotificationBox.tsx]: Please move this to `flags.ts` or `config.ts`, I'd recommend flags

File: packages/mobile/src/language/Language.tsx [hunk 5]
```diff
@@ -54,6 +56,12 @@ export default function Language({ route }: Props) {
...
+}
+
+export default Language
```
Comment (jmrossy) [inline packages/mobile/src/language/Language.tsx]: Nit, move to bottom

File: packages/mobile/src/utils/Logger.ts [hunk 6]
```diff
@@ -49,12 +49,12 @@ class Logger extends ReactNativeLogger {
...
       if (await RNFS.exists(rnLogsSrc)) {
+        await RNFS.writeFile(combinedLogsPath, '========React Native Logs========\n')
         await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(rnLogsSrc))
       }
-      await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
       if (await RNFS.exists(gethLogsSrc)) {
+        await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
         await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(gethLogsSrc))
       }
       return combinedLogsPath
```
Comment (jmrossy) [inline packages/mobile/src/utils/Logger.ts]: What happens if `combinedLogsPath` doesn't exist cause neither of these if statements hit?

**Review by jmrossy — APPROVED** [review]
Mostly lgtm, please see small comments below

File: packages/mobile/src/utils/Logger.ts (hunk 6 above)
Comment (tarikbellamine) [reply packages/mobile/src/utils/Logger.ts]: I'm not sure I follow. If neither of the if statements hit, wouldn't the log file just be empty? It looks to me that `combinedLogsPath` should always exist

Comment (jmrossy) [reply packages/mobile/src/utils/Logger.ts]: If RNFS.writeFile doesn't get called, the file won't exist.

File: packages/mobile/src/utils/Logger.ts [hunk 7]
```diff
@@ -49,12 +49,12 @@ class Logger extends ReactNativeLogger {
       // one time file access permissions which we cannot use here since the library we are using it
       // does not understand that.
       const combinedLogsPath = this.getCombinedLogsFilePath()
-      await RNFS.writeFile(combinedLogsPath, '========React Native Logs========\n')
       if (await RNFS.exists(rnLogsSrc)) {
+        await RNFS.writeFile(combinedLogsPath, '========React Native Logs========\n')
         await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(rnLogsSrc))
       }
```
Comment (tarikbellamine) [inline packages/mobile/src/utils/Logger.ts]:
```suggestion
      await RNFS.writeFile(combinedLogsPath, '========React Native Logs========\n')
      if (await RNFS.exists(rnLogsSrc)) {
        await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(rnLogsSrc))
      }
```

File: packages/mobile/src/utils/Logger.ts [hunk 8]
```diff
@@ -49,12 +49,12 @@ class Logger extends ReactNativeLogger {
...
-      await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
       if (await RNFS.exists(gethLogsSrc)) {
+        await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
         await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(gethLogsSrc))
       }
```
Comment (tarikbellamine) [inline packages/mobile/src/utils/Logger.ts]:
```suggestion
      await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')      
      if (await RNFS.exists(gethLogsSrc)) {
        await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(gethLogsSrc))
      }
```

File: packages/mobile/src/utils/Logger.ts [hunk 9]
```diff
@@ -53,7 +53,7 @@ class Logger extends ReactNativeLogger {
       if (await RNFS.exists(rnLogsSrc)) {
         await RNFS.appendFile(combinedLogsPath, await RNFS.readFile(rnLogsSrc))
       }
-      await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
+      await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
```
Comment (tarikbellamine) [inline packages/mobile/src/utils/Logger.ts]:
```suggestion
      await RNFS.appendFile(combinedLogsPath, '\n\n========Geth Logs========\n')
```

File: packages/mobile/src/utils/Logger.ts (hunk 6 above)
Comment (tarikbellamine) [reply packages/mobile/src/utils/Logger.ts]: Oh, I see what you mean. I thought the log file already existed somewhere. Reverting my changes.
