### PR TITLE
Wait for Web3 to be ready before trying to redeem an invite

### LINKED ISSUE #51: Users SBAT redeem invite on the first try
### Expected Behavior

RedeemInvite failed first time, but worked second time.

### Current Behavior

Should work the first time.

### PR DESCRIPTION
**Pull request by martinvol**
### Description

Previously Web3 syncking was triggered manually from `Sync.tsx` screen, that's only executed the first time is the onboarding flow, causing issues.

Web3 still fails after waiting for it to be ready, so a retry was implemented. Opened #277 to investigate why is that so.

### Tested

- Tests Added

### Other changes

Moved a couple of error strings to json files.

### Related issues

- Fixes #51

### Backwards compatibility

-

### CODE REVIEW

File: packages/mobile/src/invite/saga.ts [hunk 1]
```diff
@@ -199,7 +195,8 @@ function* redeemSuccess(name: string, account: string) {
 export function* redeemInviteSaga(action: RedeemInviteAction) {
   const { inviteCode, name } = action
 
-  yield call(waitForGethConnectivity)
+  yield call(waitForNetwork)
```
Comment (martinvol) [inline packages/mobile/src/invite/saga.ts]: This is the example usage to replace `waitForGethConnectivity`.

File: packages/mobile/src/web3/saga.ts [hunk 2]
```diff
@@ -133,9 +122,15 @@ function* checkSyncProgressWorker() {
           continue
         }
 
-        Logger.debug(TAG, 'Sync Progress Completed')
-        yield put(setSyncProgress(100))
-        yield put(setIsReady(true))
+        const latestBlock: Block = yield getLatestBlock()
+        if (latestBlock && latestBlock.number > 0) {
+          yield put(setLatestBlockNumber(latestBlock.number)) // Don't understand why we need this
```
Comment (martinvol) [inline packages/mobile/src/web3/saga.ts]: I couldn't figure out why we're doing this as I couldn't find an usage of this store variable that's set here.

File: packages/mobile/src/web3/saga.ts [hunk 3]
```diff
@@ -133,9 +122,15 @@ function* checkSyncProgressWorker() {
           continue
         }
 
-        Logger.debug(TAG, 'Sync Progress Completed')
```
Comment (martinvol) [inline packages/mobile/src/web3/saga.ts:136]: This was redundant.

File: packages/mobile/src/invite/saga.ts [hunk 4]
```diff
@@ -116,10 +116,6 @@ export function* sendInvite(
     const temporaryWalletAccount = web3.eth.accounts.create()
     const temporaryAddress = temporaryWalletAccount.address
     const inviteCode = createInviteCode(temporaryWalletAccount.privateKey)
-
-    // TODO: Improve this by not checking specifically for this
-    // display name. Requires improvements in recipient handling
-    recipientName = recipientName === i18n.t('sendFlow7:mobileNumber') ? '' : ' ' + recipientName
```
Comment (jmrossy) [inline packages/mobile/src/invite/saga.ts]: Why remove this? We need it to prevent sending SMS messages with the text "Hi Mobile #"

File: packages/mobile/src/web3/saga.ts [hunk 5]
```diff
@@ -31,47 +33,65 @@ import {
...
+  }
+}
+
 // checks if web3 claims it is currently syncing or not
-function* checkWeb3SyncProgressClaim() {
-  Logger.debug(TAG, 'Checking sync progress claim')
+export function* checkWeb3SyncProgressClaim() {
+  // yield call(waitForGethConnectivity)
   while (true) {
+    yield delay(1000) // Doesn't need to update that fast
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: what's this for?

File: packages/mobile/src/web3/saga.ts [hunk 6]
```diff
@@ -31,47 +33,65 @@ import {
...
-      Logger.debug(TAG, 'Sync progress', syncProgress)
+      const syncProgress = yield web3.eth.isSyncing() // return false when it's still syncing and thus not ready
 
       if (typeof syncProgress === 'boolean' && !syncProgress) {
-        // For some weird reason, checkSyncProgressWorker is flaky and does not work for the long running
-        // sync tasks.
-        Logger.debug(TAG, 'sync complete')
-        yield put(setSyncProgress(100))
-        yield put(setIsReady(true))
+        if (!(yield select(web3ReadySelector))) {
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: I don't understand why we check that here? 
When would we reach this point but have already set is ready to true?

File: packages/mobile/src/web3/saga.ts [hunk 7]
```diff
@@ -31,47 +33,65 @@ import {
...
       yield put(updateWeb3SyncProgress(syncProgress))
     } catch (error) {
       if (error.toString().toLowerCase() === BLOCK_CHAIN_CORRUPTION_ERROR.toLowerCase()) {
         CeloAnalytics.track(CustomEventNames.blockChainCorruption, {}, true)
         const deleted = yield call(deleteChainData)
         if (deleted) {
-          navigate(Screens.ErrorScreen, {
-            errorMessage: 'Corrupted chain data has been deleted, please restart the app',
-          })
+          yield put(showError(ErrorMessages.SEND_PAYMENT_FAILED, ERROR_BANNER_DURATION))
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: I'm wondering if navigating to error was a better choice here? The user may miss the banner. I think they have no other options except restarting the app at this point right?

File: packages/mobile/src/web3/saga.ts (hunk 2 above)
Comment (jmrossy) [reply packages/mobile/src/web3/saga.ts]: For the debug screen I guess? Probably doesn't need to be in store though, you're right.

File: packages/mobile/src/web3/saga.ts [hunk 8]
```diff
@@ -133,9 +122,15 @@ function* checkSyncProgressWorker() {
           continue
         }
 
-        Logger.debug(TAG, 'Sync Progress Completed')
-        yield put(setSyncProgress(100))
-        yield put(setIsReady(true))
+        const latestBlock: Block = yield getLatestBlock()
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: i used to see instances where web3 CLAIMED to be done syncing but actually latestBlock was still 0, which is why we used to check for that case and keep waiting.

File: packages/mobile/src/web3/saga.ts (hunk 7 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts]: Probably `navigateToError` is a better option now that you mention.

File: packages/mobile/src/web3/saga.ts (hunk 5 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts]: Because it's inside of a while loop that's triggered ass soon as the app starts. Without delay the app would be looping to fast and spending too much resources pooling Web3 status. Maybe it'd be better if we trigger this check from `waitForNetwork` to avoid pooling Web3.

My solution has a worse case were Web3 gets disconnected just before checking for `isReady` and before the next `web3.eth.isSyncing()` call.

File: packages/mobile/src/web3/saga.ts (hunk 6 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts]: It's there because the loop is infinite for the lifecycle of the app.

File: packages/mobile/src/invite/saga.ts (hunk 4 above)
Comment (martinvol) [reply packages/mobile/src/invite/saga.ts]: Don't really know how this ended up here, will restore

**Comment by martinvol** [comment]
So, independently of how I implemented this, currently this branch makes sure both Geth and Web3 are ready at the contract call `const stableBalance = new BigNumber(yield call(StableToken.methods.balanceOf(tempAccount).call))` 

Still fails with `Uncaught Error: Returned values aren't valid, did it run Out of Gas? at ABICoder.push../node_modules/web3-eth-abi/src/index.js.ABICoder.decodeParameters (index.js:227) at ABICoder.push../node_modules/web3-eth-abi/src/index.js.ABICoder.decodeLog (index.js:277)`.

I tried upgrade web3 to latest beta but then `yield web3.eth.isSyncing()` fails.

Any clue where I should look further to solve this issue?

**Comment by martinvol** [comment]
I thought that my `waitForNetwork` fixed the issue but it turned out to be more difficult to reproduce than I originally thought.

I implemented a re-try for the contract call so the invite can work again while we figure out what could be causing the exception.

File: packages/utils/src/miscellaneous.ts [hunk 9]
```diff
@@ -0,0 +1,18 @@
+// import Logger from '@celo/mobile/src/utils/Logger';
+
+const TAG = 'utils/src/miscellaneous'
+
+export const reTryAsync = async (inFunction: any, tries: number, params: any) => {
+  let saveError
+  for (let i = 0; i < tries + 1; i++) {
+    try {
+      return await inFunction(...params)
```
Comment (jmrossy) [inline packages/utils/src/miscellaneous.ts]: why `return await` here?

File: packages/utils/src/miscellaneous.ts [hunk 10]
```diff
@@ -0,0 +1,18 @@
+// import Logger from '@celo/mobile/src/utils/Logger';
+
+const TAG = 'utils/src/miscellaneous'
+
+export const reTryAsync = async (inFunction: any, tries: number, params: any) => {
```
Comment (jmrossy) [inline packages/utils/src/miscellaneous.ts]: Nit: `reTry` -> `retry`

File: packages/mobile/src/invite/saga.ts [hunk 11]
```diff
@@ -217,7 +220,13 @@ export function* redeemInviteSaga(action: RedeemInviteAction) {
 
     // Check that the balance of the new account is not 0
     const StableToken = yield call(getStableTokenContract, web3)
-    const stableBalance = new BigNumber(yield call(StableToken.methods.balanceOf(tempAccount).call))
+    Logger.debug(TAG + '@redeemInviteCode', 'web3 is: ' + (yield select(web3ReadySelector)))
+
+    // Try to get balance once + two retries before failing
+    const stableBalance = new BigNumber(
+      yield call(reTryAsync, StableToken.methods.balanceOf(tempAccount).call, 2, [])
```
Comment (jmrossy) [inline packages/mobile/src/invite/saga.ts]: I don't think that adding retry logic is the way to go. We'd have to add it everywhere to be consistent and I'm not sure it helps chances of success here.

File: packages/mobile/src/web3/saga.ts (hunk 6 above)
Comment (jmrossy) [reply packages/mobile/src/web3/saga.ts]: I don't think that's what we want though. If this saga is constantly running for the lifetime of the app, then it's wasting resources and can potentially interfere with other saga (we've seen that issue before)

File: packages/utils/src/miscellaneous.ts (hunk 9 above)
Comment (martinvol) [reply packages/utils/src/miscellaneous.ts]: I await here because I don't want to return the promise, I want the function to run otherwise it'd always do all the retries.

File: packages/mobile/src/web3/saga.ts [hunk 12]
```diff
@@ -48,30 +45,24 @@ let AssignAccountLock = false
...
     try {
-      const syncProgress = yield web3.eth.isSyncing()
-      Logger.debug(TAG, 'Sync progress', syncProgress)
-
+      const syncProgress = yield web3.eth.isSyncing() // returns true when it's still syncing and thus not ready
       if (typeof syncProgress === 'boolean' && !syncProgress) {
-        // For some weird reason, checkSyncProgressWorker is flaky and does not work for the long running
-        // sync tasks.
-        Logger.debug(TAG, 'sync complete')
+        Logger.debug(TAG, 'checkWeb3SyncProgressClaim', 'sync complete')
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:52]: Nit, we typically join the Tag and function name into one param (with a + sign or with string interpolation).
I guess this is more or less equivalent, not sure why we don't use this syntax more. Any thoughts?

File: packages/mobile/src/web3/saga.ts [hunk 13]
```diff
@@ -48,30 +45,24 @@ let AssignAccountLock = false
...
+
         yield put(setSyncProgress(100))
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:54]: Does anything still consume syncProgress?

File: packages/mobile/src/web3/saga.ts [hunk 14]
```diff
@@ -81,70 +72,40 @@ function* checkWeb3SyncProgressClaim() {
...
-        Logger.debug(TAG, 'Sync Progress Completed')
-        yield put(setSyncProgress(100))
-        yield put(setIsReady(true))
-      } catch (error) {
-        Logger.error(TAG, `checkSyncProgressWorker error: ${error}`)
+      if (timeout) {
+        Logger.error(TAG, 'Could not complete sync progress check')
         navigate(Screens.ErrorScreen, {
-          errorMessage: 'Error occurred during sync, please try again later',
+          errorMessage: 'Failing to sync, check your network connection',
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: Can we i18n this?

File: packages/mobile/src/web3/saga.ts [hunk 15]
```diff
@@ -266,7 +227,10 @@ export function* watchRefreshGasPrice() {
   yield takeLatest(Actions.SET_GAS_PRICE, refreshGasPrice)
 }
 
+// export function* watchRequestSyncProgress() {
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: Remove this?

File: packages/utils/src/miscellaneous.ts (hunk 9 above)
Comment (jmrossy) [reply packages/utils/src/miscellaneous.ts]: Can you add a comment and maybe put the return on the next line to make this more clear?

File: packages/utils/src/miscellaneous.ts [hunk 16]
```diff
@@ -0,0 +1,23 @@
...
+  tries: number,
+  params: any,
+  delay = 100
+) => {
+  let saveError
+  for (let i = 0; i < tries + 1; i++) {
+    try {
+      return await inFunction(...params)
+    } catch (error) {
+      await new Promise((resolve) => setTimeout(resolve, delay))
```
Comment (jmrossy) [inline packages/utils/src/miscellaneous.ts]: What is this for?

**Review by jmrossy — COMMENTED** [review]
Mostly looks good to me! Just some questions below

File: packages/mobile/src/web3/saga.ts (hunk 12 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts:52]: This is kinda inconsistent through the project, I like this one because it doesn't involve any extra code.

File: packages/mobile/src/web3/saga.ts (hunk 13 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts:54]: Currently, no. I feel that code might be useful in the future.

File: packages/utils/src/miscellaneous.ts [hunk 17]
```diff
@@ -0,0 +1,24 @@
...
+export const retryAsync = async (
+  inFunction: InFunction,
+  tries: number,
+  params: any,
+  delay = 100
+) => {
+  let saveError
+  for (let i = 0; i < tries + 1; i++) {
+    try {
+      // it awaits otherwaise it'd always do all the retries
```
Comment (jmrossy) [inline packages/utils/src/miscellaneous.ts]: typo: otherwise
Can you also mention that the inFunction *must* throw an error on failures otherwise this mechanism doesn't work

**Review by jmrossy — DISMISSED** [review]
One typo below but looks good!
Love a PR that removes many more lines than it adds!

File: packages/utils/src/miscellaneous.ts [hunk 18]
```diff
@@ -0,0 +1,26 @@
+const TAG = 'utils/src/miscellaneous'
```
Comment (cmcewen) [inline packages/utils/src/miscellaneous.ts]: Do you have any other name ideas for this file? `async-helpers`?

File: packages/mobile/src/web3/saga.ts [hunk 19]
```diff
@@ -81,70 +71,36 @@ function* checkWeb3SyncProgressClaim() {
...
-      TAG,
-      `web3 indicated sync complete, yet the latest block is ${JSON.stringify(latestBlock)}`
-    )
-  }
-}
-
 // The worker listening to sync progress requests
-function* checkSyncProgressWorker() {
-  while (true) {
+export function* checkWeb3Sync() {
```
Comment (cmcewen) [inline packages/mobile/src/web3/saga.ts:76]: Could you add some tests for these functions?

File: packages/mobile/src/web3/reducer.ts [hunk 20]
```diff
@@ -17,7 +16,6 @@ export interface State {
 }
 
 const initialState: State = {
-  isReady: false,
```
Comment (cmcewen) [inline packages/mobile/src/web3/reducer.ts:20]: I think since we don't persist this we don't need a redux-persist migration, but just a heads up for next time

File: packages/mobile/src/networkInfo/saga.ts [hunk 21]
```diff
@@ -13,6 +15,11 @@ export function* waitForRehydrate() {
   return
 }
 
+export function* waitForNetwork() {
+  yield waitForGethConnectivity()
+  yield checkWeb3Sync()
```
Comment (cmcewen) [inline packages/mobile/src/networkInfo/saga.ts:20]: From my understanding of the code, this will make a call to web3 to get the latest block every time, which is a little different than the way the rest of our waitFor functions work. Does this need to get the latest block, or is there a way to just signified we reached latest block once already in the session and then we are good to go

File: packages/utils/src/miscellaneous.ts (hunk 18 above)
Comment (jmrossy) [reply packages/utils/src/miscellaneous.ts]: +1 for rename here

File: packages/mobile/src/networkInfo/saga.ts (hunk 21 above)
Comment (martinvol) [reply packages/mobile/src/networkInfo/saga.ts:20]: This function is not actually executing any work, it's just waiting for web3 to sync (meaning `web3.eth.isSyncing` returns `false`).

It doesn't respect the same pattern as when we wait for geth because I didn't want it to be checking the function `web3.eth.isSyncing` and dispatching transactions. We chatted with @jmrossy it might be a good idea to refactor `waitForGethConnectivity` to respect this pattern as well.

What do you think?

File: packages/mobile/src/web3/saga.ts (hunk 19 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts:76]: done!

File: packages/mobile/src/web3/reducer.ts (hunk 20 above)
Comment (martinvol) [reply packages/mobile/src/web3/reducer.ts:20]: Yeah, as the migration tests didn't fail I figured. Is that how I'm supposed to check of this heuristic can fail?

File: packages/mobile/src/networkInfo/saga.ts (hunk 21 above)
Comment (cmcewen) [reply packages/mobile/src/networkInfo/saga.ts:20]: I get that it's not sending transactions, but it is still making a web3 call, which to me is like making an API call (will have some cost to communicate), and then also afterwards calls getLatestBlock (https://github.com/celo-org/celo-monorepo/pull/100/files#diff-ba0401a32c25d663ec689871b8ec6d86R90). I guess this isn't explicitly defined, but the way I think of our `waitFor` saga actions is to check some state, if it's the proper state then return, otherwise wait for an action that will set that state to something else, and that's it. So they are basically "free" in terms of cost because they don't do much work except checking state and waiting. This breaks that convention and does some work, so that is just why I am a little hesitant about using that name, and also would be hesitant about using this a lot of places

File: packages/mobile/src/web3/reducer.ts (hunk 20 above)
Comment (cmcewen) [reply packages/mobile/src/web3/reducer.ts:20]: Yeah that would make sense to me - would defer to Rossy or Jean since they have worked with it more recently

File: packages/mobile/src/networkInfo/saga.ts (hunk 21 above)
Comment (martinvol) [reply packages/mobile/src/networkInfo/saga.ts:20]: I could implement this using the same 'waitForGethConnectivity' and that would be free, but it'd have to pool web3 on the back everytime. This approach only pools web3 before making a contract call.

Comment (cmcewen) [reply packages/mobile/src/networkInfo/saga.ts:20]: I think if you are going to poll something, just maybe have one worker that manages the polling, and then everything else can just wait on the state to be updated properly

Comment (martinvol) [reply packages/mobile/src/networkInfo/saga.ts:20]: The problem with that is that if you have a store variable set to true when it's ready, I'd never go back to false if you're not pooling all the time and would leave the store in an inconsistent state.

File: packages/mobile/src/web3/saga.ts [hunk 22]
```diff
@@ -38,40 +36,33 @@ const ETH_PRIVATE_KEY_LENGTH = 64
...
-// The timeout for web3 to complete syncing
-const CHECK_WEB3_SYNC_PROGRESS_TIMEOUT = 60000
 // The timeout for web3 to complete syncing and the latestBlock to be > 0
 const CHECK_SYNC_PROGRESS_TIMEOUT = 60000
 const BLOCK_CHAIN_CORRUPTION_ERROR = "Error: CONNECTION ERROR: Couldn't connect to node on IPC."
 
 let AssignAccountLock = false
 
 // checks if web3 claims it is currently syncing or not
+// exported for testing
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: We probably don't need this comment. Also the function is not exported

File: packages/mobile/src/web3/saga.ts [hunk 23]
```diff
@@ -267,6 +224,9 @@ export function* watchRefreshGasPrice() {
 }
 
 export function* web3Saga() {
-  yield spawn(checkSyncProgressWorker)
   yield spawn(watchRefreshGasPrice)
 }
+
+// exported for testing
+export const _checkWeb3SyncProgressClaim = checkWeb3SyncProgressClaim
+export const _CHECK_SYNC_PROGRESS_TIMEOUT = CHECK_SYNC_PROGRESS_TIMEOUT // Camell case because
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts]: `Camell case because`?

File: packages/mobile/src/web3/saga.ts [hunk 24]
```diff
@@ -267,6 +224,9 @@ export function* watchRefreshGasPrice() {
 }
 
 export function* web3Saga() {
-  yield spawn(checkSyncProgressWorker)
   yield spawn(watchRefreshGasPrice)
 }
+
+// exported for testing
+export const _checkWeb3SyncProgressClaim = checkWeb3SyncProgressClaim
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:231]: what do you think of just renaming `checkWeb3SyncProgressClaim` to `_checkWeb3SyncProgressClaim` and exporting it?

File: packages/mobile/src/web3/saga.ts [hunk 25]
```diff
@@ -267,6 +224,9 @@ export function* watchRefreshGasPrice() {
 }
 
 export function* web3Saga() {
-  yield spawn(checkSyncProgressWorker)
```
Comment (jmrossy) [inline packages/mobile/src/web3/saga.ts:270]: Shouldn't `getConnectedAccount` use the new web3 wait? Many functions rely on that helper

**Review by jmrossy — COMMENTED** [review]
Approach looks good to

File: packages/mobile/src/web3/saga.ts (hunk 25 above)
Comment (martinvol) [reply packages/mobile/src/web3/saga.ts:270]: done

File: packages/utils/test/miscellaneous.test.ts [hunk 26]
```diff
@@ -0,0 +1,24 @@
+import { retryAsync } from '../src/async-helpers'
+
+describe('utils->miscellaneous', () => {
```
Comment (jmrossy) [inline packages/utils/test/miscellaneous.test.ts]: Please rename this file and edit string here

Comment (martinvol) [reply packages/utils/test/miscellaneous.test.ts]: Nice catch

**Review by jmrossy — APPROVED** [review]
