### PR TITLE
[Wallet] New camera permission flow

### LINKED ISSUE #1397: New camera permission flow
### Expected Behavior

camera_permissioning

### Current Behavior

- On iOS: it displays a blank screen when trying to scan QR codes.
- On Android: when the permission is denied, it navigates to the qr code display screen, but this incorrect when the qr scanner is used from the send flow.

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

camera_permissioning

Highlights:
- react-native-camera now handles the details of asking for permissions
- a custom view is displayed when the permission has been denied so the
user can navigate to the settings and allow the permission

### Tested

Tested the flow on both iOS and Android.
- go to qr scanner > deny permission > it shows the message instructing to go to the settings to allow permission > tap 'Settings' > Settings open
- go to qr scanner > accept permission > it can successfully scan

**iOS**
IMG_2740
IMG_2737
IMG_2735

**Android**
iTerm2 NCkoL3
iTerm2 Yn4EU2
iTerm2 uPNfeQ

### Other changes

- You can now tap the QR icon next to "Show your QR code" to trigger the action ;) Previously only tapping the text would trigger it.

### Related issues

- Fixes #1397

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/qrcode/NotAuthorizedView.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+import { Linking, Platform, StyleSheet, Text, View } from 'react-native'
+import * as AndroidOpenSettings from 'react-native-android-open-settings'
+import { Namespaces } from 'src/i18n'
+
+type Props = WithNamespaces
+
+function NotAuthorizedView({ t }: Props) {
+  const onPressSettings = useCallback(async () => {
+    if (Platform.OS === 'ios') {
+      await Linking.openURL('app-settings:')
```
Comment (jmrossy) [inline packages/mobile/src/qrcode/NotAuthorizedView.tsx]: Please use `navigateToUri`

**Review by jmrossy — APPROVED** [review]
One nit but otherwise lgtm
