### PR TITLE
[Wallet Redesign] ImportContactsScreen redesign

### LINKED ISSUE #4178: User is not redirect back to "Connect Contacts" screen from "Verifying + <Phone number>" screen after tapping on < Arrow from Connect Contacts screen.
**Frequency:** 100%
**Repro App version:** Celo Integration Wallet build v1.8.2 (39)
**Repro on device:** Iphone 11(13.3)
**Repro Steps:** 
1) Launch the app 
2)  Navigate to Verify Phone number screen 
3) Copy & paste the Three verification code.  
4) Make sure once after Submitting the codes user navigates to Almost done and later to Connect Contacts screen
5) Tap on < arrow from Connect contact screen. 
6) Observe user stuck on "Verifying + <Phone number>" screen

**Current Behavior:**  User is not redirect back to "Connect Contacts" screen 
**Expected Behavior:**  User is should redirect back to "Connect Contacts" screen 
**Investigation:** User cannot navigate from connect contacts page to connect contacts page by tapping < arrow
 **Impact** User is blocked to navigate back to Connect Contacts screen
**Attachment:** [ IOS_VerificationFlowIssue.Mp4](https://drive.google.com/file/d/1eY70G82uOS7ZNvR1_tiwfY9w5EBSNnPj/view?usp=sharing) (Bug Observed at 06Sec)

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Redesign of ImportContactsScreen

### Other changes
Refactored to use hooks

### Tested
Yes

### Related issues
Part of #3645
Closes #4178

### Backwards compatibility
Yes

IMG_4273

IMG_4274

IMG_4275

IMG_4276

### CODE REVIEW

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 1]
```diff
@@ -1,227 +1,187 @@
...
-    const isSkipHidden = status === ImportContactsStatus.Done
-
-    return (
-      <SafeAreaView style={styles.container}>
-        <ScrollView contentContainerStyle={styles.scrollContainer}>
-          {status <= ImportContactsStatus.Stopped && (
+  return (
+    <SafeAreaView style={styles.container}>
+      <ScrollView contentContainerStyle={styles.scrollContainer}>
+        <View>
```
Comment (jeanregisser) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: nit: because we use fullscreen layout for onboarding screens, on iOS this makes the content collide with the navigation bar content when you overscroll,



One way to prevent this is to start the scrollview under the navigation bar like done in:
https://github.com/celo-org/celo-monorepo/blob/aae2b147608ef1303df18b208c6778e01a22ccfd/packages/mobile/src/verify/VerificationEducationScreen.tsx#L68-L69

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 2]
```diff
@@ -1,227 +1,187 @@
...
-  }
-
-  onToggleFindMeSwitch = (value: boolean) => {
-    this.setState({
-      isFindMeSwitchChecked: value,
-    })
-  }
-
-  onFinish = () => {
+  function onFinish() {
```
Comment (jeanregisser) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: nit: I think we agreed to use fat arrow for inline handlers.

**Review by jeanregisser — APPROVED** [review]
Looks great thanks! 👍

File: packages/mobile/locales/en-US/onboarding.json [hunk 3]
```diff
@@ -4,12 +4,9 @@
     "body": "Adding your contacts makes it easy to send and request payments with your friends. Connecting does not send invites to your contacts.",
     "findSwitch": "Allow contacts to find you",
     "syncing": {
-      "loadingHeader": "Syncing contacts...",
-      "loadingStatus0": "Importing",
-      "loadingStatus1": "Processing {{total}} contacts",
-      "loadingStatus2": "Finding matches",
```
Comment (jmrossy) [inline packages/mobile/locales/en-US/onboarding.json:10]: Why have we removed these? For slow phones, having more steps would be nice to show progress?

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 4]
```diff
@@ -1,227 +1,187 @@
...
+  headerTitle: () => (
+    <HeaderTitleWithSubtitle
+      title={i18n.t('onboarding:verificationEducation.title')}
+      subTitle={i18n.t('onboarding:step', { step: '5' })}
+    />
+  ),
+  headerRight: () => (
+    <TopBarTextButton
+      title={i18n.t('global:skip')}
+      testID="VerificationEducationSkip"
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: Copy paste bug

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 5]
```diff
@@ -1,227 +1,187 @@
...
 
+ImportContactsScreen.navigationOptions = ({ navigation }: ScreenProps) => ({
+  ...nuxNavigationOptionsNoBackButton,
+  headerTitle: () => (
+    <HeaderTitleWithSubtitle
+      title={i18n.t('onboarding:verificationEducation.title')}
+      subTitle={i18n.t('onboarding:step', { step: '5' })}
+    />
+  ),
+  headerRight: () => (
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: The skip button shouldn't show when matching is done.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 6]
```diff
@@ -1,227 +1,187 @@
...
+    <TopBarTextButton
+      title={i18n.t('global:skip')}
+      testID="VerificationEducationSkip"
+      // tslint:disable-next-line: jsx-no-lambda
+      onPress={() => navigate(Screens.OnboardingSuccessScreen)}
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: This is missing a lot of the stuff we need to do onSkip right? Like cancelling the import

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 7]
```diff
@@ -1,227 +1,187 @@
...
+      titleStyle={{ color: colors.goldDark }}
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: inline style

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 8]
```diff
@@ -1,227 +1,187 @@
...
-                {t('contacts.syncing.successHeader', { matches: matchesFound })}
-              </Text>
-              <Text style={styles.h2Status}>{t('contacts.syncing.successStatus')}</Text>
-            </>
-          ) : (
-            <Text style={styles.h1Status}>{t('contacts.syncing.successStatus')}</Text>
-          )}
-        </View>
-      )
+  // If import has already been done, move user forward
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: When would this happen?

**Review by jmrossy — CHANGES_REQUESTED** [review]
It seems like this breaks some functionality that was working in my initial implementation.
I'd strongly prefer we not convert things to functional components without a good reason, especially if it increases risks of regressions

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 9]
```diff
@@ -1,227 +1,187 @@
...
 
-    let h2Text: string
-    if (status === ImportContactsStatus.Processing) {
-      h2Text = 'contacts.syncing.loadingStatus1'
-    } else if (status === ImportContactsStatus.Matchmaking) {
-      h2Text = 'contacts.syncing.loadingStatus2'
-    } else {
-      h2Text = 'contacts.syncing.loadingStatus0'
+  React.useEffect(() => {
+    const prevImportContactProgress = prevImportContactProgressRef.current
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx:111]: Does this work when the status has multiple steps? Or does the ref *always* have the first value of `importContactsProgress`?

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 10]
```diff
@@ -1,227 +1,187 @@
...
+  }, [])
 
-    let h2Text: string
-    if (status === ImportContactsStatus.Processing) {
-      h2Text = 'contacts.syncing.loadingStatus1'
-    } else if (status === ImportContactsStatus.Matchmaking) {
-      h2Text = 'contacts.syncing.loadingStatus2'
-    } else {
-      h2Text = 'contacts.syncing.loadingStatus0'
+  React.useEffect(() => {
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx:109]: Maybe I'm just a cranky old react developer, but do people feel like this ref + useEffect pattern is handling this scenario more elegantly than the class pattern? There are some things I like about hooks but this feels worse to me

**Review by jmrossy — COMMENTED** [review]
Looking at the screenshots, it looks like we need some more padding btwn the main elements right? Why keep them cramped but then have a giant open space beneath? @coreycelo

File: packages/mobile/locales/en-US/onboarding.json (hunk 3 above)
Comment (tarikbellamine) [reply packages/mobile/locales/en-US/onboarding.json:10]: Discussed with @coreycelo. I do not feel strongly about this.

Comment (coreycelo) [reply packages/mobile/locales/en-US/onboarding.json:10]: My understanding is we can no longer show progress (ie. 30 of 134 contacts) and only total (134 contacts) so we simplified it since there was less value add.

**Comment by coreycelo** [comment]
> Looking at the screenshots, it looks like we need some more padding btwn the main elements right? Why keep them cramped but then have a giant open space beneath? @coreycelo

There's a few things here including that the iPhone is particularly long and we're generally optimizing for a smaller screen. Overall just trying to keep this matching formatting throughout onboarding. Agree it's a bit cramped. A quick measure looks like the margins may be a bit different than spec'd, but assuming this matches the rest of onboarding, would rather get to that in a polish session across onboarding.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 6 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: I certainly could be wrong, but it looked to me that `denyImportContacts` wasn't actually doing anything. It triggered an action that flipped `askedContactsPermission` in redux state to `true` but as far as I can tell `askedContactsPermission` is not used anywhere. I didn't want to delete without knowing the background. Do you have insight into the context there? 

On second thought, I can see why having `cancelImportContacts` occur on skip is useful for much slower phones. I will add that back. It happens so quickly on my phone it felt useless to have but need to get better at remembering that's not likely to be the norm.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 8 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: Unclear if it's possible in the wild. It was happening pretty frequently while testing so I built it as a catch-all. If you can't think of any instance where this would happen (I can't off top of my head), I am happy to remove it

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 9 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx:111]: I believe it does. We update the ref to the latest instance on every update (line 69)

File: packages/mobile/locales/en-US/onboarding.json (hunk 3 above)
Comment (jmrossy) [reply packages/mobile/locales/en-US/onboarding.json:10]: The importing step is while we literally import and the finding step is while we wait for matchmaking results from PGPNP. Given that they're distinct tasks and I already did the work to dispatch fine-grained status updates, I don't know why we would cut this.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 6 above)
Comment (jmrossy) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: Yeah askedContactsPermission was used in navigator but looks like thats gone now, probably during the big nav update. 
I think that's still useful to track this though in case we want to show different UI for users that saw this and skipped vs never saw it at all.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 8 above)
Comment (jmrossy) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: If it happened, it seems like a bug that we didn't correctly reset the import status before coming here.
It shouldn't ever happen cause you need to get verified before we import contacts? Maybe one edge case is the invite screen? We should just cut that crappy screen IMO haha

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 9 above)
Comment (jmrossy) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx:111]: Ah now I see. so the initial setting of prevImportContactProgressRef on line 34 is not actually the previous. Is the current.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 1 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: I like this approach, thanks!

File: packages/mobile/locales/en-US/onboarding.json (hunk 3 above)
Comment (tarikbellamine) [reply packages/mobile/locales/en-US/onboarding.json:10]: Designs have been updated and I've added it back in. Processing happens too quickly for me to catch it in the screenshots

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 6 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: Gotcha, I will add `denyImportContacts` back into the `onSkip` stuff with the understanding that we may make use of it sometime in the future

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 8 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: I was bumping into it when using the dev verification toggle, which we don't need to worry about in prod.

I think all routes to the Invite screen are being cut off as part of the redesign so I will go ahead and remove this catch-all then.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 9 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx:111]: Yep that's right, similar to how prev props don't really exist on first render

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx (hunk 10 above)
Comment (tarikbellamine) [reply packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx:109]: This is an interesting point. I was working under the assumption that refactoring everything to use hooks was a matter of when not if, so I was doing it every chance I got.

@cmcewen might it be worthwhile to discuss our team philosophy on this?

File: packages/mobile/locales/en-US/onboarding.json (hunk 3 above)
Comment (jmrossy) [reply packages/mobile/locales/en-US/onboarding.json:10]: Yeah on most phones it'll be too fast. On my old Nexus 7 with 2000 contacts it shows for a while.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 11]
```diff
@@ -1,227 +1,222 @@
...
+  const importStatus = importContactsProgress.status
+  const totalContacts = importContactsProgress.total
+  const prevImportContactProgressRef = React.useRef(importContactsProgress)
+  const matchedContacts = useSelector(matchedContactsSelector)
+  const matchedContactsCount = Object.keys(matchedContacts).length
+  const dispatch = useDispatch()
+  const insets = useSafeArea()
+  const headerHeight = useHeaderHeight()
+
+  function renderStatusContainer() {
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: Nit: per our convention, these should be lambdas. Though I would consider pulling this out entirely into its own SFC at the top of the file.

File: packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx [hunk 12]
```diff
@@ -1,227 +1,222 @@
...
+        </View>
+      </View>
+    )
   }
 
-  componentWillUnmount() {
-    if (this.onFinishTimeout) {
-      clearTimeout(this.onFinishTimeout)
-    }
+  function onFinish() {
```
Comment (jmrossy) [inline packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx]: ditto, lamdba

**Review by jmrossy — APPROVED** [review]
Looks good now, thanks! Two nits below
