### PR TITLE
[wip] LinkedList cycle fix

### LINKED ISSUE #913: Users SNBAT create a cycle in LinkedList
### Expected Behavior

In `insert()`, check that `key` is not equal to `previousKey` or `nextKey`

### Current Behavior

Users can create a cycle by setting `previousKey` equal to `key`

### PR DESCRIPTION
**Pull request by mrsmkl**
### Description

Just add the check to make sure that when inserting, the added key cannot be the same as the previous or next key.

### Tested

Added some test files, didn't see any existing test for simple linked lists, and there were already checks for this in the other cases. I still want to add a test that would have actually made a cycle with the previous code.

### Other changes

None

### Related issues

- Fixes #913 

### Backwards compatibility

No effect.

### CODE REVIEW

File: packages/protocol/test/common/linkedlist.ts [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+  describe('#insert()', () => {
+    const NULL_KEY = '0x00'
+    const first_key = '0x01'
+    const keys = ['0x01', '0x02', '0x03']
+    const middle_key = '0x02'
+    const last_key = '0x03'
+    const added_key = '0x04'
+
+    it('should revert if previous is equal to key (empty list)', async () => {
```
Comment (m-chrzan) [inline packages/protocol/test/common/linkedlist.ts]: Nit: Would recommend wrapping these in a `describe('when inserting into an empty list` (or similar wording), and then remove "(empty list)" from these `it` messages.

File: packages/protocol/test/common/linkedlist.ts [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+    it('should revert if next is equal to key (empty list)', async () => {
+      await assertRevert(linkedListTest.insert(added_key, NULL_KEY, added_key))
+    })
+
+    describe('singleton', () => {
+      beforeEach(async () => {
+        await linkedListTest.insert(first_key, NULL_KEY, NULL_KEY)
+      })
+
+      it('should revert if next is equal to key (singleton)', async () => {
```
Comment (m-chrzan) [inline packages/protocol/test/common/linkedlist.ts]: Nit: "(singleton)" not needed since context is already given in the `describe`.

File: packages/protocol/migrationsConfig.js [hunk 3]
```diff
@@ -69,7 +69,7 @@ const DefaultConfig = {
 }
 
 const linkedLibraries = {
-  LinkedList: ['AddressLinkedList', 'SortedLinkedList'],
+  LinkedList: ['AddressLinkedList', 'SortedLinkedList', 'LinkedListTest'],
```
Comment (m-chrzan) [inline packages/protocol/migrationsConfig.js:73]: I think it'd be best if we didn't need to link test contracts in the production migrations. Can this linking be done in a `before` in the Truffle tests?

File: packages/protocol/test/common/linkedlist.ts [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+contract('LinkedListTest', () => {
+  let linkedListTest: LinkedListTestInstance
+
+  beforeEach(async () => {
+    linkedListTest = await LinkedListTest.new()
+  })
+
+  describe('#insert()', () => {
+    const NULL_KEY = '0x00'
+    const first_key = '0x01'
```
Comment (m-chrzan) [inline packages/protocol/test/common/linkedlist.ts]: Style nit: `camelCase` for typescript variables.

**Review by m-chrzan — COMMENTED** [review]
Looks great! Just a few comments to address.

File: packages/protocol/migrationsConfig.js (hunk 3 above)
Comment (mrsmkl) [reply packages/protocol/migrationsConfig.js:73]: I don't think it will have any impact in a production migration (because the test contracts should not be deployed then). Anyway, you can check from this branch what linking inside the testsuite  would look like: https://github.com/mrsmkl/celo-monorepo/compare/linked-list...mrsmkl:linking?expand=1
So one problem is that there is no link property for contracts in Truffle typings. But I can do the same thing for other test contracts too.

**Review by m-chrzan — APPROVED** [review]
