### PR TITLE
Fix changes that lead account:get-metadata to fail

### LINKED ISSUE #4901: celocli @0.0.53 account:get-metadata breaks after updating attestation v1.0.1 to v1.0.2
TLDR: ` blacklistedRegionCodes` is expected but missing in `/status` attestation response. should be added or **not** expected. possibly related to this string from changelog:
*Renamed BLACKLIST config options params to UNSUPPORTED_REGIONS though existing configs are backwards compatible and will work unchanged*

### Expected Behavior

```
# celocli account:get-metadata $CELO_VALIDATOR1_RG_ADDRESS 
Metadata contains the following claims: 

Type                    Value                          Status Created At   
ATTESTATION_SERVICE_URL URL: https://agx1att.agx10k.ml Valid! 4 months ago 
```

### Current Behavior
```
# celocli account:get-metadata $CELO_VALIDATOR1_RG_ADDRESS | less -R
Metadata contains the following claims: 

Type                    Value                          Status                                                                                                                                                                    Created At   
ATTESTATION_SERVICE_URL URL: https://agx1att.agx10k.ml Invalid: Response from https://agx1att.agx10k.ml/status?messageToSign=0x315d8d188c38883d3e693f19ea9b30ef7f9b58fb3b7d3b87513df711a354f366 could not be parsed successfully 4 months ago 
```

comparing `curl` output looks like this:
v1.0.3:
```
# curl -s 'https://agx1att.agx10k.ml/status?messageToSign=0xa8ab2d666d6542ea10f0c5509bbcfe3e6d47df33ce1e10b6b9b7682b2104dd00'  | jq
{
  "status": "ok",
  "smsProviders": [
    "twilio"
  ],
  "accountAddress": "0x943e9a5c750adcc467575F4fE81bf6b1C3A2aeD7",
  "signature": "0xeb88d4ab82e14098cff11c7e7daa191fdcc8a0e170e82e014c2187a863dfc0812405af189ed35456d578f8492bdad7d98fcead0aca968e36f97563d384de3be91b",
  "version": "1.0.3",
  "latestBlock": 2250122,
  "ageOfLatestBlock": 0.8010001182556152,
  "isNodeSyncing": false,
  "appSignature": "unknown"
}
```
v1.0.1
```
# curl -s 'https://agx1att.agx10k.ml/status?messageToSign=0xa8ab2d666d6542ea10f0c5509bbcfe3e6d47df33ce1e10b6b9b7682b2104dd00'  | jq
{
  "status": "ok",
  "smsProviders": [
    "twilio"
  ],
  "blacklistedRegionCodes": [],
  "accountAddress": "0x943e9a5c750adcc467575F4fE81bf6b1C3A2aeD7",
  "signature": "0xeb88d4ab82e14098cff11c7e7daa191fdcc8a0e170e82e014c2187a863dfc0812405af189ed35456d578f8492bdad7d98fcead0aca968e36f97563d384de3be91b",
  "version": "1.0.1",
  "latestBlock": 2250133,
  "ageOfLatestBlock": 4.516999959945679,
  "isNodeSyncing": false,
  "appSignature": "unknown"
}
```

### PR DESCRIPTION
**Pull request by timmoreton**
### Description

A backwards incompatible change was introduced in #4585 to `AttestationServiceStatusResponse` that causes existing versions of the cli to be unable to parse status responses from new versions of Attestation Service 1.0.{2,3}. 

This PR:

* re-adds the missing field to Attestation Service's `/status` response so existing versions of the CLI will work when this is released (1.0.4).

* will allow new versions of the CLI to parse the response from existing, not yet upgraded Attestation Services 

### Tested

Before:

```
tim@Tims-MacBook-Pro cli % celocli account:get-metadata 0x9ea3f9130E7e5Df7D553cc311687bdE0c3d88822
 ›   Warning: @celo/celocli update available from 0.0.52 to 0.0.53.
Metadata contains the following claims:
Type                    Value                                                                                            Status                                   Created At
ACCOUNT                 {"timestamp":1591421683,"type":"ACCOUNT","address":"0xFA592ae90E407Da044602342625AAABBF5d50C22"} Verified!                                3 months ago
ATTESTATION_SERVICE_URL URL: https://celo-attester-prod-us-west-2.alphavirtual.com/                                      Invalid: Response from https://celo-att… 3 months ago
NAME                    Name: "Alpha Virtual Oregon"                                                                     N/A                                      22 days ago
```

After:

```
tim@Tims-MacBook-Pro cli % bin/run account:get-metadata 0x9ea3f9130E7e5Df7D553cc311687bdE0c3d88822
Metadata contains the following claims:

Type                    Value                                                                                            Status    Created At
ACCOUNT                 {"timestamp":1591421683,"type":"ACCOUNT","address":"0xFA592ae90E407Da044602342625AAABBF5d50C22"} Verified! 3 months ago
ATTESTATION_SERVICE_URL URL: https://celo-attester-prod-us-west-2.alphavirtual.com/                                      Valid!    3 months ago
NAME                    Name: "Alpha Virtual Oregon"                                                                     N/A       22 days ago
```

and on the server, local /status endpoint has correct structure.

### Related issues

- Fixes #4901 

### Backwards compatibility

As above.

### CODE REVIEW

File: packages/attestation-service/src/requestHandlers/status.ts [hunk 1]
```diff
@@ -34,6 +34,7 @@ export async function handleStatusRequest(
         AttestationServiceStatusResponseType.encode({
           status: 'ok',
           smsProviders: configuredSmsProviders(),
+          blacklistedRegionCodes: [],
```
Comment (aslawson) [inline packages/attestation-service/src/requestHandlers/status.ts]: add comment "for backwards compatability"

**Review by aslawson — APPROVED** [review]

**Review by jmrossy — APPROVED** [review]
LGTM!
