### PR TITLE
Audit timeout and responses

### LINKED ISSUE #9845: Audit timeout logic
- Signer timeout logic is sketchy
  - even though the signer will now respond with a 500, it tries to also send an additional response if it does complete its logic (i.e. can timeout, send that response, and then log that it has tried to send a different success/failure response)
  - timeout errors don't roll back DB transactions (would need to move the timeouts into the db transactions for this to happen)
- Consider whether it makes sense to remove the endpoint timeout logic, and push this handling to the requester (since the combiner already also implements its own signer timeout logic) as well as the `perform` functions themselves where trxs can be rolled back
- Audit the combiner timeouts & its handling of signer timeout logic

Output could be: 
- removing timeout logic and explanation of why

### LINKED ISSUE #9859: Audit combiner and signer endpoint error handling
Audit how we are sending responses & handling errors in the signer.
- Ensure that we are catching and responding to errors or handing off errors to Express's error handlers
- Likely add test cases for generic errors being thrown in unexpected places.
- Ensure that when returning failures, processes do not continue & do not attempt to send multiple responses (io is disconnected from performance; `perform` needs to return once errors have been reached as well -- ideally restructure like with the domain endpoints as this is cleaner)
  - seems like this may be an issue in the `quotaStatus` endpoint -- seems to be (in some test case) throwing an `ERR_HTTP_HEADERS_SENT` error in the controller after sending the first response; ensure that this is investigated and fixed

### PR DESCRIPTION
**Pull request by eelanagaraj**
### Changes
- moves `timeout` errors in signer from outer endpoint handler -> actions, so that timeout errors will roll back DB transactions (as opposed to allowing a process to continue after a timeout error has been thrown/responded to the user, and then charging quota)
  - moves timeout error handling into the controller class
- adds outer error-handling in the server for the combiner & signer (& logs errors where responses are sent multiple times)
- standardizes some error handling in controller (propagates more error messages when standard `ErrorMessages` or `WarningMessages` are thrown); this address some of celo-org/social-connect#17 though does not fully fix everything in that ticket
  - in order to do this, updates DB errors to throw standard errors based on the message (i.e. DATABASE_GET_FAILURE)
- adds/updates unit tests for DB errors & timeouts being thrown

### Related issues

- Fixes celo-org/celo-monorepo#9859
- Fixes celo-org/celo-monorepo#9845

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/phone-number-privacy/combiner/src/server.ts [hunk 1]
```diff
@@ -170,11 +170,21 @@ export async function meterResponse(
       logger.info({ res }, 'Response sent')
     })
     .catch((err) => {
-      logger.error(ErrorMessage.UNKNOWN_ERROR)
-      logger.error(err)
+      logger.error({ err }, 'Caught error in outer endpoint handler')
+      if (!res.finished && !res.headersSent) {
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/combiner/src/server.ts]: I'm still looking into exactly why typescript thinks the combiner/signer are using slightly different versions of express Responses. In the signer, it's slightly newer and has the `writableEnded` property available (while `finished` is deprecated), but not the case in the combiner.

File: packages/phone-number-privacy/combiner/test/unit/domain-response-logger.test.ts [hunk 2]
```diff
@@ -309,7 +309,6 @@ describe('domain response logger', () => {
   ]
   testCases.forEach((testCase) => {
     it(testCase.it, () => {
-      console.log(testCase.responses)
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/combiner/test/unit/domain-response-logger.test.ts:312]: happy to re-add if this was intentionally left in!!

File: packages/phone-number-privacy/combiner/src/server.ts [hunk 3]
```diff
@@ -170,11 +170,21 @@ export async function meterResponse(
       logger.info({ res }, 'Response sent')
     })
     .catch((err) => {
-      logger.error(ErrorMessage.UNKNOWN_ERROR)
-      logger.error(err)
+      logger.error({ err }, 'Caught error in outer endpoint handler')
```
Comment (eelanagaraj) [inline packages/phone-number-privacy/combiner/src/server.ts]: note: after investigating that weird req/res type discrepancy, this handling is the same in the signer/combiner; happy to extract this into a function in the common package though also not really sure it's super necessary. No strong opinion here!

File: packages/phone-number-privacy/signer/src/common/action.ts [hunk 4]
```diff
@@ -17,5 +17,5 @@ export type Session<R extends OdisRequest> = R extends DomainRequest
 export interface Action<R extends OdisRequest> {
   readonly config: SignerConfig
   readonly io: IO<R>
-  perform(session: Session<R>): Promise<void>
+  perform(session: Session<R>, timeoutError: symbol): Promise<void>
```
Comment (alecps) [inline packages/phone-number-privacy/signer/src/common/action.ts:20]: Out of curiosity, could / should this be 'timeoutError: unique symbol' ?

File: packages/phone-number-privacy/signer/src/server.ts [hunk 5]
```diff
@@ -60,35 +58,25 @@ export function startSigner(
...
-        let errorMsg: string = ErrorMessage.UNKNOWN_ERROR
-        let errToLog = err
-        if (err === timeoutRes) {
-          Counters.timeouts.inc()
-          errorMsg = ErrorMessage.TIMEOUT_FROM_SIGNER
-          errToLog = new Error(errorMsg)
-        }
-        childLogger.error({ errToLog })
-        if (!res.writableEnded) {
+        childLogger.error({ err }, 'Caught error in outer endpoint handler')
```
Comment (alecps) [inline packages/phone-number-privacy/signer/src/server.ts]: I left a comment in the combiner about adding an ErrorMessage so we can enable log based metrics here. It would be good to log that same error message here, even though the signer monitoring setup doesn't use log based metrics. Could you also create a prometheus metric so we can alert on this for the signer as well?

File: packages/phone-number-privacy/combiner/src/server.ts (hunk 3 above)
Comment (alecps) [reply packages/phone-number-privacy/combiner/src/server.ts]: I agree it's probably not super necessary. This seems like a reasonable place to have duplicate code

Comment (alecps) [inline packages/phone-number-privacy/combiner/src/server.ts]: I could imagine us wanting to set up monitoring and alerting for this. Could you create an ErrorMessage so we can have log based metrics here?

**Review by alecps — APPROVED** [review]
😮‍💨

File: packages/phone-number-privacy/signer/src/common/action.ts (hunk 4 above)
Comment (eelanagaraj) [reply packages/phone-number-privacy/signer/src/common/action.ts:20]: i don't think so :-/ seems to be reserved for static readonly properties which would then need to be defined and set at instantiation time (i.e. in the server class, can't be passed in at runtime from the Controller)

File: packages/phone-number-privacy/signer/src/server.ts (hunk 5 above)
Comment (eelanagaraj) [reply packages/phone-number-privacy/signer/src/server.ts]: yup good idea!
