### PR TITLE
[Wallet] Exchange flow formatting fixes

### LINKED ISSUE #731: Exchange textbox content height is different than placeholder
### Expected Behavior

When there is content inside the textbox, the numbers/dollar sign should be the same height as the placeholder & centered vertically with the text cursor

### Current Behavior

Found on a Pixel 3, API 28, target Android 9.0 (Google APIs)

Placeholder text is in the correct height:
Screen Shot 2019-08-27 at 10 33 40 AM

But when there is real content, the text is shifted higher:
Screen Shot 2019-08-27 at 10 33 51 AM

### LINKED ISSUE #890: Small dollar -> gold exchanges show 0 gold
tmp1

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

- Fix handling of small amounts in exchanges
- Enforce a minimum amount to proceed
- Fix some style issues in exchange flow
- Improve typing in and around exchange flow

The formatting and display of currencies could be further de-duped. Made an issue to track:
https://github.com/celo-org/celo-monorepo/issues/962

### Tested

Ran through exchange flow

### Related issues

- Fixes #890 
- Fixes #731 

### Backwards compatibility

Yes

wa-exchange-allowed
wa-exchange-confirmation

### CODE REVIEW

File: packages/mobile/src/components/AccountOverview.tsx [hunk 1]
```diff
@@ -90,7 +91,7 @@ export class AccountOverview extends React.Component<Props> {
                 style={[style.education, !this.props.stableEducationCompleted && style.dotOffset]}
               >
                 <CurrencyDisplay
-                  amount={dollarBalance}
+                  amount={new BigNumber(dollarBalance || 0)}
```
Comment (jeanregisser) [inline packages/mobile/src/components/AccountOverview.tsx]: This makes `<CurrencyDisplay />` re-render every time this component is rendered. I don't think it's a problem. just noting it.

Comment (jeanregisser) [inline packages/mobile/src/components/AccountOverview.tsx:94]: This makes `<CurrencyDisplay />` re-render every time this component is rendered. I don't think it's a problem. just noting it.

File: packages/mobile/src/components/CurrencyDisplay.tsx [hunk 2]
```diff
@@ -28,7 +29,8 @@ export default class CurrencyDisplay extends React.PureComponent<Props> {
       transform: [{ translateY: Math.round(size * 0.1) }],
     }
   }
-  amount() {
+
+  getAmount() {
     return this.props.amount == null ? '0.00' : getMoneyDisplayValue(this.props.amount || 0)
```
Comment (jeanregisser) [inline packages/mobile/src/components/CurrencyDisplay.tsx]: amount can't be null anymore. This could be simplified to only `getMoneyDisplayValue(this.props.amount)`.

File: packages/mobile/src/config.ts [hunk 3]
```diff
@@ -62,3 +62,6 @@ export const LOCAL_CURRENCY_SYMBOL = Config.LOCAL_CURRENCY_SYMBOL || null
 
 // The number of seconds before the sender can reclaim the payment.
 export const ESCROW_PAYMENT_EXPIRY_SECONDS = 172800 // 2 days
+
+// The minimum allowed value for a transaction such as a transfer or exchange
+export const TRANSACTION_MIN_AMOUNT = 0.01
```
Comment (jeanregisser) [inline packages/mobile/src/config.ts]: Why `0.01`?

File: packages/mobile/src/exchange/ExchangeConfirmationCard.tsx [hunk 4]
```diff
@@ -39,66 +53,52 @@ class ExchangeConfirmationCard extends React.PureComponent<Props> {
...
         </View>
 
         <View style={styles.title}>
-          <ExchangeRate rate={this.exchangeRateToDisplay()} makerToken={this.props.token} />
+          <ExchangeRate rate={this.getExchangeRate()} makerToken={token} />
         </View>
 
-        {shouldRenderBalance && this.renderNewBalances(newDollarBalance, newGoldBalance)}
+        {!!newDollarBalance &&
+          !!newGoldBalance &&
```
Comment (jeanregisser) [inline packages/mobile/src/exchange/ExchangeConfirmationCard.tsx]: nit: `!!` is not necessary here since we're not dealing with strings

File: packages/mobile/src/exchange/ExchangeTradeScreen.tsx [hunk 5]
```diff
@@ -17,10 +17,11 @@ import CeloAnalytics from 'src/analytics/CeloAnalytics'
 import { CustomEventNames, DefaultEventNames } from 'src/analytics/constants'
 import componentWithAnalytics from 'src/analytics/wrapper'
 import { ErrorMessages } from 'src/app/ErrorMessages'
+import { TRANSACTION_MIN_AMOUNT } from 'src/config'
 import { fetchExchangeRate } from 'src/exchange/actions'
 import ExchangeRate from 'src/exchange/ExchangeRate'
 import { ExchangeRatePair } from 'src/exchange/reducer'
-import { CURRENCIES, CURRENCY_ENUM as Token } from 'src/geth/consts'
+import { CURRENCIES, CURRENCY_ENUM as Tokens } from 'src/geth/consts'
```
Comment (jeanregisser) [inline packages/mobile/src/exchange/ExchangeTradeScreen.tsx]: Maybe we should rename CURRENCY_ENUM globally?

File: packages/mobile/src/exchange/ExchangeTradeScreen.tsx [hunk 6]
```diff
@@ -130,75 +131,98 @@ export class ExchangeTradeScreen extends React.Component<Props, State> {
...
       return ''
     }
   }
 
-  render() {
+  getMakerTakerProps = () => {
     const { t } = this.props
+    const dollarProps = {
+      token: Tokens.DOLLAR,
+      tokenText: t('global:celoDollars') + ' (cUSD)',
```
Comment (jeanregisser) [inline packages/mobile/src/exchange/ExchangeTradeScreen.tsx:192]: We should avoid programmatically concatenating user facing strings. This makes it impossible to correctly translate this in languages that use a different order.

File: packages/mobile/src/utils/formatting.ts [hunk 7]
```diff
@@ -1,12 +1,22 @@
...
+  value: BigNumber.Value,
+  currency: CURRENCY_ENUM = CURRENCY_ENUM.DOLLAR,
+  includeSymbol: boolean = false
+): string => {
+  const decimals = CURRENCIES[currency].displayDecimals
+  const symbol = CURRENCIES[currency].symbol
+  const formattedValue = numeral(roundDown(value, decimals).toNumber()).format(
+    '0,0.' + '0'.repeat(decimals)
+  )
+  return includeSymbol ? symbol + formattedValue : formattedValue
```
Comment (jeanregisser) [inline packages/mobile/src/utils/formatting.ts:19]: nit: This will be wrong on some locales. Here for instance the symbol is expected to be after the number.

**Review by jeanregisser — COMMENTED** [review]
Looks mostly good! Main question is why limiting to minimum 0.01 transfers? Does this apply to exchanges too?

**Comment by jeanregisser** [comment]
I noticed the entered amount is not vertically centered with the TextInput and cursor in the exchange screen.

File: packages/mobile/src/exchange/ExchangeConfirmationCard.tsx [hunk 8]
```diff
@@ -6,28 +6,42 @@ import { withNamespaces, WithNamespaces } from 'react-i18next'
 import { StyleSheet, Text, View } from 'react-native'
 import CurrencyDisplay from 'src/components/CurrencyDisplay'
 import ExchangeRate from 'src/exchange/ExchangeRate'
-import { CURRENCY_ENUM } from 'src/geth/consts'
+import { CURRENCY_ENUM, CURRENCY_ENUM as Tokens } from 'src/geth/consts'
```
Comment (annakaz) [inline packages/mobile/src/exchange/ExchangeConfirmationCard.tsx]: Is there any reason to use both `CURRENCY_ENUM` and  the`Tokens` alias in the same file?

Comment (annakaz) [reply packages/mobile/src/exchange/ExchangeConfirmationCard.tsx]: We should decide on consistent `CURRENCY_ENUM` vs `Tokens` usage then rename throughout

File: packages/mobile/src/config.ts (hunk 3 above)
Comment (jmrossy) [reply packages/mobile/src/config.ts]: This is just the desired behavior for now

File: packages/mobile/src/exchange/ExchangeTradeScreen.tsx (hunk 5 above)
Comment (jmrossy) [reply packages/mobile/src/exchange/ExchangeTradeScreen.tsx]: Yes, considered it but should be a separate PR

File: packages/mobile/src/exchange/ExchangeTradeScreen.tsx (hunk 6 above)
Comment (jmrossy) [reply packages/mobile/src/exchange/ExchangeTradeScreen.tsx:192]: Agreed. Not new logic though, just moved it around

File: packages/mobile/src/utils/formatting.ts (hunk 7 above)
Comment (jmrossy) [reply packages/mobile/src/utils/formatting.ts:19]: Good point but we can cross that bridge when we come to it. This PR doesn't worsen any of our i18n issues, in fact it will make it easier to fix by centralizing the formatting in one place

File: packages/mobile/src/components/AccountOverview.tsx (hunk 1 above)
Comment (jmrossy) [reply packages/mobile/src/components/AccountOverview.tsx:94]: Noted, thanks.

File: packages/mobile/src/exchange/ExchangeConfirmationCard.tsx (hunk 8 above)
Comment (jmrossy) [reply packages/mobile/src/exchange/ExchangeConfirmationCard.tsx]: Nope, just a mistake! Will fix.
I'll align to CURRENCY_ENUM in this PR and open another to rename more broadly

File: packages/mobile/src/exchange/ExchangeConfirmationCard.tsx (hunk 4 above)
Comment (jmrossy) [reply packages/mobile/src/exchange/ExchangeConfirmationCard.tsx]: Fixed

File: packages/mobile/src/utils/formatting.ts (hunk 7 above)
Comment (jeanregisser) [reply packages/mobile/src/utils/formatting.ts:19]: Yep! 👍

**Comment by jmrossy** [comment]
> I noticed the entered amount is not vertically centered with the TextInput and cursor in the exchange screen.

Already fixed, just an outdated screenshot sorry

**Review by jeanregisser — APPROVED** [review]
Nice! 👍
