### PR TITLE
[Wallet] Fix exchange input on iOS and feed item display

### LINKED ISSUE #2181: Currency Name is not shown for transaction activity other than the exchange activity in “Activity” Section when user has selected currency other than USD.
**Frequency:** 100%
**App version:** Staging build v1.5.2
**Does not repro:** Play store build v1.5.2. 
**Repro on:** Samsung Galaxy Note 5 (7.0), Samsung Galaxy s5 (6.0.1)  

**Pre-condition:** User must have Exchange activity in Activity section. 

**Repro Steps:** 
1) Launch the app. 
2) Tap on Cog icon. 
3) Tap on Currency option. 
4) select a currency other than the USD. 
5) Navigate back to wallet tab. 
6) Observed. 

**Impact:** Inconsistency in the Activity section as currency name is shown for only exchange activity/transaction, not for other transactions. 

**Investigation:**
 1. Issue does not repro when USD currency is selected
2. Issue does not repro for other activities such as Sent transaction,Received transactions, Verification fee.  

**Current Behavior:** Currency name is shown for exchange activity. 
**Expected Behavior:** Currency name should not display for only one activity
**Attachment:** Android_ExchangeActivityIssue.png
Android_ExchangeActivityIssue

### LINKED ISSUE #2309: Entered amount is hidden on “Amount Gold” field from “Buy and Sell Gold” screen
**Frequency:** 100%
**App version:** IOS test flight build v1.5.2 (17)
**Repro on:** iPhone 7 (13.3), iPhone XS Max (13.2), iPhone 7+ (12.4)

**Repro Steps:** 
1) Launch the app. 
2) Tap on the Gold tab. 
3) Tap on either the Bug or sell button. 
4) Enter an amount on the “Amount Gold” field. 
5) Observed. 

**Impact** User may 
**Current Behavior:** Entered amount is hidden. 
**Expected Behavior:** Enter the amount should be shown. 
**Attachment:** [IOS_AmuntNotShownGoldTab.mov ](https://drive.google.com/file/d/1AskhGi-oVyYYshg1--hAwrBvVLM-jH3N/view?usp=sharing) (Bug observed at 07  sec)

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Exchange input wasn't displaying correctly on iOS.

### Tested

**Before**

exchange-input-bug-ios

**After**

exchange-input-fixed-ios

### Other changes

- Don't show currency code for exchange items to be consistent with the other items.

**Before**

image

**After**

image

### Related issues

- Fixes #2309
- Fixes #2181

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/exchange/ExchangeTradeScreen.tsx [hunk 1]
```diff
@@ -226,54 +226,44 @@ export class ExchangeTradeScreen extends React.Component<Props, State> {
...
+              keyboardType={'decimal-pad'}
+              onChangeText={this.onChangeExchangeAmount}
+              value={this.getInputValue()}
+              placeholderTextColor={'#BDBDBD'}
+              placeholder={'0'}
+              style={styles.currencyInput}
+            />
+          </View>
+          <HorizontalLine />
+          {/* <View style={styles.line} /> */}
```
Comment (jmrossy) [inline packages/mobile/src/exchange/ExchangeTradeScreen.tsx:256]: Nit, cleanup

**Review by jmrossy — APPROVED** [review]
