### PR TITLE
Fixing a check for validator:deregister

### LINKED ISSUE #2993: celocli validator:deregister is throwing an unexpected error
### Expected Behavior

call: `celocli validator:deregister --from <address>`
Should either succeed or print out reasonable error message

### Current Behavior

```
celocli validator:deregister --from 2d95969046f762ac370a2d31e53210e65b1d8698
Running Checks:
   ✔  2d95969046f762ac370a2d31e53210e65b1d8698 is Signer or registered Account 
   ✔  Signer can sign Validator Txs 
   ✔  Signer account is Validator 
Error: overflow (operation="setValue", fault="overflow", details="Number can only safely store up to 53 bits")
    at Object.throwError (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:17)
    at BigNumber.toNumber (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/node_modules/ethers/utils/bignumber.js:169:20)
    at ~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:643:78
    at Array.forEach (<anonymous>)
    at unpack (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:640:12)
    at CoderTuple.decode (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:767:22)
    at AbiCoder.decode (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:912:61)
    at ABICoder.decodeParameters (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/src/index.js:229:30)
    at Contract._decodeMethodReturn (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-core-method/src/index.js:473:33)
    at ~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:147:9
    at callbackDecorator (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.18.1/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```

```
celocli --version
@celo/celocli/0.0.35-baklava2 linux-x64 node-v10.18.1

Docker image: us.gcr.io/celo-testnet/celo-node (ImageID: bec34c412cff, Geth 1.9)
```

### PR DESCRIPTION
**Pull request by mrsmkl**
### Description

There was an error in the checks I added last time.
Added an extra case for non-affiliated validators.

### Tested

Checked the case where error occurred.

### Related issues

- Fixes #2993

### CODE REVIEW

File: packages/cli/src/utils/checks.ts [hunk 1]
```diff
@@ -323,6 +323,9 @@ class CheckBuilder {
       `Account isn't a member of a validator group`,
       this.withValidators(async (v, _signer, account) => {
         const { affiliation } = await v.getValidator(account)
+        if (eqAddress(affiliation!, NULL_ADDRESS)) {
```
Comment (nategraf) [inline packages/cli/src/utils/checks.ts]: What is the result if affiliation is `null`? Based on some of the code in the Validator contracts wrapper, the following seems reasonable.
```suggestion
        if (!affiliation || eqAddress(affiliation, NULL_ADDRESS)) {
```

**Review by nategraf — APPROVED** [review]
Looks good overall. Once comment about an edge case.
