### PR TITLE
[Wallet] fix attestation codes being wrongly set as completed

### LINKED ISSUE #4477: Error processing attestation code :: No issuer found for attestion code
### Expected Behavior

Users able to complete verification

### Current Behavior

One of the three text messages resulted in this error.

`Info [2020-07-16T17:14:11.355Z] identity/verification@attestationCodeReceiver :: Error processing attestation code :: No issuer found for attestion code in index.android.bundle:1884:11497`

Can provide more specific information if needed

### PR DESCRIPTION
**Pull request by i1skn**
### Description

Fix a bug, described in details here - https://github.com/celo-org/celo-monorepo/issues/4477#issuecomment-665275466

### Other changes

* Remove error toast, when verification fails, cause we show Modal instead.
* Fix a bug, when user presses `Enter Codes` on the error modal but nothing happens until timer has elapsed.

### Tested

iOS simulator

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/4477

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/identity/actions.ts [hunk 1]
```diff
@@ -69,14 +70,19 @@ export interface ReceiveAttestationMessageAction {
   inputType: CodeInputType
 }
 
+export interface SetCompletedCodes {
```
Comment (jmrossy) [inline packages/mobile/src/identity/actions.ts]: Should be `SetCompletedCodesAction` or `SetNumCompletedCodesAction`

File: packages/mobile/src/redux/migrations.ts [hunk 2]
```diff
@@ -54,4 +54,13 @@ export const migrations = {
       },
     }
   },
+  4: (state: any) => {
```
Comment (jmrossy) [inline packages/mobile/src/redux/migrations.ts:57]: Please make a test for this new migration in `migrations.test.ts`

**Review by jmrossy — COMMENTED** [review]
LGTM, see two minor comments below

File: packages/mobile/src/redux/migrations.ts [hunk 3]
```diff
@@ -54,4 +54,13 @@ export const migrations = {
...
+    return {
+      ...state,
+      identity: {
+        ...state.identity,
+        acceptedAttestationCodes: [],
+      },
+    }
+  },
```
Comment (jeanregisser) [inline packages/mobile/src/redux/migrations.ts:65]: Not super important but I think we should also update the test schema to avoid confusion.
https://github.com/celo-org/celo-monorepo/blob/52d5de63a990d3bb5dbf8333b59722e489f1588a/packages/mobile/test/schemas.ts#L332
I saw `v3Schema` was missing and added it in https://github.com/celo-org/celo-monorepo/pull/4545/files#diff-2d8d77f9d884fa463eafd5c95a7cb7d0

What do you think?

**Review by jeanregisser — COMMENTED** [review]
Looks great to me! 👍 
I'll let people with a deeper understanding of the verification do the actual approval 👀

File: packages/mobile/src/redux/migrations.ts (hunk 3 above)
Comment (i1skn) [reply packages/mobile/src/redux/migrations.ts:65]: I think, if we treat migration as something, which could update only the data and keep the schema untouched, we should only update the schema when it was really changed. So migration number and schema are disconnected. wdyt?

**Review by jmrossy — APPROVED** [review]

File: packages/mobile/src/redux/migrations.ts (hunk 3 above)
Comment (jeanregisser) [reply packages/mobile/src/redux/migrations.ts:65]: Yep!

**Review by aslawson — COMMENTED** [review]
nice work! 🙌
