### PR TITLE
[Wallet]: Update radio button to new design 

### LINKED ISSUE #6270: Update CICO radio button component with new design
New designs available on [Figma](https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=3005%3A42941)
If link doesn't work, it's in Wallet Refresh > Pages: Design Kit > Frame labelled "UI Controls"

Screen Shot 2020-12-16 at 11 38 18 AM

### PR DESCRIPTION
**Pull request by michellewong793**
### Description

Current Behavior: The CheckCircle component is used to signify a selected item in the Settings page. This PR replaces the CheckCircle component with a file called RadioButton.tsx to better reflect the updated designs to be closer to what we have in the currentt design system.  

-Changes the CheckCircle.tsx file to RadioButton.tsx 
-Updates accordingly in files where CheckCircle was used 

### Other changes
Updates that RadioButton receives the "disabled" property from parent. This was an error that Cal caught! Fixed it up to make sure that the circle appears to be Disabled, rather than Unselected. 
Deletes circle styles defined in SelectionOption component 
Updates how RadioButton styles works 

### Tested

image

Will also test on Android 
### Related issues

- Fixes #6270

### Backwards compatibility

These are the only places so far that use this component, so it should be backwards compatible!

### CODE REVIEW

File: packages/react-components/icons/CheckCircle.tsx [hunk 1]
```diff
@@ -9,8 +9,8 @@ interface Props {
 
 export default class CheckCircle extends React.PureComponent<Props> {
   static defaultProps = {
```
Comment (gnardini) [inline packages/react-components/icons/CheckCircle.tsx]: This class is called `CheckCircle` but it's not a check anymore :P Also, there's a radio button that looks just like this one called `RadioIcon` on `src/icons/RadioIcon.tsx` maybe we can leave just one of these?

Comment (michellewong793) [reply packages/react-components/icons/CheckCircle.tsx]: hahaha :P i was gonna name it "RadioButton" oh dang - I'll delete one of them!

File: packages/react-components/components/SelectionOption.tsx [hunk 2]
```diff
@@ -33,7 +32,7 @@ export default function SelectionOption({
           <View style={styles.iconContainer}>
             {/* TODO: make proper checkbox */}
             {!isSelected && <View style={styles.circle} />}
-            {isSelected && <CheckCircle />}
+            {isSelected && <RadioButton />}
```
Comment (tarikbellamine) [inline packages/react-components/components/SelectionOption.tsx]: It looks like you forgot to import `RadioButton` into this file

**Review by tarikbellamine — COMMENTED** [review]
Left one comment but there are a few other things to consider:
1. You deleted `RadioIcon.tsx` but it looks like it's still being used in `FiatExchangeOptions.tsx`. You'll probably also want to replace that with your new `RadioButton.tsx` file or you'll run into more build errors
2. When you make UI changes like this, you need to update the test snapshots or you'll get CI test errors. To do this run `yarn test -u` from the `/mobile` directory and the `/react-components` directory (the `-u` flag is what tells jest to update snapshots)
3. Please make sure you are following proper PR hygiene. Make sure your PRs description is always updated after new commits (e.g., you made the naming change so make sure to update your description to reflect that). Also be sure to add the `wallet` tag and use `celo-org/wallet` for reviewers so that the whole team knows it needs review :)

File: packages/react-components/components/SelectionOption.tsx (hunk 2 above)
Comment (michellewong793) [reply packages/react-components/components/SelectionOption.tsx]: thanks!

File: packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx [hunk 3]
```diff
@@ -18,7 +18,7 @@ import { KOTANI_URI, PONTO_URI, SIMPLEX_URI } from 'src/config'
 import FundingEducationDialog from 'src/fiatExchanges/FundingEducationDialog'
 import i18n, { Namespaces } from 'src/i18n'
 import InfoIcon from 'src/icons/InfoIcon'
-import RadioIcon from 'src/icons/RadioIcon'
+import RadioButton from 'src/icons/RadioButton'
```
Comment (tarikbellamine) [inline packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx]: Importing from the wrong place. Should be `@celo/react-components/components/RadioButton`. Look at the file path for the file you created ;)

**Review by tarikbellamine — COMMENTED** [review]
Getting closer. Left another comment...I also don't think you've uploaded new snapshots?

File: packages/react-components/icons/RadioButton.tsx [hunk 4]
```diff
@@ -0,0 +1,30 @@
+import colors from '@celo/react-components/styles/colors'
+import * as React from 'react'
+import Svg, { Circle } from 'svgs'
+
+interface Props {
+  height?: number
+  color?: string
+}
```
Comment (jeanregisser) [inline packages/react-components/icons/RadioButton.tsx]: This won't pass TypeScript build phase as it doesn't support the `enabled` property which is used in some places.

Comment (michellewong793) [reply packages/react-components/icons/RadioButton.tsx]: do you mean the `selected` property of RadioButton? :o

File: packages/react-components/icons/RadioButton.tsx [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+  render() {
+    return (
+      <Svg
+        xmlns="http://www.w3.org/2000/svg"
+        height={this.props.height}
+        width={this.props.height}
+        viewBox="0 0 20 20"
+      >
+      <Circle cx="10" cy="10" r="9" stroke={this.props.disabled ? colors.gray2 : this.props.color} strokeWidth={2} />  
+      {this.props.selected ? <Circle cx="10" cy="10" r="6" fill={this.props.color} /> : <View style={styles.circle} />
```
Comment (tarikbellamine) [inline packages/react-components/icons/RadioButton.tsx]: Could you do something even more simple here and just have a conditional for the `fill` property? Something like: `fill = {this.props.selected ? this.props.color : undefined}`

File: packages/react-components/components/SelectionOption.tsx [hunk 6]
```diff
@@ -63,8 +61,8 @@ const styles = StyleSheet.create({
   },
   circle: {
```
Comment (tarikbellamine) [inline packages/react-components/components/SelectionOption.tsx]: This can be deleted now right?

File: packages/react-components/icons/RadioButton.tsx [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+  },
+})
+
+export default class RadioButton extends React.PureComponent<Props> {
+  static defaultProps = {
+    width: 20,
+    height: 20,
+    color: colors.greenUI,
+    selected: true, 
+    disabled: false,
```
Comment (tarikbellamine) [inline packages/react-components/icons/RadioButton.tsx:31]: I don't see how disabled is being incorporated into the component yet. Shouldn't this impact the Svg somehow?

File: packages/react-components/icons/RadioButton.tsx (hunk 5 above)
Comment (tarikbellamine) [reply packages/react-components/icons/RadioButton.tsx]: I think `stroke` would have to change too actually...but still think that's more simple than rendering a `View` circle with all it's own styling and sizing

File: packages/react-components/components/SelectionOption.tsx (hunk 6 above)
Comment (michellewong793) [reply packages/react-components/components/SelectionOption.tsx]: yep

File: packages/react-components/icons/RadioButton.tsx (hunk 5 above)
Comment (michellewong793) [reply packages/react-components/icons/RadioButton.tsx:45]: mm sure, i can try something out! that makes sense

Comment (michellewong793) [reply packages/react-components/icons/RadioButton.tsx]: i think it's actually a little simpler to keep it as is, since we are also keeping track of whether or not something is `disabled` for the stroke. It gets a little complicated since the stroke also changes if the RadioButton is disabled haha. Do you have something specific in mind?

File: packages/react-components/icons/RadioButton.tsx [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+    borderColor: colors.gray4,
+  },
+})
+
+export default class RadioButton extends React.PureComponent<Props> {
+  static defaultProps = {
+    width: 20,
+    height: 20,
+    color: colors.greenUI,
+    selected: true,
```
Comment (tarikbellamine) [inline packages/react-components/icons/RadioButton.tsx]: This should probably default to `false`

File: packages/react-components/icons/RadioButton.tsx (hunk 5 above)
Comment (gnardini) [reply packages/react-components/icons/RadioButton.tsx]: The following are not crucial by any means, I just believe these things help with readability and robustness:

- Defining things only once and reusing (color variable):

On `RadioIcon` we had this line instead: `{selected && <Circle cx="10" cy="10" r="6" fill={color} />}`. `color` was defined as `const color = selected ? colors.greenUI : colors.gray3` which in this case could be changed to `const color = selected ? props.color : colors.gray3` to achieve the same result.

I did notice that the outer circle is using `colors.gray2` but the inner use is using `colors.gray4`. It would probably be best to unify those to be the same. Defining the color only once would prevent this issue.

- Having the UI in one place:

This doesn't always apply, but in this case, if we have everything defined in the `render` method there's no need to scroll up to look at the `styles.circle` to understand the disabled state, one can understand the whole thing by looking at only one place. Also, I'm not sure why the disabled state is necessary, isn't it doing the same thing as the first `Circle`?

- The last thing is that we're using standard css (`styles.circle`) instead of properties from the `svgs` package, which I'm not completely sure if it has any implications in certain phone sizes (this might not be an issue).


Again, this code is working, so great job on that and the comments above might seem a bit opinionated but I do believe that they lead to easier to read and maintain code.

File: packages/react-components/icons/RadioButton.tsx [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+    paddingTop: 2,
+    height: 20,
+    width: 20,
+    borderRadius: 12,
+    borderWidth: 2,
+    borderColor: colors.gray4,
+  },
+})
+
+export default class RadioButton extends React.PureComponent<Props> {
```
Comment (gnardini) [inline packages/react-components/icons/RadioButton.tsx:12]: No need to change it now, but for the future, it's better to use functional components instead of classes. Mainly because it's the direction React is going and class components may not be supported anymore in future versions or become "second class citizens" like not receiving performance improvements or being actively maintained anymore.

File: packages/react-components/icons/RadioButton.tsx (hunk 5 above)
Comment (michellewong793) [reply packages/react-components/icons/RadioButton.tsx]: i think the disabled state was just from the design, and they are different colors, and without the second circle in the middle. 

I updated the line in the latest commit to be: `const fill = (this.props.selected && !this.props.disabled) ? this.props.color : undefined;` 
since we're keeping track that it's both not selected and not disabled to have the middle circle.

Comment (michellewong793) [reply packages/react-components/icons/RadioButton.tsx]: i also removed the standard css usage and simplified it to use the svgs package instead! thanks for your comments Gonza

File: packages/react-components/icons/RadioButton.tsx (hunk 9 above)
Comment (michellewong793) [reply packages/react-components/icons/RadioButton.tsx:12]: totally- makes sense!

File: packages/react-components/icons/RadioButton.tsx (hunk 5 above)
Comment (gnardini) [reply packages/react-components/icons/RadioButton.tsx]: > think the disabled state was just from the design, and they are different colors

I see, I hadn't caught that :P

**Review by gnardini — APPROVED** [review]
Looks great! I think you just need to appease the linter and update snapshots :)

File: packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx [hunk 10]
```diff
@@ -82,7 +83,7 @@ function CurrencyRadioItem({
           { borderColor: currencyBorderColor(selected) },
         ]}
       >
-        <RadioIcon selected={selected} />
+        <RadioButton selected={selected} />
```
Comment (tarikbellamine) [inline packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx]: Shouldn't this also accept a `disabled` property, similar to how you've done below?

**Review by tarikbellamine — APPROVED** [review]
Nice work. Left one minor comment but once that's addressed then ship it!

File: packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx (hunk 10 above)
Comment (michellewong793) [reply packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx]: thanks! forgot about dis one :P

**Comment by Lss-Ankit** [comment]
hey @michellewong793 I have verified this issue using latest Android Internal Build V 1.10.0(1004294335) & Test Flight Build V1.10.0(45) & observed following observations.

- [x] User able to see both radio button & CELO option in disabled mode from "Select Digital currency i " field. As previously we have observed that radio button shown still in enabled mode & text is in disabled mode on Add Funds screen.
- [x] Also we have observed same for "Debit Card or bank account" option from "Pay with" field on Add Funds screen.
- [x] Also we have observed same observations for "cUSD/CELO address" & "Gift Cards and Mobile Top Up" options from "Receive funds in" field on Cash Out screen.
**Verified on devices:** Samsung Galaxy A5(7.0), iPhone XR (14.2)
**Attachment:** [CELOAddFundsScreen.png](https://drive.google.com/file/d/1OmQdJr6hXfu0G985vMGwIk_IwbD4jgFO/view?usp=sharing)
Let me know if anything need to test.
