### PR TITLE
Switch to using native pbkdf to fix hanging on older devices

### LINKED ISSUE #1356: [Android] [Device specific] App get crashed when user launch the app after installing.
**App version:** zero-sync build: Staging build v1.5.0 (101548577)
**Repro APK:** 1) App-x86_64-alfajores.apk, 2) app-arm64-v8a-alfajores.apk, 3) app-x86-alfajores.apk. 
**Does not repro APK:** app-armeabi-v7a-alfajores.apk.
**Repro on:** Samsung Galaxy S4 mini (4.4.2)  
**Does not Repro:** Moto E (4.4.4), Galaxy Grand Prime (5.1.1), Samsung J7 Prime (6.0.1)
**Testing Account:**  680 208 0265/Backup Kay
 
**Repro Steps:** 
1) Install the using given APK file. 
2) Launch the app. 
3) Observe. 

**Investigation:** In APK file: app-armeabi-v7a-alfajores.apk. Error “Importing Wallet Failed” is shown when user sign up using backup key
**Impact:** User is blocked to use the app and sign up using the backup key 
**Current Behavior:** App get crashed
**Expected Behavior:** User should be able to launch the app successfully and sign up with a backup key. 
**Attachment:**
 1) [Android_4OS_AppCrashed.MOV](https://drive.google.com/file/d/1kMhuniJdQYbbz89SrwO5HK4EKnfRSRpB/view?usp=sharing) (Bug observe after  1:34 sec)
2) [Android_4OS_ImportingFailed_BackupKeyissue.MOV](https://drive.google.com/file/d/1Xe6tw5J_Rtu7D6koNzByc7Lmry1OrIPj/view?usp=sharing) (Bug Observe at 1:08)
3) [Crashlog.txt](https://github.com/celo-org/celo-monorepo/files/3734353/Crashlog.txt)

### LINKED ISSUE #1668: [32-bit device specific] Error “Redeem invite time out” is shown on “Enter invite code” after pasting the invitation code.
**Frequency:** 100%
**App version:** Pilot build v1.5.1
**Used APK: ** app-x86-pilot.apk
**Repro on:** Samsung Galaxy A5 (7.0), Moto z play (7.0)
**Does not repro: ** Google Pixel XL (8.1), Google Pixel XL 2 (9.0)

**Repro Steps:** 
1) Launch the app. 
2) Enter name, Country and phone number. 
3) Tap on the Continue button. 
4) Paste the invitation code 
5) Wait for the moment and observed. 
**Impact:** User is blocked to sign up in-app. 
**Investigation:** Issue does not repro for 64-bit devices. 
**Current Behavior:**  Error “Redeem invite time out” is shown 
**Expected Behavior:** User should be able to accept invite code successfully and proceed for sign up. 
**Attachment:**[ Android_32-bit_InvitationIssue.mp4](https://drive.google.com/file/d/1xOxQuvIGfTw4ZChYZ-h8tjVvq6nKuZ23/view?usp=sharing) (Bug observe at  1:17 sec)

### PR DESCRIPTION
**Pull request by cmcewen**
### Description

Older devices would hang when generating a new local private key due to pbkdf being very slow in Hermes. This switches to using a native version. There were two changes I had to make to the library due to crashes on APIs 16-18 (https://github.com/EdgeApp/react-native-fast-crypto/pulls).

Also made this change: https://github.com/celo-org/react-native-bip39/compare/master...celo-org:cmcewen/fast-crypto

### Tested

Ran locally in simulator targeting API 18. Also tested in SL.

### Other changes

Had to add back the MultidexApplication for local dev on older devices

### Related Issues

fixes #1668
fixes #1356

### CODE REVIEW

File: packages/mobile/src/import/saga.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export function* importBackupPhraseSaga({ phrase, useEmptyWallet }: ImportBackup
       return
     }
 
-    const privateKey = mnemonicToSeedHex(phrase)
+    const privateKey = yield mnemonicToSeedHex(phrase)
```
Comment (jeanregisser) [inline packages/mobile/src/import/saga.ts]: We should use `yield call(mnemonicToSeedHex, phrase)`

File: packages/mobile/src/web3/saga.ts [hunk 2]
```diff
@@ -152,7 +152,7 @@ export function* getOrCreateAccount() {
       throw new Error('Failed to generate mnemonic')
     }
 
-    const privateKey = mnemonicToSeedHex(mnemonic)
+    const privateKey = yield mnemonicToSeedHex(mnemonic)
```
Comment (jeanregisser) [inline packages/mobile/src/web3/saga.ts]: Same comment as above.

**Review by jeanregisser — CHANGES_REQUESTED** [review]
Very nice! 🎉

**Review by jeanregisser — APPROVED** [review]
