### PR TITLE
Fix validatorgroup:list bug by not fetching unneeded info

### LINKED ISSUE #2098: CLI command validatorgroup:list does not work on Baklava testnet
### Expected Behavior

`$ celocli validatorgroup:list` should succeed.

### Current Behavior

`$ celocli validatorgroup:list` returns error in many cases.
Looks like it's getting harder to get list without error now.
Yesterday I can retrieve list of `validatorgroup` when trying query about three times.

```
$ celocli validatorgroup:list
Fetching Validator Groups... !
Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-eth-abi/src/index.js:226:15)
    at Contract._decodeMethodReturn (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/src/index.js:465:22)
    at Method.outputFormatter (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-eth-contract/src/index.js:818:46)
    at Method.formatOutput (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-method/src/index.js:473:33)
    at ~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:147:9
    at callbackDecorator (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```

### PR DESCRIPTION
**Pull request by asaj**
### Description

celo-blockchain seems to have trouble handling the large number of RPCs that are sent to it by `validatorgroup:list`. We can fix this by not fetching the group affiliates when we don't need to.

### Tested

It works, the most recent deployment does not.

### Other changes

None

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/2098

### CODE REVIEW

File: packages/contractkit/src/wrappers/Validators.ts [hunk 1]
```diff
@@ -211,14 +211,20 @@ export class ValidatorsWrapper extends BaseWrapper<Validators> {
...
+    getAffiliates: boolean = true
+  ): Promise<ValidatorGroup> {
     const res = await this.contract.methods.getValidatorGroup(address).call()
     const accounts = await this.kit.contracts.getAccounts()
     const name = (await accounts.getName(address)) || ''
-    const validators = await this.getRegisteredValidators()
-    const affiliates = validators
-      .filter((v) => v.affiliation === address)
-      .filter((v) => !res[0].includes(v.address))
+    let affiliates: Validator[] = []
```
Comment (timmoreton) [inline packages/contractkit/src/wrappers/Validators.ts:221]: preexisting, nit: we tend to use `members` elsewhere and in docs, right?

**Review by timmoreton — APPROVED** [review]

File: packages/contractkit/src/wrappers/Validators.ts (hunk 1 above)
Comment (asaj) [reply packages/contractkit/src/wrappers/Validators.ts:221]: Yeah but these are the ones that are affiliated to the group that are specifically not members
