### PR TITLE
Fix potential hard timeouts

### LINKED ISSUE #2071: make sure fetching from medium and events from airtable doesnt time out

### PR DESCRIPTION
**Pull request by aaronmgdr**
### Description

Add `try` and `catch` around the routes we use for fetching data from medium and for events from air table also put a timeout on fetching from sortable.

### Tested

messed with the timeout on the abort function while fetching /proxy/events and proxy/medium

### Other changes

changed param on abort from `url` to `message` to better reflect it doesnt need to be a url

### Related issues

- Fixes #2071 

### Backwards compatibility

yes

### CODE REVIEW

File: packages/web/server/index.ts [hunk 1]
```diff
@@ -154,13 +155,21 @@ function wwwRedirect(req, res, nextAction) {
...
+    } catch (e) {
+      res.status(e.statusCode || 500).json({ message: e.message || 'unknownError' })
+    }
   })
 
   server.get('/proxy/events/', async (_, res) => {
-    const events = await getFormattedEvents()
-    res.json(events)
+    try {
+      const events = await Promise.race([getFormattedEvents(), abort('Events from Airtable')])
```
Comment (cmcewen) [inline packages/web/server/index.ts]: Just for consistency, could you do the abort in the same place for both of these proxy routes? (either in the getFormatted function or at the top level here?

**Review by cmcewen — APPROVED** [review]
